Repository docker/cli, pull requests merged in 2018-10, with the labels that each got.

#1346 connhelper: add e2e
  docker.Makefile
  dockerfiles/Dockerfile.e2e
  e2e/compose-env.connhelper-ssh.yaml
  e2e/testdata/Dockerfile.connhelper-ssh
  e2e/testdata/connhelper-ssh/entrypoint.sh
  internal/test/environment/testenv.go
  scripts/test/e2e/run
Labels: area/testing, status/2-code-review

#1399 Docs: Add Spaces Around Parenthesis Where Needed
  docs/deprecated.md
  docs/reference/builder.md
  docs/reference/commandline/run.md
  docs/reference/run.md
Labels: status/3-docs-review

#1400 [master] Expose licensing details before loading
  cli/command/engine/activate.go
  cli/command/engine/activate_test.go
  cli/command/engine/testdata/expired-license-display-only.golden
  internal/licenseutils/client_test.go
  internal/licenseutils/utils.go
  vendor.conf
  vendor/github.com/docker/licensing/client.go
  vendor/github.com/docker/licensing/model/subscriptions.go
  vendor/github.com/docker/licensing/storage.go
Labels: status/2-code-review

#1405 Refine how metadata dir is handled
  cli/command/engine/activate.go
  cli/command/engine/activate_test.go
  cli/command/engine/check.go
  cli/command/engine/check_test.go
  cli/command/engine/update.go
  cli/command/engine/update_test.go
  internal/containerizedengine/types.go
  internal/containerizedengine/update.go
  internal/containerizedengine/update_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  types/types.go
Labels: status/2-code-review

#1408 [18.09] Fix panic in display only case for license
  cli/command/engine/activate.go
  cli/command/engine/activate_test.go
  cli/command/engine/testdata/expired-hub-license-display-only.golden
  internal/licenseutils/utils.go
  internal/licenseutils/utils_test.go
Labels: status/2-code-review

#1409 Remove unused health check func
  cli/command/engine/activate.go
  cli/command/engine/client_test.go
  cli/command/engine/update.go
  internal/containerizedengine/update.go
  internal/containerizedengine/update_test.go
  types/types.go
Labels: status/2-code-review

#1407 Allow to transform any source type into the target struct
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
Labels: status/2-code-review

#1402 [18.09] backport connhelper: try sending SIGTERM before SIGKILL
  cli/connhelper/connhelper.go
Labels: status/0-triage

#1418 Clarify in docs that docker tag doesn't publish
  man/src/image/tag.md
Labels: status/0-triage

#1414 Fix login documentation layout
  docs/reference/commandline/login.md
  docs/reference/commandline/logout.md
Labels: kind/docs, status/3-docs-review

#1434 Minor typo fix in run documentation
  docs/reference/run.md
Labels: kind/docs, status/4-merge

#1427 build: only show buildkit-specific flags if buildkit is enabled
  cli/command/cli.go
  cli/command/image/build.go
  cmd/docker/docker.go
Labels: area/builder, status/2-code-review

#1426 Bump Go to 1.11.1
  appveyor.yml
  cli/command/stack/swarm/deploy_test.go
  cli/registry/client/fetcher.go
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  opts/hosts_test.go
  scripts/build/osx
Labels: status/2-code-review

#1421 [18.09] Update release note link to final location
  cli/command/engine/check.go
  cli/command/engine/testdata/check-all.golden
  cli/command/engine/testdata/check-no-downgrades.golden
  cli/command/engine/testdata/check-no-prerelease.golden
  cli/command/engine/testdata/check-patches-only.golden
  internal/containerizedengine/update.go
  internal/containerizedengine/update_test.go
  types/types.go
Labels: status/2-code-review

#1433 [18.06] backport using strings.Builder instead of string appending
  cli/command/image/prune.go
Labels: status/0-triage

#1449 err message improve when ssh fail
  cli/connhelper/connhelper.go
Labels: status/0-triage

#1432 [18.09] backport using strings.Builder instead of string appending
  cli/command/image/prune.go
Labels: status/2-code-review

#1425 Deprecate legacy overlay storage driver
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/3-docs-review

#1443 fixes #1441 set default schema to tcp for docker host
  cli/command/cli.go
  cli/command/cli_test.go
  opts/hosts.go
Labels: status/0-triage

#1446 Documenting example default-ulimit in daemon.json
  docs/reference/commandline/dockerd.md
Labels: status/0-triage

#1451 builder/prune: rename max-age filter to unused-for in help output
  cli/command/builder/prune.go
Labels: area/builder, status/2-code-review

#1453 [18.09 backport] builder/prune: rename max-age filter to unused-for in help output
  cli/command/builder/prune.go
Labels: area/builder, status/2-code-review

#1424 Deprecate "devicemapper" storage driver.
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/3-docs-review

#1455 [18.09 backport] deprecate devicemapper and legacy overlay storage drivers
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/3-docs-review

#1447 Adjust formatting on daemon.json documentation
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#1445 Updating rmi doc example to specify latest tag
  docs/reference/commandline/rmi.md
Labels: kind/docs, status/3-docs-review

#1458 [18.09] Bump licensing lib
  cli/command/engine/activate_test.go
  internal/licenseutils/client_test.go
  internal/licenseutils/utils.go
  internal/licenseutils/utils_test.go
  vendor.conf
  vendor/github.com/docker/licensing/accounts.go
  vendor/github.com/docker/licensing/client.go
  vendor/github.com/docker/licensing/model/accounts.go
  vendor/github.com/docker/licensing/model/users.go
Labels: status/0-triage

#1474 build: update session support detection
  cli/command/image/build.go
  cli/command/image/build_buildkit.go
  cli/command/image/build_session.go
Labels: status/0-triage

#1429 Fix `docker invalid-subcommand` regression
  cmd/docker/docker.go
  cmd/docker/docker_test.go
Labels: status/2-code-review

#1482 docs, ssh: unsupport password auth explicitly
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#1325 Expose product license in info output
  cli/command/system/info.go
Labels: status/2-code-review

#1472 Enhancement: don't need to type ssh password twice when docker logs with ssh
  cli/command/container/logs.go
Labels: status/0-triage

#1483 [18.09 backport] various docs fixes
  cli/command/trust/sign_test.go
  docs/deprecated.md
  docs/reference/builder.md
  docs/reference/commandline/create.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/login.md
  docs/reference/commandline/logout.md
  docs/reference/commandline/rmi.md
  docs/reference/commandline/run.md
  docs/reference/run.md
  man/src/image/tag.md
Labels: kind/docs, status/3-docs-review
