Repository docker/cli, pull requests merged in 2018-11, with the labels that each got.

#1520 Bump to gotest.tools v2.2.0
  vendor.conf
  vendor/gotest.tools/LICENSE
  vendor/gotest.tools/README.md
  vendor/gotest.tools/assert/cmp/compare.go
  vendor/gotest.tools/assert/result.go
  vendor/gotest.tools/env/env.go
  vendor/gotest.tools/fs/file.go
  vendor/gotest.tools/fs/manifest.go
  vendor/gotest.tools/fs/ops.go
  vendor/gotest.tools/fs/path.go
  vendor/gotest.tools/fs/report.go
  vendor/gotest.tools/golden/golden.go
  vendor/gotest.tools/icmd/command.go
  vendor/gotest.tools/icmd/ops.go
  vendor/gotest.tools/internal/difflib/difflib.go
  vendor/gotest.tools/internal/source/defers.go
  vendor/gotest.tools/internal/source/source.go
Labels: status/2-code-review

#1415 Fix panic in display only case for license - forward port #1408 to master
  cli/command/engine/activate.go
  cli/command/engine/activate_test.go
  cli/command/engine/testdata/expired-hub-license-display-only.golden
  internal/licenseutils/utils.go
  internal/licenseutils/utils_test.go
Labels: status/2-code-review

#1523 Documenting ENTRYPOINT can empty value of CMD
  docs/reference/builder.md
Labels: status/0-triage

#1526 [18.09 backport] Fix bash completion for `service update --force`
  contrib/completion/bash/docker
Labels: area/completion, status/2-code-review

#1528 Update daemon.json example to show that log-opts must be a string
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/0-triage, status/3-docs-review

#1530 [18.09 backport] Update daemon.json example to show that log-opts must be a string
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#1493 add more buildkit docs
  docs/reference/builder.md
Labels: area/builder, kind/docs, status/3-docs-review

#1531 [18.09 backport] builder documentation updates
  docs/reference/builder.md
Labels: area/builder, kind/docs, status/3-docs-review

#1527 prune: move image pruning before build cache pruning
  cli/command/image/prune.go
  cli/command/system/prune.go
Labels: status/2-code-review

#1517 Migrate TestTrustedCreateFromBadTrustServer from moby into cli/e2e
  e2e/compose-env.yaml
  e2e/container/create_test.go
  e2e/internal/fixtures/fixtures.go
  e2e/testdata/Dockerfile.evil-notary-server
  e2e/testdata/notary-evil/notary-config.json
  e2e/testdata/notary-evil/notary-server.cert
  e2e/testdata/notary-evil/notary-server.key
  e2e/testdata/notary-evil/root-ca.cert
Labels: area/testing, status/2-code-review

#1532 [18.09] prune: move image pruning before build cache pruning
  cli/command/image/prune.go
  cli/command/system/prune.go
Labels: status/0-triage

#1454 [18.09 backport] fixes #1441 set default schema to tcp for docker host
  cli/command/cli.go
  cli/command/cli_test.go
  opts/hosts.go
Labels: status/2-code-review

#1509 Data Path Port configuration support
  cli/command/swarm/init.go
  cli/command/swarm/opts.go
  cli/command/system/info.go
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/reference/commandline/swarm_init.md
  vendor.conf
  vendor/github.com/docker/docker/api/types/swarm/swarm.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/docker/swarmkit/api/genericresource/resource_management.go
  vendor/github.com/docker/swarmkit/api/genericresource/validate.go
  vendor/github.com/docker/swarmkit/api/objects.pb.go
  vendor/github.com/docker/swarmkit/api/objects.proto
  vendor/github.com/docker/swarmkit/api/types.pb.go
  vendor/github.com/docker/swarmkit/api/types.proto
  vendor/github.com/docker/swarmkit/manager/raftselector/raftselector.go
  vendor/github.com/docker/swarmkit/vendor.conf
Labels: impact/changelog, impact/documentation, status/2-code-review

#1536 Replace environmental with environment
  docs/reference/commandline/service_create.md
Labels: impact/documentation, status/3-docs-review

#1306 man: obey SOURCE_DATE_EPOCH when generating man pages
  man/generate.go
Labels: status/0-triage

#1252 Add bash completion for experimental CLI commands (manifest)
  cli/command/manifest/util.go
  contrib/completion/bash/docker
Labels: area/completion, status/2-code-review

#1539 Fix yamldocs outputing `[flags]` in usage output
  docs/yaml/generate.go
Labels: kind/docs, status/2-code-review

#1544 [18.09] Bump Go to 1.10.5
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review
