Repository docker/cli, pull requests merged in 2018-07, with the labels that each got.

#1160 config/credentials: don't run 'pass' to detect it
  cli/config/credentials/default_store_linux.go
  vendor/github.com/docker/docker-credential-helpers/pass/pass_linux.go
Labels: status/2-code-review

#1168 Update TESTING.md to replace testify by gotest.tools
  TESTING.md
Labels: status/2-code-review

#1169 Add a doc.go file so the compose/schema/data directory can be vendore…
  cli/compose/schema/bindata.go
  cli/compose/schema/data/doc.go
  cli/compose/schema/schema.go
Labels: status/2-code-review

#1170 Add omitempty on compose config top-level types
  cli/command/stack/kubernetes/stackclient_test.go
  cli/compose/types/types.go
Labels: status/2-code-review

#1165 [18.06] Updated the go-winio library to release 0.4.8 that has the fix for Windows containers
  vendor.conf
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
Labels: status/2-code-review

#1171 Fix Format example typo"
  man/src/image/history.md
Labels: status/2-code-review

#1172 Remove composefiles length check on k8s RunDeploy
  cli/command/stack/kubernetes/deploy.go
Labels: area/kubernetes, area/stack, status/2-code-review

#1176 build: --iidfile support with buildkit
  cli/command/image/build_buildkit.go
Labels: area/builder, kind/experimental, status/2-code-review

#1183 [18.06] Fix manifest lists to always use correct size
  cli/command/manifest/annotate.go
  cli/command/manifest/inspect.go
  cli/command/manifest/inspect_test.go
  cli/command/manifest/push.go
  cli/command/manifest/testdata/inspect-annotate.golden
  cli/command/manifest/testdata/inspect-manifest-list.golden
  cli/manifest/store/store.go
  cli/manifest/types/types.go
  cli/registry/client/fetcher.go
Labels: impact/changelog, kind/experimental, status/2-code-review

#1187 [18.06] build: use strconv.ParseBool to parse DOCKER_BUILDKIT to allow value "0"
  cli/command/image/build.go
Labels: status/2-code-review

#1163 bump docker and dependencies
  cli/command/image/build.go
  vendor.conf
  vendor/github.com/containerd/containerd/LICENSE
  vendor/github.com/containerd/containerd/NOTICE
  vendor/github.com/containerd/containerd/README.md
  vendor/github.com/containerd/containerd/errdefs/errors.go
  vendor/github.com/containerd/containerd/errdefs/grpc.go
  vendor/github.com/containerd/containerd/log/context.go
  vendor/github.com/containerd/containerd/platforms/cpuinfo.go
  vendor/github.com/containerd/containerd/platforms/database.go
  vendor/github.com/containerd/containerd/platforms/defaults.go
  vendor/github.com/containerd/containerd/platforms/platforms.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/configs.go
  vendor/github.com/docker/docker/api/types/network/network.go
  vendor/github.com/docker/docker/client/image_build.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/pkg/archive/archive_windows.go
  vendor/github.com/docker/docker/pkg/archive/changes_linux.go
  vendor/github.com/docker/docker/pkg/streamformatter/streamformatter.go
  vendor/github.com/docker/docker/pkg/system/lcow.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/moby/buildkit/README.md
  vendor/github.com/moby/buildkit/api/services/control/control.pb.go
  vendor/github.com/moby/buildkit/api/services/control/control.proto
  vendor/github.com/moby/buildkit/client/client.go
  vendor/github.com/moby/buildkit/client/llb/exec.go
  vendor/github.com/moby/buildkit/client/llb/marshal.go
  vendor/github.com/moby/buildkit/client/llb/meta.go
  vendor/github.com/moby/buildkit/client/llb/resolver.go
  vendor/github.com/moby/buildkit/client/llb/source.go
  vendor/github.com/moby/buildkit/client/llb/state.go
  vendor/github.com/moby/buildkit/client/workers.go
  vendor/github.com/moby/buildkit/solver/pb/ops.pb.go
  vendor/github.com/moby/buildkit/solver/pb/ops.proto
  vendor/github.com/moby/buildkit/util/progress/progressui/display.go
  vendor/github.com/moby/buildkit/vendor.conf
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
Labels: status/2-code-review

#1174 [18.06] Remove composefiles lenght check on k8s RunDeploy..
  cli/command/stack/kubernetes/deploy.go
Labels: area/kubernetes, status/2-code-review

#1185 [18.06] build: --iidfile support with buildkit
  cli/command/image/build_buildkit.go
Labels: status/2-code-review

#1166 Sort plugin names in a natural order
  cli/command/plugin/list.go
  cli/command/plugin/list_test.go
  cli/command/plugin/testdata/plugin-list-sort.golden
Labels: status/2-code-review

#1190 [18.06] vendor: docker/docker to docker/engine 0d029b0
  vendor.conf
  vendor/github.com/containerd/console/console_linux.go
  vendor/github.com/containerd/console/console_windows.go
  vendor/github.com/containerd/containerd/LICENSE
  vendor/github.com/containerd/containerd/NOTICE
  vendor/github.com/containerd/containerd/README.md
  vendor/github.com/containerd/containerd/errdefs/errors.go
  vendor/github.com/containerd/containerd/errdefs/grpc.go
  vendor/github.com/containerd/containerd/log/context.go
  vendor/github.com/containerd/containerd/platforms/cpuinfo.go
  vendor/github.com/containerd/containerd/platforms/database.go
  vendor/github.com/containerd/containerd/platforms/defaults.go
  vendor/github.com/containerd/containerd/platforms/platforms.go
  vendor/github.com/containerd/containerd/vendor.conf
  vendor/github.com/containerd/continuity/syscallx/syscall_unix.go
  vendor/github.com/containerd/continuity/syscallx/syscall_windows.go
  vendor/github.com/containerd/continuity/sysx/file_posix.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_386.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_amd64.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_arm.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_arm64.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_ppc64.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_ppc64le.go
  vendor/github.com/containerd/continuity/sysx/xattr_linux_s390x.go
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/client/image_build.go
  vendor/github.com/docker/docker/pkg/archive/changes_linux.go
  vendor/github.com/docker/docker/pkg/streamformatter/streamformatter.go
  vendor/github.com/docker/docker/pkg/system/lcow.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/moby/buildkit/README.md
  vendor/github.com/moby/buildkit/api/services/control/control.pb.go
  vendor/github.com/moby/buildkit/api/services/control/control.proto
  vendor/github.com/moby/buildkit/client/client.go
  vendor/github.com/moby/buildkit/client/llb/exec.go
  vendor/github.com/moby/buildkit/client/llb/marshal.go
  vendor/github.com/moby/buildkit/client/llb/meta.go
  vendor/github.com/moby/buildkit/client/llb/resolver.go
  vendor/github.com/moby/buildkit/client/llb/source.go
  vendor/github.com/moby/buildkit/client/llb/state.go
  vendor/github.com/moby/buildkit/client/workers.go
  vendor/github.com/moby/buildkit/solver/pb/ops.pb.go
  vendor/github.com/moby/buildkit/solver/pb/ops.proto
  vendor/github.com/moby/buildkit/util/progress/progressui/display.go
  vendor/github.com/moby/buildkit/vendor.conf
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
Labels: status/0-triage

#1194 use sort.Slice for sorting commands' output
  cli/command/config/ls.go
  cli/command/formatter/container.go
  cli/command/formatter/service.go
  cli/command/network/list.go
  cli/command/node/list.go
  cli/command/secret/ls.go
  cli/command/service/list.go
  cli/command/service/opts.go
  cli/command/service/update.go
  cli/command/volume/list.go
Labels: status/2-code-review

#1196 refactored commands to use sort.Slice
  cli/command/formatter/trust.go
  cli/command/formatter/trust_test.go
  cli/command/registry/search.go
  cli/command/trust/common.go
  cli/command/trust/inspect_pretty.go
  cli/compose/convert/service.go
  cli/compose/convert/service_test.go
  cli/compose/loader/loader_test.go
Labels: status/2-code-review

#1178 Propagate the provided external CA certificate to the external CA object in swarm
  cli/command/swarm/ca.go
  cli/command/swarm/ca_test.go
  cli/command/swarm/opts.go
  cli/command/swarm/update.go
  cli/command/swarm/update_test.go
Labels: area/swarm, status/2-code-review

#1199 [18.06] Propagate the provided external CA certificate to the external CA object in swarm
  cli/command/swarm/ca.go
  cli/command/swarm/ca_test.go
  cli/command/swarm/opts.go
  cli/command/swarm/update.go
  cli/command/swarm/update_test.go
Labels: status/2-code-review

#1205 [18.06] Bump engine to tip of 18.06 branch
  vendor.conf
  vendor/github.com/containerd/console/console_linux.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/docker/swarmkit/api/objects.pb.go
  vendor/github.com/docker/swarmkit/api/storeobject.go
Labels: status/2-code-review

#1204 Improve version output alignment
  cli/command/system/testdata/docker-client-version.golden
  cli/command/system/version.go
  cli/command/system/version_test.go
Labels: status/2-code-review

#1210 Add bash completion for `service create|update --init`
  contrib/completion/bash/docker
Labels: status/2-code-review

#1208 Update gometalinter to v2.0.6, remove nakedret
  cli/command/container/opts_test.go
  cli/command/registry/login_test.go
  cli/command/trust/signer_remove.go
  dockerfiles/Dockerfile.lint
Labels: area/testing, status/2-code-review

#1211 [18.06] Add bash completion for `service create|update --init`
  contrib/completion/bash/docker
Labels: status/2-code-review

#1212 Update CircleCI Docker version to 18.03
  circle.yml
Labels: area/testing, status/2-code-review

#1192 For docker/docker.github.io/issues/6987
  docs/reference/commandline/history.md
Labels: status/3-docs-review

#1019 import environment variables that are present
  opts/envfile.go
  opts/envfile_test.go
  opts/file.go
  opts/parse.go
Labels: status/2-code-review

#1216 Update deploy.go
  cli/command/stack/deploy.go
  cli/command/stack/kubernetes/cli.go
Labels: area/kubernetes, area/stack, status/4-merge

#1214 [18.06] documentation and man-page fixes
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/history.md
  man/src/image/history.md
Labels: status/3-docs-review

#1207 [18.06] Improve version output alignment
  cli/command/system/testdata/docker-client-version.golden
  cli/command/system/version.go
  cli/command/system/version_test.go
Labels: status/0-triage

#1226 Bump version to 18.09.0-dev
  VERSION
Labels: status/2-code-review

#1227 Added events filter scope for bash and zsh completion
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
Labels: status/2-code-review

#1232 Fixed typo breaking zsh docker update autocomplete (closes #1231)
  contrib/completion/zsh/_docker
Labels: status/2-code-review

#1235 Add missing fields in compose/types
  cli/compose/types/types.go
Labels: status/2-code-review

#1237 Migrate to non-deprecated functions of `api/types/filters`
  cli/command/service/ps.go
  cli/command/system/prune.go
  cli/command/utils.go
  opts/opts.go
Labels: status/2-code-review

#990 Import TestBuildIidFileSquash from moby to cli
  docker.Makefile
  e2e/compose-env.experimental.yaml
  e2e/image/build_test.go
  internal/test/environment/testenv.go
  scripts/test/e2e/run
  scripts/test/e2e/wrapper
Labels: area/testing, status/2-code-review

#1241 [18.06] Fix: Warning Message
  cli/config/config.go
Labels: status/0-triage

#1222 Update --compose-file flag description to mention stdin
  cli/command/stack/deploy.go
  contrib/completion/zsh/_docker
  docs/reference/commandline/deploy.md
  docs/reference/commandline/stack_deploy.md
Labels: area/stack, status/2-code-review

#1240 Add API-version anotation for --data-path-addr
  cli/command/swarm/init.go
  cli/command/swarm/join.go
Labels: impact/changelog, status/2-code-review

#1244 Exposes compose `loader.Transform` function…
  cli/compose/loader/loader.go
Labels: status/2-code-review

#1242 build: add -buildmode=pie
  scripts/build/dynbinary
Labels: status/2-code-review

#1248 Add `help` and remove `watch` targets in docker.Makefile
  Makefile
  docker.Makefile
Labels: status/2-code-review

#1246 Bump mergo to v0.3.6
  vendor.conf
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/merge.go
Labels: status/2-code-review

#1215 Add bash completion for `service logs --details|--raw`
  contrib/completion/bash/docker
Labels: status/2-code-review
