Repository docker/cli, pull requests merged in 2018-04, with the labels that each got.

#980 Fix --format example for docker history
  docs/reference/commandline/history.md
Labels: status/3-docs-review

#979 Use printf, not echo when creating secrets
  docs/reference/commandline/secret_create.md
Labels: status/3-docs-review

#983 Fix error with merge composefile with networks…
  cli/compose/loader/merge.go
  cli/compose/loader/merge_test.go
  vendor.conf
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
Labels: area/stack, status/2-code-review

#981 Fix `docker stack deploy` reference flag
  docs/reference/commandline/stack_deploy.md
Labels: process/cherry-pick, status/3-docs-review

#986 Bump Golang to 1.9.5
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review

#978 [docs] Fix typo in manifest command docs: updated `MANFEST` to `MANIFEST`.
  cli/command/manifest/create_list.go
  docs/reference/commandline/manifest.md
Labels: process/cherry-pick, status/3-docs-review

#984 add fish completions for docker trust subcommand
  contrib/completion/fish/docker.fish
Labels: status/2-code-review

#992 Bump version to 18.05.0-dev
  VERSION
Labels: status/2-code-review

#994 Fixed gometalinter errors on test files
  cli/command/container/attach_test.go
  cli/command/formatter/checkpoint_test.go
  cli/command/formatter/diff_test.go
  cli/command/network/connect_test.go
  cli/command/network/create_test.go
  cli/command/service/opts_test.go
  cli/command/stack/kubernetes/conversion_test.go
  cli/command/trust/inspect_pretty_test.go
Labels: status/2-code-review

#988 Update examples to reflect docker-runc's runtime root for plugins.
  docs/extend/index.md
Labels: status/2-code-review

#997 Update Notary vendor to 0.6.1
  vendor.conf
  vendor/github.com/theupdateframework/notary/README.md
  vendor/github.com/theupdateframework/notary/client/changelist/change.go
  vendor/github.com/theupdateframework/notary/fips.go
  vendor/github.com/theupdateframework/notary/tuf/utils/x509.go
  vendor/github.com/theupdateframework/notary/vendor.conf
Labels: status/2-code-review

#963 Fix stack deploy re-deploying service after --force
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/stack/swarm/deploy_test.go
Labels: area/stack, impact/changelog, status/2-code-review

#970 Clarify --build-arg documentation
  docs/reference/commandline/build.md
Labels: process/cherry-pick, status/3-docs-review

#1007 docs: Typofix in example "docker image ls"
  docs/reference/commandline/load.md
Labels: process/cherry-pick, status/3-docs-review

#999 build.md: Document --build-arg without value
  docs/reference/commandline/build.md
Labels: status/3-docs-review

#1008 Revert unencryted storage warning prompt
  cli/command/registry/login.go
Labels: process/cherry-pick, status/2-code-review

#1004 Add bash completion for `secret|config create --template-driver`
  contrib/completion/bash/docker
Labels: process/cherry-pick, status/2-code-review

#1012 Add Silvin as maintainer
  MAINTAINERS
Labels: status/3-docs-review

#1013 Update AUTHORS and mailmap
  .mailmap
  AUTHORS
  MAINTAINERS
Labels: status/3-docs-review

#1020 Handle some TODOs in tests
  cli/command/cli_test.go
  cli/command/container/run.go
  cli/command/plugin/install.go
  cli/command/plugin/remove.go
  cli/command/system/info.go
  e2e/container/attach_test.go
  e2e/container/kill_test.go
  e2e/container/run_test.go
  e2e/stack/remove_test.go
  vendor.conf
Labels: status/2-code-review

#1022 Cleaning some manifest documentation typos
  cli/command/manifest/create_list.go
  cli/command/manifest/inspect.go
  docs/reference/commandline/manifest.md
Labels: process/cherry-pick, status/2-code-review

#1017 Warn when using host-ip for published ports
  opts/port.go
Labels: status/2-code-review

#903 Add warnings client side before deployment on Kubernetes
  cli/command/stack/kubernetes/convert.go
  cli/command/stack/kubernetes/deploy.go
  cli/command/stack/kubernetes/stackclient.go
  cli/command/stack/kubernetes/stackclient_test.go
  cli/command/stack/kubernetes/testdata/warnings.golden
  cli/command/stack/kubernetes/warnings.go
  cli/command/stack/kubernetes/warnings_test.go
  cli/command/stack/swarm/deploy.go
Labels: area/kubernetes, status/2-code-review

#973 Orchestrator column
  cli/command/formatter/stack.go
  cli/command/formatter/stack_test.go
  cli/command/stack/kubernetes/list.go
  cli/command/stack/swarm/list.go
  cli/command/stack/testdata/stack-list-sort-natural.golden
  cli/command/stack/testdata/stack-list-sort.golden
  cli/command/stack/testdata/stack-list-without-format.golden
  docs/reference/commandline/stack_ls.md
Labels: area/kubernetes, area/stack, impact/changelog, status/2-code-review

#1028 Add exec_die to the list of known container events
  docs/reference/commandline/events.md
Labels: process/cherry-pick, status/3-docs-review
