Repository docker/cli, pull requests merged in 2018-09, with the labels that each got.

#1327 build: add options to builder prune
  cli/command/builder/prune.go
  cli/command/container/prune.go
  cli/command/formatter/buildcache.go
  cli/command/formatter/disk_usage.go
  cli/command/formatter/disk_usage_test.go
  cli/command/network/prune.go
  cli/command/system/df.go
  cli/command/system/prune.go
  cli/command/volume/prune.go
  vendor.conf
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/client/build_prune.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/vendor.conf
Labels: status/0-triage

#1334 [18.09] build: add options to builder prune
  cli/command/builder/prune.go
  cli/command/container/prune.go
  cli/command/formatter/buildcache.go
  cli/command/formatter/disk_usage.go
  cli/command/formatter/disk_usage_test.go
  cli/command/network/prune.go
  cli/command/system/df.go
  cli/command/system/prune.go
  cli/command/volume/prune.go
  vendor.conf
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/client/build_prune.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/vendor.conf
Labels: status/0-triage

#1340 connhelper: fix cmd.Wait() race
  cli/connhelper/connhelper.go
Labels: status/2-code-review

#1329 update usage for 'docker build' with '--progress' and '--secret' options
  docs/reference/commandline/build.md
Labels: status/0-triage

#1314 update docs with currently supported features options
  docs/reference/commandline/dockerd.md
Labels: status/3-docs-review

#1353 Fix 'wether'->'whether'
  internal/test/output/output.go
Labels: status/0-triage

#1359 cli/config/configfile: Atomically rewrite the config file when saving.
  cli/config/configfile/file.go
  cli/config/configfile/file_test.go
Labels: status/2-code-review

#1326 Allow marshalling of Compose config to JSON
  cli/command/stack/kubernetes/convert.go
  cli/command/stack/kubernetes/warnings_test.go
  cli/compose/convert/service.go
  cli/compose/convert/service_test.go
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
  cli/compose/loader/types_test.go
  cli/compose/types/types.go
Labels: status/2-code-review

#1361 Remove containerizedengine package dependency from docker/cli/command…
  cli/command/cli.go
  cli/command/engine/activate.go
  cli/command/engine/activate_test.go
  cli/command/engine/check.go
  cli/command/engine/check_test.go
  cli/command/engine/client_test.go
  cli/command/engine/init.go
  cli/command/engine/init_test.go
  cli/command/engine/rm.go
  cli/command/engine/rm_test.go
  cli/command/engine/update_test.go
  cli/command/formatter/updates.go
  cli/command/formatter/updates_test.go
  cmd/docker/docker.go
  cmd/docker/docker_test.go
  docs/yaml/generate.go
  e2eengine/utils.go
  internal/containerizedengine/client_test.go
  internal/containerizedengine/containerd.go
  internal/containerizedengine/containerd_test.go
  internal/containerizedengine/engine.go
  internal/containerizedengine/engine_test.go
  internal/containerizedengine/types.go
  internal/containerizedengine/update.go
  internal/containerizedengine/update_test.go
  internal/containerizedengine/versions.go
  internal/test/cli.go
  man/generate.go
  types/types.go
Labels: status/2-code-review, version/18.03

#1362 Add `docker engine` commands only on Linux…
  cli/command/commands/commands.go
Labels: status/2-code-review, version/18.03

#1365 [18.09] backport add `docker engine` commands only on Linux…
  cli/command/commands/commands.go
Labels: status/0-triage

#1364 [18.09] backport: remove containerizedengine package dependency from docker/cli/command…
  cli/command/cli.go
  cli/command/engine/activate.go
  cli/command/engine/activate_test.go
  cli/command/engine/check.go
  cli/command/engine/check_test.go
  cli/command/engine/client_test.go
  cli/command/engine/init.go
  cli/command/engine/init_test.go
  cli/command/engine/rm.go
  cli/command/engine/rm_test.go
  cli/command/engine/update_test.go
  cli/command/formatter/updates.go
  cli/command/formatter/updates_test.go
  cmd/docker/docker.go
  cmd/docker/docker_test.go
  docs/yaml/generate.go
  e2eengine/utils.go
  internal/containerizedengine/client_test.go
  internal/containerizedengine/containerd.go
  internal/containerizedengine/containerd_test.go
  internal/containerizedengine/engine.go
  internal/containerizedengine/engine_test.go
  internal/containerizedengine/types.go
  internal/containerizedengine/update.go
  internal/containerizedengine/update_test.go
  internal/containerizedengine/versions.go
  internal/test/cli.go
  man/generate.go
  types/types.go
Labels: status/2-code-review

#1352 Typo fix
  cli/command/trust/sign_test.go
  docs/reference/commandline/create.md
Labels: status/2-code-review

#1354 Fix some typo
  cli/command/stack/kubernetes/services.go
  cli/command/stack/kubernetes/stackclient.go
  e2e/stack/remove_test.go
Labels: status/2-code-review

#1351 Typo fix: filesytem -> filesystem
  docs/reference/commandline/create.md
Labels: status/0-triage

#1309 Bump version to 19.03.0-dev
  VERSION
  e2eengine/altroot/altroot_test.go
  e2eengine/multi/multi_test.go
Labels: status/2-code-review

#1370 system/df: allow -v with --format
  cli/command/formatter/buildcache.go
  cli/command/formatter/disk_usage.go
  cli/command/formatter/disk_usage_test.go
  cli/command/system/df.go
Labels: status/2-code-review

#1324 Add support for multiple signing keys
  internal/licenseutils/types.go
  internal/licenseutils/utils.go
  vendor.conf
  vendor/github.com/docker/licensing/LICENSE
  vendor/github.com/docker/licensing/README.md
  vendor/github.com/docker/licensing/client.go
  vendor/github.com/docker/licensing/license.go
Labels: status/2-code-review

#1374 [18.09] backport update usage for 'docker build' with '--progress' and '--secret' options
  docs/reference/commandline/build.md
Labels: area/builder, status/3-docs-review

#1371 LCOW: --platform on import (already in API)
  cli/command/image/import.go
  docs/reference/commandline/import.md
  man/src/image/import.md
Labels: impact/documentation, kind/bug, status/0-triage, status/1-design-review

#1373 [18.09] backport getEngineConfigFilePath is only used during test so moving it in test files for now.
  internal/containerizedengine/engine.go
  internal/containerizedengine/engine_test.go
Labels: area/testing, status/2-code-review

#1375 [18.09] backport LCOW: --platform on import (already in API)
  cli/command/image/import.go
  docs/reference/commandline/import.md
  man/src/image/import.md
Labels: kind/experimental, status/2-code-review

#1378 fix insecure manifest inspect with restrictive certs perms
  cli/registry/client/fetcher.go
Labels: status/2-code-review

#1382 [18.09] backport fix insecure manifest inspect with restrictive certs perms
  cli/registry/client/fetcher.go
Labels: status/2-code-review

#1392 Fix substitution with non-empty env-var
  cli/compose/template/template.go
  cli/compose/template/template_test.go
Labels: area/stack, status/2-code-review

#1342 [18.09] backport connhelper: fix cmd.Wait() race
  cli/connhelper/connhelper.go
Labels: status/2-code-review

#1394 [18.09] backport fix substitution with non-empty env-var
  cli/compose/template/template.go
  cli/compose/template/template_test.go
Labels: area/stack, status/2-code-review

#1389 [18.09] fix subscription filter
  internal/licenseutils/utils.go
Labels: status/0-triage

#1195 Allow npipe volume type on stack file
  cli/compose/convert/volume.go
  cli/compose/convert/volume_test.go
  docs/reference/commandline/service_create.md
Labels: impact/changelog, impact/compose-file, platform/windows, status/2-code-review

#1345 connhelper: try sending SIGTERM before SIGKILL
  cli/connhelper/connhelper.go
Labels: status/2-code-review

#1387 [18.09] Expose licensing details before loading
  cli/command/engine/activate.go
  cli/command/engine/activate_test.go
  cli/command/engine/testdata/expired-license-display-only.golden
  internal/licenseutils/client_test.go
  internal/licenseutils/utils.go
  vendor.conf
  vendor/github.com/docker/licensing/client.go
  vendor/github.com/docker/licensing/model/subscriptions.go
  vendor/github.com/docker/licensing/storage.go
Labels: status/2-code-review
