Repository docker/cli, pull requests merged in 2018-06, with the labels that each got.

#1097 Allow `x-*` extension on 3rd level objects
  cli/compose/schema/bindata.go
  cli/compose/schema/data/config_schema_v3.7.json
  cli/compose/schema/schema_test.go
Labels: area/stack, impact/changelog, impact/compose-file, impact/documentation, status/2-code-review

#1094 Hide experimental checkpoint features on Windows
  cli/command/checkpoint/cmd.go
  cli/command/container/start.go
  cmd/docker/docker.go
  docs/yaml/yaml.go
Labels: kind/experimental, status/2-code-review

#1101 Fix service filtering by name on Kubernetes
  cli/command/stack/kubernetes/services.go
  cli/command/stack/kubernetes/services_test.go
Labels: area/kubernetes, area/stack, status/2-code-review

#1105 Fix panics when --compress and --stream are used together
  cli/command/image/build.go
Labels: kind/experimental, status/2-code-review

#1106 Add a "top-level" annotation to hide persistent flags
  cmd/docker/docker.go
Labels: priority/P1, status/2-code-review

#948 K8s: more robust stack error detection on deploy
  cli/command/stack/kubernetes/cli.go
  cli/command/stack/kubernetes/deploy.go
  cli/command/stack/kubernetes/stackclient.go
  cli/command/stack/kubernetes/watcher.go
  cli/command/stack/kubernetes/watcher_test.go
  vendor.conf
  vendor/github.com/morikuni/aec/LICENSE
  vendor/github.com/morikuni/aec/README.md
  vendor/github.com/morikuni/aec/aec.go
  vendor/github.com/morikuni/aec/ansi.go
  vendor/github.com/morikuni/aec/builder.go
  vendor/github.com/morikuni/aec/sgr.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/k8s.io/kubernetes/pkg/api/v1/pod/util.go
Labels: area/kubernetes, area/stack, status/2-code-review

#1104 Add more example to the full-example tests
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
Labels: status/2-code-review

#1115 Mark @thajeztah as a MAINTAINER…
  MAINTAINERS
Labels: status/2-code-review

#1119 Check errors when initializing the docker client in the help command
  cmd/docker/docker.go
Labels: status/2-code-review

#1122 Bump Golang to 1.10.3
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#479 Add --init option to `docker service create`
  cli/command/formatter/service.go
  cli/command/service/create.go
  cli/command/service/opts.go
  cli/command/service/update.go
  cli/command/service/update_test.go
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_update.md
Labels: impact/changelog, status/2-code-review

#1123 Export Push and Save
  cli/command/image/push.go
  cli/command/image/save.go
Labels: status/2-code-review

#1124 Use command.Cli interface instead of concrete type…
  cli/command/commands/commands.go
  cli/command/system/inspect.go
Labels: status/2-code-review

#1137 Fix broken swarm commands with Kubernetes defined as orchestrator
  cli/cobra.go
  cli/command/cli.go
  cli/command/cli_test.go
  cli/command/orchestrator.go
  cli/command/orchestrator_test.go
  cli/command/stack/cmd.go
  cli/command/stack/deploy.go
  cli/command/stack/kubernetes/cli.go
  cli/command/stack/list.go
  cli/command/stack/list_test.go
  cli/command/stack/ps.go
  cli/command/stack/ps_test.go
  cli/command/stack/remove.go
  cli/command/stack/remove_test.go
  cli/command/stack/services.go
  cli/command/stack/services_test.go
  cli/command/system/testdata/docker-client-version.golden
  cli/command/system/version.go
  cli/command/system/version_test.go
  cli/config/configfile/file.go
  cli/flags/common.go
  cmd/docker/docker.go
  docs/reference/commandline/cli.md
  docs/reference/commandline/stack.md
  docs/reference/commandline/stack_deploy.md
  docs/reference/commandline/stack_ls.md
  docs/reference/commandline/stack_ps.md
  docs/reference/commandline/stack_rm.md
  docs/reference/commandline/stack_services.md
  docs/reference/commandline/version.md
  e2e/stack/deploy_test.go
  e2e/stack/remove_test.go
  internal/test/cli.go
Labels: area/kubernetes, area/stack, docs/revisit, impact/changelog, impact/documentation, status/2-code-review

#1139 Warn if DOCKER_ORCHESTRATOR is still used but not DOCKER_STACK_ORCHESTRATOR
  cli/command/orchestrator.go
  cli/command/orchestrator_test.go
  cli/command/stack/cmd.go
  cli/command/system/version.go
Labels: status/1-design-review

#1141 fixed output leak from TestRunCommandWithContentTrustErrors
  cli/command/container/run_test.go
Labels: area/testing, status/2-code-review

#1126 Add an `Extras` field on the compose config types.
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
  cli/compose/types/types.go
Labels: status/2-code-review

#1129 Add `init` support in 3.7 schema
  cli/compose/convert/service.go
  cli/compose/loader/loader_test.go
  cli/compose/schema/bindata.go
  cli/compose/schema/data/config_schema_v3.7.json
  cli/compose/types/types.go
Labels: impact/changelog, impact/compose-file, impact/documentation, status/2-code-review

#1138 Add env variable option for experimental
  cli/command/cli.go
  docs/reference/commandline/cli.md
Labels: status/1-design-review

#1147 Refactor `stack` command/package
  cli/command/stack/common.go
  cli/command/stack/deploy.go
  cli/command/stack/deploy_test.go
  cli/command/stack/kubernetes/deploy.go
  cli/command/stack/ps.go
  cli/command/stack/ps_test.go
  cli/command/stack/remove.go
  cli/command/stack/remove_test.go
  cli/command/stack/services.go
  cli/command/stack/services_test.go
  cli/command/stack/swarm/common.go
  cli/command/stack/swarm/deploy.go
  cli/command/stack/swarm/deploy_bundlefile.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/stack/swarm/deploy_test.go
  cli/command/stack/swarm/ps.go
  cli/command/stack/swarm/ps_test.go
  cli/command/stack/swarm/remove.go
  cli/command/stack/swarm/remove_test.go
  cli/command/stack/swarm/services.go
  cli/command/stack/swarm/services_test.go
Labels: status/2-code-review

#1128 Add options to the compose loader
  cli/compose/interpolation/interpolation.go
  cli/compose/loader/interpolate.go
  cli/compose/loader/loader.go
  cli/compose/template/template.go
  cli/compose/template/template_test.go
Labels: status/2-code-review

#1149 added unit tests covering content trust for plugin install command
  cli/command/plugin/client_test.go
  cli/command/plugin/install.go
  cli/command/plugin/install_test.go
Labels: area/testing, status/2-code-review

#1151 Update docker-credential-helpers dependency
  cli/config/credentials/default_store_linux.go
  vendor.conf
  vendor/github.com/docker/docker-credential-helpers/README.md
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/github.com/docker/docker-credential-helpers/pass/pass_linux.go
Labels: status/2-code-review

#1159 Add bash completion for `exec_die` event
  contrib/completion/bash/docker
Labels: status/2-code-review

#1158 Add bash completion for `dockerd --default-address-pool`
  contrib/completion/bash/docker
Labels: status/2-code-review

#1152 Extract StackConverter from the StackClient
  cli/command/stack/kubernetes/convert.go
  cli/command/stack/kubernetes/convert_test.go
  cli/command/stack/kubernetes/deploy.go
  cli/command/stack/kubernetes/list.go
  cli/command/stack/kubernetes/stack.go
  cli/command/stack/kubernetes/stackclient.go
  cli/command/stack/kubernetes/stackclient_test.go
Labels: status/2-code-review

#1155 added unit tests to cover plugin list command
  cli/command/plugin/client_test.go
  cli/command/plugin/list_test.go
  cli/command/plugin/testdata/plugin-list-with-format.golden
  cli/command/plugin/testdata/plugin-list-with-no-trunc-option.golden
  cli/command/plugin/testdata/plugin-list-with-quiet-option.golden
  cli/command/plugin/testdata/plugin-list-without-format.golden
Labels: status/2-code-review

#1145 Add: Add missing option
  docs/reference/commandline/dockerd.md
Labels: status/3-docs-review

#1157 Updated the go-winio library to release 0.4.8 that has the fix for Windows Container
  vendor.conf
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/pipe.go
  vendor/github.com/Microsoft/go-winio/zsyscall_windows.go
Labels: status/0-triage
