Repository docker/cli, pull requests merged in 2019-08, with the labels that each got.

#1697 Explain -s flag on docker ps
  docs/reference/commandline/ps.md
Labels: kind/docs, status/3-docs-review

#2015 [18.09] Bump Go to 1.11.12
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review

#2021 [18.09 backport] Disable TLS for e2e docker-in-docker daemon
  e2e/compose-env.yaml
Labels: area/testing, status/2-code-review

#2022 [19.03 backport] Disable TLS for e2e docker-in-docker daemon
  e2e/compose-env.yaml
Labels: area/testing, status/2-code-review

#1998 [19.03 backport] Bump golang 1.12.7
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#1946 [19.03 backport] Bump golang 1.12.6
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review

#2006 bump docker-credential-helpers v0.6.3
  vendor.conf
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.c
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.go
  vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.c
  vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go
Labels: process/cherry-pick, status/2-code-review

#1984 [18.09 backport] bump docker-credential-helpers v0.6.3
  vendor.conf
  vendor/github.com/docker/docker-credential-helpers/README.md
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.c
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_go18.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_non_go18.go
  vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.c
  vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go
Labels: status/2-code-review

#1983 [19.03 backport] bump docker-credential-helpers v0.6.3
  vendor.conf
  vendor/github.com/docker/docker-credential-helpers/README.md
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.c
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_go18.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_non_go18.go
  vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.c
  vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go
Labels: status/2-code-review

#1970 [19.03 backport] Windows: skip permissions check on key
  cli/command/trust/key_load.go
Labels: area/trust, status/2-code-review

#2009 CircleCI/Jenkins: use buildkit
  .dockerignore
  Jenkinsfile
  circle.yml
Labels: area/testing, process/cherry-pick, status/4-merge

#2043 Bump golang 1.12.8 (CVE-2019-9512, CVE-2019-9514)
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  opts/hosts_test.go
Labels: process/cherry-picked, status/2-code-review

#2045 [18.09] Bump golang 1.11.13 (CVE-2019-9512, CVE-2019-9514)
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  opts/hosts_test.go
Labels: status/2-code-review

#2044 [19.03 backport] Bump golang 1.12.8 (CVE-2019-9512, CVE-2019-9514)
  appveyor.yml
  docker.Makefile
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  opts/hosts_test.go
Labels: status/2-code-review

#1993 e2e: remove docker engine testing remnants
  dockerfiles/Dockerfile.e2e
Labels: area/testing, process/cherry-pick, status/2-code-review

#1985 [19.03 backport] context: produce consistent output on `context create`.
  cli/command/context/create.go
  cli/command/context/create_test.go
  internal/test/cli.go
Labels: area/context, status/2-code-review

#2059 restore support for env variables to configure proxy
  cli/command/cli_test.go
  cli/context/docker/load.go
Labels: process/cherry-pick, status/2-code-review

#2061 [19.03 backport] restore support for env variables to configure proxy
  cli/command/cli_test.go
  cli/context/docker/load.go
Labels: status/2-code-review

#2048 [19.03 backport] CI and testing improvements
  .dockerignore
  Jenkinsfile
  circle.yml
  dockerfiles/Dockerfile.e2e
Labels: area/testing, status/2-code-review

#2064 Update AUTHORS and mailmap
  .mailmap
  AUTHORS
Labels: status/0-triage

#2053 Fix phrasing when referring to the freezer cgroup
  docs/reference/commandline/pause.md
  docs/reference/commandline/unpause.md
  man/src/container/pause.md
  man/src/container/unpause.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#2072 Updating deprecated command example in search.md
  docs/reference/commandline/search.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#2069 fix(pull_test): --quiet option
  cli/command/image/pull_test.go
  cli/command/image/testdata/pull-command-success.simple-quiet.golden
Labels: area/testing, process/cherry-pick, status/2-code-review

#2066 add rudimentary fish completions for docker network
  contrib/completion/fish/docker.fish
Labels: area/completion, process/cherry-pick, status/2-code-review
