Repository docker/cli, pull requests merged in 2019-06, with the labels that each got.

#1924 Fix detection of invalid context files when importing
  cli/context/store/store.go
  cli/context/store/store_test.go
Labels: area/context, process/cherry-picked, status/2-code-review

#1929 [19.03 backport] Fix detection of invalid context files when importing
  cli/context/store/store.go
  cli/context/store/store_test.go
Labels: area/context, status/2-code-review

#1927 [19.03] Backport #1857: Support GOARM and windows .exe in binary target
  docker.Makefile
  scripts/build/.variables
Labels: status/2-code-review

#1941 Bump golang 1.12.6
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: process/cherry-pick, status/2-code-review

#1842 [18.09 backport] bump buildkit 05766c5c21a1e528eeb1c3522b2f05493fe9ac47 (docker-18.09 branch)
  vendor.conf
  vendor/github.com/moby/buildkit/README.md
  vendor/github.com/moby/buildkit/client/llb/source.go
  vendor/github.com/moby/buildkit/client/llb/state.go
  vendor/github.com/moby/buildkit/frontend/gateway/grpcclient/client.go
  vendor/github.com/moby/buildkit/session/session.go
  vendor/github.com/moby/buildkit/vendor.conf
  vendor/github.com/tonistiigi/fsutil/walker.go
Labels: area/builder, status/2-code-review

#1935 bump docker-credential-helpers v0.6.2
  vendor.conf
  vendor/github.com/docker/docker-credential-helpers/README.md
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_go18.go
  vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_non_go18.go
  vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go
Labels: process/cherry-pick, status/2-code-review

#1956 deprecate registry v2 schema 1
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, process/cherry-picked, status/3-docs-review

#1948 fix: docker login autocomplete for zsh
  contrib/completion/zsh/_docker
Labels: area/completion, status/2-code-review

#1963 Fix advanced options for backward compatibility
  cli/command/container/opts.go
  cli/command/container/opts_test.go
Labels: area/networking, process/cherry-picked, status/2-code-review

#1960 [19.03 backport] deprecate registry v2 schema 1
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review

#1841 Do not disable sig-proxy when using a TTY
  cli/command/container/run.go
  e2e/container/proxy_signal_test.go
  vendor.conf
  vendor/github.com/kr/pty/License
  vendor/github.com/kr/pty/README.md
  vendor/github.com/kr/pty/doc.go
  vendor/github.com/kr/pty/go.mod
  vendor/github.com/kr/pty/ioctl.go
  vendor/github.com/kr/pty/ioctl_bsd.go
  vendor/github.com/kr/pty/pty_darwin.go
  vendor/github.com/kr/pty/pty_dragonfly.go
  vendor/github.com/kr/pty/pty_freebsd.go
  vendor/github.com/kr/pty/pty_linux.go
  vendor/github.com/kr/pty/pty_openbsd.go
  vendor/github.com/kr/pty/pty_unsupported.go
  vendor/github.com/kr/pty/run.go
  vendor/github.com/kr/pty/util.go
  vendor/github.com/kr/pty/ztypes_386.go
  vendor/github.com/kr/pty/ztypes_amd64.go
  vendor/github.com/kr/pty/ztypes_arm.go
  vendor/github.com/kr/pty/ztypes_arm64.go
  vendor/github.com/kr/pty/ztypes_dragonfly_amd64.go
  vendor/github.com/kr/pty/ztypes_freebsd_386.go
  vendor/github.com/kr/pty/ztypes_freebsd_amd64.go
  vendor/github.com/kr/pty/ztypes_freebsd_arm.go
  vendor/github.com/kr/pty/ztypes_mipsx.go
  vendor/github.com/kr/pty/ztypes_openbsd_386.go
  vendor/github.com/kr/pty/ztypes_openbsd_amd64.go
  vendor/github.com/kr/pty/ztypes_ppc64.go
  vendor/github.com/kr/pty/ztypes_ppc64le.go
  vendor/github.com/kr/pty/ztypes_s390x.go
Labels: status/2-code-review

#1967 [19.03 backport] Fix advanced options for backward compatibility
  cli/command/container/opts.go
  cli/command/container/opts_test.go
Labels: status/2-code-review

#1934 bump compose-on-kubernetes v0.4.23
  vendor.conf
Labels: area/kubernetes, status/2-code-review
