Repository docker/cli, pull requests merged in 2019-11, with the labels that each got.

#2177 [19.03 backport] Do not disable sig-proxy when using a TTY
  cli/command/container/run.go
  e2e/container/proxy_signal_test.go
  vendor.conf
  vendor/github.com/kr/pty/License
  vendor/github.com/kr/pty/README.md
  vendor/github.com/kr/pty/doc.go
  vendor/github.com/kr/pty/go.mod
  vendor/github.com/kr/pty/ioctl.go
  vendor/github.com/kr/pty/ioctl_bsd.go
  vendor/github.com/kr/pty/pty_darwin.go
  vendor/github.com/kr/pty/pty_dragonfly.go
  vendor/github.com/kr/pty/pty_freebsd.go
  vendor/github.com/kr/pty/pty_linux.go
  vendor/github.com/kr/pty/pty_openbsd.go
  vendor/github.com/kr/pty/pty_unsupported.go
  vendor/github.com/kr/pty/run.go
  vendor/github.com/kr/pty/util.go
  vendor/github.com/kr/pty/ztypes_386.go
  vendor/github.com/kr/pty/ztypes_amd64.go
  vendor/github.com/kr/pty/ztypes_arm.go
  vendor/github.com/kr/pty/ztypes_arm64.go
  vendor/github.com/kr/pty/ztypes_dragonfly_amd64.go
  vendor/github.com/kr/pty/ztypes_freebsd_386.go
  vendor/github.com/kr/pty/ztypes_freebsd_amd64.go
  vendor/github.com/kr/pty/ztypes_freebsd_arm.go
  vendor/github.com/kr/pty/ztypes_mipsx.go
  vendor/github.com/kr/pty/ztypes_openbsd_386.go
  vendor/github.com/kr/pty/ztypes_openbsd_amd64.go
  vendor/github.com/kr/pty/ztypes_ppc64.go
  vendor/github.com/kr/pty/ztypes_ppc64le.go
  vendor/github.com/kr/pty/ztypes_s390x.go
Labels: impact/changelog, status/2-code-review

#2054 Update service_create.md
  docs/reference/commandline/service_create.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#2179 unused-for is a deprecated synonym for until
  cli/command/builder/prune.go
Labels: area/builder, impact/documentation, status/2-code-review

#2107 Fix CREATED field when listing image if date is not specified
  cli/command/formatter/image.go
  cli/command/formatter/image_test.go
Labels: status/2-code-review

#2182 Add interpolation type cast for max_replicas_per_node
  cli/compose/loader/interpolate.go
  cli/compose/loader/loader_test.go
Labels: area/stack, impact/compose-file, process/cherry-pick, status/2-code-review

#2187 Bump compose-on-kubernetes from v0.4.25-alpha1 to v0.5.0-alpha1
  vendor.conf
Labels: status/2-code-review

#2095 APP-214 Load Client info in getter function
  cli/command/cli.go
Labels: status/2-code-review

#2197 Add support for docker push --quiet
  cli/command/image/push.go
  cli/command/image/push_test.go
  contrib/completion/bash/docker
  docs/reference/commandline/push.md
Labels: area/distribution, impact/changelog, status/2-code-review

#2198 Typo in documentation of volume create
  man/src/volume/create.md
Labels: kind/docs, status/3-docs-review

#2194 cp: allow trailing slash in non-existant destination
  cli/command/utils.go
  cli/command/utils_test.go
Labels: process/cherry-pick, status/2-code-review

#2202 Fixing some links and deleting an older page reference
  docs/reference/builder.md
Labels: kind/docs, status/3-docs-review
