Repository docker/cli, pull requests merged in 2019-03, with the labels that each got.

#1698 Fix unknown $(MOUNTS) variable in makefile plugins target
  docker.Makefile
Labels: status/0-triage

#1702 connhelper: export functions for other projects
  cli/connhelper/commandconn/commandconn.go
  cli/connhelper/commandconn/commandconn_linux.go
  cli/connhelper/commandconn/commandconn_nolinux.go
  cli/connhelper/commandconn/commandconn_unix_test.go
  cli/connhelper/connhelper.go
  cli/connhelper/ssh/ssh.go
  cli/connhelper/ssh/ssh_test.go
  e2e/cli-plugins/dial_test.go
Labels: status/2-code-review

#1701 Fix cli-plugins build.
  docker.Makefile
Labels: status/2-code-review

#1680 Fix issue where plugin command error exit code is printed out
  cli-plugins/examples/helloworld/main.go
  cmd/docker/docker.go
  e2e/cli-plugins/run_test.go
  e2e/cli-plugins/testdata/docker-help-helloworld.golden
Labels: area/plugins, status/2-code-review

#1717 Export cli/command/config
  cli/command/config/create.go
  cli/command/config/inspect.go
  cli/command/config/ls.go
  cli/command/config/remove.go
Labels: status/2-code-review

#1693 Upgrade shellcheck 0.6.0
  contrib/completion/bash/docker
  dockerfiles/Dockerfile.shellcheck
  scripts/gen/windows-resources
  scripts/test/e2e/run
  scripts/warn-outside-container
Labels: status/2-code-review

#1538 Use official shellcheck image
  dockerfiles/Dockerfile.shellcheck
  scripts/warn-outside-container
Labels: area/completion, area/testing, status/2-code-review

#1720 hardening config.Path() to disallow directory traversal
  cli-plugins/manager/manager.go
  cli-plugins/manager/manager_test.go
  cli/config/config.go
  cli/config/config_test.go
Labels: area/plugins, status/2-code-review

#1710 Disable `docker system dial-stdio` on Windows
  cli-plugins/plugin/plugin.go
  cli/command/system/cmd.go
Labels: area/plugins, status/2-code-review

#1728 Fixes for e2e testing after Alpine bump
  e2e/testdata/Dockerfile.connhelper-ssh
Labels: status/2-code-review

#1688 use char to check blockIO type
  cli/command/container/stats_helpers.go
  cli/command/container/stats_unit_test.go
Labels: status/2-code-review

#1729 [18.09 backport] Fixes for e2e testing after Alpine bump
  e2e/testdata/Dockerfile.connhelper-ssh
Labels: area/testing, status/2-code-review

#1718 dial-stdio: handle connections which lack CloseRead method.
  cli-plugins/plugin/plugin.go
  cli/command/system/cmd.go
  cli/command/system/dial_stdio.go
Labels: status/2-code-review

#1722 Allow plugins to have --flags which are the same as the top-level
  cli-plugins/examples/helloworld/main.go
  cli-plugins/plugin/plugin.go
  cli/cobra.go
  cmd/docker/docker.go
  cmd/docker/docker_test.go
  e2e/cli-plugins/flags_test.go
  e2e/cli-plugins/run_test.go
  e2e/cli-plugins/testdata/docker-help-helloworld.golden
Labels: area/plugins, status/2-code-review

#1674 Add exit status to docker exec manpage
  man/src/container/exec.md
Labels: kind/docs, status/3-docs-review

#1712 Fix test for Go 1.12.x
  cli/config/config_test.go
Labels: area/testing, status/2-code-review

#1737 Fix regression for CLI plugins using PersistentPreRunE
  cli-plugins/examples/helloworld/main.go
  cli-plugins/plugin/plugin.go
  e2e/cli-plugins/run_test.go
  e2e/cli-plugins/testdata/docker-help-helloworld.golden
Labels: area/plugins, status/2-code-review

#1713 Fix: plugin-tests discarding current environment
  e2e/plugin/trust_test.go
  scripts/test/e2e/run
Labels: area/testing, status/2-code-review

#1734 [18.09 backport] Fix test for Go 1.12.x
  cli/config/config_test.go
Labels: area/testing, status/2-code-review

#1629 Improve `docker image rm` reference docs
  docs/reference/commandline/rmi.md
Labels: kind/docs, status/3-docs-review

#1690 Always initialize context store
  cli/command/cli.go
  cli/command/cli_test.go
  e2e/cli-plugins/dial_test.go
Labels: status/2-code-review

#1745 cli-plugins: disable use of dial-stdio
  cli-plugins/plugin/plugin.go
  e2e/cli-plugins/dial_test.go
Labels: area/plugins, status/2-code-review

#1719 Makes the default docker context behavior consistent
  cli/command/cli.go
  cli/command/context/create_test.go
  cli/command/context/export.go
  cli/command/context/inspect.go
  cli/command/context/list.go
  cli/command/context/list_test.go
  cli/command/context/remove_test.go
  cli/command/context/testdata/list.golden
  cli/command/context/testdata/list.no-context.golden
  cli/command/context/testdata/quiet-list.golden
  cli/command/defaultcontextstore.go
  cli/command/defaultcontextstore_test.go
  cli/command/stack/cmd.go
  cli/command/testdata/ca.pem
  cli/command/testdata/test-kubeconfig
  cli/context/store/store.go
  cli/context/store/store_test.go
  internal/test/cli.go
Labels: area/plugins, status/2-code-review

#1748 Add some spaces in docs for cosmetics and readability reasons.
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review

#1742 Bump Golang 1.11.6
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review

#1741 [18.09 backport] Fix: plugin-tests discarding current environment
  e2e/plugin/trust_test.go
  scripts/test/e2e/run
Labels: area/testing, status/2-code-review

#1524 Fix "warning" output on docker system prune
  cli/command/system/prune.go
  cli/command/system/prune_test.go
Labels: status/2-code-review

#1750 CircleCI: Increase no-output timeout to 15 minutes for vendoring
  circle.yml
Labels: area/testing, status/2-code-review

#1397 [master] fix subscription filter
  internal/licenseutils/utils.go
Labels: status/2-code-review

#1749 Update compose 3.8 to disallow additional properties
  cli/compose/schema/bindata.go
  cli/compose/schema/data/config_schema_v3.8.json
  cli/compose/schema/schema_test.go
Labels: impact/compose-file, status/2-code-review

#1744 [18.09 backport] various docs fixes
  docs/reference/commandline/attach.md
  docs/reference/commandline/build.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/manifest.md
  docs/reference/commandline/node_ps.md
  docs/reference/commandline/rmi.md
  docs/reference/commandline/run.md
  docs/reference/commandline/service_create.md
  docs/reference/commandline/stats.md
  man/src/container/exec.md
  man/src/image/rm.md
Labels: kind/docs, status/3-docs-review

#1740 build: enable platform flag for build if buildkit
  cli/command/image/build.go
  docs/reference/commandline/cli.md
Labels: area/builder, status/2-code-review

#1708 Bump Golang 1.12.1
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#1663 Add docs for --device option in Windows
  docs/reference/commandline/run.md
Labels: kind/docs, platform/windows, status/3-docs-review

#1746 [carry] Add support for `template_driver` in composefiles
  cli/compose/convert/compose.go
  cli/compose/loader/loader_test.go
  cli/compose/schema/bindata.go
  cli/compose/schema/data/config_schema_v3.8.json
  cli/compose/types/types.go
Labels: area/stack, impact/changelog, impact/compose-file, status/2-code-review

#1732 [pretty print] pretty print and healthcheck
  cli/command/service/formatter.go
  cli/command/service/inspect_test.go
Labels: status/2-code-review

#1671 Fix labels copying value from environment variables
  cli/command/config/create.go
  cli/command/container/opts.go
  cli/command/image/build.go
  cli/command/network/create.go
  cli/command/secret/create.go
  cli/command/service/opts.go
  cli/command/volume/create.go
  opts/envfile_test.go
  opts/file.go
  opts/opts.go
  opts/opts_test.go
Labels: status/2-code-review

#1704 Allow flags to be passed to e2e tests
  Makefile
  docker.Makefile
  scripts/test/e2e/run
Labels: area/testing, status/2-code-review

#1754 Add systctl support for services
  cli/command/service/create.go
  cli/command/service/formatter.go
  cli/command/service/opts.go
  cli/command/service/opts_test.go
  cli/command/service/update.go
  cli/command/service/update_test.go
  cli/compose/convert/service.go
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
  cli/compose/types/types.go
  contrib/completion/bash/docker
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_update.md
Labels: impact/changelog, impact/compose-file, impact/documentation, status/2-code-review

#1758 Update some dependencies
  vendor.conf
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/any.go
  vendor/github.com/json-iterator/go/iter_float.go
  vendor/github.com/json-iterator/go/iter_skip_strict.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_marshaler.go
  vendor/github.com/mattn/go-shellwords/shellwords.go
  vendor/github.com/mattn/go-shellwords/util_go15.go
  vendor/github.com/mattn/go-shellwords/util_posix.go
  vendor/github.com/mattn/go-shellwords/util_windows.go
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: status/2-code-review

#1763 bump docker/licensing to 9781369abdb5281cdc07a2a446c6df01347ec793
  vendor.conf
  vendor/github.com/docker/licensing/lib/go-auth/jwt/jwt.go
  vendor/github.com/docker/licensing/model/subscriptions.go
  vendor/github.com/docker/licensing/storage.go
  vendor/github.com/docker/licensing/types/types.go
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/uuid.go
Labels: status/2-code-review

#1759 Update authors
  .mailmap
  AUTHORS
Labels: status/3-docs-review

#1760 Search Windows CLI plugins also in ProgramFiles
  cli-plugins/manager/manager_windows.go
  docs/extend/cli_plugins.md
Labels: area/plugins, status/2-code-review

#1726 Add bash completion for `network ls --filter dangling`
  contrib/completion/bash/docker
Labels: area/completion, status/4-merge

#1727 Add bash completion for `builder prune`
  contrib/completion/bash/docker
Labels: area/builder, area/completion, status/2-code-review

#1764 Fix Windows LDFLAGS to use cli version package
  scripts/make.ps1
Labels: status/2-code-review

#1769 Fix annnotation on docker config create --template-driver
  cli/command/config/create.go
Labels: status/0-triage

#1766 build: allow setting buildkit outputs
  cli/command/image/build.go
  cli/command/image/build_buildkit.go
Labels: area/builder, docs/revisit, impact/changelog, status/4-merge

#1714 container: --gpus support
  cli/command/container/opts.go
  opts/gpus.go
  opts/gpus_test.go
Labels: status/4-merge

#1768 Fix error message on experimental flags
  cmd/docker/docker.go
Labels: status/0-triage

#1765 Add `--pids-limit` flag to `docker update`
  cli/command/container/update.go
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/reference/commandline/update.md
Labels: docs/revisit, impact/changelog, impact/documentation, status/2-code-review

#1733 [18.09 backport] dial-stdio: handle connections which lack CloseRead method
  cli/command/system/dial_stdio.go
Labels: status/2-code-review

#1678 give `docker save` a gzip usage guide
  docs/reference/commandline/save.md
Labels: dco/no, kind/docs, status/3-docs-review

#1626 Add bash completion for `docker engine` command family
  contrib/completion/bash/docker
Labels: area/completion, status/2-code-review

#1692 Remove some bashisms
  scripts/build/cross
  scripts/gen/windows-resources
  scripts/test/e2e/entry
  scripts/test/e2e/load-image
  scripts/test/e2e/run
  scripts/test/e2e/wrapper
Labels: status/2-code-review

#1770 Fix archive detection
  cli/command/image/build/context.go
  cli/command/image/build/context_test.go
  cli/command/image/testdata/Dockerfile.test
  cli/command/image/testdata/gittar.test
  cli/command/image/testdata/tar.test
Labels: status/0-triage

#1778 [18.09] bump engine 200b524eff60a9c95a22bc2518042ac2ff617d07 (18.09 branch)
  vendor.conf
  vendor/github.com/docker/docker/builder/remotecontext/git/gitutils.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/pkg/archive/copy.go
  vendor/github.com/docker/docker/pkg/mount/sharedsubtree_linux.go
  vendor/github.com/docker/docker/pkg/progress/progress.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/github.com/docker/docker/vendor.conf
Labels: status/2-code-review

#1785 Fix annotation on docker secret create --template-driver
  cli/command/secret/create.go
Labels: status/2-code-review

#1776 [18.09 backport] use official shellcheck 0.6.0, and don't patch Dockerfiles in CI
  circle.yml
  contrib/completion/bash/docker
  docker.Makefile
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.shellcheck
  scripts/gen/windows-resources
  scripts/test/e2e/run
  scripts/warn-outside-container
Labels: area/testing, status/2-code-review

#1775 [18.09 backport] fixes 1492: tty initial size error
  cli/command/container/client_test.go
  cli/command/container/export_test.go
  cli/command/container/tty.go
  cli/command/container/tty_test.go
Labels: status/2-code-review

#1788 [18.09 backport] fix annotations on --template-driver
  cli/command/config/create.go
  cli/command/secret/create.go
Labels: status/2-code-review

#1789 Fix login logout when engine is down and credential helper is in use
  cli/command/registry.go
Labels: status/0-triage

#1787 cli-plugins: Reinstate deprecated `-h` short form of `--help`.
  cli/cobra.go
  e2e/cli-plugins/run_test.go
Labels: area/plugins, status/2-code-review
