Repository docker/cli, pull requests merged in 2019-09, with the labels that each got.

#2050 Bump golang 1.12.9
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: process/cherry-pick, status/2-code-review

#2073 Add docker-compose schema v3.9
  Makefile
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
  cli/compose/schema/bindata.go
  cli/compose/schema/data/config_schema_v3.9.json
  cli/compose/schema/schema_test.go
  docker.Makefile
Labels: impact/changelog, impact/compose-file, status/2-code-review

#2051 bump miekg/pkcs11 v1.0.2
  vendor.conf
  vendor/github.com/miekg/pkcs11/go.mod
  vendor/github.com/miekg/pkcs11/params.go
  vendor/github.com/miekg/pkcs11/pkcs11.go
  vendor/github.com/miekg/pkcs11/release.go
Labels: process/cherry-pick, status/2-code-review

#2028 Sort list of services from swarm stacks using natural sorting
  cli/command/stack/swarm/services.go
Labels: area/stack, status/2-code-review

#1958 bump gorilla/mux v1.7.2
  vendor.conf
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
Labels: process/cherry-pick, status/2-code-review

#2084 Add riscv64 to manifest annotation and bash completion
  cli/command/manifest/util.go
  contrib/completion/bash/docker
Labels: status/0-triage

#2077 Clarifying docker config rules
  docs/reference/commandline/cli.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#2060 Add option to remove `env_file` entry once it's merged in the `environment` section
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
Labels: process/cherry-pick, status/2-code-review

#2090 [19.03 backport] Bump golang 1.12.9
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#2081 [18.09 backport] bump LK4D4/vndr v0.0.3 and revendor
  dockerfiles/Dockerfile.dev
  vendor/github.com/google/uuid/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gotest.tools/go.mod
Labels: status/2-code-review

#2099 [19.03 backport] bump LK4D4/vndr v0.0.3 and revendor
  dockerfiles/Dockerfile.dev
  vendor/github.com/gogo/googleapis/go.mod
  vendor/github.com/gogo/protobuf/go.mod
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/gorilla/mux/go.mod
  vendor/github.com/jaguilar/vt100/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/mattn/go-shellwords/go.mod
  vendor/github.com/moby/buildkit/go.mod
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/tonistiigi/fsutil/go.mod
  vendor/golang.org/x/crypto/go.mod
  vendor/golang.org/x/net/go.mod
  vendor/golang.org/x/sync/go.mod
  vendor/golang.org/x/sys/go.mod
  vendor/google.golang.org/grpc/go.mod
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gotest.tools/go.mod
Labels: status/2-code-review

#2101 cli/config: use os.UserHomeDir instead of github.com/docker/docker/pkg/homedir
  cli/config/config.go
  cli/config/config_test.go
Labels: status/0-triage

#2106 config: keep configDir empty when homedir errors
  cli/config/config.go
Labels: status/0-triage

#2103 vendor: update buildkit to 10cef0c and fsutil 7f9f923
  cli/command/image/build_buildkit.go
  vendor.conf
  vendor/github.com/moby/buildkit/README.md
  vendor/github.com/moby/buildkit/client/llb/exec.go
  vendor/github.com/moby/buildkit/client/llb/meta.go
  vendor/github.com/moby/buildkit/client/llb/state.go
  vendor/github.com/moby/buildkit/client/solve.go
  vendor/github.com/moby/buildkit/frontend/gateway/grpcclient/client.go
  vendor/github.com/moby/buildkit/go.mod
  vendor/github.com/moby/buildkit/session/auth/auth.go
  vendor/github.com/moby/buildkit/session/content/caller.go
  vendor/github.com/moby/buildkit/session/filesync/diffcopy.go
  vendor/github.com/moby/buildkit/session/filesync/filesync.go
  vendor/github.com/moby/buildkit/session/secrets/secrets.go
  vendor/github.com/moby/buildkit/session/sshforward/copy.go
  vendor/github.com/moby/buildkit/session/sshforward/ssh.go
  vendor/github.com/moby/buildkit/session/sshforward/sshprovider/agentprovider.go
  vendor/github.com/moby/buildkit/solver/pb/caps.go
  vendor/github.com/tonistiigi/fsutil/go.mod
  vendor/github.com/tonistiigi/fsutil/stat.go
Labels: status/0-triage

#2079 [19.03 backport] bump miekg/pkcs11 v1.0.2
  vendor.conf
  vendor/github.com/miekg/pkcs11/go.mod
  vendor/github.com/miekg/pkcs11/params.go
  vendor/github.com/miekg/pkcs11/pkcs11.go
  vendor/github.com/miekg/pkcs11/release.go
Labels: status/2-code-review

#2113 [19.03 backport] bump golang 1.12.10 (CVE-2019-16276)
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/0-triage, status/2-code-review

#2112 bump golang 1.12.10 (CVE-2019-16276)
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, process/cherry-pick, status/0-triage, status/2-code-review

#2114 [18.09] bump golang 1.12.10 (CVE-2019-16276)
  appveyor.yml
  docker.Makefile
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review
