Repository docker/cli, pull requests merged in 2019-07, with the labels that each got.

#1484 Deprecate AuFS storage driver
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/3-docs-review

#1976 [19.03 backport] Deprecate AuFS storage driver
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review

#1973 Fix Rollback config type interpolation
  cli/compose/loader/interpolate.go
  cli/compose/loader/loader_test.go
Labels: area/stack, impact/compose-file, process/cherry-pick, status/2-code-review

#1978 [18.09 backport] Fix Rollback config type interpolation
  cli/compose/loader/interpolate.go
  cli/compose/loader/loader_test.go
Labels: area/stack, status/2-code-review

#1968 Windows: skip permissions check on key
  cli/command/trust/key_load.go
Labels: area/trust, process/cherry-pick, status/2-code-review

#1974 Nvidia gpu access
  docs/reference/commandline/run.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#1992 e2e: use stable-dind image for testing
  e2e/compose-env.yaml
Labels: area/testing, process/cherry-pick, status/2-code-review

#1990 Detect Windows absolute paths on non-Windows CLI
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
  cli/compose/loader/windows_path.go
  cli/compose/loader/windows_path_test.go
Labels: area/stack, platform/windows, status/2-code-review

#1999 docs: add info for events backlog and scope
  docs/reference/commandline/events.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#1979 [19.03 backport] Fix Rollback config type interpolation
  cli/compose/loader/interpolate.go
  cli/compose/loader/loader_test.go
Labels: area/stack, status/2-code-review

#1972 [19.03 backport] bump compose-on-kubernetes v0.4.23
  vendor.conf
Labels: area/kubernetes, area/stack, status/2-code-review

#2000 docker ps: add State field to formatting
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
  cli/command/formatter/custom.go
  docs/reference/commandline/ps.md
Labels: impact/changelog, kind/enhancement, status/2-code-review

#1996 Bump golang 1.12.7
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, process/cherry-picked, status/2-code-review

#1599 Update CircleCI Docker version to 18.09.3
  circle.yml
Labels: area/testing, process/cherry-pick, status/2-code-review

#2014 builder.md: Correct copy/paste error
  docs/reference/builder.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#2008 Dockerfile: use GO_VERSION build-arg for overriding Go version
  docker.Makefile
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: process/cherry-pick, status/2-code-review

#2002 [18.09 backport] assorted docs and completion script fixes
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/reference/commandline/events.md
Labels: area/completion, kind/docs, status/2-code-review

#2001 [19.03 backport] assorted docs and completion script fixes
  contrib/completion/zsh/_docker
  docs/reference/commandline/events.md
  docs/reference/commandline/run.md
Labels: area/completion, kind/docs, status/2-code-review

#1793 [18.09 backport] CircleCI: Increase no-output timeout to 15 minutes for vendoring
  circle.yml
Labels: area/testing, status/2-code-review

#1709 [18.09 backport] bump Golang 1.11.11, and some makefile improvements
  Makefile
  appveyor.yml
  cli/command/stack/swarm/deploy_test.go
  cli/registry/client/fetcher.go
  docker.Makefile
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  opts/hosts_test.go
  scripts/build/osx
Labels: status/2-code-review

#1994 [18.09 backport] Detect Windows absolute paths on non-Windows CLI
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
  cli/compose/loader/windows_path.go
  cli/compose/loader/windows_path_test.go
Labels: area/stack, impact/changelog, status/2-code-review

#1971 [18.09 backport] Windows: skip permissions check on key
  cli/command/trust/key_load.go
Labels: area/trust, status/2-code-review

#1959 [18.09 backport] bump docker/licensing to 9781369abdb5281cdc07a2a446c6df01347ec793
  vendor.conf
  vendor/github.com/docker/licensing/lib/go-auth/jwt/jwt.go
  vendor/github.com/docker/licensing/model/subscriptions.go
  vendor/github.com/docker/licensing/storage.go
  vendor/github.com/docker/licensing/types/types.go
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/satori/go.uuid/LICENSE
  vendor/github.com/satori/go.uuid/README.md
  vendor/github.com/satori/go.uuid/uuid.go
Labels: status/2-code-review

#1961 [18.09 backport] bump gotest.tools 2.3.0, and reformat vendor.conf
  vendor.conf
  vendor/gotest.tools/LICENSE
  vendor/gotest.tools/README.md
  vendor/gotest.tools/assert/cmp/compare.go
  vendor/gotest.tools/assert/cmp/result.go
  vendor/gotest.tools/assert/result.go
  vendor/gotest.tools/env/env.go
  vendor/gotest.tools/fs/file.go
  vendor/gotest.tools/fs/manifest.go
  vendor/gotest.tools/fs/ops.go
  vendor/gotest.tools/fs/path.go
  vendor/gotest.tools/fs/report.go
  vendor/gotest.tools/golden/golden.go
  vendor/gotest.tools/icmd/command.go
  vendor/gotest.tools/icmd/ops.go
  vendor/gotest.tools/internal/difflib/difflib.go
  vendor/gotest.tools/internal/source/defers.go
  vendor/gotest.tools/internal/source/source.go
  vendor/gotest.tools/poll/check.go
  vendor/gotest.tools/poll/poll.go
  vendor/gotest.tools/skip/skip.go
Labels: area/testing, status/2-code-review

#1995 [19.03 backport] Detect Windows absolute paths on non-Windows CLI
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
  cli/compose/loader/windows_path.go
  cli/compose/loader/windows_path_test.go
Labels: area/stack, status/2-code-review

#2020 Disable TLS for e2e docker-in-docker daemon
  e2e/compose-env.yaml
Labels: area/testing, process/cherry-pick, status/2-code-review

#2023 switch kr/pty to creack/pty v1.1.7
  NOTICE
  e2e/container/proxy_signal_test.go
  vendor.conf
  vendor/github.com/creack/pty/LICENSE
  vendor/github.com/creack/pty/README.md
  vendor/github.com/creack/pty/doc.go
  vendor/github.com/creack/pty/ioctl.go
  vendor/github.com/creack/pty/ioctl_bsd.go
  vendor/github.com/creack/pty/ioctl_solaris.go
  vendor/github.com/creack/pty/pty_darwin.go
  vendor/github.com/creack/pty/pty_dragonfly.go
  vendor/github.com/creack/pty/pty_freebsd.go
  vendor/github.com/creack/pty/pty_linux.go
  vendor/github.com/creack/pty/pty_openbsd.go
  vendor/github.com/creack/pty/pty_solaris.go
  vendor/github.com/creack/pty/pty_unsupported.go
  vendor/github.com/creack/pty/run.go
  vendor/github.com/creack/pty/util.go
  vendor/github.com/creack/pty/util_solaris.go
  vendor/github.com/creack/pty/ztypes_386.go
  vendor/github.com/creack/pty/ztypes_amd64.go
  vendor/github.com/creack/pty/ztypes_arm.go
  vendor/github.com/creack/pty/ztypes_arm64.go
  vendor/github.com/creack/pty/ztypes_dragonfly_amd64.go
  vendor/github.com/creack/pty/ztypes_freebsd_386.go
  vendor/github.com/creack/pty/ztypes_freebsd_amd64.go
  vendor/github.com/creack/pty/ztypes_freebsd_arm.go
  vendor/github.com/creack/pty/ztypes_mipsx.go
  vendor/github.com/creack/pty/ztypes_openbsd_386.go
  vendor/github.com/creack/pty/ztypes_openbsd_amd64.go
  vendor/github.com/creack/pty/ztypes_ppc64.go
  vendor/github.com/creack/pty/ztypes_ppc64le.go
  vendor/github.com/creack/pty/ztypes_riscvx.go
  vendor/github.com/creack/pty/ztypes_s390x.go
  vendor/github.com/kr/pty/go.mod
Labels: area/testing, process/cherry-pick, status/2-code-review

#2016 TestSigProxyWithTTY: fix
  e2e/container/proxy_signal_test.go
Labels: area/testing, status/2-code-review
