Repository docker/cli, pull requests merged in 2020-04, with the labels that each got.

#2417 Bump Golang 1.13.9
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: process/cherry-pick, status/2-code-review

#2419 [19.03 backport] Bump Golang 1.13.9
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review

#2428 CI: update notary test certificates
  e2e/testdata/notary-evil/notary-server.cert
  e2e/testdata/notary-evil/notary-server.key
  e2e/testdata/notary-evil/root-ca.cert
  e2e/testdata/notary/notary-server.cert
  e2e/testdata/notary/notary-server.key
  e2e/testdata/notary/root-ca.cert
Labels: area/testing, process/cherry-pick, status/2-code-review

#2427 TestHistoryContext_CreatedSince: skip on non-UTC environments
  cli/command/image/formatter_history_test.go
Labels: area/testing, status/2-code-review

#2426 test: make sure environment vars are reset after tests
  cli/command/image/trust_test.go
  cli/config/config_test.go
Labels: area/testing, status/2-code-review

#2430 Bump Golang 1.13.10
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, process/cherry-pick, status/2-code-review

#2435 [19.03 backport] CI: update notary test certificates
  e2e/testdata/notary-evil/notary-server.cert
  e2e/testdata/notary-evil/notary-server.key
  e2e/testdata/notary-evil/root-ca.cert
  e2e/testdata/notary/notary-server.cert
  e2e/testdata/notary/notary-server.key
  e2e/testdata/notary/root-ca.cert
Labels: area/testing, status/2-code-review

#2431 [19.03 backport] Bump Golang 1.13.10
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#2415 calculateMemUsageUnixNoCache: subtract total_inactive_file, not cache
  cli/command/container/stats_helpers.go
  cli/command/container/stats_helpers_test.go
  docs/reference/commandline/stats.md
Labels: impact/changelog, status/2-code-review

#2418 vendor: update go-events to fix alignment for 32bit systems
  vendor.conf
  vendor/github.com/docker/go-events/retry.go
Labels: process/cherry-pick, status/2-code-review

#2434 opts: use constants instead of vars for defaults and un-export them
  opts/hosts.go
  opts/hosts_test.go
  opts/hosts_unix.go
  opts/hosts_windows.go
  opts/opts_unix.go
  opts/opts_windows.go
Labels: status/2-code-review

#2443 Add "host-gateway" to tests for extra_hosts / --add-host
  cli/command/service/update_test.go
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/loader_test.go
  opts/hosts_test.go
Labels: area/testing, process/cherry-picked, status/2-code-review

#2444 [19.03 backport] Skip IPAddr validation for "host-gateway" string
  cli/command/service/update_test.go
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/loader_test.go
  opts/hosts.go
  opts/hosts_test.go
Labels: status/2-code-review

#2442 [19.03 backport] vendor: update go-events to fix alignment for 32bit systems
  vendor.conf
  vendor/github.com/docker/go-events/retry.go
Labels: status/2-code-review

#2424 cli: perform feature detection lazily
  cli/command/cli.go
  cli/command/image/build.go
  cli/command/image/build_test.go
  cmd/docker/docker.go
Labels: process/cherry-pick, status/2-code-review

#2454 yamldocs: add description to base command
  docs/yaml/generate.go
Labels: kind/docs, process/cherry-picked, status/3-docs-review

#2429 Add script to regenerate test-certificate fixtures
  e2e/testdata/gen-certs.sh
Labels: area/testing, process/cherry-pick, status/2-code-review

#2433 Jenkinsfile: split e2e tests to separate stages
  Jenkinsfile
Labels: area/testing, process/cherry-pick, status/2-code-review

#2432 improve "network prune" output to mention custom networks only
  cli/command/network/prune.go
  docs/reference/commandline/network_prune.md
Labels: kind/enhancement, process/cherry-picked, status/2-code-review

#2445 [19.03 backport] improve "network prune" output to mention custom networks only
  cli/command/network/prune.go
  docs/reference/commandline/network_prune.md
Labels: status/2-code-review

#2465 Add container_iface_prefix option to documentation
  docs/reference/commandline/network_create.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#2466 service update: fix service create example
  docs/reference/commandline/service_update.md
Labels: area/swarm, kind/docs, process/cherry-pick, status/3-docs-review

#2469 [19.03 backport] assorted docs fixes
  docs/reference/commandline/network_create.md
  docs/reference/commandline/service_update.md
Labels: kind/docs, status/3-docs-review

#1918 completion with container names on restart
  contrib/completion/zsh/_docker
Labels: area/completion, status/2-code-review

#2476 vendor: update gotest.tools v3.0.2
  vendor.conf
  vendor/gotest.tools/v3/assert/assert.go
Labels: area/testing, status/2-code-review

#2474 plugin: make runplugin public
  cli-plugins/plugin/plugin.go
Labels: status/2-code-review

#2472 vendor: update kubernetes and dependencies v1.16.9
  vendor.conf
  vendor/k8s.io/api/go.mod
  vendor/k8s.io/apiextensions-apiserver/go.mod
  vendor/k8s.io/apimachinery/go.mod
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/intstr.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/net/http.go
  vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go
  vendor/k8s.io/apiserver/go.mod
  vendor/k8s.io/client-go/go.mod
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/client-go/util/connrotation/connrotation.go
  vendor/k8s.io/component-base/go.mod
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/kubernetes/go.mod
Labels: area/kubernetes, status/2-code-review

#2478 vendor: sirupsen/logrus v1.5.0
  vendor.conf
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: status/2-code-review

#2479 info: print Cgroup Version
  cli/command/system/info.go
  vendor.conf
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/vendor.conf
Labels: status/2-code-review

#2480 docs: fix links, and minor markdown touch-ups
  docs/reference/builder.md
  docs/reference/run.md
Labels: kind/docs, process/cherry-picked, status/3-docs-review

#2481 [19.03 backport] docs: fix links, and minor markdown touch-ups
  docs/reference/builder.md
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review

#2470 [19.03 backport] vendor: bump gopkg.in/yaml.v2 v2.2.8
  vendor.conf
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/gopkg.in/yaml.v2/yamlh.go
Labels: status/2-code-review

#2471 [19.03 backport] fix panic on single-character volumes
  cli/compose/loader/volume.go
  cli/compose/loader/volume_test.go
Labels: status/2-code-review

#2457 [19.03 backport] cli: perform feature detection lazily
  cli/command/cli.go
  cli/command/image/build.go
  cli/command/image/build_test.go
  cmd/docker/docker.go
Labels: status/2-code-review

#2484 [19.03 backport] builder: fix broken link
  docs/reference/builder.md
Labels: area/builder, kind/docs, status/3-docs-review

#2483 builder: fix broken link
  docs/reference/builder.md
Labels: area/builder, kind/docs, process/cherry-pick, status/3-docs-review
