Repository docker/cli, pull requests merged in 2020-06, with the labels that each got.

#2569 Use consistent name for errors
  cli/command/container/run.go
Labels: status/2-code-review

#2448 Deprecate classic Swarm and overlay networks using external k/v stores
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review

#2562 Bump Golang 1.13.12
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: process/cherry-pick, status/2-code-review

#2547 docs: fix broken link in dockerd.md
  docs/reference/commandline/dockerd.md
Labels: kind/docs, process/cherry-picked, status/3-docs-review

#2548 [19.03 backport] docs: fix broken link in dockerd.md
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#2563 CircleCI: update docker versions used in CI
  circle.yml
Labels: area/testing, status/2-code-review

#2551 Platform on create
  cli/command/container/client_test.go
  cli/command/container/create.go
  cli/command/container/create_test.go
  cli/command/container/run_test.go
  vendor.conf
  vendor/github.com/docker/docker/api/types/configs.go
  vendor/github.com/docker/docker/api/types/container/container_top.go
  vendor/github.com/docker/docker/api/types/volume.go
  vendor/github.com/docker/docker/api/types/volume/volume_create.go
  vendor/github.com/docker/docker/api/types/volume/volume_list.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/client/errors.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/docker/docker/pkg/idtools/idtools.go
  vendor/github.com/docker/docker/pkg/system/syscall_windows.go
  vendor/github.com/docker/docker/registry/config_unix.go
  vendor/github.com/docker/docker/registry/config_windows.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/github.com/docker/docker/vendor.conf
Labels: impact/changelog, status/2-code-review

#2572 Don't loose additional metadata fields when read/writing contexts metadata
  cli/command/context.go
  cli/command/context_test.go
Labels: area/context, status/2-code-review

#2570 [19.03 backport] Use consistent name for errors
  cli/command/container/run.go
Labels: status/2-code-review

#2579 config: fix error message using incorrect filename
  cli/config/config.go
Labels: status/2-code-review

#2578 Added support for setting OS version in docker manifest annotate.
  cli/command/manifest/annotate.go
  cli/command/manifest/annotate_test.go
  cli/command/manifest/testdata/inspect-annotate.golden
  docs/reference/commandline/manifest.md
Labels: kind/experimental, status/2-code-review

#2580 Remove 'images' alias from 'image ls' command
  cli/command/image/list.go
  cli/command/image/list_test.go
Labels: status/2-code-review

#2561 docs: fix broken link
  docs/reference/builder.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#2586 [19.03 backport] Don't loose additional metadata fields
  cli/command/context.go
  cli/command/context_test.go
Labels: status/2-code-review

#2574 Environment variable changes (carry #806)
  docs/reference/commandline/cli.md
  docs/reference/commandline/dockerd.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#2575 [19.03 backport] Bump Golang 1.13.12
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#2557 [19.03 backport] docs/extend: fix broken link and some markdown touch-ups
  docs/extend/config.md
  docs/extend/plugins_network.md
Labels: kind/docs, status/3-docs-review

#2583 Don't filter out registries to logout from with config file contents
  cli/command/registry/logout.go
Labels: status/2-code-review

#2591 [19.03 backport] assorted docs fixes
  docs/reference/builder.md
  docs/reference/commandline/cli.md
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#2592 [19.03 backport] Don't filter out registries to logout from with config file contents
  cli/command/registry/logout.go
Labels: impact/changelog, status/2-code-review

#2503 Add support for --limit-pids on service create / update and stacks (swarm)
  cli/command/service/formatter.go
  cli/command/service/inspect_test.go
  cli/command/service/opts.go
  cli/command/service/opts_test.go
  cli/command/service/testdata/service-inspect-pretty.golden
  cli/command/service/update.go
  cli/command/service/update_test.go
  cli/command/stack/kubernetes/convert.go
  cli/compose/convert/service.go
  cli/compose/convert/service_test.go
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/types_test.go
  cli/compose/schema/bindata.go
  cli/compose/schema/data/config_schema_v3.9.json
  cli/compose/types/types.go
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_update.md
Labels: area/swarm, impact/changelog, impact/documentation, status/2-code-review

#2593 docs: fix example output for docker plugin ls
  docs/reference/commandline/plugin_create.md
  docs/reference/commandline/plugin_disable.md
  docs/reference/commandline/plugin_enable.md
  docs/reference/commandline/plugin_install.md
  docs/reference/commandline/plugin_ls.md
  docs/reference/commandline/plugin_push.md
Labels: area/plugins, kind/docs, process/cherry-pick, status/3-docs-review

#2556 docs/extend: fix broken link and some markdown touch-ups
  docs/extend/config.md
  docs/extend/plugins_network.md
Labels: kind/docs, process/cherry-picked, status/3-docs-review

#2571 [master forward-port] list state `ready` for filtering in stack_ps.md
  docs/reference/commandline/stack_ps.md
Labels: kind/docs, status/3-docs-review

#2581 config: remove redundant os.Stat()
  cli/config/config.go
  cli/config/config_test.go
Labels: status/2-code-review

#2568 vendor: gorilla/mux v1.7.4
  vendor.conf
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/context.go
  vendor/github.com/gorilla/mux/go.mod
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
Labels: status/2-code-review

#2600 docs: update for cgroup v2 and rootless
  docs/reference/commandline/dockerd.md
  man/docker-run.1.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review

#2604 command/container: skip some tests on macOS
  cli/command/container/opts_test.go
Labels: area/testing, status/2-code-review

#2603 ReadKVEnvStrings/ReadKVStrings return nil if empty, and add tests
  opts/parse.go
  opts/parse_test.go
Labels: status/2-code-review

#2608 [19.03 backport] minor vendor bumps
  vendor.conf
  vendor/github.com/beorn7/perks/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/mitchellh/mapstructure/go.mod
Labels: status/2-code-review

#2609 [19.03 backport] assorted docs fixes
  docs/reference/commandline/plugin_create.md
  docs/reference/commandline/plugin_disable.md
  docs/reference/commandline/plugin_enable.md
  docs/reference/commandline/plugin_install.md
  docs/reference/commandline/plugin_ls.md
  docs/reference/commandline/plugin_push.md
  docs/reference/commandline/stack_ps.md
Labels: kind/docs, status/3-docs-review
