Repository docker/cli, pull requests merged in 2020-07, with the labels that each got.

#2617 docs/builder: add note about handling of leading whitespace
  docs/reference/builder.md
Labels: area/builder, kind/docs, process/cherry-pick, status/3-docs-review

#2616 refactor opts tests
  cli/command/container/opts_test.go
Labels: area/testing, status/2-code-review

#2612 vendor: xeipuuv/gojsonschema v1.2.0
  vendor.conf
  vendor/github.com/xeipuuv/gojsonschema/README.md
  vendor/github.com/xeipuuv/gojsonschema/draft.go
  vendor/github.com/xeipuuv/gojsonschema/errors.go
  vendor/github.com/xeipuuv/gojsonschema/format_checkers.go
  vendor/github.com/xeipuuv/gojsonschema/go.mod
  vendor/github.com/xeipuuv/gojsonschema/jsonContext.go
  vendor/github.com/xeipuuv/gojsonschema/jsonLoader.go
  vendor/github.com/xeipuuv/gojsonschema/locales.go
  vendor/github.com/xeipuuv/gojsonschema/result.go
  vendor/github.com/xeipuuv/gojsonschema/schema.go
  vendor/github.com/xeipuuv/gojsonschema/schemaLoader.go
  vendor/github.com/xeipuuv/gojsonschema/schemaPool.go
  vendor/github.com/xeipuuv/gojsonschema/subSchema.go
  vendor/github.com/xeipuuv/gojsonschema/types.go
  vendor/github.com/xeipuuv/gojsonschema/utils.go
  vendor/github.com/xeipuuv/gojsonschema/validation.go
Labels: status/2-code-review

#2611 vendor: mitchellh/mapstructure v1.3.2
  vendor.conf
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/mitchellh/mapstructure/mapstructure.go
Labels: status/2-code-review

#2596 Add checks for dependencies that are not vendored
  .dockerignore
  .gitignore
  Makefile
  scripts/validate/check-all-packages-vendored
Labels: area/testing, status/2-code-review

#2620 [19.03 backport] docs/builder: add note about handling of leading whitespace
  docs/reference/builder.md
Labels: kind/docs, status/3-docs-review

#2546 Some minor refactoring and reformatting
  cli/command/stack/swarm/deploy.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/stack/swarm/deploy_test.go
Labels: status/2-code-review

#2599 config: ignore empty config file instead of printing warning
  cli/config/config_test.go
  cli/config/configfile/file.go
Labels: status/2-code-review

#2623 [19.03 backport] vendor: golang.org/x/crypto 2aa609cf4a9d7d1126360de73b55b6002f9e052a
  vendor.conf
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.go
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
  vendor/golang.org/x/crypto/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.s
  vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/poly1305/sum_s390x.s
  vendor/golang.org/x/crypto/poly1305/sum_vmsl_s390x.s
  vendor/golang.org/x/crypto/ssh/internal/bcrypt_pbkdf/bcrypt_pbkdf.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
Labels: status/2-code-review

#2595 Handle errors on close in config file write.
  cli/config/configfile/file.go
Labels: status/2-code-review

#2630 Add CodeQL Analysis workflow
  .github/workflows/codeql.yml
Labels: area/testing, status/2-code-review

#2628 Move circle.yml to .circleci/config.yml
  .circleci/config.yml
Labels: area/testing, process/cherry-picked, status/2-code-review

#2629 [19.03 backport] CircleCI updates
  .circleci/config.yml
Labels: area/testing, status/2-code-review

#2627 Fix ConfigFile.Save() replacing symlink with file
  cli/config/configfile/file.go
  cli/config/configfile/file_test.go
Labels: status/2-code-review

#2632 Bump Golang 1.13.13
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, process/cherry-picked, status/2-code-review

#2626 Cleanup some tests formatting, and remove deprecated compareMultipleValues() utility
  cli/command/formatter/container_test.go
  cli/command/formatter/custom_test.go
  cli/command/formatter/image_test.go
  cli/command/formatter/volume_test.go
Labels: area/testing, status/2-code-review

#2631 [19.03] handle close error on save
  cli/config/configfile/file.go
  cli/config/configfile/file_unix.go
  cli/config/configfile/file_windows.go
Labels: status/2-code-review

#2633 [19.03 backport] Bump Golang 1.13.13
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#2640 Revert "Add CodeQL Analysis workflow"
  .github/workflows/codeql.yml
Labels: area/testing, status/2-code-review

#2624 scripts/make.ps1: actually define the CommitSuffix parameter
  scripts/make.ps1
Labels: area/testing, status/2-code-review

#2638 added 'docker build --target' to zsh completion
  contrib/completion/zsh/_docker
Labels: area/completion, status/2-code-review

#2634 Bump Golang 1.13.14
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, process/cherry-picked, status/2-code-review

#2635 [19.03 backport] Bump Golang 1.13.14
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#2639 Replace mattn/go-shellwords with google/shlex
  cli/compose/loader/loader.go
  vendor.conf
  vendor/github.com/mattn/go-shellwords/LICENSE
  vendor/github.com/mattn/go-shellwords/README.md
  vendor/github.com/mattn/go-shellwords/go.mod
  vendor/github.com/mattn/go-shellwords/shellwords.go
  vendor/github.com/mattn/go-shellwords/util_go15.go
  vendor/github.com/mattn/go-shellwords/util_posix.go
  vendor/github.com/mattn/go-shellwords/util_windows.go
Labels: impact/compose-file, status/2-code-review

#2641 vendor: update docker and buildkit
  vendor.conf
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/client/client_unix.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/LICENSE
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/README.md
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/doc.go
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/go.mod
  vendor/github.com/grpc-ecosystem/go-grpc-middleware/wrappers.go
  vendor/github.com/moby/buildkit/README.md
  vendor/github.com/moby/buildkit/client/client.go
  vendor/github.com/moby/buildkit/client/connhelper/connhelper.go
  vendor/github.com/moby/buildkit/client/llb/async.go
  vendor/github.com/moby/buildkit/client/llb/definition.go
  vendor/github.com/moby/buildkit/client/llb/exec.go
  vendor/github.com/moby/buildkit/client/llb/fileop.go
  vendor/github.com/moby/buildkit/client/llb/marshal.go
  vendor/github.com/moby/buildkit/client/llb/source.go
  vendor/github.com/moby/buildkit/client/llb/sourcemap.go
  vendor/github.com/moby/buildkit/client/llb/state.go
  vendor/github.com/moby/buildkit/frontend/gateway/grpcclient/client.go
  vendor/github.com/moby/buildkit/frontend/gateway/pb/caps.go
  vendor/github.com/moby/buildkit/frontend/gateway/pb/gateway.proto
  vendor/github.com/moby/buildkit/go.mod
  vendor/github.com/moby/buildkit/session/auth/auth.go
  vendor/github.com/moby/buildkit/session/filesync/diffcopy.go
  vendor/github.com/moby/buildkit/session/filesync/filesync.go
  vendor/github.com/moby/buildkit/session/grpc.go
  vendor/github.com/moby/buildkit/session/secrets/secrets.go
  vendor/github.com/moby/buildkit/session/secrets/secretsprovider/secretsprovider.go
  vendor/github.com/moby/buildkit/session/session.go
  vendor/github.com/moby/buildkit/solver/pb/ops.pb.go
  vendor/github.com/moby/buildkit/solver/pb/ops.proto
  vendor/github.com/moby/buildkit/util/entitlements/entitlements.go
  vendor/github.com/moby/buildkit/util/flightcontrol/flightcontrol.go
  vendor/github.com/moby/buildkit/util/grpcerrors/grpcerrors.go
  vendor/github.com/moby/buildkit/util/grpcerrors/intercept.go
  vendor/github.com/moby/buildkit/util/progress/progressui/display.go
  vendor/github.com/moby/buildkit/util/progress/progressui/printer.go
  vendor/github.com/moby/buildkit/util/stack/generate.go
  vendor/github.com/moby/buildkit/util/stack/stack.go
  vendor/github.com/moby/buildkit/util/stack/stack.pb.go
  vendor/github.com/moby/buildkit/util/stack/stack.proto
  vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
  vendor/github.com/opencontainers/runc/libcontainer/system/proc.go
  vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_32.go
  vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go
  vendor/github.com/opencontainers/runc/libcontainer/system/sysconfig.go
  vendor/github.com/opencontainers/runc/libcontainer/system/sysconfig_notcgo.go
  vendor/github.com/opencontainers/runc/libcontainer/system/unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/system/xattrs_linux.go
Labels: status/2-code-review

#2395 Add DefaultAddressPool to docker info
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-info-badsec.golden
  cli/command/system/testdata/docker-info-badsec.json.golden
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-legacy-warnings.json.golden
  cli/command/system/testdata/docker-info-no-swarm.golden
  cli/command/system/testdata/docker-info-no-swarm.json.golden
  cli/command/system/testdata/docker-info-plugins.golden
  cli/command/system/testdata/docker-info-plugins.json.golden
  cli/command/system/testdata/docker-info-with-swarm.golden
  cli/command/system/testdata/docker-info-with-swarm.json.golden
Labels: area/networking, impact/changelog, status/2-code-review

#2652 deprecate `docker run --kernel-memory`
  docs/deprecated.md
  docs/reference/commandline/update.md
  man/src/container/update.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review

#2659 vendor: update docker/docker 0f41a77c6993ade605a639fb25994cfe5e1b3fe8
  vendor.conf
  vendor/github.com/docker/docker/api/types/container/host_config.go
  vendor/github.com/docker/docker/api/types/swarm/container.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/client/service_create.go
  vendor/github.com/docker/docker/client/service_update.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/docker/swarmkit/api/specs.pb.go
  vendor/github.com/docker/swarmkit/api/specs.proto
Labels: area/swarm, status/2-code-review

#2658 vendor: update tonistiigi/fsutil ae3a8d753069d0f76fbee396457e8b6cfd7cb8c3
  vendor.conf
  vendor/github.com/tonistiigi/fsutil/go.mod
  vendor/github.com/tonistiigi/fsutil/stat_unix.go
  vendor/github.com/tonistiigi/fsutil/walker.go
Labels: status/2-code-review

#2654 support emulated version detection
  cli/command/image/build_buildkit.go
  cli/command/system/version.go
  vendor.conf
  vendor/github.com/tonistiigi/go-rosetta/LICENSE
  vendor/github.com/tonistiigi/go-rosetta/go.mod
  vendor/github.com/tonistiigi/go-rosetta/rosetta.go
  vendor/github.com/tonistiigi/go-rosetta/rosetta_unsupported.go
Labels: area/builder, status/2-code-review

#2657 vendor: update containerd/continuity efbc4488d8fe1bdc16bde3b2d2990d9b3a899165
  vendor.conf
  vendor/github.com/containerd/continuity/fs/path.go
  vendor/github.com/containerd/continuity/go.mod
  vendor/github.com/containerd/continuity/syscallx/syscall_unix.go
  vendor/github.com/containerd/continuity/syscallx/syscall_windows.go
  vendor/github.com/containerd/continuity/sysx/file_posix.go
  vendor/github.com/containerd/continuity/sysx/xattr.go
  vendor/github.com/containerd/continuity/sysx/xattr_unsupported.go
Labels: status/2-code-review
