Repository docker/cli, pull requests merged in 2020-08, with the labels that each got.

#2655 docs: remove docs for —-from=index
  docs/reference/builder.md
Labels: area/builder, kind/docs, process/cherry-pick, status/3-docs-review

#2636 Replaces ADD with COPY in the COPY section
  docs/reference/builder.md
Labels: area/builder, kind/docs, process/cherry-pick, status/3-docs-review

#2526 document deprecation of legacy `~/.dockercfg` config-file
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, status/3-docs-review

#2671 Update authors and mailmap
  .mailmap
  AUTHORS
Labels: status/3-docs-review

#2668 Fix order of processing of some xx-add/xx-rm service update flags
  cli/command/service/update.go
  cli/command/service/update_test.go
Labels: area/swarm, impact/changelog, status/2-code-review

#2673 Bump Golang 1.13.15
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.cross
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, process/cherry-picked, status/2-code-review

#2672 Issue 2549/autocomplete group and gpus support
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
Labels: area/completion, status/2-code-review

#2646 Add shorthand for --tail option
  cli/command/container/logs.go
  cli/command/service/logs.go
  contrib/completion/bash/docker
  contrib/completion/fish/docker.fish
  contrib/completion/zsh/_docker
  docs/reference/commandline/logs.md
  docs/reference/commandline/service_logs.md
Labels: impact/changelog, impact/documentation, status/2-code-review

#2678 Return zero exit-code when force-removing non-existing containers
  cli/command/container/client_test.go
  cli/command/container/rm.go
  cli/command/container/rm_test.go
Labels: impact/changelog, status/2-code-review

#2694 Replace vbom.ml/util with fvbommel/sortorder
  cli-plugins/manager/manager.go
  cli/command/config/ls.go
  cli/command/context/list.go
  cli/command/network/list.go
  cli/command/node/list.go
  cli/command/plugin/list.go
  cli/command/secret/ls.go
  cli/command/service/formatter.go
  cli/command/stack/list.go
  cli/command/stack/services.go
  cli/command/system/prune.go
  cli/command/task/print.go
  cli/command/trust/common.go
  cli/command/trust/inspect_pretty.go
  cli/command/volume/list.go
  cli/context/store/metadatastore.go
  vendor.conf
  vendor/github.com/fvbommel/sortorder/LICENSE
  vendor/github.com/fvbommel/sortorder/README.md
  vendor/github.com/fvbommel/sortorder/doc.go
  vendor/github.com/fvbommel/sortorder/go.mod
  vendor/github.com/fvbommel/sortorder/natsort.go
  vendor/vbom.ml/util/README.md
  vendor/vbom.ml/util/sortorder/README.md
Labels: area/testing, process/cherry-picked, status/2-code-review

#2695 [19.03 backport] Replace vbom.ml/util with fvbommel/sortorder
  cli/command/config/ls.go
  cli/command/context/list.go
  cli/command/network/list.go
  cli/command/node/list.go
  cli/command/plugin/list.go
  cli/command/secret/ls.go
  cli/command/service/list.go
  cli/command/stack/list.go
  cli/command/system/prune.go
  cli/command/trust/common.go
  cli/command/trust/inspect_pretty.go
  cli/command/volume/list.go
  cli/context/store/metadatastore.go
  vendor.conf
  vendor/github.com/fvbommel/sortorder/LICENSE
  vendor/github.com/fvbommel/sortorder/README.md
  vendor/github.com/fvbommel/sortorder/doc.go
  vendor/github.com/fvbommel/sortorder/go.mod
  vendor/github.com/fvbommel/sortorder/natsort.go
  vendor/vbom.ml/util/README.md
  vendor/vbom.ml/util/sortorder/README.md
Labels: area/testing, status/2-code-review

#2693 Dockerfile: fix dynbinary inside dev container
  dockerfiles/Dockerfile.dev
Labels: area/testing, status/2-code-review

#2700 formatter: minor refactor to reduce needless conversions
  cli/command/container/formatter_stats.go
  cli/command/stack/formatter/formatter.go
  cli/command/stack/formatter/formatter_test.go
  cli/command/stack/list.go
Labels: status/2-code-review

#2679 opts: simplify ValidateEnv to use os.LookupEnv
  opts/env.go
  opts/env_test.go
Labels: status/2-code-review

#2697 vendor: bump github.com/fvbommel/sortorder v1.0.1
  vendor.conf
  vendor/github.com/fvbommel/sortorder/README.md
  vendor/github.com/fvbommel/sortorder/go.mod
Labels: status/2-code-review
