Repository docker/cli, pull requests merged in 2021-08, with the labels that each got.

#3211 GitHub Actions for lint
  .circleci/config.yml
  .github/workflows/validate.yml
  Makefile
  docker-bake.hcl
  docker.Makefile
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.shellcheck
  scripts/validate/shellcheck
Labels: area/testing, status/2-code-review

#3235 Update Go to 1.16.7
  Dockerfile
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, process/cherry-picked

#3238 replace docker/pkg/signal with github.com/moby/sys/signal
  cli/command/container/attach.go
  cli/command/container/opts.go
  cli/command/container/run.go
  cli/command/container/signals.go
  cli/command/container/signals_test.go
  cli/command/container/start.go
  cli/command/container/tty.go
  vendor.conf
  vendor/github.com/docker/docker/pkg/signal/README.md
  vendor/github.com/docker/docker/pkg/signal/trap.go
  vendor/github.com/moby/sys/mount/go.mod
  vendor/github.com/moby/sys/signal/go.mod
  vendor/github.com/moby/sys/signal/signal.go
  vendor/github.com/moby/sys/signal/signal_darwin.go
  vendor/github.com/moby/sys/signal/signal_freebsd.go
  vendor/github.com/moby/sys/signal/signal_linux.go
  vendor/github.com/moby/sys/signal/signal_linux_mipsx.go
  vendor/github.com/moby/sys/signal/signal_unix.go
  vendor/github.com/moby/sys/signal/signal_unsupported.go
  vendor/github.com/moby/sys/signal/signal_windows.go
Labels: status/2-code-review

#3239 vendor: update logrus v1.8.1, containerd v1.5.5, runc v1.0.1
  vendor.conf
  vendor/github.com/containerd/containerd/go.mod
  vendor/github.com/containerd/containerd/version/version.go
  vendor/github.com/opencontainers/runc/go.mod
  vendor/github.com/opencontainers/runc/libcontainer/nsenter/test/escape.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
Labels: status/2-code-review

#3243 build: fix AddDockerfileToBuildContext not de-referencing tar header template
  cli/command/image/build/context.go
Labels: status/2-code-review, area/builder, area/builder/classic-builder, kind/bugfix

#3240 vendor: update docker to current master (API v1.42)
  cli/command/system/df.go
  vendor.conf
  vendor/github.com/docker/docker/api/common.go
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/client/disk_usage.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/copy.go
  vendor/github.com/docker/docker/pkg/system/image_os.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/docker/swarmkit/vendor.conf
Labels: impact/changelog, status/2-code-review, area/api

#3253 cli/compose: use go1.16 native embed functionality for schemas
  Makefile
  cli/compose/schema/bindata.go
  cli/compose/schema/schema.go
  docker.Makefile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, kind/refactor

#3236 [20.10 backport] Update Go to 1.16.7
  Dockerfile
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#3050 Enable ssh forwarding when building a remote target
  cli/command/image/build_buildkit.go
Labels: status/2-code-review, area/builder

#3230 info: skip client-side warning about seccomp profile on API >= 1.42
  cli/command/system/info.go
Labels: status/2-code-review, process/cherry-pick
