Repository docker/cli, pull requests merged in 2021-10, with the labels that each got.

#3234 GitHub Actions cross
  .circleci/config.yml
  .github/workflows/build.yml
  Makefile
  README.md
  docker-bake.hcl
  docker.Makefile
  dockerfiles/Dockerfile.cross
Labels: status/2-code-review, area/testing

#3319 docs: man page: typo fix in docker_1
  man/docker.1.md
Labels: kind/docs, status/3-docs-review

#3304 bump imdario/mergo v0.3.12
  vendor.conf
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/doc.go
  vendor/github.com/imdario/mergo/go.mod
  vendor/github.com/imdario/mergo/map.go
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/imdario/mergo/mergo.go
Labels: status/2-code-review, area/stack, kind/bugfix

#3316 docs: fix search results by filtered is-official
  docs/reference/commandline/search.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#3321 docs: create.md: typo fix
  docs/reference/commandline/create.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick
