Repository docker/cli, pull requests merged in 2021-06, with the labels that each got.

#3120 Fix minor wording
  docs/reference/commandline/run.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#3122 vendor: github.com/docker/docker v20.10.7
  vendor.conf
  vendor/github.com/containerd/continuity/fs/copy.go
  vendor/github.com/containerd/continuity/fs/copy_linux.go
  vendor/github.com/containerd/continuity/fs/copy_unix.go
  vendor/github.com/containerd/continuity/fs/copy_windows.go
  vendor/github.com/containerd/continuity/fs/diff.go
  vendor/github.com/containerd/continuity/fs/diff_unix.go
  vendor/github.com/containerd/continuity/fs/diff_windows.go
  vendor/github.com/containerd/continuity/fs/dtype_linux.go
  vendor/github.com/containerd/continuity/fs/du.go
  vendor/github.com/containerd/continuity/fs/du_unix.go
  vendor/github.com/containerd/continuity/fs/du_windows.go
  vendor/github.com/containerd/continuity/fs/hardlink.go
  vendor/github.com/containerd/continuity/fs/hardlink_unix.go
  vendor/github.com/containerd/continuity/fs/hardlink_windows.go
  vendor/github.com/containerd/continuity/fs/path.go
  vendor/github.com/containerd/continuity/fs/stat_darwinfreebsd.go
  vendor/github.com/containerd/continuity/fs/stat_linuxopenbsd.go
  vendor/github.com/containerd/continuity/fs/time.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/docker/docker/pkg/archive/archive_other.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/pkg/idtools/idtools.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
  vendor/github.com/docker/docker/pkg/signal/signal.go
  vendor/github.com/docker/docker/vendor.conf
Labels: process/cherry-pick, status/2-code-review

#3124 vendor: github.com/docker/docker-credential-helpers v0.6.4
  vendor.conf
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
Labels: process/cherry-pick, status/2-code-review

#3134 e2e: make sure that os.environ is preserved
  e2e/internal/fixtures/fixtures.go
Labels: area/testing, status/2-code-review

#3123 [20.10] vendor: github.com/docker/docker v20.10.7
  vendor.conf
  vendor/github.com/containerd/continuity/fs/copy.go
  vendor/github.com/containerd/continuity/fs/copy_linux.go
  vendor/github.com/containerd/continuity/fs/copy_unix.go
  vendor/github.com/containerd/continuity/fs/copy_windows.go
  vendor/github.com/containerd/continuity/fs/diff.go
  vendor/github.com/containerd/continuity/fs/diff_unix.go
  vendor/github.com/containerd/continuity/fs/diff_windows.go
  vendor/github.com/containerd/continuity/fs/dtype_linux.go
  vendor/github.com/containerd/continuity/fs/du.go
  vendor/github.com/containerd/continuity/fs/du_unix.go
  vendor/github.com/containerd/continuity/fs/du_windows.go
  vendor/github.com/containerd/continuity/fs/hardlink.go
  vendor/github.com/containerd/continuity/fs/hardlink_unix.go
  vendor/github.com/containerd/continuity/fs/hardlink_windows.go
  vendor/github.com/containerd/continuity/fs/path.go
  vendor/github.com/containerd/continuity/fs/stat_darwinfreebsd.go
  vendor/github.com/containerd/continuity/fs/stat_linuxopenbsd.go
  vendor/github.com/containerd/continuity/fs/time.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/docker/docker/pkg/archive/archive_other.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
  vendor/github.com/docker/docker/pkg/signal/signal.go
  vendor/github.com/docker/docker/vendor.conf
Labels: status/2-code-review

#3137 CI: update engine versions and Jenkins labels
  .circleci/config.yml
  Jenkinsfile
Labels: area/testing, process/cherry-pick, status/2-code-review

#3013 vendor: github.com/spf13/cobra v1.1.3
  vendor.conf
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.go
Labels: status/2-code-review

#3131 vendor: moby/term, Azure/go-ansiterm for golang.org/x/sys/windows compat
  vendor.conf
  vendor/github.com/Azure/go-ansiterm/go.mod
  vendor/github.com/Azure/go-ansiterm/winterm/ansi.go
  vendor/github.com/moby/term/go.mod
  vendor/github.com/moby/term/windows/console.go
Labels: platform/windows, process/cherry-picked, status/2-code-review

#3156 [20.10 backport] vendor: github.com/docker/docker-credential-helpers v0.6.4
  vendor.conf
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
Labels: status/2-code-review

#3108 Document option for daemon config validation
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/reference/commandline/dockerd.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review

#3166 Deprecate Kubernetes stack support
  docs/deprecated.md
Labels: area/kubernetes, area/stack, impact/deprecation, kind/docs, process/cherry-pick, status/3-docs-review

#2940 UX: don't reverse progress-bars when rolling back
  cli/command/service/progress/progress.go
Labels: area/swarm, impact/changelog, status/1-design-review
