Repository docker/cli, pull requests merged in 2021-11, with the labels that each got.

#3245 create/run: remove default --stop-signal
  cli/command/container/opts.go
  docs/reference/commandline/create.md
  docs/reference/commandline/kill.md
  docs/reference/commandline/run.md
  man/docker-run.1.md
Labels: impact/changelog, status/2-code-review

#3357 Update Go to 1.16.10
  Dockerfile
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, process/cherry-picked

#3320 GitHub Actions e2e tests
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  Dockerfile
  Jenkinsfile
  Makefile
  README.md
  docker-bake.hcl
  docker.Makefile
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.e2e
  scripts/build/.variables
  scripts/build/binary
  scripts/build/plugins
  scripts/build/plugins-osx
  scripts/build/plugins-windows
Labels: status/2-code-review, area/testing

#3358 [20.10 backport] Update Go to 1.16.10
  Dockerfile
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review
