Repository docker/cli, pull requests merged in 2021-07, with the labels that each got.

#3167 Deprecate Kubernetes stack support
  cli/command/context/create.go
  cli/command/context/export.go
  cli/command/context/update.go
  cli/command/stack/cmd.go
  cli/command/stack/kubernetes/cli.go
  cli/command/stack/list.go
  cli/command/system/version.go
  docs/deprecated.md
  docs/yaml/yaml.go
Labels: area/context, area/kubernetes, impact/changelog, impact/deprecation, process/cherry-pick, status/2-code-review

#3176 [20.10 backport] CI: update engine versions and Jenkins labels
  .circleci/config.yml
  Jenkinsfile
Labels: area/testing, status/2-code-review

#3163 Cleaned up formatting/typesetting.
  man/src/container/attach.md
Labels: kind/docs, status/3-docs-review

#3179 docker info: skip API connection if possible
  cli/command/system/info.go
  cli/command/system/info_test.go
Labels: impact/changelog, status/2-code-review

#3175 [20.10 backport] docs fixes
  docs/reference/commandline/network_create.md
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review

#3044 info: print errors to stderr
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-info-badsec-stderr.golden
  cli/command/system/testdata/docker-info-badsec.golden
  cli/command/system/testdata/docker-info-badsec.json.golden
  cli/command/system/testdata/docker-info-errors-stderr.golden
  cli/command/system/testdata/docker-info-errors.golden
Labels: impact/changelog, status/2-code-review

#3147 Dockerfile: remove custom go build for windows/arm64
  Dockerfile
Labels: process/cherry-pick, status/2-code-review

#3196 [20.10 backport] Dockerfile: remove custom go build for windows/arm64
  Dockerfile
Labels: status/2-code-review

#3158 Add completion for docker-compose plugin
  contrib/completion/bash/docker
Labels: area/completion, status/2-code-review

#3199 Update go-md2man to v2.0.1 to fix table rendering in man-pages
  vendor.conf
  vendor/github.com/cpuguy83/go-md2man/v2/go.mod
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/entities.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  vendor/github.com/shurcooL/sanitized_anchor_name/README.md
  vendor/github.com/shurcooL/sanitized_anchor_name/go.mod
  vendor/github.com/shurcooL/sanitized_anchor_name/main.go
Labels: kind/docs, process/cherry-picked, status/2-code-review

#3074 Add support for ALL_PROXY
  cli/command/container/create_test.go
  cli/config/configfile/file.go
  cli/config/configfile/file_test.go
  docs/reference/builder.md
  docs/reference/commandline/cli.md
  man/Dockerfile.5.md
Labels: area/builder, docs/revisit, impact/changelog, kind/enhancement, status/2-code-review

#3200 [20.10 backport] Update go-md2man to v2.0.1 to fix table rendering in man-pages
  vendor.conf
  vendor/github.com/cpuguy83/go-md2man/v2/go.mod
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/entities.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  vendor/github.com/shurcooL/sanitized_anchor_name/README.md
  vendor/github.com/shurcooL/sanitized_anchor_name/go.mod
  vendor/github.com/shurcooL/sanitized_anchor_name/main.go
Labels: kind/docs, status/2-code-review

#3204 Update Dockerfiles to latest syntax, remove "experimental"
  Dockerfile
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: process/cherry-picked, status/2-code-review

#3205 [20.10 backport] Update Dockerfiles to latest syntax, remove "experimental"
  Dockerfile
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review

#2855 scripts/build/.variables: Support SOURCE_DATE_EPOCH
  scripts/build/.variables
Labels: status/2-code-review

#3190 Fix typo in documentation - build.md
  docs/reference/commandline/build.md
Labels: kind/docs, process/cherry-pick, status/3-docs-review

#3140 e2e: update docker-compose to 1.29.2
  dockerfiles/Dockerfile.e2e
Labels: area/testing, process/cherry-pick, status/2-code-review

#3208 Add doc for BUILDKIT_PROGRESS env var
  docs/reference/commandline/cli.md
Labels: area/builder, area/builder/buildkit, kind/docs, process/cherry-pick, status/3-docs-review

#3210 CircleCI: update BUILDX_VERSION to v0.6.0
  .circleci/config.yml
Labels: area/testing, status/2-code-review

#3213 cli/context: ignore linting warnings about RFC 1423 encryption
  cli/context/docker/load.go
Labels: area/context, process/cherry-pick, status/2-code-review

#3218 context: deprecate support for encrypted TLS private keys
  cli/command/cli.go
  cli/context/docker/load.go
  docs/deprecated.md
Labels: area/context, impact/deprecation, process/cherry-pick, status/2-code-review

#3174 [20.10 backport] Deprecate Kubernetes stack support
  cli/command/context/create.go
  cli/command/context/export.go
  cli/command/context/update.go
  cli/command/stack/cmd.go
  cli/command/stack/kubernetes/cli.go
  cli/command/stack/list.go
  cli/command/system/version.go
  docs/deprecated.md
  docs/yaml/yaml.go
Labels: area/context, area/kubernetes, impact/changelog, impact/deprecation, status/2-code-review

#3222 e2e: update gotestsum to v1.7.0
  dockerfiles/Dockerfile.e2e
Labels: area/testing, status/2-code-review

#3221 change TestNewAPIClientFromFlagsWithHttpProxyEnv to an e2e test
  cli/command/cli_test.go
  e2e/global/cli_test.go
Labels: area/testing, process/cherry-pick, status/2-code-review

#3223 docs: update deprecation status of LCOW to "removed"
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review

#3219 [20.10 backport] context: deprecate support for encrypted TLS private keys
  cli/command/cli.go
  cli/context/docker/load.go
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, impact/documentation, status/2-code-review

#3197 Bump go 1.16.6
  Dockerfile
  appveyor.yml
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  scripts/build/plugins
  scripts/test/e2e/run
Labels: process/cherry-pick, status/2-code-review

#3203 cli/command: don't use client.CustomHTTPHeaders()
  cli/command/cli_test.go
Labels: area/testing, status/2-code-review

#3224 [20.10 backport] Bump go 1.16.6
  Dockerfile
  appveyor.yml
  cli/command/cli_test.go
  cli/command/container/create_test.go
  cli/command/context/create_test.go
  cli/command/context/list_test.go
  cli/command/context/testdata/inspect.golden
  cli/command/context/testdata/list.golden
  cli/command/context/testdata/test-kubeconfig
  cli/command/image/trust_test.go
  cli/command/registry_test.go
  cli/command/swarm/ca_test.go
  cli/config/configfile/file_test.go
  cli/config/credentials/file_store_test.go
  cli/connhelper/connhelper.go
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  e2e/global/cli_test.go
  scripts/build/plugins
  scripts/test/e2e/run
Labels: impact/changelog, status/2-code-review

#3034 yamldocs: various improvements
  docs/yaml/generate.go
  docs/yaml/markdown.go
  docs/yaml/markdown_test.go
  docs/yaml/yaml.go
  scripts/docs/generate-yaml.sh
Labels: kind/docs, status/2-code-review
