Repository docker/cli, pull requests merged in 2022-01, with the labels that each got.

#3392 make compose plugin detection in bash completion work on Mac OS
  contrib/completion/bash/docker
Labels: status/2-code-review, area/completion, kind/bugfix

#3264 fix innocuous data-race when config.Load called in parallel
  cli/config/config.go
Labels: status/2-code-review, area/context, kind/bugfix

#3220 Remove support for encrypted TLS private keys
  cli/command/cli.go
  cli/command/cli_test.go
  cli/context/docker/load.go
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/2-code-review

#3412 Some fixes for "make vendor"
  dockerfiles/Dockerfile.vendor
  scripts/vendor
Labels: status/2-code-review, area/testing

#3414 Correct device syntax to --gpus
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick
