Repository docker/cli, pull requests merged in 2022-12, with the labels that each got.

#3890 Update mailmap and AUTHORS
  .mailmap
  AUTHORS
  scripts/docs/generate-authors.sh
Labels: status/2-code-review, area/packaging

#3891 vendor: docker/docker v20.10.3-0.20221201081640-bb2eab21c6db (v23.0.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/client/image_list.go
  vendor/github.com/docker/docker/registry/session.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#3892 container port: sort ports before printing
  cli/command/container/port.go
  cli/command/container/port_test.go
  cli/command/container/testdata/container-port-all-ports.golden
  cli/command/container/testdata/container-port-ipv6-and-ipv4-443-udp.golden
  cli/command/container/testdata/container-port-ipv6-and-ipv4.golden
Labels: impact/changelog, kind/enhancement, status/2-code-review

#3894 vendor: docker/docker v20.10.3-0.20221201203946-b21e8f72f254 (v23.0.0-dev)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#3896 Dockerfile: add ALPINE_VERSION build-arg
  Dockerfile
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, kind/bugfix, area/packaging

#3897 [20.10 backport] Dockerfile: add ALPINE_VERSION build-arg
  Dockerfile
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, kind/bugfix, area/packaging

#3812 add ability to override ints in compose files with 0
  cli/compose/loader/merge.go
  cli/compose/loader/merge_test.go
Labels: impact/changelog, status/2-code-review, area/swarm, area/stack, kind/bugfix

#3829 updated additionalHelp text
  cli/cobra.go
Labels: kind/docs, status/2-code-review

#3661 docs: various (minor) changes and rewording
  docs/extend/config.md
  docs/reference/commandline/attach.md
  docs/reference/commandline/commit.md
  docs/reference/commandline/events.md
  docs/reference/commandline/exec.md
  docs/reference/commandline/info.md
  docs/reference/commandline/ps.md
  docs/reference/commandline/pull.md
  docs/reference/commandline/service_create.md
  docs/reference/commandline/system_events.md
  docs/reference/run.md
  man/src/container/attach.md
  man/src/container/ls.md
  man/src/image/ls.md
  man/src/image/pull.md
  man/src/system/events.md
  man/src/system/info.md
Labels: kind/docs, status/3-docs-review

#3903 cil/command: use dummy client for build-tests
  cli/command/cli_options.go
  cmd/docker/builder_test.go
Labels: status/2-code-review, area/testing

#3901 Fix bug where incorrect response is returned [carry 3845]
  cmd/docker/docker.go
Labels: status/2-code-review, kind/bugfix

#3904 cmd/docker: make feature detection lazy again
  cmd/docker/docker.go
Labels: status/2-code-review, kind/bugfix

#3907 update to go1.19.4
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: impact/changelog, status/2-code-review, area/packaging

#3908 [20.10] update to go1.18.9
  Dockerfile
  appveyor.yml
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#3906 Dockerfile: update buildx to v0.9.1
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#3912 vendor: github.com/docker/docker v23.0.0-beta.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#3900 Fix ssh process killed when context is done
  cli/connhelper/commandconn/commandconn.go
Labels: status/2-code-review, kind/bugfix

#3905 cmd/docker: improve error message if BUILDKIT_ENABLED=0
  cmd/docker/builder.go
  cmd/docker/builder_test.go
  e2e/image/build_test.go
Labels: kind/enhancement, status/2-code-review, area/builder, area/builder/classic-builder, area/builder/buildkit

#3917 [20.10 backport] update gotestsum to v1.8.2
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
Labels: status/2-code-review, area/testing

#3918 [20.10 backport] assorted docs fixes
  docs/reference/builder.md
  docs/reference/commandline/inspect.md
  docs/reference/commandline/logs.md
  docs/reference/commandline/version.md
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review

#3919 [20.10] update docker/docker and buildkit
  vendor.conf
  vendor/github.com/docker/docker/builder/remotecontext/git/gitutils.go
  vendor/github.com/docker/docker/registry/service_v2.go
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/moby/buildkit/go.mod
Labels: status/2-code-review, area/runtime, area/builder/buildkit

#3923 Added missing backslash to documentation cli snippet
  docs/reference/commandline/service_create.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#3925 cmd/docker: fix typo in deprecation warning
  cmd/docker/builder.go
  cmd/docker/builder_test.go
  e2e/image/build_test.go
Labels: status/2-code-review, kind/bugfix

#3926 [20.10 backport] Added missing backslash to documentation sites cli snippet
  docs/reference/commandline/service_create.md
Labels: kind/docs, status/3-docs-review

#3927 [20.10] vendor: github.com/docker/docker v20.10.22
  vendor.conf
  vendor/github.com/docker/docker/vendor.conf
Labels: status/2-code-review, area/runtime

#3929 vendor: update docker/docker to tip of v23.0 branch
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/errdefs/http_helpers.go
  vendor/github.com/klauspost/compress/README.md
  vendor/github.com/klauspost/compress/huff0/decompress.go
  vendor/github.com/klauspost/compress/huff0/decompress_amd64.go
  vendor/github.com/klauspost/compress/huff0/decompress_amd64.s
  vendor/github.com/klauspost/compress/huff0/decompress_generic.go
  vendor/github.com/klauspost/compress/internal/snapref/encode_other.go
  vendor/github.com/klauspost/compress/zstd/README.md
  vendor/github.com/klauspost/compress/zstd/blockdec.go
  vendor/github.com/klauspost/compress/zstd/bytebuf.go
  vendor/github.com/klauspost/compress/zstd/decoder.go
  vendor/github.com/klauspost/compress/zstd/decoder_options.go
  vendor/github.com/klauspost/compress/zstd/enc_best.go
  vendor/github.com/klauspost/compress/zstd/enc_better.go
  vendor/github.com/klauspost/compress/zstd/enc_dfast.go
  vendor/github.com/klauspost/compress/zstd/enc_fast.go
  vendor/github.com/klauspost/compress/zstd/framedec.go
  vendor/github.com/klauspost/compress/zstd/fse_decoder_amd64.go
  vendor/github.com/klauspost/compress/zstd/fse_decoder_amd64.s
  vendor/github.com/klauspost/compress/zstd/history.go
  vendor/github.com/klauspost/compress/zstd/seqdec.go
  vendor/github.com/klauspost/compress/zstd/seqdec_amd64.go
  vendor/github.com/klauspost/compress/zstd/seqdec_amd64.s
  vendor/github.com/klauspost/compress/zstd/seqdec_generic.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/almost_equal.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/difflib.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#3933 vendor: github.com/inconshreveable/mousetrap v1.1.0
  vendor.mod
  vendor.sum
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/modules.txt
Labels: status/2-code-review

#3934 vendor: github.com/docker/docker v23.0.0-rc.1 (use tag)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#3935 cli/command/container: remove unused NetworkDisabled field
  cli/command/container/opts.go
Labels: status/2-code-review, kind/refactor

#3931 Missing exec_die event
  docs/reference/commandline/system_events.md
Labels: dco/no, kind/docs, status/3-docs-review

#3939 docs/run: Fix url to blog "Docker can now run within Docker"
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review

#3941 [20.10 backport] docs fixes
  docs/reference/commandline/system_events.md
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review

#3936 Replace uses of `strings.Split(N)` with `strings.Cut()`
  cli/command/container/cp.go
  cli/command/container/opts.go
  cli/command/container/opts_test.go
  cli/command/network/connect.go
  cli/command/service/opts.go
  cli/command/service/scale.go
  cli/command/service/update.go
  cli/command/stack/loader/loader.go
  cli/command/swarm/opts.go
  cli/command/utils.go
  cli/command/volume/create.go
  cli/compose/convert/service.go
  cli/compose/loader/loader.go
  cli/compose/template/template.go
  cli/config/configfile/file.go
  cli/config/credentials/file_store.go
  internal/test/strings.go
  opts/config.go
  opts/env.go
  opts/file.go
  opts/gpus.go
  opts/hosts.go
  opts/mount.go
  opts/network.go
  opts/opts.go
  opts/opts_test.go
  opts/parse.go
  opts/port.go
  opts/secret.go
  opts/throttledevice.go
  opts/weightdevice.go
  service/logs/parse_logs.go
  service/logs/parse_logs_test.go
Labels: status/2-code-review, kind/refactor
