Repository docker/cli, pull requests merged in 2022-09, with the labels that each got.

#3762 build: replace uses of archive.CanonicalTarNameForPath
  cli/command/image/build.go
  cli/command/image/build/dockerignore.go
Labels: status/2-code-review, area/builder, kind/refactor

#3768 update to golangci-lint v1.49.0 for compatibilty with go1.19
  .golangci.yml
  cli-plugins/manager/plugin.go
  cli/command/cli_options_test.go
  cli/command/config/inspect.go
  cli/command/container/opts.go
  cli/command/formatter/tabwriter/tabwriter.go
  cli/command/image/build/context.go
  cli/command/image/formatter_history_test.go
  cli/command/manifest/inspect_test.go
  cli/command/node/inspect.go
  cli/command/secret/inspect.go
  cli/command/service/list.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/swarm/opts_test.go
  cli/command/trust/common.go
  cli/command/trust/inspect_pretty_test.go
  cli/command/trust/inspect_test.go
  cli/command/trust/sign.go
  cli/command/trust/sign_test.go
  cli/command/trust/signer_add.go
  cli/command/trust/signer_add_test.go
  cli/command/trust/signer_remove.go
  cli/command/trust/signer_remove_test.go
  cli/context/store/tlsstore.go
  cli/trust/trust.go
  dockerfiles/Dockerfile.lint
  docs/reference/commandline/trust_inspect.md
  docs/reference/commandline/trust_sign.md
  docs/reference/commandline/trust_signer_add.md
  e2e/plugin/basic/basic.go
  opts/envfile_test.go
  opts/hosts.go
  opts/hosts_test.go
Labels: status/2-code-review, area/testing

#3766 vendor: github.com/docker/go-units v0.5.0
  cli/command/container/opts_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/go-units/size.go
  vendor/modules.txt
Labels: status/2-code-review

#3769 opts: remove unused RuntimeOpt
  opts/runtime.go
Labels: status/2-code-review, kind/refactor

#3761 cli/command: NewDockerCli(): use WithStandardStreams()
  cli/command/cli.go
Labels: status/2-code-review, kind/refactor

#3772 Update to go 1.18.6 to address CVE-2022-27664, CVE-2022-32190
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: impact/changelog, status/2-code-review, area/packaging

#3773 [20.10 backport] Update to go 1.18.6 to address CVE-2022-27664, CVE-2022-32190
  Dockerfile
  appveyor.yml
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#3774 vendor: golang.org/x/net v0.0.0-20220906165146-f3363e06e74c
  vendor.mod
  vendor.sum
  vendor/golang.org/x/net/AUTHORS
  vendor/golang.org/x/net/CONTRIBUTORS
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/errors.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/hpack/huffman.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/idna/trieval.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
Labels: status/2-code-review

#3764 cli: createContainer() remove intermediate variable
  cli/command/container/create.go
Labels: status/2-code-review, kind/refactor

#3767 update to golang 1.19.1
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  scripts/vendor
  vendor.mod
Labels: impact/changelog, status/2-code-review, area/packaging

#3775 vendor: docker v20.10.3-0.20220909113731-8af2e62556de (22.06 branch)
  vendor.mod
  vendor.sum
  vendor/github.com/klauspost/compress/.gitignore
  vendor/github.com/klauspost/compress/README.md
  vendor/github.com/klauspost/compress/huff0/autogen.go
  vendor/github.com/klauspost/compress/huff0/bitreader.go
  vendor/github.com/klauspost/compress/huff0/bitwriter.go
  vendor/github.com/klauspost/compress/huff0/bytereader.go
  vendor/github.com/klauspost/compress/huff0/compress.go
  vendor/github.com/klauspost/compress/huff0/decompress.go
  vendor/github.com/klauspost/compress/huff0/decompress_8b_amd64.s
  vendor/github.com/klauspost/compress/huff0/decompress_8b_amd64.s.in
  vendor/github.com/klauspost/compress/huff0/decompress_amd64.go
  vendor/github.com/klauspost/compress/huff0/decompress_amd64.s
  vendor/github.com/klauspost/compress/huff0/decompress_amd64.s.in
  vendor/github.com/klauspost/compress/huff0/decompress_generic.go
  vendor/github.com/klauspost/compress/internal/cpuinfo/cpuinfo.go
  vendor/github.com/klauspost/compress/internal/cpuinfo/cpuinfo_amd64.go
  vendor/github.com/klauspost/compress/internal/cpuinfo/cpuinfo_amd64.s
  vendor/github.com/klauspost/compress/zstd/README.md
  vendor/github.com/klauspost/compress/zstd/bitreader.go
  vendor/github.com/klauspost/compress/zstd/bitwriter.go
  vendor/github.com/klauspost/compress/zstd/blockdec.go
  vendor/github.com/klauspost/compress/zstd/bytebuf.go
  vendor/github.com/klauspost/compress/zstd/bytereader.go
  vendor/github.com/klauspost/compress/zstd/decoder.go
  vendor/github.com/klauspost/compress/zstd/decoder_options.go
  vendor/github.com/klauspost/compress/zstd/enc_better.go
  vendor/github.com/klauspost/compress/zstd/enc_dfast.go
  vendor/github.com/klauspost/compress/zstd/encoder.go
  vendor/github.com/klauspost/compress/zstd/encoder_options.go
  vendor/github.com/klauspost/compress/zstd/framedec.go
  vendor/github.com/klauspost/compress/zstd/fse_decoder.go
  vendor/github.com/klauspost/compress/zstd/fse_decoder_amd64.go
  vendor/github.com/klauspost/compress/zstd/fse_decoder_amd64.s
  vendor/github.com/klauspost/compress/zstd/fse_decoder_generic.go
  vendor/github.com/klauspost/compress/zstd/fse_encoder.go
  vendor/github.com/klauspost/compress/zstd/fuzz.go
  vendor/github.com/klauspost/compress/zstd/fuzz_none.go
  vendor/github.com/klauspost/compress/zstd/hash.go
  vendor/github.com/klauspost/compress/zstd/seqdec.go
  vendor/github.com/klauspost/compress/zstd/seqdec_amd64.go
  vendor/github.com/klauspost/compress/zstd/seqdec_amd64.s
  vendor/github.com/klauspost/compress/zstd/seqdec_generic.go
  vendor/github.com/klauspost/compress/zstd/zip.go
  vendor/github.com/klauspost/compress/zstd/zstd.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#3779 cli: use N/A as placeholder for old CREATED dates
  cli/command/image/formatter_history.go
  cli/command/image/formatter_history_test.go
Labels: status/2-code-review

#3783 vendor: docker v20.10.3-0.20220922131805-e143eed8bc4f (22.06 branch)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/container_create.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#3784 vendor: gotest.tools v3.3.0 and use t.SetEnv()
  cli/command/cli_test.go
  cli/command/defaultcontextstore_test.go
  cli/command/image/build_test.go
  cli/command/image/trust_test.go
  cli/compose/interpolation/interpolation_test.go
  cli/config/config_test.go
  cmd/docker/builder_test.go
  e2e/image/build_test.go
  opts/parse_test.go
  vendor.mod
  vendor.sum
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/assert_go113.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/compare_go113.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/env/env.go
  vendor/gotest.tools/v3/fs/manifest.go
  vendor/gotest.tools/v3/fs/ops.go
  vendor/gotest.tools/v3/fs/report.go
  vendor/gotest.tools/v3/golden/golden.go
  vendor/gotest.tools/v3/icmd/command.go
  vendor/gotest.tools/v3/icmd/exitcode.go
  vendor/gotest.tools/v3/internal/assert/assert.go
  vendor/gotest.tools/v3/internal/assert/result.go
  vendor/gotest.tools/v3/internal/source/defers.go
  vendor/gotest.tools/v3/internal/source/source.go
  vendor/gotest.tools/v3/internal/source/update.go
  vendor/gotest.tools/v3/internal/source/version.go
  vendor/modules.txt
Labels: status/2-code-review, area/testing

#3760 vendor: github.com/docker/docker-credential-helpers v0.7.0
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/modules.txt
Labels: status/2-code-review

#3791 docker context rm: allow --force to ignore non-existing contexts
  cli/command/context/remove.go
  cli/command/context/remove_test.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/context

#3795 fix broken alias check is buildx is installed as alias for builder
  cmd/docker/aliases.go
  cmd/docker/docker.go
Labels: status/2-code-review, kind/bugfix

#3790 context: various cleanups and improvements
  cli/command/cli.go
  cli/command/context/create.go
  cli/command/context/remove.go
  cli/command/context/remove_test.go
  cli/command/context/use_test.go
  cli/command/defaultcontextstore.go
  cli/command/defaultcontextstore_test.go
  cli/context/store/metadata_test.go
  cli/context/store/metadatastore.go
  cli/context/store/store.go
  cli/context/store/store_test.go
  cli/context/store/storeconfig.go
  cli/context/store/storeconfig_test.go
  cli/context/store/tlsstore.go
  cli/context/store/tlsstore_test.go
  cli/context/tlsdata.go
Labels: status/2-code-review, area/context, kind/refactor

#3796 cli-plugins/manager: add IsPluginCommand(() utility
  cli-plugins/manager/manager.go
  cli-plugins/manager/plugin.go
  cli/cobra.go
  cmd/docker/aliases.go
  cmd/docker/docker.go
Labels: status/2-code-review, area/plugins
