Repository docker/cli, pull requests merged in 2022-08, with the labels that each got.

#3717 missing DWARF symbol table
  Dockerfile
  scripts/build/.variables
Labels: status/2-code-review, kind/bugfix, area/packaging

#3722 cli: set timeout connection ping on sockets as well
  cli/command/cli.go
  cli/command/cli_test.go
Labels: status/2-code-review, kind/bugfix

#3725 Update golang to 1.18.5
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: impact/changelog, status/2-code-review, area/packaging

#3726 [20.10] Update golang to 1.17.13
  Dockerfile
  appveyor.yml
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#3729 Update link to libnetwork docs
  docs/extend/plugins_network.md
Labels: kind/docs, status/2-code-review

#3730 Move notes about required buildkit
  docs/reference/commandline/build.md
Labels: kind/docs, status/3-docs-review, area/builder

#3731 Dockerfile: update buildx to v0.9.0
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#3737 Update issues form
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: status/2-code-review

#3739 complete the "-g" / "--graph" daemon option deprecation
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/3-docs-review, impact/documentation

#3743 [20.10 backport] lint: update golangci-lint to v1.45.2
  .golangci.yml
  cli/command/config/formatter_test.go
  cli/command/config/inspect_test.go
  cli/command/container/create.go
  cli/command/container/create_test.go
  cli/command/container/formatter_stats.go
  cli/command/container/formatter_stats_test.go
  cli/command/formatter/container_test.go
  cli/command/formatter/disk_usage_test.go
  cli/command/formatter/formatter.go
  cli/command/formatter/image_test.go
  cli/command/formatter/volume_test.go
  cli/command/image/build.go
  cli/command/inspect/inspector.go
  cli/command/inspect/inspector_test.go
  cli/command/network/formatter_test.go
  cli/command/node/formatter_test.go
  cli/command/plugin/formatter_test.go
  cli/command/plugin/inspect_test.go
  cli/command/plugin/list_test.go
  cli/command/registry/formatter_search_test.go
  cli/command/secret/formatter_test.go
  cli/command/secret/inspect_test.go
  cli/command/service/formatter_test.go
  cli/command/service/opts.go
  cli/command/stack/formatter/formatter_test.go
  cli/command/stack/list_test.go
  cli/command/stack/loader/loader.go
  cli/command/stack/services_test.go
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/version.go
  cli/command/task/formatter_test.go
  cli/command/trust/formatter_test.go
  cli/command/volume/create.go
  cli/command/volume/create_test.go
  cli/command/volume/inspect_test.go
  cli/compose/interpolation/interpolation.go
  cli/compose/interpolation/interpolation_test.go
  cli/config/credentials/native_store.go
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, area/testing

#3747 [20.10] update dependencies for go1.18 compatibility
  vendor.conf
  vendor/github.com/google/gofuzz/go.mod
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/adapter.go
  vendor/github.com/json-iterator/go/any_str.go
  vendor/github.com/json-iterator/go/config.go
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/iter.go
  vendor/github.com/json-iterator/go/iter_array.go
  vendor/github.com/json-iterator/go/iter_float.go
  vendor/github.com/json-iterator/go/iter_int.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/iter_skip.go
  vendor/github.com/json-iterator/go/iter_skip_sloppy.go
  vendor/github.com/json-iterator/go/reflect.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_json_raw_message.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_marshaler.go
  vendor/github.com/json-iterator/go/reflect_native.go
  vendor/github.com/json-iterator/go/reflect_optional.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/reflect_struct_encoder.go
  vendor/github.com/json-iterator/go/stream.go
  vendor/github.com/json-iterator/go/stream_float.go
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/modern-go/reflect2/go_above_118.go
  vendor/github.com/modern-go/reflect2/go_above_17.go
  vendor/github.com/modern-go/reflect2/go_above_19.go
  vendor/github.com/modern-go/reflect2/go_below_118.go
  vendor/github.com/modern-go/reflect2/go_below_17.go
  vendor/github.com/modern-go/reflect2/go_below_19.go
  vendor/github.com/modern-go/reflect2/reflect2.go
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/modern-go/reflect2/unsafe_link.go
  vendor/github.com/modern-go/reflect2/unsafe_map.go
Labels: status/2-code-review, area/packaging

#3746 [20.10 backport] Update golang to 1.18.5
  Dockerfile
  appveyor.yml
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  templates/templates.go
Labels: impact/changelog, status/2-code-review, area/packaging

#3738 update cli-docs-tool to v0.5.0
  docs/go.mod
  scripts/docs/generate-yaml.sh
Labels: kind/docs, status/2-code-review

#3744 ci: update github actions
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing

#3753 [20.10 backport] fix race condition in TestRemoveForce
  cli/command/container/rm_test.go
Labels: status/2-code-review, area/testing, kind/bugfix

#3754 [20.10] vendor: github.com/docker/docker v20.10.17
  vendor.conf
  vendor/github.com/docker/docker/api/common_unix.go
  vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go
  vendor/github.com/docker/docker/client/client_unix.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/errdefs/http_helpers.go
  vendor/github.com/docker/docker/pkg/archive/archive_other.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/pkg/archive/changes_other.go
  vendor/github.com/docker/docker/pkg/archive/changes_unix.go
  vendor/github.com/docker/docker/pkg/archive/copy_unix.go
  vendor/github.com/docker/docker/pkg/archive/time_unsupported.go
  vendor/github.com/docker/docker/pkg/fileutils/fileutils_unix.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_others.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
  vendor/github.com/docker/docker/pkg/idtools/usergroupadd_unsupported.go
  vendor/github.com/docker/docker/pkg/idtools/utils_unix.go
  vendor/github.com/docker/docker/pkg/ioutils/temp_unix.go
  vendor/github.com/docker/docker/pkg/signal/signal_linux.go
  vendor/github.com/docker/docker/pkg/signal/signal_linux_mipsx.go
  vendor/github.com/docker/docker/pkg/signal/signal_unix.go
  vendor/github.com/docker/docker/pkg/signal/signal_unsupported.go
  vendor/github.com/docker/docker/pkg/system/chtimes_nowindows.go
  vendor/github.com/docker/docker/pkg/system/filesys_unix.go
  vendor/github.com/docker/docker/pkg/system/lcow.go
  vendor/github.com/docker/docker/pkg/system/lcow_unsupported.go
  vendor/github.com/docker/docker/pkg/system/lstat_unix.go
  vendor/github.com/docker/docker/pkg/system/meminfo_unsupported.go
  vendor/github.com/docker/docker/pkg/system/mknod.go
  vendor/github.com/docker/docker/pkg/system/mknod_freebsd.go
  vendor/github.com/docker/docker/pkg/system/mknod_unix.go
  vendor/github.com/docker/docker/pkg/system/path_unix.go
  vendor/github.com/docker/docker/pkg/system/process_unix.go
  vendor/github.com/docker/docker/pkg/system/rm.go
  vendor/github.com/docker/docker/pkg/system/stat_bsd.go
  vendor/github.com/docker/docker/pkg/system/stat_unix.go
  vendor/github.com/docker/docker/pkg/system/syscall_unix.go
  vendor/github.com/docker/docker/pkg/system/umask.go
  vendor/github.com/docker/docker/pkg/system/utimes_unix.go
  vendor/github.com/docker/docker/pkg/system/utimes_unsupported.go
  vendor/github.com/docker/docker/pkg/system/xattrs_unsupported.go
  vendor/github.com/docker/docker/registry/config_unix.go
  vendor/github.com/docker/docker/vendor.conf
Labels: status/2-code-review

#3752 [20.10 backport] Add completion for docker-compose plugin
  contrib/completion/bash/docker
Labels: kind/enhancement, status/2-code-review, area/completion

#3755 replace pkg/system Sequential funcs with moby/sys/sequential
  cli/command/config/create.go
  cli/command/image/load.go
  cli/command/secret/create.go
  cli/command/utils.go
  vendor.mod
  vendor.sum
  vendor/github.com/moby/sys/sequential/LICENSE
  vendor/github.com/moby/sys/sequential/doc.go
  vendor/github.com/moby/sys/sequential/sequential_unix.go
  vendor/github.com/moby/sys/sequential/sequential_windows.go
  vendor/modules.txt
Labels: status/2-code-review, kind/refactor

#3763 vendor: docker v20.10.3-0.20220831131523-b5a0d7a188ac (22.06 branch)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/system/filesys.go
  vendor/github.com/docker/docker/pkg/system/filesys_deprecated.go
  vendor/github.com/docker/docker/pkg/system/filesys_unix.go
  vendor/github.com/docker/docker/pkg/system/filesys_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime
