Repository docker/cli, pull requests merged in 2022-04, with the labels that each got.

#3508 Tweak description of some commands
  cli/command/container/exec.go
  cli/command/container/run.go
  cli/command/image/pull.go
  cli/command/image/push.go
  contrib/completion/fish/docker.fish
  contrib/completion/zsh/_docker
  docs/reference/commandline/cli.md
  docs/reference/commandline/container.md
  docs/reference/commandline/exec.md
  docs/reference/commandline/image.md
  docs/reference/commandline/index.md
  docs/reference/commandline/pull.md
  docs/reference/commandline/push.md
  docs/reference/commandline/run.md
  man/docker-run.1.md
Labels: status/3-docs-review, impact/documentation

#3524 docs: reference: remove trailing space to fix yaml formatting
  docs/reference/commandline/cp.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked, kind/bugfix

#3419 Describe privileged mode in terms of capabilities
  docs/reference/run.md
Labels: dco/no, kind/docs, status/3-docs-review, process/cherry-pick

#3529 Dockerfile: update buildx to v0.8.2
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#3530 [20.10] circleci: update buildx to v0.8.2
  .circleci/config.yml
Labels: status/2-code-review, area/testing

#3531 tweak description of login/logout
  TESTING.md
  cli/command/registry/login.go
  cli/command/registry/logout.go
  contrib/completion/fish/docker.fish
  contrib/completion/zsh/_docker
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/index.md
  docs/reference/commandline/login.md
  docs/reference/commandline/logout.md
  docs/reference/commandline/manifest.md
  man/src/login.md
  man/src/logout.md
Labels: status/3-docs-review, impact/documentation

#3535 scripts/build: fix build-date generation on macOS, and make sure it's in UTC
  scripts/build/.variables
Labels: status/2-code-review, kind/bugfix, area/packaging

#3540 fix: remove asterisk from docker command suggestions
  contrib/completion/zsh/_docker
Labels: status/2-code-review, process/cherry-pick, area/completion, kind/bugfix

#2504 Deprecation: config: remove support for old ~/.dockercfg
  cli/config/config.go
  cli/config/config_test.go
  cli/config/configfile/file.go
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/2-code-review

#3538 update mailmap and authors
  .mailmap
  AUTHORS
Labels: status/3-docs-review

#3541 Update 21.xx -> 22.04
  VERSION
  docs/deprecated.md
  vendor.mod
Labels: kind/docs, status/3-docs-review

#3542 update status of deprecated features for 22.04 (docs, and some code)
  cli/command/container/update.go
  cli/command/system/info.go
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/2-code-review

#3512 client: local changes after engine update
  cli/command/cli.go
  cli/command/context/list.go
  cli/command/context/use.go
  cli/context/docker/load.go
  cli/flags/common.go
  internal/test/environment/testenv.go
Labels: status/2-code-review

#3520 fix race condition in TestRemoveForce
  cli/command/container/rm_test.go
Labels: status/2-code-review, area/testing, kind/bugfix

#3506 re-organize --help output
  cli/cobra.go
  cli/command/commands/commands.go
  cli/command/config/cmd.go
  cli/command/container/exec.go
  cli/command/container/list.go
  cli/command/container/run.go
  cli/command/image/build.go
  cli/command/image/list.go
  cli/command/image/pull.go
  cli/command/image/push.go
  cli/command/registry/login.go
  cli/command/registry/logout.go
  cli/command/registry/search.go
  cli/command/secret/cmd.go
  cli/command/service/cmd.go
  cli/command/stack/cmd.go
  cli/command/system/info.go
  cli/command/system/version.go
  docs/reference/commandline/config.md
  docs/reference/commandline/secret.md
  docs/reference/commandline/service.md
  docs/reference/commandline/stack.md
Labels: kind/enhancement, status/2-code-review

#3527 [20.10] update remaining Dockerfiles to go 1.16.15
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.e2e
Labels: status/2-code-review

#3526 [20.10 backport] e2e: update docker-compose to 1.29.2
  dockerfiles/Dockerfile.e2e
Labels: status/2-code-review, area/testing

#3523 [20.10 backport] assorted documentation fixes
  docs/reference/builder.md
  docs/reference/commandline/build.md
  docs/reference/commandline/config_ls.md
  docs/reference/commandline/context.md
  docs/reference/commandline/context_use.md
  docs/reference/commandline/cp.md
  docs/reference/commandline/create.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/history.md
  docs/reference/commandline/images.md
  docs/reference/commandline/import.md
  docs/reference/commandline/index.md
  docs/reference/commandline/network_connect.md
  docs/reference/commandline/network_create.md
  docs/reference/commandline/network_ls.md
  docs/reference/commandline/node_ls.md
  docs/reference/commandline/node_ps.md
  docs/reference/commandline/plugin_ls.md
  docs/reference/commandline/run.md
  docs/reference/commandline/search.md
  docs/reference/commandline/secret_ls.md
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_ls.md
  docs/reference/commandline/service_ps.md
  docs/reference/commandline/stack_ls.md
  docs/reference/commandline/stack_ps.md
  docs/reference/commandline/stack_services.md
  docs/reference/commandline/stats.md
  docs/reference/commandline/system_df.md
  docs/reference/commandline/volume_ls.md
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review

#3521 [20.10 backport] Dockerfile: update xx to 1.1
  Dockerfile
Labels: status/2-code-review, area/packaging

#3561 Add Djordje Lukic and Nicolas De Loof to maintainers
  MAINTAINERS
Labels: status/3-docs-review

#3556 [20.10 backport] update go to 1.17
  Dockerfile
  appveyor.yml
  cli-plugins/manager/manager_unix.go
  cli-plugins/manager/suffix_unix.go
  cli/command/container/signals_unix.go
  cli/command/container/signals_unix_test.go
  cli/command/image/build/context_unix.go
  cli/command/image/build/context_windows.go
  cli/config/configfile/file_unix.go
  cli/config/credentials/default_store_unsupported.go
  cli/connhelper/commandconn/commandconn_unix_test.go
  cli/connhelper/commandconn/pdeathsig_nolinux.go
  cli/connhelper/commandconn/session_unix.go
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
  opts/hosts_unix.go
  opts/hosts_windows.go
Labels: impact/changelog, area/packaging

#3532 [20.10] vendor: docker/docker 20.10.14, docker/distribution v2.8.1, image-spec v1.0.2
  vendor.conf
  vendor/github.com/docker/distribution/README.md
  vendor/github.com/docker/distribution/blobs.go
  vendor/github.com/docker/distribution/manifest/manifestlist/manifestlist.go
  vendor/github.com/docker/distribution/registry/client/repository.go
  vendor/github.com/docker/distribution/vendor.conf
  vendor/github.com/docker/docker/vendor.conf
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
Labels: status/2-code-review

#3550 docs: deprecated: add entry for "fluent-async-connect" log-opt
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, status/3-docs-review, process/cherry-picked

#3562 update golang to 1.18.1
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: impact/changelog, status/2-code-review, area/packaging

#3543 remove "Experimental" client field from "docker version"
  cli/command/system/testdata/docker-client-version.golden
  cli/command/system/version.go
  cli/command/system/version_test.go
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/2-code-review

#3555 cli/command/image: remove use of docker/docker/pkg/urlutil
  cli/command/image/import.go
Labels: status/2-code-review, kind/refactor

#3578 Remove bash completion for deprecated orchestrator flags
  contrib/completion/bash/docker
Labels: status/2-code-review, area/stack, area/kubernetes, area/completion

#3577 Add bash completion for `docker stack config`
  contrib/completion/bash/docker
  docs/reference/commandline/stack_config.md
Labels: status/2-code-review, area/completion

#3539 Improvements to makefile and development container
  Makefile
  docker.Makefile
  dockerfiles/Dockerfile.dev
  scripts/warn-outside-container
Labels: kind/enhancement, status/2-code-review

#3547 Add --force option to network rm subcommand
  cli/command/network/client_test.go
  cli/command/network/remove.go
  cli/command/network/remove_test.go
  contrib/completion/bash/docker
  docs/reference/commandline/network_rm.md
Labels: impact/changelog, kind/enhancement, status/2-code-review

#1502 Add example get API version
  docs/reference/commandline/version.md
Labels: kind/docs, status/3-docs-review
