Repository docker/cli, pull requests merged in 2022-03, with the labels that each got.

#3445 cli/compose/schema: make version: "3" equivalent to "3.x" (latest)
  cli/compose/loader/loader_test.go
  cli/compose/schema/schema.go
  cli/compose/schema/schema_test.go
Labels: impact/changelog, status/2-code-review, impact/documentation, area/stack, docs/revisit, impact/compose-file

#3449 docs: add missing documentation for --pull flag
  docs/reference/commandline/create.md
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#3450 docs: unify "docker create" and "docker run" reference
  docs/reference/commandline/create.md
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#3451 docs: daemon: remove LCOW configuration options
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/run.md
Labels: impact/deprecation, kind/docs, kind/experimental, status/3-docs-review, platform/windows

#3377 cli/command: Add quiet option for create and run
  cli/command/container/create.go
  cli/command/container/run.go
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/reference/commandline/create.md
  docs/reference/commandline/run.md
Labels: impact/changelog, kind/docs, kind/enhancement, area/completion

#3454 vendor: gotest.tools/v3 v3.1.0
  vendor.mod
  vendor.sum
  vendor/gotest.tools/v3/assert/assert_go113.go
  vendor/gotest.tools/v3/assert/cmp/compare_go113.go
  vendor/gotest.tools/v3/fs/file.go
  vendor/gotest.tools/v3/fs/manifest_unix.go
  vendor/gotest.tools/v3/golden/golden.go
  vendor/gotest.tools/v3/icmd/command.go
  vendor/gotest.tools/v3/icmd/exitcode.go
  vendor/gotest.tools/v3/poll/check.go
  vendor/modules.txt
Labels: status/2-code-review, area/testing

#2992 Implement WithDefaultContextStoreConfig() DockerCliOption
  cli/command/cli.go
  cli/command/cli_options.go
Labels: status/2-code-review, area/context

#3460 remove duplicate imports, update or remove aliases on imports
  cli/cobra.go
  cli/command/cli.go
  cli/command/cli_test.go
  cli/command/image/trust.go
  cli/command/manifest/inspect_test.go
  cli/command/registry/formatter_search.go
  cli/command/system/info_test.go
  cli/context/store/store.go
  cli/flags/common.go
  cli/flags/common_test.go
  cli/manifest/store/store.go
  cli/registry/client/fetcher.go
  cli/trust/trust.go
  cli/trust/trust_test.go
Labels: status/2-code-review, kind/refactor

#3461 [20.10] update to go 1.16.15 to address CVE-2022-24921
  Dockerfile
  appveyor.yml
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review

#3463 improve cp documentation with some illustration examples
  docs/reference/commandline/cp.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#3469 Handle relative source mounts
  cli/command/container/opts.go
  opts/mount.go
  opts/mount_test.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/volumes

#3125 docs: remove note about buildkit not supporting git subdirectories
  docs/reference/commandline/build.md
Labels: kind/docs, status/3-docs-review, area/builder

#3470 search: do not sort results by stars on client side
  cli/command/registry/search.go
Labels: impact/changelog, status/2-code-review, area/distribution

#3136 Remove ClientInfo as it is not practically used.
  cli/command/cli.go
  cli/command/cli_test.go
  cmd/docker/docker.go
  internal/test/cli.go
Labels: status/2-code-review, area/api, kind/refactor

#2704 Reference docs: Fix CMD --ignored-param1 example
  docs/reference/builder.md
Labels: kind/docs, status/3-docs-review, area/builder, process/cherry-pick

#2953 Update the list of log drivers
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#3475 Dockerfile: use syntax=docker/dockerfile:1
  Dockerfile
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.shellcheck
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review

#3476 vendor: golang.org/x/crypto v0.0.0-20220315160706-3147a52a75dd
  vendor.mod
  vendor.sum
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/const.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/edwards25519.go
  vendor/modules.txt
Labels: status/2-code-review

#3489 Dockerfile: update xx to 1.1
  Dockerfile
Labels: status/2-code-review, process/cherry-pick

#3491 Dockerfile: use xx-apt-get instead of xx-apt
  Dockerfile
Labels: status/2-code-review

#3490 scripts/build: make sure osusergo is set for static with CGO enabled
  scripts/build/.variables
Labels: status/2-code-review, process/cherry-pick, kind/bugfix

#3383 update go to 1.17
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: impact/changelog, status/2-code-review

#3496 vendor dependencies with go1.17
  scripts/vendor
  vendor.mod
  vendor.sum
  vendor/github.com/Azure/go-ansiterm/go.mod
  vendor/github.com/Azure/go-ansiterm/go.sum
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/cespare/xxhash/v2/go.mod
  vendor/github.com/cespare/xxhash/v2/go.sum
  vendor/github.com/creack/pty/go.mod
  vendor/github.com/docker/go-metrics/go.mod
  vendor/github.com/docker/go-metrics/go.sum
  vendor/github.com/fvbommel/sortorder/go.mod
  vendor/github.com/fvbommel/sortorder/go.sum
  vendor/github.com/google/shlex/go.mod
  vendor/github.com/gorilla/mux/go.mod
  vendor/github.com/imdario/mergo/go.mod
  vendor/github.com/imdario/mergo/go.sum
  vendor/github.com/klauspost/compress/go.mod
  vendor/github.com/klauspost/compress/go.sum
  vendor/github.com/miekg/pkcs11/go.mod
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/github.com/moby/sys/signal/go.mod
  vendor/github.com/moby/sys/signal/go.sum
  vendor/github.com/moby/sys/symlink/go.mod
  vendor/github.com/moby/sys/symlink/go.sum
  vendor/github.com/moby/term/go.mod
  vendor/github.com/moby/term/go.sum
  vendor/github.com/opencontainers/go-digest/go.mod
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/pflag/go.mod
  vendor/github.com/spf13/pflag/go.sum
  vendor/github.com/theupdateframework/notary/go.mod
  vendor/github.com/theupdateframework/notary/go.sum
  vendor/github.com/tonistiigi/go-rosetta/go.mod
  vendor/github.com/xeipuuv/gojsonschema/go.mod
  vendor/github.com/xeipuuv/gojsonschema/go.sum
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/xerrors/go.mod
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/modules.txt
Labels: status/2-code-review

#3495 gofmt with go1.17
  cli-plugins/manager/manager_unix.go
  cli-plugins/manager/suffix_unix.go
  cli/command/container/signals_unix.go
  cli/command/container/signals_unix_test.go
  cli/command/image/build/context_unix.go
  cli/command/image/build/context_windows.go
  cli/config/configfile/file_unix.go
  cli/config/credentials/default_store_unsupported.go
  cli/connhelper/commandconn/commandconn_unix_test.go
  cli/connhelper/commandconn/pdeathsig_nolinux.go
  cli/connhelper/commandconn/session_unix.go
  docs/generate.go
  docs/tools.go
  man/generate.go
  man/tools.go
  opts/hosts_unix.go
  opts/hosts_windows.go
Labels: status/2-code-review

#3307 doc: Add `default-runtime` opt to daemon.json
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review, platform/windows

#3500 Change "COMPANY_NAME" to "PACKAGER_NAME"
  Dockerfile
  Makefile
  docker-bake.hcl
  docker.Makefile
  scripts/build/mkversioninfo
Labels: status/2-code-review, area/packaging

#3502 lint: update golangci-lint to v1.45.2
  .golangci.yml
  cli/command/config/formatter_test.go
  cli/command/config/inspect_test.go
  cli/command/container/create.go
  cli/command/container/create_test.go
  cli/command/container/formatter_stats.go
  cli/command/container/formatter_stats_test.go
  cli/command/formatter/container_test.go
  cli/command/formatter/disk_usage_test.go
  cli/command/formatter/formatter.go
  cli/command/formatter/image_test.go
  cli/command/formatter/volume_test.go
  cli/command/image/build.go
  cli/command/inspect/inspector.go
  cli/command/inspect/inspector_test.go
  cli/command/network/formatter_test.go
  cli/command/node/formatter_test.go
  cli/command/plugin/formatter_test.go
  cli/command/plugin/inspect_test.go
  cli/command/plugin/list_test.go
  cli/command/registry/formatter_search_test.go
  cli/command/secret/formatter_test.go
  cli/command/secret/inspect_test.go
  cli/command/service/formatter_test.go
  cli/command/service/opts.go
  cli/command/stack/formatter/formatter_test.go
  cli/command/stack/list_test.go
  cli/command/stack/loader/loader.go
  cli/command/stack/services_test.go
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/version.go
  cli/command/task/formatter_test.go
  cli/command/trust/formatter_test.go
  cli/command/volume/create.go
  cli/command/volume/create_test.go
  cli/command/volume/inspect_test.go
  cli/compose/interpolation/interpolation.go
  cli/compose/interpolation/interpolation_test.go
  cli/config/credentials/native_store.go
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, area/testing

#3493 Update to debian bullseye
  .github/workflows/e2e.yml
  Dockerfile
  docker-bake.hcl
Labels: status/2-code-review

#3504 Fix flaky TestContainerList tests
  cli/command/container/testdata/container-list-without-format-no-trunc.golden
  cli/command/container/testdata/container-list-without-format.golden
  internal/test/builders/container.go
Labels: status/2-code-review, area/testing, kind/bugfix

#3501 update go to 1.18.0
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  templates/templates.go
Labels: impact/changelog, status/2-code-review

#3507 Dockerfile: update buildx to v0.8.1
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review

#3471 search: remove client-side default for --limit
  cli/command/registry/search.go
  docs/reference/commandline/index.md
  docs/reference/commandline/search.md
  man/src/search.md
Labels: status/2-code-review, area/distribution

#3513 use GO_LDFLAGS instead of LDFLAGS to prevent inheriting unrelated options
  scripts/build/.variables
  scripts/build/binary
  scripts/build/plugins
Labels: status/2-code-review, process/cherry-pick, kind/bugfix, area/packaging

#3516 [20.10] vendor.conf: don't use git:// protocol
  vendor.conf
Labels: status/2-code-review, kind/bugfix, area/packaging

#3511 registry: remove some dead code / leftovers from "engine activate"
  cli/command/manifest/client_test.go
  cli/registry/client/client.go
  cli/registry/client/fetcher.go
Labels: status/2-code-review, area/distribution, kind/refactor

#3517 trim leading 0 for minor in the version quad
  scripts/build/mkversioninfo
Labels: status/2-code-review, platform/windows, kind/bugfix, area/packaging
