Repository docker/cli, pull requests merged in 2023-03, with the labels that each got.

#4063 [23.0 backport] context: avoid corrupt file writes
  cli/context/store/metadatastore.go
  cli/context/store/store_test.go
  cli/context/store/tlsstore.go
Labels: status/2-code-review, kind/bugfix

#4061 [23.0 backport] test/cli: Use empty array as empty output of images/json
  cli/command/image/client_test.go
  cli/command/image/list_test.go
Labels: status/2-code-review, area/testing, kind/bugfix

#4065 [23.0 backport] formatter: Consider empty RepoTags and RepoDigests as dangling
  cli/command/formatter/image.go
Labels: status/2-code-review, area/api

#4043 Dockerfile: update buildx to v0.10.3
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, process/cherry-pick

#4038 update to go1.19.6
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, process/cherry-picked, area/packaging

#4039 [23.0 backport] update to go1.19.6
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#4069 docs: Deprecate buildkit's build information
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, area/builder, process/cherry-pick, area/builder/buildkit

#4060 [20.10 backport] test/cli: Use empty array as empty output of images/json
  cli/command/image/client_test.go
  cli/command/image/list_test.go
Labels: status/2-code-review, area/testing, kind/bugfix

#4035 [23.0 backport] changed the container name in docker stats page
  docs/reference/commandline/stats.md
Labels: kind/docs, status/3-docs-review

#4076 [23.0 backport] docs: Deprecate buildkit's build information
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, status/3-docs-review, area/builder, area/builder/buildkit

#4077 [23.0 backport] Dockerfile: update buildx to v0.10.3
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review

#4081 stack/loader: Ignore cmd.exe special env variables
  cli/command/stack/loader/loader.go
  cli/command/stack/loader/loader_test.go
Labels: process/cherry-pick, area/stack, platform/windows, kind/bugfix

#4087 Dockerfile: update buildx to v0.10.4
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, process/cherry-picked

#4088 [23.0 backport] Dockerfile: update buildx to v0.10.4
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review

#4085 update to go1.19.7
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, process/cherry-picked, area/packaging

#4086 [23.0 backport] update to go1.19.7
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#4094 Add bash completion for available plugins
  contrib/completion/bash/docker
Labels: kind/enhancement, status/2-code-review, area/completion

#4107 [23.0 backport] Don't automatically request size if `--size` was explicitly set to `false`
  cli/command/container/list.go
  cli/command/container/list_test.go
Labels: impact/changelog, status/2-code-review, kind/bugfix

#4110 cli/command: remove deprecated ElectAuthServer()
  cli/command/registry.go
Labels: impact/changelog, status/2-code-review

#4092 [23.0 backport] Add bash completion for available plugins
  contrib/completion/bash/docker
Labels: kind/enhancement, status/2-code-review, area/completion

#4114 cli/trust: remove special handling for "plugin" Class
  cli/command/container/create.go
  cli/command/image/build.go
  cli/command/image/pull.go
  cli/command/image/trust.go
  cli/command/plugin/install.go
  cli/command/plugin/push.go
  cli/command/trust/common.go
  cli/command/trust/revoke.go
  cli/command/trust/sign.go
  cli/command/trust/signer_add.go
  cli/command/trust/signer_remove.go
  cli/trust/trust.go
Labels: status/2-code-review, area/distribution, area/plugins, area/trust, kind/refactor

#4117 Dockerfile: align go version
  docker-bake.hcl
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, process/cherry-pick, area/packaging

#4123 e2e: update notary certificates
  docker-bake.hcl
  e2e/testdata/Dockerfile.gencerts
  e2e/testdata/gen-certs.sh
  e2e/testdata/notary-evil/notary-server.cert
  e2e/testdata/notary-evil/notary-server.key
  e2e/testdata/notary-evil/root-ca.cert
  e2e/testdata/notary/notary-server.cert
  e2e/testdata/notary/notary-server.key
  e2e/testdata/notary/root-ca.cert
Labels: status/2-code-review, process/cherry-pick, area/testing, kind/bugfix

#4122 don't use null values in the bake definition
  docker-bake.hcl
Labels: status/2-code-review, area/packaging

#4126 [23.0 backport] Dockerfile: align go version
  docker-bake.hcl
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, area/packaging

#4130 ci: enhanced build workflow
  .github/workflows/build.yml
Labels: kind/enhancement, status/2-code-review, area/testing

#4066 [20.10 backport] formatter: Consider empty RepoTags and RepoDigests as dangling
  cli/command/formatter/image.go
Labels: status/2-code-review, area/api

#4133 vendor: github.com/docker/docker v23.0.2
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-pick

#4121 Fix grammar in docs by adding omitted word
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4129 improve and load plugin command stubs when required
  cli-plugins/manager/cobra.go
  cli-plugins/manager/manager.go
  cli/cobra.go
  cmd/docker/docker.go
  e2e/cli-plugins/run_test.go
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-pick, area/completion, area/performance

#4118 Dockerfile: build binary if no target specified
  Dockerfile
Labels: status/2-code-review, kind/bugfix

#4032 [20.10 backport] update to go1.19.7
  Dockerfile
  appveyor.yml
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#4140 update to go1.20.2
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4139 [23.0 backport] gha: align stray go 1.19.4 version
  .github/workflows/test.yml
Labels: status/2-code-review, area/testing, kind/bugfix

#4091 [20.10 backport] Add bash completion for available plugins
  contrib/completion/bash/docker
Labels: kind/enhancement, status/2-code-review, area/completion

#4137 Improve docker cp progress output
  cli/command/container/cp.go
Labels: status/2-code-review, process/cherry-pick, area/ux

#4147 revert "improve plugins discovery performance"
  cli-plugins/manager/manager.go
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: status/2-code-review, area/completion, kind/bugfix, area/performance

#4142 vendor: docker/docker master (v24.0.0-dev), containerd v1.6.20
  vendor.mod
  vendor.sum
  vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/artifact.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime
