Repository docker/cli, pull requests merged in 2023-06, with the labels that each got.

#4320 [24.0] vendor: github.com/docker/docker v24.0.2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4327 Dockerfile.vendor: update GOPROXY to use default with fallback
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, process/cherry-pick, area/testing

#4329 [23.0 backport] Dockerfile.vendor: update GOPROXY to use default with fallback
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, area/testing

#4328 [24.0 backport] Dockerfile.vendor: update GOPROXY to use default with fallback
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, area/testing

#4324 cli/command: fix GoDoc referencing wrong const
  cli/command/cli.go
Labels: status/3-docs-review, process/cherry-pick, kind/bugfix

#4326 [24.0 backport] cli/command: fix GoDoc referencing wrong const
  cli/command/cli.go
Labels: status/3-docs-review, kind/bugfix

#4307 docs: remove devicemapper
  docs/deprecated.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/run.md
  man/docker-run.1.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review

#4330 docs: added example for specifying socket path with -H
  docs/reference/commandline/cli.md
Labels: kind/docs, status/3-docs-review

#4325 cli/command: add EnvOverrideContext const for "DOCKER_CONTEXT"
  cli/command/cli.go
  cli/command/defaultcontextstore.go
Labels: kind/enhancement, status/2-code-review, area/context

#4226 ssh: fix error on commandconn close, add ping and default timeout
  cli/command/cli.go
  cli/connhelper/commandconn/commandconn.go
  cli/connhelper/commandconn/commandconn_unix_test.go
  cli/connhelper/connhelper.go
  cli/connhelper/connhelper_test.go
  vendor/github.com/docker/docker/pkg/process/doc.go
  vendor/github.com/docker/docker/pkg/process/process_unix.go
  vendor/github.com/docker/docker/pkg/process/process_windows.go
  vendor/modules.txt
Labels: impact/changelog, status/2-code-review

#4339 [24.0 backport] docs: move "--detach-keys" example to examples section, add to "docker run" as well
  docs/reference/commandline/attach.md
  docs/reference/commandline/run.md
  man/src/container/attach.md
Labels: kind/docs, status/3-docs-review

#4337 cli/command/container: don't mutate ConfigFile.DetachKeys
  cli/command/container/attach.go
  cli/command/container/create.go
  cli/command/container/create_test.go
  cli/command/container/run.go
  cli/command/container/start.go
Labels: status/2-code-review, kind/refactor

#4350 update go to go1.20.5, alpine 3.17
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, process/cherry-picked, area/packaging

#4355 Dockerfile: update gotestsum to v1.10.0
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#4364 [23.0] update go to go1.19.10, alpine 3.17
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4351 [24.0 backport] update go to go1.20.5, alpine 3.17
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4362 cli/command/context: don't pass CLI if we only need context-store
  cli/command/context/create.go
  cli/command/context/options.go
  cli/command/context/update.go
Labels: status/2-code-review, area/context, kind/refactor

#4363 cli/command: newAPIClientFromEndpoint: use WithUserAgent
  cli/command/cli.go
Labels: status/2-code-review, kind/refactor

#4346 build: error if Dockerfile name is passed with Dockerfile from stdin
  cli/command/image/build.go
  cli/command/image/build/context.go
  cli/command/image/build/context_test.go
Labels: status/2-code-review, area/builder, area/builder/classic-builder, kind/bugfix

#4343 replace some basic uses of fmt.Sprintf(), and minor refactor
  cli/command/config/formatter.go
  cli/command/container/create.go
  cli/command/container/run.go
  cli/command/formatter/container.go
  cli/command/network/formatter.go
  cli/command/secret/formatter.go
  cli/command/system/events.go
  cli/compose/convert/service.go
  cli/compose/convert/service_test.go
Labels: status/2-code-review, kind/refactor

#4361 Dockerfile: update buildx to v0.11.0
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#4344 docs: update the runtime configuration section
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4370 cli/command/context: don't use pkg/homedir in test
  cli/command/context/use_test.go
Labels: status/2-code-review, area/testing

#4371 [24.0 backport] cli/command/context: don't use pkg/homedir in test
  cli/command/context/use_test.go
Labels: status/2-code-review, area/testing

#4369 [24.0 backport] docs: update the runtime configuration section
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#4372 docs: fix broken link
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4373 [24.0 Backport] Fix broken link in dockerd cli reference
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#4374 docs: fix static ip example, network needs a subnet
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4375 [24.0 Backport] Fix static ip example (docker run)
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review

#4289 docs: update link location for the overlay driver
  docs/reference/commandline/service_create.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4381 [24.0 backport] docs: update link location for the overlay driver
  docs/reference/commandline/service_create.md
Labels: kind/docs, status/3-docs-review

#4385 cli/config: add EnvOverrideConfigDir const
  cli/config/config.go
  e2e/context/context_test.go
  e2e/internal/fixtures/fixtures.go
Labels: kind/enhancement, status/2-code-review

#4378 rename and update mergo module
  cli/compose/loader/merge.go
  cli/compose/loader/merge_test.go
  vendor.mod
  vendor.sum
  vendor/dario.cat/mergo/.deepsource.toml
  vendor/dario.cat/mergo/.gitignore
  vendor/dario.cat/mergo/.travis.yml
  vendor/dario.cat/mergo/CODE_OF_CONDUCT.md
  vendor/dario.cat/mergo/CONTRIBUTING.md
  vendor/dario.cat/mergo/LICENSE
  vendor/dario.cat/mergo/README.md
  vendor/dario.cat/mergo/SECURITY.md
  vendor/dario.cat/mergo/doc.go
  vendor/dario.cat/mergo/map.go
  vendor/dario.cat/mergo/merge.go
  vendor/dario.cat/mergo/mergo.go
  vendor/modules.txt
Labels: status/2-code-review

#4368 [24.0 backport] Dockerfile: update gotestsum to v1.10.0, buildx v0.11.0
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#4386 cli/flags: add EnvEnableTLS const for "DOCKER_TLS"
  cli/flags/options.go
Labels: kind/enhancement, status/2-code-review

#4366 cli/command/context: remove deprecated k8s / orchestrator option-stubs
  cli/command/context/create.go
  cli/command/context/export.go
  cli/command/context/update.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/kubernetes, area/context

#4383 vendor: docker/docker 7f8b1cd7f928dee54174d51dc9da17f443c31480 (v25.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/changes.go
  vendor/github.com/docker/docker/pkg/archive/copy.go
  vendor/github.com/docker/docker/pkg/archive/diff.go
  vendor/github.com/docker/docker/pkg/homedir/homedir.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_windows.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
  vendor/github.com/docker/docker/registry/auth.go
  vendor/github.com/docker/docker/registry/endpoint_v1.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/github.com/docker/docker/registry/search.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/session.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4388 cli: move "config" flag to cli/flags/ClientOptions.InstallFlags()
  cli/cobra.go
  cli/flags/options.go
Labels: status/2-code-review, kind/refactor

#4389 cli: SetupRootCommand: remove redundant flags return
  cli-plugins/plugin/plugin.go
  cli/cobra.go
  cmd/docker/docker.go
  docs/generate/generate.go
Labels: status/2-code-review, kind/refactor

#4392 docker info: fix condition for printing debug information
  cli/command/system/info.go
Labels: status/2-code-review, process/cherry-picked, kind/bugfix

#4393 [24.0 backport] docker info: fix condition for printing debug information
  cli/command/system/info.go
Labels: status/2-code-review, kind/bugfix

#4394 commandconn: return original error while closing
  cli/connhelper/commandconn/commandconn.go
  cli/connhelper/commandconn/commandconn_unix_test.go
Labels: status/2-code-review, process/cherry-pick, area/testing, kind/bugfix

#4395 [24.0 backport] ssh: fix error on commandconn close, add ping and default timeout
  cli/command/cli.go
  cli/connhelper/commandconn/commandconn.go
  cli/connhelper/commandconn/commandconn_unix_test.go
  cli/connhelper/connhelper.go
  cli/connhelper/connhelper_test.go
Labels: impact/changelog, status/2-code-review, kind/bugfix
