Repository docker/cli, pull requests merged in 2023-04, with the labels that each got.

#4150 vendor: github.com/docker/docker v24.0.0-beta.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4152 cli/command: fix deprecation comments for Stream types
  cli/command/streams.go
Labels: impact/deprecation, status/2-code-review, process/cherry-picked, kind/bugfix

#4151 improve plugins listing performance
  cli-plugins/manager/candidate_test.go
  cli-plugins/manager/manager.go
  cli-plugins/manager/plugin.go
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-pick, area/completion, kind/bugfix, area/performance

#4136 Fix plugin completion results parsing for `ShellCompDirectiveFilterFileExt`
  contrib/completion/bash/docker
Labels: status/2-code-review, process/cherry-pick, area/completion, kind/bugfix

#4141 [23.0 backport] improve and load plugin command stubs when required
  cli-plugins/manager/candidate_test.go
  cli-plugins/manager/cobra.go
  cli-plugins/manager/manager.go
  cli-plugins/manager/plugin.go
  cli/cobra.go
  cmd/docker/docker.go
  e2e/cli-plugins/run_test.go
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: impact/changelog, status/2-code-review, area/completion, area/performance

#4157 [23.0 backport] improve cp progress
  cli/command/container/cp.go
Labels: status/2-code-review, kind/bugfix, area/ux

#4154 [23.0 backport] cli/command: fix deprecation comments for Stream types
  cli/command/streams.go
Labels: impact/deprecation, status/2-code-review, kind/bugfix

#4162 update go to go1.20.3
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4164 [23.0] update go to go1.19.8
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4163 [20.10] update go to go1.19.8
  Dockerfile
  appveyor.yml
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#3972 cli/command: embed "Streams" interface in "Cli"
  cli/command/cli.go
Labels: status/2-code-review, kind/refactor

#4169 scripts/docs/generate-md.sh: fix location of generate code
  docs/reference/commandline/container_rm.md
  docs/reference/commandline/rm.md
  scripts/docs/generate-md.sh
Labels: kind/docs, status/2-code-review, process/cherry-pick, kind/bugfix

#4170 Update version to v24.0.0-dev
  VERSION
Labels: status/2-code-review, area/packaging

#3978 some minor cleanups
  cli/command/container/create.go
  cli/command/container/opts_test.go
  cli/command/container/run.go
Labels: status/2-code-review, kind/refactor

#4179 docs: update engine versions in some examples
  docs/reference/commandline/build.md
  docs/reference/commandline/info.md
  docs/reference/commandline/node_ls.md
  docs/reference/commandline/version.md
  man/src/system/info.md
  man/src/version.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked

#4177 [23.0 backport] Fix plugin completion parsing for plugins using `ShellCompDirectiveFilterFileExt`
  contrib/completion/bash/docker
Labels: status/2-code-review, area/completion, kind/bugfix

#4178 [23.0] vendor: github.com/docker/docker v23.0.3
  vendor.mod
  vendor.sum
  vendor/github.com/containerd/containerd/platforms/defaults_windows.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4182 [23.0 backport] docs: update engine versions in some examples
  docs/reference/commandline/build.md
  docs/reference/commandline/info.md
  docs/reference/commandline/node_ls.md
  docs/reference/commandline/version.md
  man/src/system/info.md
  man/src/version.md
Labels: kind/docs, status/3-docs-review

#4176 [23.0 backport] Fix grammar in docs by adding omitted word
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#4175 [23.0 backport] ci: enhanced build workflow
  .github/workflows/build.yml
Labels: kind/enhancement, status/2-code-review, area/testing

#4172 [23.0 backport] scripts/docs/generate-md.sh: fix location of generate code
  docs/reference/commandline/container_rm.md
  docs/reference/commandline/rm.md
  scripts/docs/generate-md.sh
Labels: kind/docs, status/2-code-review, kind/bugfix

#4168 fix docker info, docker version --format=json not outputting json format
  cli/command/formatter/formatter.go
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-client-version.json.golden
  cli/command/system/version.go
  cli/command/system/version_test.go
  docs/reference/commandline/info.md
  docs/reference/commandline/system_info.md
  docs/reference/commandline/version.md
Labels: status/2-code-review, process/cherry-pick, kind/bugfix, area/ux

#4192 cli/command: fix documentation for ResolveAuthConfig
  cli/command/registry.go
Labels: status/2-code-review, area/distribution, process/cherry-pick

#4194 docs: deprecated: fix version (23.1.0 -> 24.0.0)
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, status/3-docs-review, process/cherry-picked

#4195 [23.0 backport] docs: deprecated: fix version (23.1.0 -> 24.0.0)
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, status/3-docs-review

#4180 docker info: include Client Version and "platform name"
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-client-version.json.golden
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-legacy-warnings.json.golden
  cli/command/system/testdata/docker-info-no-swarm.golden
  cli/command/system/testdata/docker-info-no-swarm.json.golden
  cli/command/system/version.go
  docs/reference/commandline/info.md
  man/src/system/info.md
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/ux

#4173 vendor: github.com/spf13/cobra v1.7.0
  vendor.mod
  vendor.sum
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: kind/enhancement, status/2-code-review, area/completion

#4022 Fix styling of arguments
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review

#4197 cli: make cobra templates a const
  cli/cobra.go
Labels: status/2-code-review, kind/refactor

#4196 [23.0 backport] cli/command: fix documentation for ResolveAuthConfig
  cli/command/registry.go
Labels: status/2-code-review, area/distribution

#4190 cli/command: some cleanups / refactoring, and fixes related to auth
  cli/command/container/create.go
  cli/command/image/push.go
  cli/command/image/trust.go
  cli/command/plugin/install.go
  cli/command/plugin/push.go
  cli/command/registry.go
  cli/command/registry/search.go
  cli/command/trust/sign.go
Labels: status/2-code-review, area/distribution

#4204 docker info: don't print "registry" (IndexServerAddress)
  cli/command/system/info.go
  cli/command/system/testdata/docker-info-badsec.golden
  cli/command/system/testdata/docker-info-no-swarm.golden
  cli/command/system/testdata/docker-info-plugins.golden
  cli/command/system/testdata/docker-info-with-labels-empty.golden
  cli/command/system/testdata/docker-info-with-labels-nil.golden
  cli/command/system/testdata/docker-info-with-swarm.golden
  docs/reference/commandline/info.md
  man/src/system/info.md
Labels: impact/changelog, status/2-code-review, docs/revisit, area/ux

#4199 docs/reference: update dockerd docs for changes in 23.0
  docs/reference/commandline/cli.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/pull.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked

#4206 docs: update deprecation status of BuildKit "buildInfo" for v24.0.0
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, status/3-docs-review, area/builder, area/builder/buildkit

#4210 vendor: github.com/docker/docker v24.0.0-beta.2
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/client_deprecated.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4209 docs: deprecation: OOM-score adjust for the daemon
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review

#4214 Swarm: Add schema 3.11, and Allow additional properties in `build`
  cli/compose/loader/loader_test.go
  cli/compose/schema/data/config_schema_v3.11.json
  cli/compose/schema/schema.go
  cli/compose/schema/schema_test.go
Labels: impact/changelog, status/2-code-review, area/stack

#4216 Handle empty DOCKER_BUILDKIT like unset
  cli/command/cli.go
  cmd/docker/builder.go
Labels: status/2-code-review, area/builder, process/cherry-picked, kind/bugfix

#4231 [23.0 backport] ci: add validation for generated docs, bump docker/bake-action
  .github/workflows/build.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing

#4230 [23.0 backport] fix docker info, docker version --format=json not outputting json format
  cli/command/formatter/formatter.go
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-client-version.json.golden
  cli/command/system/version.go
  cli/command/system/version_test.go
  docs/reference/commandline/info.md
  docs/reference/commandline/system_info.md
  docs/reference/commandline/version.md
Labels: status/2-code-review, kind/bugfix, area/ux

#4220 docs: update deprecation status for overlay2.override_kernel_check
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review, docs/revisit

#4205 cli/command/system: prettyPrintServerInfo: don't depend on IndexServerAddress and credential-store
  cli/command/system/info.go
Labels: status/2-code-review, area/distribution, kind/refactor

#4174 cli/command: remove deprecated Stream types
  cli/command/streams.go
Labels: impact/deprecation, status/2-code-review, kind/refactor

#4219 docs: update deprecation status of "overlay" and "AuFS"
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review, docs/revisit

#4144 Docs freshness updates to Docker run command docs
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked

#4232 [23.0 backport] Docs freshness updates
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review

#4233 [23.0] vendor: github.com/docker/docker v23.0.4
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4045 test/e2e: Fix running `test-e2e` on non-amd64 platforms
  cli/command/image/build_test.go
  e2e/container/run_test.go
  e2e/container/testdata/run-attached-from-remote-and-remove.golden
  e2e/image/build_test.go
  e2e/image/pull_test.go
  e2e/image/push_test.go
  e2e/image/testdata/pull-with-content-trust-err.golden
  e2e/image/testdata/pull-with-content-trust.golden
  e2e/internal/fixtures/fixtures.go
  e2e/stack/testdata/full-stack.yml
  e2e/stack/testdata/stack-with-named-resources.yml
  e2e/testdata/Dockerfile.evil-notary-server
  e2e/testdata/Dockerfile.notary-server
  e2e/trust/sign_test.go
  internal/test/environment/testenv.go
  scripts/test/e2e/load-image
Labels: status/2-code-review, area/testing, kind/bugfix

#4234 [23.0] vendor: github.com/docker/docker v23.0.5
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/client_deprecated.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4242 remove uses of deprecated VirtualSize field
  cli/command/formatter/disk_usage.go
  cli/command/formatter/image.go
  cli/command/formatter/image_test.go
Labels: impact/deprecation, status/2-code-review
