Repository docker/cli, pull requests merged in 2023-08, with the labels that each got.

#4471 [24.0 backport] vendor: gotest.tools/v3 v3.5.0
  .golangci.yml
  vendor.mod
  vendor.sum
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/env/env.go
  vendor/gotest.tools/v3/icmd/command.go
  vendor/gotest.tools/v3/icmd/ops.go
  vendor/gotest.tools/v3/poll/check.go
  vendor/gotest.tools/v3/poll/poll.go
  vendor/modules.txt
Labels: status/2-code-review, area/testing

#4474 update to go1.20.7
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4477 [23.0 backport] update to go1.20.7
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4476 [24.0 backport] update to go1.20.7
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4475 [20.10] update to go1.19.12
  Dockerfile
  appveyor.yml
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#4485 vendor: github.com/docker/docker 4b19b2f4babd (25.0-dev)
  cli/command/registry/formatter_search.go
  cli/command/registry/formatter_search_test.go
  cli/command/system/testdata/docker-info-badsec.json.golden
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-legacy-warnings.json.golden
  cli/command/system/testdata/docker-info-no-swarm.json.golden
  cli/command/system/testdata/docker-info-plugins.json.golden
  cli/command/system/testdata/docker-info-with-swarm.json.golden
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/github.com/docker/docker/api/types/system/info.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/container_stats.go
  vendor/github.com/docker/docker/client/hijack.go
  vendor/github.com/docker/docker/client/options.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/client/transport.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/search.go
  vendor/github.com/moby/swarmkit/v2/api/api.pb.txt
  vendor/github.com/moby/swarmkit/v2/api/types.pb.go
  vendor/github.com/moby/swarmkit/v2/api/types.proto
  vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: status/2-code-review

#4448 docs: add missing docs for "DOCKER_TLS" env-var
  docs/reference/commandline/cli.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4399 docs: document special host-gateway value for add-host
  docs/reference/commandline/build.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick, area/networking

#4412 cli/command: ResolveAuthConfig, GetDefaultAuthConfig: take ConfigFile as arg
  cli/command/cli.go
  cli/command/container/create.go
  cli/command/image/push.go
  cli/command/image/trust.go
  cli/command/plugin/install.go
  cli/command/plugin/push.go
  cli/command/registry.go
  cli/command/registry/login.go
  cli/command/registry/search.go
  cli/command/registry_test.go
  cli/command/service/create.go
  cli/command/service/trust.go
  cli/command/service/update.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/trust/sign.go
Labels: status/2-code-review, kind/refactor

#4491 [24.0 Backport] docs: document special host-gateway value for add-host
  docs/reference/commandline/build.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review

#4413 search: deprecate "is-automated" filter and "IsAutomated" field
  cli/command/registry/formatter_search.go
  cli/command/registry/formatter_search_test.go
  cli/command/registry/search.go
  cli/command/registry/testdata/search-context-write-stars-table.golden
  cli/command/registry/testdata/search-context-write-table.golden
  docs/deprecated.md
  docs/reference/commandline/search.md
  man/src/search.md
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/distribution

#4478 login: Add message about using PATs
  cli/command/registry.go
  cli/hints/hints.go
Labels: kind/feature, status/2-code-review, area/ux, area/authentication

#4497 Update docs/command output for volume pruning
  cli/command/system/prune.go
  cli/command/volume/prune.go
  docs/reference/commandline/index.md
  docs/reference/commandline/system_prune.md
  docs/reference/commandline/volume.md
  docs/reference/commandline/volume_prune.md
Labels: kind/docs, status/4-merge, process/cherry-pick, area/volumes

#4500 [24.0 backport] login: Add message about using PATs
  cli/command/registry.go
  cli/hints/hints.go
Labels: kind/feature, status/2-code-review, area/ux, area/authentication

#4511 cli/registry/client: set actions when authn with token
  cli/registry/client/client.go
  cli/registry/client/endpoint.go
Labels: status/2-code-review, area/distribution, process/cherry-pick, kind/bugfix, area/manifest

#4506 cmd/docker: areFlagsSupported: don't Ping if not needed
  cmd/docker/docker.go
Labels: status/2-code-review, process/cherry-picked, kind/bugfix

#4509 [23.0 backport] cmd/docker: areFlagsSupported: don't Ping if not needed
  cmd/docker/docker.go
Labels: status/2-code-review, kind/bugfix

#4508 [24.0 backport] cmd/docker: areFlagsSupported: don't Ping if not needed
  cmd/docker/docker.go
Labels: status/2-code-review, kind/bugfix

#4516 update flag-description for --cgroup-parent
  cli/command/image/build.go
  docs/reference/commandline/build.md
  docs/reference/commandline/builder_build.md
  docs/reference/commandline/image_build.md
Labels: kind/enhancement, status/2-code-review, area/builder, area/builder/classic-builder, area/ux

#4514 replace dockerfile/dockerignore with patternmatcher/ignorefile
  cli/command/image/build/dockerignore.go
  vendor.mod
  vendor.sum
  vendor/github.com/moby/patternmatcher/ignorefile/ignorefile.go
  vendor/modules.txt
Labels: status/2-code-review, area/builder, process/cherry-pick

#4512 [24.0 backport] cli/registry/client: set actions when authn with token
  cli/registry/client/client.go
  cli/registry/client/endpoint.go
Labels: status/2-code-review, area/distribution, kind/bugfix, area/manifest

#4513 [23.0 backport] cli/registry/client: set actions when authn with token
  cli/registry/client/client.go
  cli/registry/client/endpoint.go
Labels: status/2-code-review, area/distribution, kind/bugfix, area/manifest

#4520 [24.0 backport] replace dockerfile/dockerignore with patternmatcher/ignorefile
  cli/command/image/build/dockerignore.go
  vendor.mod
  vendor.sum
  vendor/github.com/moby/patternmatcher/ignorefile/ignorefile.go
  vendor/modules.txt
Labels: status/2-code-review, area/builder

#4517 [24.0 backport] Stop slowing bash init by caching plugins path slowly
  contrib/completion/bash/docker
Labels: status/2-code-review, area/completion, kind/bugfix, area/performance

#4518 [23.0 backport] Stop slowing bash init by caching plugins path slowly
  contrib/completion/bash/docker
Labels: status/2-code-review, area/completion, kind/bugfix, area/performance

#4519 [20.10 backport] Stop slowing bash init by caching plugins path slowly
  contrib/completion/bash/docker
Labels: status/2-code-review, area/completion, kind/bugfix, area/performance

#4526 adding -c option for docker run/build in manpages
  man/docker-build.1.md
  man/docker-run.1.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4524 docs, man, contribute: update links to go documentation, and use https where available
  CONTRIBUTING.md
  cli/command/manifest/util.go
  docs/reference/commandline/config_inspect.md
  docs/reference/commandline/events.md
  docs/reference/commandline/info.md
  docs/reference/commandline/inspect.md
  docs/reference/commandline/logs.md
  docs/reference/commandline/network_inspect.md
  docs/reference/commandline/node_inspect.md
  docs/reference/commandline/secret_inspect.md
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_inspect.md
  docs/reference/commandline/service_logs.md
  docs/reference/commandline/system_events.md
  docs/reference/commandline/volume_inspect.md
  man/src/container/exec.md
  man/src/inspect.md
  man/src/network/inspect.md
  man/src/system/events.md
  man/src/volume/inspect.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked

#4528 [24.0 backport] assorted (docs) backports
  CONTRIBUTING.md
  cli/command/image/build.go
  cli/command/manifest/util.go
  cli/command/system/prune.go
  cli/command/volume/prune.go
  docs/reference/commandline/build.md
  docs/reference/commandline/builder_build.md
  docs/reference/commandline/cli.md
  docs/reference/commandline/config_inspect.md
  docs/reference/commandline/events.md
  docs/reference/commandline/image_build.md
  docs/reference/commandline/index.md
  docs/reference/commandline/info.md
  docs/reference/commandline/inspect.md
  docs/reference/commandline/logs.md
  docs/reference/commandline/network_inspect.md
  docs/reference/commandline/node_inspect.md
  docs/reference/commandline/secret_inspect.md
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_inspect.md
  docs/reference/commandline/service_logs.md
  docs/reference/commandline/system_events.md
  docs/reference/commandline/system_prune.md
  docs/reference/commandline/volume.md
  docs/reference/commandline/volume_inspect.md
  docs/reference/commandline/volume_prune.md
  man/docker-build.1.md
  man/docker-run.1.md
  man/src/container/exec.md
  man/src/inspect.md
  man/src/network/inspect.md
  man/src/system/events.md
  man/src/volume/inspect.md
Labels: kind/docs, status/3-docs-review

#3781 un-skip history test and fix golden mismatches
  cli/command/image/history_test.go
  cli/command/image/testdata/history-command-success.non-human.golden
  cli/command/image/testdata/history-command-success.simple.golden
Labels: status/4-merge, process/cherry-pick, area/testing, kind/bugfix

#4533 rewrite TestParseRestartPolicy to use sub-tests
  cli/command/container/opts_test.go
  opts/parse.go
Labels: status/2-code-review, area/testing, kind/refactor

#4536 docs/reference: run.md: remove stray whitespace
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick, kind/bugfix

#4531 update cli-docs-tool to v0.6.0
  docs/reference/commandline/system.md
  scripts/docs/generate-md.sh
Labels: kind/docs, status/2-code-review, process/cherry-pick

#4532 force TestNewHistoryCommandSuccess to use UTC timezone
  cli/command/image/history_test.go
  cli/command/image/testdata/history-command-success.simple.golden
Labels: status/2-code-review, process/cherry-pick, area/testing, kind/bugfix

#4534 vendor: github.com/docker/docker 5b53ddfcdd1c (v25.0.0-dev)
  cli/command/checkpoint/client_test.go
  cli/command/checkpoint/create.go
  cli/command/checkpoint/create_test.go
  cli/command/checkpoint/formatter.go
  cli/command/checkpoint/formatter_test.go
  cli/command/checkpoint/list.go
  cli/command/checkpoint/list_test.go
  cli/command/checkpoint/remove.go
  cli/command/checkpoint/remove_test.go
  cli/command/container/opts.go
  cli/command/container/opts_test.go
  opts/parse.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/checkpoint/list.go
  vendor/github.com/docker/docker/api/types/checkpoint/options.go
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/container/errors.go
  vendor/github.com/docker/docker/api/types/container/hostconfig.go
  vendor/github.com/docker/docker/api/types/events/events.go
  vendor/github.com/docker/docker/api/types/network/ipam.go
  vendor/github.com/docker/docker/api/types/network/network.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/api/types/versions/compare.go
  vendor/github.com/docker/docker/client/README.md
  vendor/github.com/docker/docker/client/checkpoint_create.go
  vendor/github.com/docker/docker/client/checkpoint_delete.go
  vendor/github.com/docker/docker/client/checkpoint_list.go
  vendor/github.com/docker/docker/client/hijack.go
  vendor/github.com/docker/docker/client/interface_experimental.go
  vendor/github.com/docker/docker/client/ping.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/internal/multierror/multierror.go
  vendor/github.com/docker/docker/pkg/archive/diff.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4522 Dockerfile: use COPY --link where possible
  Dockerfile
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
Labels: kind/enhancement, status/2-code-review, process/cherry-pick, area/testing, area/packaging

#4541 cli/registry/client: remove some redundant conditions
  cli/registry/client/fetcher.go
Labels: status/2-code-review, kind/refactor, area/manifest

#4542 [24.0 backport] cli/registry: fix client.pullManifestList not de-referencing manifest, and remove "v1" check
  cli/registry/client/fetcher.go
Labels: status/2-code-review, kind/bugfix, area/manifest

#4538 [24.0 backport] un-skip history test and fix golden mismatches
  cli/command/image/history_test.go
  cli/command/image/testdata/history-command-success.non-human.golden
  cli/command/image/testdata/history-command-success.simple.golden
Labels: status/2-code-review, area/testing, kind/bugfix

#4537 [24.0 backport] docs/reference: run.md: remove stray whitespace and update cli-docs-tool to v0.6.0
  docs/reference/commandline/system.md
  docs/reference/run.md
  scripts/docs/generate-md.sh
Labels: kind/docs, status/3-docs-review

#4530 cli/command/system: fix "docker events" not supporting --format=json
  cli/command/events_utils.go
  cli/command/system/client_test.go
  cli/command/system/events.go
  cli/command/system/events_test.go
  cli/command/system/testdata/docker-events-default.golden
  cli/command/system/testdata/docker-events-json-action.golden
  cli/command/system/testdata/docker-events-json-template.golden
  cli/command/system/testdata/docker-events-json.golden
  docs/reference/commandline/events.md
  docs/reference/commandline/system_events.md
Labels: status/2-code-review, process/cherry-pick, kind/bugfix, area/ux

#4544 [24.0 backport] cli/command/system: fix "docker events" not supporting --format=json
  cli/command/events_utils.go
  cli/command/system/client_test.go
  cli/command/system/events.go
  cli/command/system/events_test.go
  cli/command/system/testdata/docker-events-default.golden
  cli/command/system/testdata/docker-events-json-action.golden
  cli/command/system/testdata/docker-events-json-template.golden
  cli/command/system/testdata/docker-events-json.golden
  docs/reference/commandline/events.md
  docs/reference/commandline/system_events.md
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/ux
