Repository docker/cli, pull requests merged in 2023-10, with the labels that each got.

#4316 mount: add `bind-recursive=<bool|string>` and deprecate `bind-nonrecursive=<bool>`
  cli/command/container/opts.go
  cli/command/service/opts.go
  cli/command/utils.go
  opts/mount.go
  opts/mount_test.go
Labels: impact/changelog, kind/enhancement, kind/feature, status/2-code-review, docs/revisit, area/ux

#4592 update go-md2man to v2.0.3
  man/go.mod
  scripts/docs/generate-man.sh
Labels: status/2-code-review, process/cherry-pick, area/packaging

#4596 update to go1.21.3
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4598 [23.0] update to go1.20.10
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4597 [24.0] update to go1.20.10
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4594 [24.0 backport] update go-md2man to v2.0.3
  man/go.mod
  scripts/docs/generate-man.sh
Labels: status/2-code-review, area/packaging

#4595 [23.0 backport] update go-md2man to v2.0.3
  man/go.mod
  scripts/docs/generate-man.sh
Labels: status/2-code-review, area/packaging

#4587 [24.0 backport] assorted dockerfile and test updates
  Dockerfile
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/compose-env.connhelper-ssh.yaml
  e2e/compose-env.experimental.yaml
  e2e/compose-env.yaml
  e2e/testdata/Dockerfile.gencerts
  scripts/test/e2e/run
  scripts/vendor
  vendor.mod
Labels: status/2-code-review, area/testing, area/packaging

#4584 [24.0 backport] build(deps): bump actions/checkout from 3 to 4
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing

#4603 vendor: github.com/docker/distribution v2.8.3
  vendor.mod
  vendor.sum
  vendor/github.com/docker/distribution/.golangci.yml
  vendor/github.com/docker/distribution/.mailmap
  vendor/github.com/docker/distribution/BUILDING.md
  vendor/github.com/docker/distribution/Dockerfile
  vendor/github.com/docker/distribution/Makefile
  vendor/github.com/docker/distribution/blobs.go
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/github.com/docker/distribution/registry.go
  vendor/github.com/docker/distribution/registry/api/v2/descriptors.go
  vendor/github.com/docker/distribution/registry/api/v2/urls.go
  vendor/github.com/docker/distribution/registry/client/blob_writer.go
  vendor/github.com/docker/distribution/registry/client/errors.go
  vendor/github.com/docker/distribution/registry/client/repository.go
  vendor/github.com/docker/distribution/registry/storage/cache/memory/memory.go
  vendor/github.com/docker/distribution/vendor.conf
  vendor/modules.txt
Labels: status/2-code-review

#4614 Add docker ps status descriptions
  docs/reference/commandline/ps.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4610 cli/compose/loader: use gotest.tools/v3/golden
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/loader_test.go
  cli/compose/loader/testdata/full-example.json.golden
  cli/compose/loader/testdata/full-example.yaml.golden
  cli/compose/loader/types_test.go
Labels: status/2-code-review, area/stack, area/testing, kind/refactor

#4611 stacks: Add schema 3.12, and add support for start interval
  cli/compose/convert/service.go
  cli/compose/convert/service_test.go
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/loader_test.go
  cli/compose/loader/testdata/full-example.json.golden
  cli/compose/loader/testdata/full-example.yaml.golden
  cli/compose/schema/data/config_schema_v3.12.json
  cli/compose/schema/schema.go
  cli/compose/schema/schema_test.go
  cli/compose/types/types.go
Labels: impact/changelog, status/2-code-review, area/swarm, area/stack, docs/revisit

#4616 vendor: gotest.tools/v3 v3.5.1
  vendor.mod
  vendor.sum
  vendor/gotest.tools/v3/fs/manifest.go
  vendor/gotest.tools/v3/fs/ops.go
  vendor/gotest.tools/v3/fs/path.go
  vendor/gotest.tools/v3/fs/report.go
  vendor/gotest.tools/v3/golden/golden.go
  vendor/gotest.tools/v3/internal/assert/result.go
  vendor/gotest.tools/v3/internal/source/update.go
  vendor/modules.txt
Labels: status/2-code-review, area/testing

#4613 Removed broken link
  CONTRIBUTING.md
Labels: status/2-code-review

#4618 [24.0 backport] Add docker ps status descriptions
  docs/reference/commandline/ps.md
Labels: kind/docs, status/3-docs-review

#4620 update to golangci-lint v1.55.0
  cli/command/image/build/context.go
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, area/testing

#4626 vendor: google.golang.org/grpc v1.56.3
  vendor.mod
  vendor.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: status/2-code-review, kind/bugfix

#4627 vendor: github.com/klauspost/compress v1.17.2
  vendor.mod
  vendor.sum
  vendor/github.com/klauspost/compress/.goreleaser.yml
  vendor/github.com/klauspost/compress/README.md
  vendor/github.com/klauspost/compress/SECURITY.md
  vendor/github.com/klauspost/compress/fse/bitwriter.go
  vendor/github.com/klauspost/compress/fse/compress.go
  vendor/github.com/klauspost/compress/huff0/bitwriter.go
  vendor/github.com/klauspost/compress/huff0/compress.go
  vendor/github.com/klauspost/compress/huff0/decompress.go
  vendor/github.com/klauspost/compress/internal/snapref/encode_other.go
  vendor/github.com/klauspost/compress/zstd/README.md
  vendor/github.com/klauspost/compress/zstd/bitreader.go
  vendor/github.com/klauspost/compress/zstd/bitwriter.go
  vendor/github.com/klauspost/compress/zstd/blockdec.go
  vendor/github.com/klauspost/compress/zstd/blockenc.go
  vendor/github.com/klauspost/compress/zstd/decoder_options.go
  vendor/github.com/klauspost/compress/zstd/dict.go
  vendor/github.com/klauspost/compress/zstd/enc_base.go
  vendor/github.com/klauspost/compress/zstd/enc_best.go
  vendor/github.com/klauspost/compress/zstd/enc_dfast.go
  vendor/github.com/klauspost/compress/zstd/enc_fast.go
  vendor/github.com/klauspost/compress/zstd/encoder.go
  vendor/github.com/klauspost/compress/zstd/encoder_options.go
  vendor/github.com/klauspost/compress/zstd/framedec.go
  vendor/github.com/klauspost/compress/zstd/frameenc.go
  vendor/github.com/klauspost/compress/zstd/matchlen_amd64.go
  vendor/github.com/klauspost/compress/zstd/matchlen_amd64.s
  vendor/github.com/klauspost/compress/zstd/matchlen_generic.go
  vendor/github.com/klauspost/compress/zstd/seqdec.go
  vendor/github.com/klauspost/compress/zstd/seqdec_amd64.s
  vendor/github.com/klauspost/compress/zstd/seqdec_generic.go
  vendor/github.com/klauspost/compress/zstd/snappy.go
  vendor/github.com/klauspost/compress/zstd/zstd.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-picked, kind/bugfix

#4629 [24.0] vendor: github.com/docker/docker v24.0.6
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/pkg/archive/diff.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4625 vendor: github.com/docker/docker fc4d035e7a4e (v25.0.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/hijack.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/moby/sys/user/LICENSE
  vendor/github.com/moby/sys/user/lookup_unix.go
  vendor/github.com/moby/sys/user/user.go
  vendor/github.com/moby/sys/user/user_fuzzer.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/github.com/opencontainers/runc/NOTICE
  vendor/go.opentelemetry.io/otel/semconv/internal/http.go
  vendor/go.opentelemetry.io/otel/semconv/v1.7.0/doc.go
  vendor/go.opentelemetry.io/otel/semconv/v1.7.0/exception.go
  vendor/go.opentelemetry.io/otel/semconv/v1.7.0/http.go
  vendor/go.opentelemetry.io/otel/semconv/v1.7.0/resource.go
  vendor/go.opentelemetry.io/otel/semconv/v1.7.0/schema.go
  vendor/go.opentelemetry.io/otel/semconv/v1.7.0/trace.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4624 Create codeql.yml
  .github/workflows/codeql.yml
Labels: status/2-code-review, area/testing
