Repository docker/cli, pull requests merged in 2023-02, with the labels that each got.

#3999 Fix bad ThrottleDevice path
  opts/throttledevice.go
Labels: status/2-code-review, process/cherry-pick, kind/bugfix

#4001 cli/command/container: exit 126 on EISDIR error
  cli/command/container/run.go
Labels: status/2-code-review, process/cherry-pick, kind/bugfix

#3965 contrib/completion: bash `nounset` mode fixes
  contrib/completion/bash/docker
Labels: status/4-merge, area/completion

#4002 vendor: github.com/docker/docker v23.0.0
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/container_wait.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-pick

#4004 [23.0 backports] assorted backports
  cli/command/container/run.go
  opts/throttledevice.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/container_wait.go
  vendor/modules.txt
Labels: impact/changelog, status/2-code-review

#4011 MAINTAINERS: add myself as curator
  MAINTAINERS
Labels: status/3-docs-review

#4017 ci: fix branch filter pattern
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: process/cherry-pick, area/testing, kind/bugfix

#4018 [23.0 backport] ci: fix branch filter pattern
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing, kind/bugfix

#4031 changed the container name in docker stats page (carry 4027)
  docs/reference/commandline/stats.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4042 context: adjust the file write logic to avoid corrupt context meta.json files
  cli/context/store/metadatastore.go
  cli/context/store/store_test.go
  cli/context/store/tlsstore.go
Labels: status/2-code-review, process/cherry-pick

#4047 [23.0 backport] docs: drop dated comments about graphdrivers
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review

#4046 formatter: Consider empty RepoTags and RepoDigests as dangling
  cli/command/formatter/image.go
Labels: status/2-code-review, process/cherry-pick, area/api
