Repository docker/cli, pull requests merged in 2023-07, with the labels that each got.

#4084 Support CDI devices in --device flag
  cli/command/container/opts.go
  cli/command/container/opts_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/container-orchestrated-devices/container-device-interface/LICENSE
  vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/parser/parser.go
  vendor/modules.txt
Labels: status/1-design-review

#4405 Add support for health start interval
  cli/command/container/opts.go
  cli/command/container/opts_test.go
  cli/command/service/opts.go
  cli/command/service/opts_test.go
  docs/reference/commandline/container_create.md
  docs/reference/commandline/container_run.md
  docs/reference/commandline/create.md
  docs/reference/commandline/run.md
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_update.md
  docs/reference/run.md
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/container/config.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/builder/remotecontext/git/gitutils.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/client/container_list.go
  vendor/github.com/docker/docker/client/node_list.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/pkg/archive/changes.go
  vendor/github.com/docker/docker/pkg/archive/changes_linux.go
  vendor/github.com/docker/docker/pkg/system/init_windows.go
  vendor/github.com/docker/docker/pkg/system/mknod_windows.go
  vendor/github.com/docker/docker/pkg/system/stat_bsd.go
  vendor/github.com/docker/docker/pkg/system/stat_darwin.go
  vendor/github.com/docker/docker/pkg/system/stat_linux.go
  vendor/github.com/docker/docker/pkg/system/stat_openbsd.go
  vendor/github.com/docker/docker/pkg/system/stat_windows.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/modules.txt
Labels: impact/changelog, status/2-code-review, impact/documentation, docs/revisit

#4416 Bump container-device-interface dependency to v0.6.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review

#4411 Dockerfile: update to xx 1.2.1
  Dockerfile
Labels: status/2-code-review, process/cherry-pick, area/testing, area/packaging

#4415 cli/container: Don't ignore error when parsing volume spec
  cli/command/container/opts.go
  cli/compose/loader/volume_test.go
  e2e/container/create_test.go
Labels: status/2-code-review, process/cherry-pick, area/volumes, kind/bugfix, area/ux

#4408 vendor: github.com/moby/swarmkit/v2 v2.0.0-20230627115642-ad0f3ae162fa
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/swarm

#4426 [24.0] vendor: github.com/docker/docker v24.0.5-0.20230714235725-36e9e796c6fc
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/hijack.go
  vendor/github.com/docker/docker/client/request.go
  vendor/modules.txt
Labels: status/2-code-review, kind/bugfix

#4422 vendor: github.com/docker/docker dab9ffb252186f4c47416addb136d579f9314c6a (25.0-dev)
  cli/command/container/client_test.go
  cli/command/container/create_test.go
  cli/command/image/client_test.go
  cli/command/node/client_test.go
  cli/command/node/formatter.go
  cli/command/node/formatter_test.go
  cli/command/node/inspect_test.go
  cli/command/node/list.go
  cli/command/node/list_test.go
  cli/command/node/ps_test.go
  cli/command/plugin/client_test.go
  cli/command/registry/login_test.go
  cli/command/registry_test.go
  cli/command/service/client_test.go
  cli/command/service/ps_test.go
  cli/command/swarm/client_test.go
  cli/command/swarm/join_test.go
  cli/command/swarm/join_token_test.go
  cli/command/swarm/unlock_test.go
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/trust/inspect_pretty_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/system/info.go
  vendor/github.com/docker/docker/api/types/system/runtime.go
  vendor/github.com/docker/docker/api/types/system/security_opts.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/container_attach.go
  vendor/github.com/docker/docker/client/container_exec.go
  vendor/github.com/docker/docker/client/distribution_inspect.go
  vendor/github.com/docker/docker/client/hijack.go
  vendor/github.com/docker/docker/client/image_build.go
  vendor/github.com/docker/docker/client/image_create.go
  vendor/github.com/docker/docker/client/image_load.go
  vendor/github.com/docker/docker/client/image_push.go
  vendor/github.com/docker/docker/client/image_search.go
  vendor/github.com/docker/docker/client/info.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/client/plugin_install.go
  vendor/github.com/docker/docker/client/plugin_push.go
  vendor/github.com/docker/docker/client/plugin_upgrade.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/client/service_create.go
  vendor/github.com/docker/docker/client/service_update.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/session.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/api

#4424 [24.0 backport] Dockerfile: update to xx 1.2.1
  Dockerfile
Labels: status/2-code-review, area/testing, area/packaging

#4421 update go to go1.20.6
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4428 [24.0 backport] update go to go1.20.6
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4429 Dockerfile: update buildx to v0.11.1
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#4430 [24.0 backport] Dockerfile: update buildx to v0.11.1
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#4423 [24.0 backport] cli/container: Don't ignore error when parsing volume spec
  cli/command/container/opts.go
  cli/compose/loader/volume_test.go
  e2e/container/create_test.go
Labels: impact/changelog, status/2-code-review, area/volumes, kind/bugfix

#4425 [24.0 backport] docs: rephrase section on credential stores for docker login
  docs/reference/commandline/cli.md
  docs/reference/commandline/login.md
Labels: kind/docs, status/3-docs-review

#4433 [23.0] vendor: github.com/docker/docker 0420d2b33c42 (23.0.7-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/hijack.go
  vendor/github.com/docker/docker/client/request.go
  vendor/modules.txt
Labels: impact/changelog, status/2-code-review, kind/bugfix

#4432 [23.0 backport] update golangci-lint to v1.52.2 (preparation for go1.20 update)
  cli/command/checkpoint/client_test.go
  cli/command/completion/functions.go
  cli/command/config/client_test.go
  cli/command/config/create_test.go
  cli/command/config/inspect_test.go
  cli/command/config/ls_test.go
  cli/command/container/client_test.go
  cli/command/container/prune.go
  cli/command/container/run.go
  cli/command/context/create.go
  cli/command/idresolver/client_test.go
  cli/command/image/build/context_test.go
  cli/command/image/client_test.go
  cli/command/network/client_test.go
  cli/command/network/prune.go
  cli/command/node/client_test.go
  cli/command/plugin/client_test.go
  cli/command/registry/login_test.go
  cli/command/secret/client_test.go
  cli/command/secret/create_test.go
  cli/command/secret/inspect_test.go
  cli/command/secret/ls_test.go
  cli/command/secret/remove_test.go
  cli/command/service/progress/progress.go
  cli/command/service/update_test.go
  cli/command/stack/client_test.go
  cli/command/stack/deploy.go
  cli/command/stack/list.go
  cli/command/stack/ps.go
  cli/command/stack/remove.go
  cli/command/stack/services.go
  cli/command/stack/swarm/client_test.go
  cli/command/swarm/client_test.go
  cli/command/swarm/ipnet_slice_test.go
  cli/command/task/client_test.go
  cli/command/trust/inspect_pretty_test.go
  cli/command/volume/prune.go
  cli/command/volume/prune_test.go
  cli/compose/convert/service_test.go
  cli/compose/schema/schema.go
  cli/config/configfile/file_test.go
  cli/connhelper/commandconn/commandconn.go
  cli/registry/client/endpoint.go
  cli/trust/trust.go
  dockerfiles/Dockerfile.lint
  internal/test/cli.go
  internal/test/network/client.go
  internal/test/notary/client.go
  opts/capabilities.go
Labels: status/2-code-review, area/testing

#4438 [24.0] vendor: github.com/docker/docker v24.0.5-0.20230717072055-8443a06149b5
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/modules.txt
Labels: status/2-code-review

#4431 [23.0 backport] Dockerfile: update gotestsum to v1.10.0, buildx v0.11.1
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#4427 cli/context/docker: Endpoint.ClientOpts, withHTTPClient: inline variables
  cli/context/docker/load.go
Labels: status/2-code-review, area/context, kind/refactor

#4434 [23.0 backport] update go to go1.20.6
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4442 [20.10] Jenkinsfile: update workers to ubuntu 20.04
  Jenkinsfile
Labels: status/2-code-review, area/testing

#4439 vendor: github.com/docker/docker-credential-helpers v0.8.0
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker-credential-helpers/client/client.go
  vendor/github.com/docker/docker-credential-helpers/client/command.go
  vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go
  vendor/github.com/docker/docker-credential-helpers/credentials/error.go
  vendor/golang.org/x/sys/execabs/execabs.go
  vendor/golang.org/x/sys/execabs/execabs_go118.go
  vendor/golang.org/x/sys/execabs/execabs_go119.go
  vendor/modules.txt
Labels: status/2-code-review

#4443 [24.0] vendor: github.com/docker/docker v24.0.5-0.20230718221249-d4a26c153000
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/hijack.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4444 Dockerfile: update buildx to v0.11.2
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, process/cherry-picked, area/testing

#4445 [24.0 backport Dockerfile: update buildx to v0.11.2
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#4447 cli/command/container: deprecate NewStartOptions
  cli/command/container/start.go
Labels: impact/changelog, impact/deprecation, status/2-code-review

#4450 [24.0 backport] configfile: Initialize nil AuthConfigs
  cli/config/configfile/file.go
  cli/config/credentials/file_store.go
Labels: status/2-code-review, kind/bugfix

#4452 [20.10 backport] configfile: Initialize nil AuthConfigs
  cli/config/configfile/file.go
  cli/config/credentials/file_store.go
Labels: status/2-code-review, kind/bugfix

#4440 [20.10] update go to go1.19.11, debian buster
  Dockerfile
  appveyor.yml
  docker-bake.hcl
  dockerfiles/Dockerfile.binary-native
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.e2e
  dockerfiles/Dockerfile.lint
Labels: impact/changelog, status/2-code-review, area/packaging

#4453 cli/command/container: waitExitOrRemoved: take APIClient as argument
  cli/command/container/run.go
  cli/command/container/start.go
  cli/command/container/utils.go
  cli/command/container/utils_test.go
Labels: status/2-code-review, kind/refactor

#4469 vendor: gotest.tools/v3 v3.5.0
  .golangci.yml
  vendor.mod
  vendor.sum
  vendor/gotest.tools/v3/assert/assert.go
  vendor/gotest.tools/v3/assert/cmp/compare.go
  vendor/gotest.tools/v3/assert/cmp/result.go
  vendor/gotest.tools/v3/env/env.go
  vendor/gotest.tools/v3/icmd/command.go
  vendor/gotest.tools/v3/icmd/ops.go
  vendor/gotest.tools/v3/poll/check.go
  vendor/gotest.tools/v3/poll/poll.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-picked, area/testing
