Repository docker/cli, pull requests merged in 2024-05, with the labels that each got.

#5049 Fix errors encountered by CodeQL
  .github/workflows/codeql.yml
  vendor.mod
Labels: status/2-code-review, area/testing

#5026 otel: simple OTEL collector/Prometheus stack for testing purposes
  hack/otel/README.md
  hack/otel/compose.yaml
  hack/otel/otelcol.yaml
  hack/otel/prom.yaml
Labels: kind/enhancement, status/2-code-review, area/testing, area/metrics, area/metrics/otel

#5060 Fix hang when container fails to start
  cli/command/container/run.go
  cli/command/container/utils.go
  e2e/container/run_test.go
Labels: kind/bugfix, process/cherry-pick/26.1

#5062 [26.1 backport] Fix hang when container fails to start
  cli/command/container/run.go
  cli/command/container/utils.go
  e2e/container/run_test.go
Labels: kind/bugfix

#5064 update to go1.21.10
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, area/dependencies

#5065 [26.1 backport] update to go1.21.10
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, area/packaging, area/dependencies

#5066 [26.1] vendor: github.com/docker/docker v26.1.2-dev (ef1912d8b6ae)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5054 docstring: typo: settings -> setting
  contrib/completion/bash/docker
Labels: status/2-code-review, area/completion

#5068 [26.1 Backport] docs: clarify that --data-path-addr doesn't restrict access
  docs/reference/commandline/swarm_init.md
Labels: kind/docs, status/3-docs-review, area/swarm

#5051 Add OTel instrumentation to CLI plugins
  cli-plugins/plugin/plugin.go
  cli/command/telemetry.go
  cli/command/telemetry_utils.go
  cmd/docker/docker.go
Labels: area/metrics/otel, process/cherry-pick/26.1

#5071 [26.1 backport] Add OTel instrumentation to CLI plugins
  cli-plugins/plugin/plugin.go
  cli/command/telemetry.go
  cli/command/telemetry_utils.go
  cmd/docker/docker.go
Labels: area/metrics/otel

#5074 vendor: github.com/moby/swarmkit/v2 master (c1c857e2dca1)
  vendor.mod
  vendor.sum
  vendor/github.com/moby/swarmkit/v2/api/api.pb.txt
  vendor/github.com/moby/swarmkit/v2/api/types.pb.go
  vendor/github.com/moby/swarmkit/v2/api/types.proto
  vendor/modules.txt
Labels: status/2-code-review, area/swarm, area/dependencies

#5073 [26.1] vendor: github.com/docker/docker v26.1.3-dev (8e96db1c328d)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/runtime

#5018 chore: remove deprecated DualStack field
  cli/registry/client/endpoint.go
  cli/trust/trust.go
Labels: status/2-code-review, kind/refactor

#5029 chore: fix function names in comment
  cli/command/image/build_test.go
Labels: status/4-merge

#5021 docs: tidy up CDI docs
  docs/reference/commandline/container_run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/26.1

#5079 docs: fix json syntax error
  docs/reference/dockerd.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/26.1

#5080 vendor: github.com/docker/docker master (06e3a49d66fa)
  cli/command/plugin/install.go
  cli/command/registry.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/common.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/image/opts.go
  vendor/github.com/docker/docker/client/image_pull.go
  vendor/github.com/docker/docker/client/image_push.go
  vendor/github.com/docker/docker/client/image_search.go
  vendor/github.com/docker/docker/client/plugin_install.go
  vendor/github.com/docker/docker/pkg/ioutils/fswriters.go
  vendor/modules.txt
Labels: status/2-code-review, area/api, area/dependencies

#5078 plugins/hooks: Don't show empty hook messages
  cli-plugins/manager/hooks.go
  cli-plugins/manager/hooks_test.go
Labels: status/2-code-review, area/plugins, kind/bugfix, area/ux

#5084 run, create: update "--rm" flag description to mention anonymous volumes
  cli/command/container/opts.go
  docs/reference/commandline/container_create.md
  docs/reference/commandline/container_run.md
  docs/reference/commandline/create.md
  docs/reference/commandline/run.md
Labels: kind/enhancement, status/2-code-review

#5077 cli/config: improve handling of errors
  cli/config/config.go
  cli/config/config_test.go
Labels: kind/enhancement, status/2-code-review

#5091 docs: use --quiet in example to simplify output
  docs/reference/commandline/container_run.md
Labels: kind/docs, status/3-docs-review

#5086 vendor: github.com/docker/docker-credential-helpers v0.8.2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/authentication, area/dependencies

#5089 Dockerfile: update buildx to v0.14.1, compose v2.27.1
  Dockerfile
Labels: status/2-code-review, area/testing

#5090 Dockerfile: update ALPINE_VERSION to 3.20
  Dockerfile
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, area/testing

#5085 docs: deprecate daemon's api-cors-header flag
  docs/deprecated.md
Labels: kind/docs, status/3-docs-review, area/api

#4994 Document CLI support for per interface sysctls
  cli/command/network/connect_test.go
  docs/reference/commandline/container_run.md
  docs/reference/commandline/network_connect.md
  opts/network_test.go
Labels: impact/changelog, kind/enhancement, impact/documentation, area/networking

#5097 cli/command/context: improve tests and add coverage for custom metadata in contexts
  cli/command/context/create.go
  cli/command/context/export-import_test.go
  cli/command/context/inspect_test.go
  cli/command/context/list_test.go
  cli/command/context/remove_test.go
  cli/command/context/show_test.go
  cli/command/context/testdata/inspect.golden
  cli/command/context/testdata/list-json-name.golden
  cli/command/context/testdata/list-json.golden
  cli/command/context/update_test.go
Labels: status/2-code-review, area/testing, area/context, process/cherry-pick/26.1

#5094 context list: temporarily add ContextType to JSON output
  cli/command/context/list.go
  cli/command/context/testdata/list-json.golden
  cli/command/formatter/context.go
Labels: status/2-code-review, process/cherry-picked, area/context

#5100 vendor: github.com/docker/docker e622cea55698 (master / v27.0.0-dev)
  cli/command/network/client_test.go
  cli/command/network/create_test.go
  cli/command/network/inspect.go
  cli/command/network/remove.go
  cli/command/network/remove_test.go
  cli/command/service/client_test.go
  cli/command/service/inspect.go
  cli/command/service/opts.go
  cli/command/service/opts_test.go
  cli/command/service/update.go
  cli/command/service/update_test.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/stack/swarm/deploy_composefile_test.go
  cli/command/system/inspect.go
  internal/test/network/client.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/network/create_response.go
  vendor/github.com/docker/docker/api/types/network/endpoint.go
  vendor/github.com/docker/docker/api/types/network/network.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/client/network_connect.go
  vendor/github.com/docker/docker/client/network_create.go
  vendor/github.com/docker/docker/client/network_disconnect.go
  vendor/github.com/docker/docker/client/network_inspect.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5095 [26.1 backport] context list: temporarily add ContextType to JSON output
  cli/command/context/create.go
  cli/command/context/export-import_test.go
  cli/command/context/inspect_test.go
  cli/command/context/list.go
  cli/command/context/list_test.go
  cli/command/context/remove_test.go
  cli/command/context/show_test.go
  cli/command/context/testdata/inspect.golden
  cli/command/context/testdata/list-json-name.golden
  cli/command/context/testdata/list-json.golden
  cli/command/context/update_test.go
  cli/command/formatter/context.go
Labels: status/2-code-review, area/context

#5083 [26.1 backport] plugins/hooks: Don't show empty hook messages
  cli-plugins/manager/hooks.go
  cli-plugins/manager/hooks_test.go
Labels: status/2-code-review, area/plugins, kind/bugfix, area/ux
