Repository docker/cli, pull requests merged in 2024-02, with the labels that each got.

#4837 [25.0 Backport] docs: Add Linode docker volume plugin #4396
  docs/extend/legacy_plugins.md
Labels: kind/docs, status/3-docs-review

#4841 [25.0] vendor: github.com/docker/docker v25.0.2
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/builder/remotecontext/urlutil/urlutil.go
  vendor/github.com/docker/docker/pkg/system/xattrs.go
  vendor/github.com/docker/docker/pkg/system/xattrs_linux.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4854 Uniform output of volume prune cmd with other prune cmds
  cli/command/volume/prune.go
  cli/command/volume/prune_test.go
  cli/command/volume/testdata/volume-prune-no.golden
Labels: status/2-code-review, area/ux

#4856 [25.0 backport] Add tests for CLI/plugin communication
  cli-plugins/socket/socket_test.go
  e2e/cli-plugins/plugins/presocket/main.go
  e2e/cli-plugins/socket_test.go
  scripts/test/e2e/run
Labels: status/2-code-review, area/plugins, area/testing

#4857 [25.0 backport] build(deps): Bump codecov/codecov-action from 3 to 4
  .github/workflows/e2e.yml
  .github/workflows/test.yml
Labels: status/2-code-review, area/testing

#4848 [24.0] vendor: github.com/docker/docker v24.0.9
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4835 vendor: github.com/docker/docker 9e075f3808a5 (master, v26.0.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/common.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/network/endpoint.go
  vendor/github.com/docker/docker/api/types/network/ipam.go
  vendor/github.com/docker/docker/api/types/versions/README.md
  vendor/github.com/docker/docker/pkg/ioutils/readers.go
  vendor/github.com/docker/docker/pkg/ioutils/writers.go
  vendor/github.com/moby/swarmkit/v2/api/genericresource/validate.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4858 [25.0] vendor: github.com/docker/docker v25.0.3
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/network/endpoint.go
  vendor/github.com/docker/docker/api/types/network/ipam.go
  vendor/github.com/docker/docker/pkg/ioutils/readers.go
  vendor/github.com/docker/docker/pkg/ioutils/writers.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4860 docker stack: allow '=' separator in extra_hosts
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
Labels: area/stack, area/networking, version/25.0

#4869 cli/connhelper/commandconn: inline variables
  cli/connhelper/commandconn/commandconn_unix_test.go
Labels: status/2-code-review, kind/refactor

#4868 vendor: github.com/docker/docker 86b86412a1b7 (v26.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/container/config.go
  vendor/github.com/moby/docker-image-spec/LICENSE
  vendor/github.com/moby/docker-image-spec/specs-go/v1/image.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4867 Test fixes needed for upgrading ci runners and engine
  e2e/container/run_test.go
  e2e/image/build_test.go
Labels: status/2-code-review, area/testing

#4872 cli-plugins/socket: remove use of deprecated distribution uuid package
  cli-plugins/socket/socket.go
Labels: status/2-code-review, area/plugins, kind/refactor

#4839 update CI
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  docker.Makefile
  e2e/compose-env.connhelper-ssh.yaml
  e2e/compose-env.yaml
  e2e/image/testdata/pull-with-content-trust.golden
  e2e/plugin/trust_test.go
  e2e/testdata/Dockerfile.connhelper-ssh
  e2e/testdata/Dockerfile.evil-notary-server
  e2e/testdata/Dockerfile.notary-server
Labels: status/2-code-review, process/cherry-pick, area/testing

#4876 Fixed typo in bash completion functions
  contrib/completion/bash/docker
Labels: status/2-code-review, area/completion, kind/bugfix

#4881 update to go1.21.7
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, process/cherry-pick, area/packaging

#4883 [25.0 backport] docs: update link targets
  docs/extend/config.md
  docs/extend/plugins_authorization.md
  docs/reference/commandline/builder_build.md
  docs/reference/commandline/cli.md
  docs/reference/commandline/container_attach.md
  docs/reference/commandline/container_cp.md
  docs/reference/commandline/container_create.md
  docs/reference/commandline/container_run.md
  docs/reference/commandline/image_build.md
  docs/reference/commandline/image_pull.md
  docs/reference/commandline/image_push.md
  docs/reference/commandline/image_tag.md
  docs/reference/commandline/index.md
  docs/reference/commandline/node_ls.md
  docs/reference/commandline/node_update.md
  docs/reference/commandline/plugin_create.md
  docs/reference/commandline/plugin_inspect.md
  docs/reference/commandline/service_create.md
  docs/reference/dockerd.md
  docs/reference/index.md
  docs/reference/run.md
  scripts/docs/generate-yaml.sh
Labels: kind/docs, status/3-docs-review

#4884 docs: regenerate markdown
  docs/reference/commandline/attach.md
  docs/reference/commandline/build.md
  docs/reference/commandline/builder_build.md
  docs/reference/commandline/commit.md
  docs/reference/commandline/container_attach.md
  docs/reference/commandline/container_commit.md
  docs/reference/commandline/container_create.md
  docs/reference/commandline/container_run.md
  docs/reference/commandline/create.md
  docs/reference/commandline/history.md
  docs/reference/commandline/image_build.md
  docs/reference/commandline/image_history.md
  docs/reference/commandline/image_pull.md
  docs/reference/commandline/image_push.md
  docs/reference/commandline/plugin_install.md
  docs/reference/commandline/plugin_push.md
  docs/reference/commandline/plugin_upgrade.md
  docs/reference/commandline/pull.md
  docs/reference/commandline/push.md
  docs/reference/commandline/run.md
  scripts/docs/generate-md.sh
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4885 [25.0 backport] docs: regenerate markdown
  docs/reference/commandline/attach.md
  docs/reference/commandline/build.md
  docs/reference/commandline/builder_build.md
  docs/reference/commandline/commit.md
  docs/reference/commandline/container_attach.md
  docs/reference/commandline/container_commit.md
  docs/reference/commandline/container_create.md
  docs/reference/commandline/container_run.md
  docs/reference/commandline/create.md
  docs/reference/commandline/history.md
  docs/reference/commandline/image_build.md
  docs/reference/commandline/image_history.md
  docs/reference/commandline/image_pull.md
  docs/reference/commandline/image_push.md
  docs/reference/commandline/plugin_install.md
  docs/reference/commandline/plugin_push.md
  docs/reference/commandline/plugin_upgrade.md
  docs/reference/commandline/pull.md
  docs/reference/commandline/push.md
  docs/reference/commandline/run.md
  scripts/docs/generate-md.sh
Labels: kind/docs, status/3-docs-review

#4875 plugins: set OTEL_RESOURCE_ATTRIBUTES when invoking a plugin
  cli-plugins/manager/cobra.go
  cli-plugins/manager/manager.go
  cmd/docker/builder.go
  vendor.mod
Labels: area/plugins

#4896 chore: `docker help` should not show plugin vendor and version
  cli/cobra.go
  e2e/cli-plugins/help_test.go
Labels: status/2-code-review, impact/documentation
