Repository docker/cli, pull requests merged in 2024-12, with the labels that each got.

#5649 [27.x] vendor: github.com/docker/docker v27.4.0-rc.3
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5660 cli/trust: GetNotaryRepository: remove uses of RepositoryInfo.Class
  cli/trust/trust.go
Labels: status/2-code-review, area/distribution, process/cherry-picked, area/trust

#5669 [27.x] update to go1.22.10
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, process/cherry-pick/25.0, process/cherry-pick/23.0, area/dependencies, process/cherry-pick/26.1

#5670 [27.x] vendor: github.com/docker/docker v27.4.0-rc.4
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/registry/types.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5667 cli/command/registry: assorted refactor and test changes
  cli/command/registry/login.go
  cli/command/registry/login_test.go
Labels: status/2-code-review, kind/refactor, area/authentication

#5664 run, create, connect: add support for gw-priority
  cli/command/container/opts.go
  cli/command/network/connect.go
  cli/command/network/connect_test.go
  docs/reference/commandline/container_run.md
  docs/reference/commandline/network_connect.md
  opts/network.go
  opts/network_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/network/endpoint.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/service_v2.go
  vendor/github.com/docker/docker/registry/types.go
  vendor/modules.txt
Labels: impact/changelog, kind/feature, status/2-code-review, impact/documentation, area/networking

#5677 [25.0] gha: update to macOS 13, add macOS 14 arm64 (Apple Silicon M1)
  .github/workflows/test.yml
Labels: status/4-merge, area/testing

#5678 [23.0] gha: update to macOS 13, add macOS 14 arm64 (Apple Silicon M1)
  .github/workflows/test.yml
Labels: status/4-merge, area/testing

#5676 [26.1] gha: update to macOS 13, add macOS 14 arm64 (Apple Silicon M1)
  .github/workflows/test.yml
Labels: status/4-merge, area/testing

#5675 [26.1] update to go1.22.10
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/testing, area/packaging

#5680 [25.0] update to go1.22.10
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/4-merge, area/packaging

#5671 vendor: update various golang.org/x/ dependencies
  vendor.mod
  vendor.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5679 cli/command/system: don't use "non-distributable-artifacts" fields in tests
  cli/command/system/info_test.go
Labels: status/2-code-review, area/distribution, area/testing, kind/refactor

#5672 vendor: google.golang.org/protobuf v1.35.2
  vendor.mod
  vendor.sum
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5673 vendor: github.com/docker/docker 5d72419486fe (master, v28.0.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/network/endpoint.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5662 run: correctly handle only STDIN attached
  cli/command/container/run.go
  e2e/container/attach_test.go
  e2e/container/run_test.go
Labels: kind/enhancement, kind/bugfix, kind/refactor, area/ux

#5674 registry/client: remove uses of APIEndpoint.TrimHostName
  cli/registry/client/endpoint.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/utils.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/service_v2.go
  vendor/modules.txt
Labels: status/2-code-review, area/distribution

#5599 Add option --ipv4
  cli/command/network/create.go
  cli/command/network/create_test.go
  cli/command/network/formatter.go
  cli/command/network/formatter_test.go
  docs/reference/commandline/network_create.md
Labels: impact/changelog, kind/feature, area/networking

#5691 cli/command/system: remove netfilter warnings from tests
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-warnings.golden
Labels: status/2-code-review, area/testing, kind/refactor

#5692 [27.x backport] cli/command/system: remove netfilter warnings from tests
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-warnings.golden
Labels: status/2-code-review, area/testing, kind/refactor

#5690 [27.x backport] update go-md2man to v2.0.5
  man/go.mod
  scripts/docs/generate-man.sh
Labels: status/2-code-review, area/packaging

#5683 update xx to v1.6.1 for compatibility with alpine 3.21
  Dockerfile
Labels: status/2-code-review, process/cherry-picked, area/testing

#5685 [27.x backport] update xx to v1.6.1 for compatibility with alpine 3.21
  Dockerfile
Labels: status/2-code-review, area/packaging

#5696 cli/command/system: remove BridgeNfIptables, BridgeNfIp6tables in tests
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-info-badsec.json.golden
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-no-swarm.json.golden
  cli/command/system/testdata/docker-info-plugins.json.golden
  cli/command/system/testdata/docker-info-with-swarm.json.golden
Labels: status/2-code-review, area/testing, kind/refactor, process/cherry-pick/27.x

#5697 cli/command/container: use local copy of pkg/system.IsAbs
  cli/command/container/cp.go
Labels: status/2-code-review, kind/refactor, area/go-sdk, process/cherry-pick/27.x

#5699 [27.x backport] cli/command/container: use local copy of pkg/system.IsAbs
  cli/command/container/cp.go
Labels: status/2-code-review, kind/refactor

#5700 [27.x backport] cli/command/system: remove BridgeNfIptables, BridgeNfIp6tables in tests
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-info-badsec.json.golden
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-no-swarm.json.golden
  cli/command/system/testdata/docker-info-plugins.json.golden
  cli/command/system/testdata/docker-info-with-swarm.json.golden
Labels: status/2-code-review, area/testing

#5702 vendor: update golang.org/x/ dependencies for docker/docker
  vendor.mod
  vendor.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5695 cli/command/system: TestEventsFormat: set cmd.Args to prevent test-failures
  cli/command/system/events_test.go
Labels: kind/enhancement, status/2-code-review, area/testing

#5682 update golangci-lint to v1.62.2
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, area/testing

#5686 [26.1 backport] update xx to v1.6.1 for compatibility with alpine 3.21
  Dockerfile
Labels: status/2-code-review, area/packaging

#5687 [25.0 backport] update xx to v1.6.1 for compatibility with alpine 3.21
  Dockerfile
Labels: status/2-code-review, area/packaging

#5688 [23.0 backport] update xx to v1.6.1 for compatibility with alpine 3.21
  Dockerfile
Labels: status/2-code-review, area/packaging

#5701 [27.x] vendor: github.com/docker/docker v27.4.1
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/client/ping.go
  vendor/github.com/docker/docker/pkg/system/lstat_unix.go
  vendor/github.com/docker/docker/pkg/system/lstat_windows.go
  vendor/github.com/docker/docker/pkg/system/mknod.go
  vendor/github.com/docker/docker/pkg/system/mknod_freebsd.go
  vendor/github.com/docker/docker/pkg/system/mknod_unix.go
  vendor/github.com/docker/docker/pkg/system/stat_linux.go
  vendor/github.com/docker/docker/pkg/system/stat_unix.go
  vendor/github.com/docker/docker/pkg/system/stat_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5703 vendor: github.com/docker/docker ad6929339acd (master, v28.0.0-dev)
  cli/command/system/testdata/docker-info-badsec.json.golden
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-no-swarm.json.golden
  cli/command/system/testdata/docker-info-plugins.json.golden
  cli/command/system/testdata/docker-info-with-swarm.json.golden
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/github.com/docker/docker/api/types/system/info.go
  vendor/github.com/docker/docker/client/ping.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/docker/docker/pkg/archive/archive_other.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/pkg/archive/archive_windows.go
  vendor/github.com/docker/docker/pkg/archive/changes.go
  vendor/github.com/docker/docker/pkg/archive/changes_linux.go
  vendor/github.com/docker/docker/pkg/archive/changes_other.go
  vendor/github.com/docker/docker/pkg/archive/changes_unix.go
  vendor/github.com/docker/docker/pkg/archive/changes_windows.go
  vendor/github.com/docker/docker/pkg/archive/copy.go
  vendor/github.com/docker/docker/pkg/archive/copy_unix.go
  vendor/github.com/docker/docker/pkg/archive/copy_windows.go
  vendor/github.com/docker/docker/pkg/archive/dev_freebsd.go
  vendor/github.com/docker/docker/pkg/archive/dev_unix.go
  vendor/github.com/docker/docker/pkg/archive/diff.go
  vendor/github.com/docker/docker/pkg/archive/time.go
  vendor/github.com/docker/docker/pkg/archive/time_linux.go
  vendor/github.com/docker/docker/pkg/archive/time_nonwindows.go
  vendor/github.com/docker/docker/pkg/archive/time_unsupported.go
  vendor/github.com/docker/docker/pkg/archive/time_windows.go
  vendor/github.com/docker/docker/pkg/archive/whiteouts.go
  vendor/github.com/docker/docker/pkg/archive/wrap.go
  vendor/github.com/docker/docker/pkg/archive/xattr_supported.go
  vendor/github.com/docker/docker/pkg/archive/xattr_supported_linux.go
  vendor/github.com/docker/docker/pkg/archive/xattr_supported_unix.go
  vendor/github.com/docker/docker/pkg/archive/xattr_unsupported.go
  vendor/github.com/docker/docker/pkg/system/lstat_unix.go
  vendor/github.com/docker/docker/pkg/system/lstat_windows.go
  vendor/github.com/docker/docker/pkg/system/mknod.go
  vendor/github.com/docker/docker/pkg/system/mknod_freebsd.go
  vendor/github.com/docker/docker/pkg/system/mknod_unix.go
  vendor/github.com/docker/docker/pkg/system/stat_bsd.go
  vendor/github.com/docker/docker/pkg/system/stat_darwin.go
  vendor/github.com/docker/docker/pkg/system/stat_illumos.go
  vendor/github.com/docker/docker/pkg/system/stat_linux.go
  vendor/github.com/docker/docker/pkg/system/stat_openbsd.go
  vendor/github.com/docker/docker/pkg/system/stat_unix.go
  vendor/github.com/docker/docker/pkg/system/stat_windows.go
  vendor/github.com/docker/docker/registry/auth.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/service_v2.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5706 [27.x] vendor: github.com/docker/docker c23af2910987 (27.x / v27.5.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/container/hostconfig.go
  vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5709 golangci-lint: sync some depguard settings with moby/moby
  .golangci.yml
Labels: status/2-code-review, area/testing

#5710 TestRunCopyFromContainerToFilesystem: use Tar without options
  cli/command/container/cp_test.go
Labels: status/2-code-review, area/testing, kind/refactor

#5711 vendor: github.com/docker/docker a72026acbbdf (master, v28.0.0-dev)
  .golangci.yml
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/idtools/idtools_windows.go
  vendor/github.com/docker/docker/pkg/system/args_windows.go
  vendor/github.com/docker/docker/pkg/system/chtimes.go
  vendor/github.com/docker/docker/pkg/system/chtimes_nowindows.go
  vendor/github.com/docker/docker/pkg/system/chtimes_windows.go
  vendor/github.com/docker/docker/pkg/system/errors.go
  vendor/github.com/docker/docker/pkg/system/filesys.go
  vendor/github.com/docker/docker/pkg/system/filesys_unix.go
  vendor/github.com/docker/docker/pkg/system/filesys_windows.go
  vendor/github.com/docker/docker/pkg/system/init_windows.go
  vendor/github.com/docker/docker/pkg/system/utimes_unix.go
  vendor/github.com/docker/docker/pkg/system/utimes_unsupported.go
  vendor/github.com/docker/docker/pkg/system/xattrs.go
  vendor/github.com/docker/docker/pkg/system/xattrs_linux.go
  vendor/github.com/docker/docker/pkg/system/xattrs_unsupported.go
  vendor/modules.txt
Labels: status/2-code-review, kind/refactor, area/dependencies

#5712 [27.x] vendor: github.com/docker/docker v27.5.0-rc.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5715 Fix container cp test to separate source and destination
  cli/command/container/cp_test.go
Labels: status/2-code-review, area/testing, kind/bugfix, process/cherry-pick/27.x
