Repository docker/cli, pull requests merged in 2024-08, with the labels that each got.

#5311 vendor: go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.21.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/metrics, area/metrics/otel, area/dependencies, process/cherry-pick/27.1

#5310 gha: set permissions to read-only by default
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate-pr.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing, process/cherry-pick/25.0, process/cherry-pick/23.0, process/cherry-pick/27.1

#5324 update to go1.21.13
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, area/dependencies

#5326 [27.x backport] tests/run: fix flaky `RunAttachTermination` test
  cli/command/container/run_test.go
Labels: status/2-code-review, area/testing

#5327 plugins: don't panic on Close if PluginServer nil
  cli-plugins/socket/socket.go
  cli-plugins/socket/socket_test.go
Labels: status/2-code-review, area/plugins, kind/bugfix, process/cherry-pick/26.1, process/cherry-pick/27.1

#5316 add security policy
  SECURITY.md
Labels: kind/docs, status/3-docs-review

#5330 vendor: github.com/docker/docker master (f3cf9359bdf6)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/common.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/image/manifest.go
  vendor/github.com/docker/docker/api/types/image/opts.go
  vendor/github.com/docker/docker/api/types/image/summary.go
  vendor/github.com/docker/docker/api/types/network/network.go
  vendor/github.com/docker/docker/client/image_list.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5325 [27.x backport] update to go1.21.13
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, area/dependencies

#5332 vendor: github.com/docker/docker 2269acc7a31d (master, v-next)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/moby/sys/userns/LICENSE
  vendor/github.com/moby/sys/userns/userns.go
  vendor/github.com/moby/sys/userns/userns_linux.go
  vendor/github.com/moby/sys/userns/userns_linux_fuzzer.go
  vendor/github.com/moby/sys/userns/userns_unsupported.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5334 [27.x backport] docs: refresh image versions in examples
  docs/reference/commandline/container_attach.md
  docs/reference/commandline/container_commit.md
  docs/reference/commandline/container_ls.md
  docs/reference/commandline/image_pull.md
  docs/reference/commandline/service_create.md
  docs/reference/commandline/system_events.md
  docs/reference/run.md
  man/src/container/attach.md
  man/src/container/ls.md
  man/src/image/ls.md
  man/src/image/pull.md
  man/src/system/events.md
Labels: kind/docs, status/2-code-review

#5335 [27.x backport] gha: set permissions to read-only by default
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate-pr.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing

#5338 docs: fix link to http proxy document
  docs/reference/commandline/docker.md
Labels: kind/docs, process/cherry-pick/27.2

#5323 run: fix GetList return empty issue for throttledevice
  opts/throttledevice.go
Labels: status/2-code-review, kind/bugfix, process/cherry-pick/25.0, process/cherry-pick/26.1, process/cherry-pick/27.1

#5336 [25.0 backport] gha: set permissions to read-only by default
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate-pr.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing

#5337 [27.x backport] plugins: don't panic on Close if PluginServer nil
  cli-plugins/socket/socket.go
  cli-plugins/socket/socket_test.go
Labels: status/2-code-review, area/plugins, kind/bugfix

#5339 [27.x backport] run: fix GetList return empty issue for throttledevice
  opts/throttledevice.go
Labels: impact/changelog, status/2-code-review, area/runtime, kind/bugfix

#5340 [26.1 backport] run: fix GetList return empty issue for throttledevice
  opts/throttledevice.go
Labels: impact/changelog, status/2-code-review, area/runtime, kind/bugfix

#5341 [25.0 backport] run: fix GetList return empty issue for throttledevice
  opts/throttledevice.go
Labels: impact/changelog, status/2-code-review, area/runtime, kind/bugfix

#5333 [27.x] vendor: github.com/docker/docker f9522e5e96c3 (v27.1.2-dev) (removes containerd dependency)
  vendor.mod
  vendor.sum
  vendor/github.com/containerd/containerd/NOTICE
  vendor/github.com/containerd/containerd/pkg/userns/userns_linux.go
  vendor/github.com/containerd/containerd/pkg/userns/userns_unsupported.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/moby/sys/user/user.go
  vendor/github.com/moby/sys/userns/LICENSE
  vendor/github.com/moby/sys/userns/userns.go
  vendor/github.com/moby/sys/userns/userns_linux.go
  vendor/github.com/moby/sys/userns/userns_linux_fuzzer.go
  vendor/github.com/moby/sys/userns/userns_unsupported.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5320 disable pseudoterminal creation
  cli/connhelper/connhelper.go
  cli/connhelper/connhelper_test.go
Labels: status/2-code-review, kind/bugfix

#5345 cli/connhelper: getConnectionHelper: move ssh-option funcs out of closure
  cli/connhelper/connhelper.go
Labels: status/2-code-review, kind/refactor

#4982 image/list: Add `--tree` flag
  cli/command/image/list.go
  cli/command/image/tree.go
  docs/reference/commandline/image_ls.md
  docs/reference/commandline/images.md
Labels: impact/changelog, area/api, area/ux, containerd-integration, process/cherry-pick/27.2

#5352 list/tree: Print <untagged> as dangling image name
  cli/command/image/tree.go
Labels: status/2-code-review, area/ux, containerd-integration, process/cherry-pick/27.2

#5351 [27.x backport] disable pseudoterminal creation
  cli/connhelper/connhelper.go
  cli/connhelper/connhelper_test.go
Labels: kind/bugfix

#5354 [27.x] vendor: github.com/docker/docker v27.2.0-dev (9942d656bade)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/common.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/image/manifest.go
  vendor/github.com/docker/docker/api/types/image/opts.go
  vendor/github.com/docker/docker/api/types/image/summary.go
  vendor/github.com/docker/docker/api/types/registry/authconfig.go
  vendor/github.com/docker/docker/client/image_list.go
  vendor/modules.txt
Labels: area/dependencies

#5353 [27.x backport] image/list: Add `--tree` flag
  cli/command/image/list.go
  cli/command/image/tree.go
  docs/reference/commandline/image_ls.md
  docs/reference/commandline/images.md
Labels: impact/changelog, status/2-code-review, area/api, area/ux, containerd-integration

#5356 list/tree: No extra spacing for graphdriver
  cli/command/image/tree.go
Labels: status/2-code-review, area/ux, containerd-integration

#5347 docs: update link to moved build context doc
  docs/reference/commandline/image_build.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked

#5358 [27.x backport] list/tree: No extra spacing for graphdriver
  cli/command/image/tree.go
Labels: status/2-code-review, area/ux, containerd-integration

#5348 [27.x backport] docs: update link to moved build context doc
  docs/reference/commandline/image_build.md
Labels: kind/docs, status/3-docs-review

#5361 login: add oauth escape hatch
  cli/command/registry/login.go
  cli/command/registry/login_test.go
  e2e/registry/login_test.go
  e2e/registry/main_test.go
Labels: status/2-code-review, area/testing, process/cherry-pick/27.2

#5362 [27.x backport] login: add oauth escape hatch
  cli/command/registry/login.go
  cli/command/registry/login_test.go
  e2e/registry/login_test.go
  e2e/registry/main_test.go
Labels: status/2-code-review, area/testing, area/authentication

#5363 cli/formatter: bracket IPv6 addrs prepended to ports
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
Labels: impact/changelog, kind/enhancement, area/ux

#5365 [27.x backport] cli/formatter: bracket IPv6 addrs prepended to ports
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/ux

#5368 [27.x backport] update link to engine api reference
  docs/reference/commandline/version.md
Labels: kind/docs, status/3-docs-review

#5371 vendor: github.com/docker/docker b27de4ef1634 (v27.2.0-dev)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/runtime, area/dependencies

#5370 Fix linting issues in preparation of Go and GolangCI-lint update
  cli/command/manifest/cmd.go
  cli/command/service/remove.go
  cli/command/service/scale.go
  cli/command/stack/swarm/remove.go
  cli/command/system/info.go
  cli/command/utils.go
  cli/required.go
  e2e/global/cli_test.go
Labels: status/2-code-review, area/testing, process/cherry-pick/27.2

#5372 [27.x backport] Fix linting issues in preparation of Go and GolangCI-lint update
  cli/command/manifest/cmd.go
  cli/command/service/remove.go
  cli/command/service/scale.go
  cli/command/stack/swarm/remove.go
  cli/command/system/info.go
  cli/command/utils.go
  cli/required.go
  e2e/global/cli_test.go
Labels: status/2-code-review, area/testing

#5374 [27.x backport] vendor: github.com/docker/docker 3ab5c7d0036c (v27.2.0-dev)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/dependencies

#5379 Revert "login: normalize `registry-1.docker.io`"
  cli/command/registry/login.go
Labels: status/2-code-review, kind/bugfix, area/authentication, process/cherry-pick/27.2

#5380 [27.x backport] Revert "login: normalize `registry-1.docker.io`"
  cli/command/registry/login.go
Labels: status/2-code-review, kind/bugfix, area/authentication
