Repository docker/cli, pull requests merged in 2024-01, with the labels that each got.

#4749 docs: add links to volume ls, network ls, stack ps formatting examples
  docs/reference/commandline/cli.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4750 [24.0 backport] docs: add links to volume ls, network ls, stack ps formatting examples
  docs/reference/commandline/cli.md
Labels: kind/docs, status/3-docs-review

#4252 Docker build command docs refresh
  docs/reference/commandline/build.md
Labels: kind/docs, status/3-docs-review, area/builder, process/cherry-pick

#4754 cli/command/container: parseSecurityOpts: fix --security-opt seccomp=builtin
  cli/command/container/opts.go
  docs/reference/commandline/run.md
Labels: impact/changelog, status/2-code-review, process/cherry-pick, kind/bugfix

#4753 vendor: github.com/docker/docker v25.0.0-rc.1
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/types.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4756 docs: fix incorrect heading levels in docker run reference
  docs/reference/commandline/run.md
Labels: kind/docs, status/3-docs-review

#4748 change back nolint -> nosec
  cli/command/image/build/context.go
Labels: status/2-code-review, area/testing

#4757 vendor: github.com/docker/go-connections v0.5.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review

#4760 cli/compose/loader: use golden.Assert() for readability
  cli/compose/loader/types_test.go
Labels: status/2-code-review, area/testing

#4768 [24.0 backport] Dockerfile: update ALPINE_VERSION to 3.18
  Dockerfile
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, area/packaging

#4766 update to go1.21.6
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4772 vendor: github.com/docker/docker-credential-helpers v0.8.1
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker-credential-helpers/client/client.go
  vendor/github.com/docker/docker-credential-helpers/credentials/error.go
  vendor/modules.txt
Labels: status/2-code-review, area/authentication

#4773 docs: dockerd: fix markdown table, and rephrase environment-variables intro
  docs/reference/commandline/dockerd.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4775 cmd/docker: move main() to the top
  cmd/docker/docker.go
Labels: status/2-code-review, kind/refactor

#4776 cli-plugins: helloworld: rename var that collided with import
  cli-plugins/examples/helloworld/main.go
Labels: status/2-code-review, area/testing, kind/refactor

#4777 cli-plugins/manager: getPluginDirs: take ConfigFile as argument
  cli-plugins/manager/manager.go
  cli-plugins/manager/manager_test.go
Labels: status/2-code-review, area/plugins, kind/refactor

#4778 cmd/docker: registerCompletionFuncForGlobalFlags: take store.Store as argument
  cmd/docker/completions.go
  cmd/docker/docker.go
Labels: status/2-code-review, kind/refactor

#4752 ci: Add bin-image workflow
  .github/workflows/build.yml
  Dockerfile
  docker-bake.hcl
  scripts/build/.variables
Labels: kind/enhancement, status/2-code-review

#4781 Dockerfile: update buildx to v0.12.1
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#4784 vendor: github.com/containerd/containerd v1.7.12
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4783 cli-plugins: don't use abstract sockets on macOS
  cli-plugins/plugin/plugin.go
  cli-plugins/socket/socket.go
  cli-plugins/socket/socket_darwin.go
  cli-plugins/socket/socket_nodarwin.go
  cmd/docker/docker.go
Labels: status/2-code-review, area/plugins, kind/bugfix

#4769 plugins: run plugin with new process group ID
  cli-plugins/manager/manager.go
  cli-plugins/manager/manager_unix.go
  cli-plugins/manager/manager_windows.go
  cmd/docker/docker.go
Labels: status/2-code-review, area/plugins, kind/refactor

#4785 temporarily revert ci: Add bin-image workflow
  .github/workflows/build.yml
  Dockerfile
  docker-bake.hcl
Labels: status/2-code-review, area/testing

#4771 vendor: github.com/docker/docker v25.0.0-rc.2
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/errdefs/is.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4790 vendor: golang.org/x/sys v0.16.0
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: status/2-code-review

#4791 ci: Add bin-image workflow (2nd approach)
  .github/workflows/build.yml
  Dockerfile
  docker-bake.hcl
Labels: kind/enhancement, status/2-code-review

#4794 gha: update to use macos-12 runners
  .github/workflows/test.yml
Labels: status/2-code-review, area/testing

#4792 cli/plugins: use same pgid + skip signal forwarding when attached to a TTY
  cli-plugins/manager/manager.go
  cli-plugins/manager/manager_unix.go
  cli-plugins/manager/manager_windows.go
  cli-plugins/socket/socket.go
  cmd/docker/docker.go
Labels: status/2-code-review, area/plugins, kind/bugfix

#4767 docs(plugins): fix typos and formatting
  docs/extend/config.md
  docs/extend/index.md
  docs/extend/legacy_plugins.md
  docs/extend/plugin_api.md
  docs/extend/plugins_authorization.md
  docs/extend/plugins_logging.md
  docs/extend/plugins_metrics.md
  docs/extend/plugins_network.md
  docs/extend/plugins_volume.md
Labels: kind/docs, status/3-docs-review

#4795 vendor: github.com/docker/docker v25.0.0-rc.3
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4799 docs: add documentation for CDI
  docs/reference/commandline/container_run.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/system_info.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4801 [25.0 backport] docs: add documentation for CDI
  docs/reference/commandline/container_run.md
  docs/reference/commandline/dockerd.md
  docs/reference/commandline/system_info.md
Labels: kind/docs, status/3-docs-review

#4800 docs: fix broken links to alias pages
  docs/reference/commandline/cli.md
  docs/reference/commandline/container_run.md
  docs/reference/commandline/docker.md
  docs/reference/commandline/image_build.md
  docs/reference/commandline/image_pull.md
  docs/reference/commandline/image_push.md
  docs/reference/commandline/image_rm.md
  scripts/docs/generate-md.sh
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#4804 [25.0 backport] docs: fix broken links to alias pages
  docs/reference/commandline/cli.md
  docs/reference/commandline/container_run.md
  docs/reference/commandline/docker.md
  docs/reference/commandline/image_build.md
  docs/reference/commandline/image_pull.md
  docs/reference/commandline/image_push.md
  docs/reference/commandline/image_rm.md
  scripts/docs/generate-md.sh
Labels: kind/docs, status/3-docs-review

#4802 vendor: github.com/docker/docker v25.0.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-picked

#4803 [25.0 backport] vendor: github.com/docker/docker v25.0.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review

#4805 socket: return from loop after EOF
  cli-plugins/socket/socket.go
Labels: status/2-code-review, area/plugins, process/cherry-pick, kind/bugfix

#4806 [25.0 backport] socket: return from loop after EOF
  cli-plugins/socket/socket.go
Labels: status/2-code-review, area/plugins, kind/bugfix

#4814 Dockerfile: update docker compose to v2.24.2
  Dockerfile
Labels: status/2-code-review, area/testing

#4815 [25.0 backport] Dockerfile: update docker compose to v2.24.2
  Dockerfile
Labels: status/2-code-review, area/testing

#4811 cli/command/container: remove deprecated NewStartOptions
  cli/command/container/start.go
Labels: impact/deprecation, status/2-code-review

#4810 cli/command: remove deprecated DockerCliOption, InitializeOpt
  cli/command/cli_options.go
Labels: impact/deprecation, status/2-code-review, kind/refactor

#4808 info: remove printServerWarningsLegacy
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-info-legacy-warnings.json.golden
Labels: status/2-code-review, kind/refactor

#4809 info: remove printSecurityOptionsWarnings, printServerWarnings
  cli/command/system/info.go
Labels: status/2-code-review, kind/refactor

#4820 vendor: github.com/docker/docker v25.0.1
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/builder/remotecontext/urlutil/urlutil.go
  vendor/github.com/docker/docker/pkg/system/xattrs.go
  vendor/github.com/docker/docker/pkg/system/xattrs_linux.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-pick, area/runtime

#4821 vendor: github.com/docker/docker 43ffb1ee9d5a (v26.0.0-dev)
  cli/command/completion/functions.go
  cli/command/container/client_test.go
  cli/command/container/create.go
  cli/command/container/create_test.go
  cli/command/image/client_test.go
  cli/command/image/import.go
  cli/command/image/import_test.go
  cli/command/image/list.go
  cli/command/image/list_test.go
  cli/command/image/pull_test.go
  cli/command/image/push.go
  cli/command/image/push_test.go
  cli/command/image/remove.go
  cli/command/image/remove_test.go
  cli/command/image/trust.go
  cli/command/trust/inspect_pretty_test.go
  cli/command/trust/sign.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/common.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/image/opts.go
  vendor/github.com/docker/docker/api/types/mount/mount.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/client/distribution_inspect.go
  vendor/github.com/docker/docker/client/image_create.go
  vendor/github.com/docker/docker/client/image_import.go
  vendor/github.com/docker/docker/client/image_list.go
  vendor/github.com/docker/docker/client/image_pull.go
  vendor/github.com/docker/docker/client/image_push.go
  vendor/github.com/docker/docker/client/image_remove.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/pkg/homedir/homedir.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_windows.go
  vendor/github.com/docker/docker/pkg/system/image_os_deprecated.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4826 [24.0] update to go1.20.13
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#4823 [23.0 backport] Fix setting ServerAddress property in NativeStore
  cli/config/credentials/native_store.go
  cli/config/credentials/native_store_test.go
Labels: status/2-code-review, kind/bugfix, area/authentication

#4825 [23.0] update to go1.20.13
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/compose-env.connhelper-ssh.yaml
  e2e/compose-env.experimental.yaml
  e2e/compose-env.yaml
  e2e/testdata/Dockerfile.gencerts
  scripts/test/e2e/run
Labels: impact/changelog, status/2-code-review, area/packaging

#4827 [24.0] vendor: github.com/docker/docker v24.0.7
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/versions/compare.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#4829 [24.0 backport] add //go:build directives to prevent downgrading to go1.16 language
  cli-plugins/manager/error.go
  cli/command/cli.go
  cli/command/config/inspect.go
  cli/command/container/inspect.go
  cli/command/context.go
  cli/command/context/create.go
  cli/command/context/create_test.go
  cli/command/context/inspect.go
  cli/command/context_test.go
  cli/command/defaultcontextstore.go
  cli/command/defaultcontextstore_test.go
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
  cli/command/formatter/custom.go
  cli/command/formatter/formatter.go
  cli/command/formatter/formatter_test.go
  cli/command/formatter/reflect.go
  cli/command/formatter/reflect_test.go
  cli/command/formatter/volume_test.go
  cli/command/idresolver/idresolver.go
  cli/command/image/inspect.go
  cli/command/inspect/inspector.go
  cli/command/network/formatter_test.go
  cli/command/network/inspect.go
  cli/command/node/formatter_test.go
  cli/command/node/inspect.go
  cli/command/plugin/formatter_test.go
  cli/command/plugin/inspect.go
  cli/command/secret/inspect.go
  cli/command/service/formatter_test.go
  cli/command/service/inspect.go
  cli/command/service/inspect_test.go
  cli/command/service/opts.go
  cli/command/stack/loader/loader.go
  cli/command/system/info.go
  cli/command/system/inspect.go
  cli/command/trust/inspect.go
  cli/command/utils.go
  cli/command/volume/inspect.go
  cli/compose/interpolation/interpolation.go
  cli/compose/interpolation/interpolation_test.go
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/interpolate.go
  cli/compose/loader/loader.go
  cli/compose/loader/loader_test.go
  cli/compose/loader/merge.go
  cli/compose/loader/merge_test.go
  cli/compose/schema/schema.go
  cli/compose/schema/schema_test.go
  cli/compose/template/template.go
  cli/compose/template/template_test.go
  cli/compose/types/types.go
  cli/context/store/metadata_test.go
  cli/context/store/metadatastore.go
  cli/context/store/store.go
  cli/context/store/store_test.go
  cli/context/store/storeconfig.go
  cli/context/store/storeconfig_test.go
  cmd/docker/builder_test.go
  templates/templates.go
Labels: status/2-code-review, kind/bugfix

#4831 Dockerfile: update docker compose to v2.24.3
  Dockerfile
Labels: status/2-code-review, process/cherry-pick, area/testing

#4832 cli/command/container: minor cleanup in attach
  cli/command/container/attach.go
Labels: status/2-code-review, kind/refactor

#4834 cli/command: don't use pflags.XXXVarP for flags without shorthand
  cli/command/checkpoint/create.go
  cli/command/checkpoint/list.go
  cli/command/checkpoint/remove.go
  cli/command/config/ls.go
  cli/command/container/exec.go
  cli/command/container/list.go
  cli/command/registry/login.go
  cli/command/secret/ls.go
  cli/command/swarm/ipnet_slice_test.go
Labels: status/2-code-review, kind/refactor

#4828 Add tests for CLI/plugin communication (i.e. let's not break everyone's plugins 🥲)
  cli-plugins/socket/socket_test.go
  e2e/cli-plugins/plugins/presocket/main.go
  e2e/cli-plugins/socket_test.go
  scripts/test/e2e/run
Labels: status/2-code-review, area/plugins, process/cherry-pick, area/testing

#4836 Remove dummy circleci config
  .circleci/config.yml
Labels: status/2-code-review, area/testing, kind/refactor

#4396 Add Linode docker volume plugin
  docs/extend/legacy_plugins.md
Labels: kind/docs, status/3-docs-review, impact/documentation

#4838 [24.0] vendor: github.com/docker/docker v24.0.8
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/client/container_wait.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
  vendor/github.com/docker/docker/pkg/ioutils/readers.go
  vendor/github.com/docker/docker/pkg/ioutils/writers.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: status/2-code-review

#4840 [24.0] vendor: github.com/opencontainers/runc v1.1.12
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime
