Repository docker/cli, pull requests merged in 2024-10, with the labels that each got.

#5480 cli/container: use github.com/moby/sys/capability for completions
  cli/command/container/completion.go
  cli/command/container/completion_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/moby/sys/capability/.codespellrc
  vendor/github.com/moby/sys/capability/.golangci.yml
  vendor/github.com/moby/sys/capability/CHANGELOG.md
  vendor/github.com/moby/sys/capability/LICENSE
  vendor/github.com/moby/sys/capability/README.md
  vendor/github.com/moby/sys/capability/capability.go
  vendor/github.com/moby/sys/capability/capability_linux.go
  vendor/github.com/moby/sys/capability/capability_noop.go
  vendor/github.com/moby/sys/capability/enum.go
  vendor/github.com/moby/sys/capability/enum_gen.go
  vendor/github.com/moby/sys/capability/syscall_linux.go
  vendor/modules.txt
Labels: status/2-code-review, area/completion, kind/refactor, area/dependencies

#5494 opts: cleanup ParseEnvFile tests
  opts/envfile_test.go
Labels: status/2-code-review, area/testing, process/cherry-pick/27.x

#5495 opts: remove ErrBadKey as it's not used as a sentinel error
  opts/file.go
Labels: status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#5496 opts: parseKeyValueFile: cleanup and remove redundant trimming
  opts/file.go
Labels: status/2-code-review, kind/refactor

#5498 [27.x backport] docs: fix a typo in run.md
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review

#5499 [27.x backport] opts: cleanup ParseEnvFile tests
  opts/envfile_test.go
Labels: status/2-code-review, area/testing

#5469 docs: use important callout for buildkit vs legacy builder
  docs/reference/commandline/image_build.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked

#5470 [27.x backport] use important callout for buildkit vs legacy builder
  docs/reference/commandline/image_build.md
Labels: kind/docs

#5502 move parsing key-value files to a separate package
  cli/command/container/opts_test.go
  opts/envfile.go
  opts/envfile_test.go
  opts/file.go
  opts/opts.go
  opts/parse.go
  pkg/kvfile/kvfile.go
  pkg/kvfile/kvfile_test.go
Labels: kind/enhancement, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#5467 command: add tests for container diff and rename
  cli/command/container/client_test.go
  cli/command/container/diff_test.go
  cli/command/container/rename_test.go
Labels: status/2-code-review, area/testing

#5509 [27.x backport] docs: fix inaccurate description of --restart=unless-stopped
  docs/reference/commandline/container_run.md
Labels: kind/docs, status/3-docs-review

#5504 ci: update to go1.22.8
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/testing, area/packaging, process/cherry-pick/25.0, process/cherry-pick/23.0, process/cherry-pick/26.1, process/cherry-pick/27.x

#5512 [27.x backport] ci: update to go1.22.8
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/testing, area/packaging

#5510 [26.1 backport] volume/update: require 1 argument/fix panic
  cli/command/volume/update.go
  cli/command/volume/update_test.go
Labels: impact/changelog, status/2-code-review, area/volumes, kind/bugfix

#5511 [25.0 backport] volume/update: require 1 argument/fix panic
  cli/command/volume/update.go
  cli/command/volume/update_test.go
Labels: impact/changelog, status/2-code-review, area/volumes, kind/bugfix

#5513 [26.1 backport] ci: update to go1.22.8
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: status/2-code-review, area/testing, area/packaging

#5516 add shell-completion for --platform flags
  cli/command/completion/functions.go
  cli/command/completion/functions_test.go
  cli/command/container/create.go
  cli/command/container/run.go
  cli/command/image/build.go
  cli/command/image/import.go
  cli/command/image/pull.go
  cli/command/image/push.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/completion, area/ux

#5506 command: add tests for container kill, commit, and pause
  cli/command/container/client_test.go
  cli/command/container/commit_test.go
  cli/command/container/kill_test.go
  cli/command/container/pause_test.go
Labels: status/2-code-review, area/testing

#5503 [27.x backport] move parsing key-value files to a separate package
  cli/command/container/opts_test.go
  opts/envfile.go
  opts/envfile_test.go
  opts/file.go
  opts/opts.go
  opts/parse.go
  pkg/kvfile/kvfile.go
  pkg/kvfile/kvfile_test.go
Labels: kind/enhancement, kind/refactor, area/go-sdk, impact/go-sdk

#5518 [27.x backport] Images Tree: Change 'Used' to 'In Use'
  cli/command/image/tree.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/ux, containerd-integration

#5519 [27.x backport] Do not underline image name
  cli/command/image/tree.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/ux, containerd-integration

#5520 cli/command/image: fix TestNewSaveCommandSuccess to actually test
  cli/command/image/save_test.go
Labels: status/2-code-review, area/testing, kind/bugfix

#5417 Update broken links in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: kind/docs, status/3-docs-review

#5524 cli/compose: implement the ports validation method
  cli/compose/schema/schema.go
  cli/compose/schema/schema_test.go
Labels: kind/enhancement

#5507 docs: Link supported Go duration strings
  docs/reference/commandline/container_prune.md
  docs/reference/commandline/image_prune.md
  docs/reference/commandline/network_prune.md
  docs/reference/commandline/system_events.md
  docs/reference/commandline/system_prune.md
  man/src/container/logs.md
  man/src/system/events.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/27.x

#5527 Improve completion of containers for `docker rm`
  cli/command/container/rm.go
Labels: status/2-code-review, area/completion

#5531 [27.x] vendor: github.com/docker/docker v27.3.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5533 cli/command/completion: add more unit-tests
  cli/command/completion/functions.go
  cli/command/completion/functions_test.go
Labels: status/2-code-review, area/testing, area/completion, process/cherry-pick/27.x

#5534 cli/command/container: set empty args in tests and discard output
  cli/command/container/list_test.go
  cli/command/container/prune_test.go
  cli/command/container/utils_test.go
Labels: status/2-code-review, area/testing, kind/bugfix, process/cherry-pick/27.x

#5537 docs: corrected the max events returned
  docs/reference/commandline/system_events.md
Labels: kind/docs, status/3-docs-review

#5535 docs: update prose about image tag/name format
  docs/reference/commandline/image_tag.md
Labels: kind/docs, status/3-docs-review

#5539 vendor: github.com/moby/swarmkit/v2 v2.0.0-20241017191044-e8ecf83ee08e
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/swarm, area/dependencies, process/cherry-pick/27.x

#5540 [27.x backport] assorted improvements for shell completion
  cli/command/completion/functions.go
  cli/command/completion/functions_test.go
  cli/command/container/completion.go
  cli/command/container/completion_test.go
  cli/command/container/create.go
  cli/command/container/rm.go
  cli/command/container/run.go
  cli/command/image/build.go
  cli/command/image/import.go
  cli/command/image/pull.go
  cli/command/image/push.go
  vendor.mod
  vendor.sum
  vendor/github.com/moby/sys/capability/.codespellrc
  vendor/github.com/moby/sys/capability/.golangci.yml
  vendor/github.com/moby/sys/capability/CHANGELOG.md
  vendor/github.com/moby/sys/capability/LICENSE
  vendor/github.com/moby/sys/capability/README.md
  vendor/github.com/moby/sys/capability/capability.go
  vendor/github.com/moby/sys/capability/capability_linux.go
  vendor/github.com/moby/sys/capability/capability_noop.go
  vendor/github.com/moby/sys/capability/enum.go
  vendor/github.com/moby/sys/capability/enum_gen.go
  vendor/github.com/moby/sys/capability/syscall_linux.go
  vendor/modules.txt
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/completion, area/dependencies

#5541 templates: add test for HeaderFunctions
  templates/templates_test.go
Labels: status/2-code-review, area/testing

#5543 [27.x backport] vendor: github.com/moby/swarmkit/v2 v2.0.0-20241017191044-e8ecf83ee08e
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/swarm, area/dependencies

#5542 cmd/docker: add tests for flag-completions, and refactor
  cmd/docker/completions.go
  cmd/docker/completions_test.go
  cmd/docker/docker.go
Labels: status/2-code-review, area/testing, area/completion

#5554 Fix bash completion for `events --filter daemon=`
  contrib/completion/bash/docker
Labels: area/completion, kind/bugfix, process/cherry-pick/27.x

#5563 [27.x backport] Fix bash completion for `events --filter daemon=`
  contrib/completion/bash/docker
Labels: status/2-code-review, area/completion, kind/bugfix

#5544 vendor: github.com/docker/docker 36a3bd090489 (master, v28.0-dev)
  docs/generate/go.mod
  man/go.mod
  scripts/vendor
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/system/info.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/client/container_resize.go
  vendor/github.com/docker/docker/client/image_build.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5551 cli/command: ConfigureAuth: fix deprecation comment
  cli/command/registry.go
Labels: impact/deprecation, status/2-code-review, process/cherry-picked, kind/bugfix, area/authentication, area/go-sdk, impact/go-sdk

#5553 cli/config/credentials: skip saving config-file if credentials didn't change
  cli/config/credentials/file_store.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/authentication, process/cherry-pick/27.x

#5552 [27.x backport] cli/command: ConfigureAuth: fix deprecation comment
  cli/command/registry.go
Labels: impact/deprecation, status/2-code-review, area/authentication, area/go-sdk, impact/go-sdk

#5557 cli/command: fix some minor linting issues
  cli/command/registry/login.go
  cli/command/utils.go
Labels: status/2-code-review, kind/refactor

#5546 cli/hints: add tests
  cli/hints/hints.go
  cli/hints/hints_test.go
Labels: status/2-code-review, area/testing

#5566 [25.0 backport] docs, man: dockerd: add documentation for "--log-format" option
  docs/reference/dockerd.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review

#5565 [26.1 backport] docs, man: dockerd: add documentation for "--log-format" option
  docs/reference/dockerd.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review

#5564 [27.x backport] cli/command/container: set empty args in tests and discard output
  cli/command/container/list_test.go
  cli/command/container/prune_test.go
  cli/command/container/utils_test.go
Labels: status/2-code-review, area/testing

#5550 cli/command: PromptUserForCredentials: assorted minor improvements and (linting) fixes
  cli/command/registry.go
Labels: kind/enhancement, status/2-code-review, kind/refactor, area/authentication, process/cherry-pick/27.x

#5547 cli/command/plugins: use errors.Join instead of custom cli.Errors, and deprecate cli.Errors
  cli/command/plugin/remove.go
  cli/error.go
Labels: impact/changelog, impact/deprecation, kind/enhancement, status/2-code-review, area/plugins, process/cherry-picked, area/go-sdk, impact/go-sdk

#5548 [27.x backport] cli/command/plugins: use errors.Join instead of custom cli.Errors, and deprecate cli.Errors
  cli/command/plugin/remove.go
  cli/error.go
Labels: impact/changelog, impact/deprecation, kind/enhancement, status/2-code-review, area/plugins, area/go-sdk, impact/go-sdk

#5549 cli: remove deprecated Errors type
  cli/error.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#5567 cli/config: improve error when failing to parse config file
  cli/config/config.go
  cli/config/config_test.go
Labels: status/2-code-review, kind/refactor

#5570 cli/config/credentials: add test for save being idempotent
  cli/config/credentials/file_store.go
  cli/config/credentials/file_store_test.go
  cli/config/credentials/native_store_test.go
Labels: status/2-code-review, process/cherry-picked, area/testing, area/authentication

#5573 docker inspect: add support for swarm configs
  cli/command/system/inspect.go
  docs/reference/commandline/inspect.md
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/swarm

#5538 Completion for `events --filter`
  cli/command/system/client_test.go
  cli/command/system/completion.go
  cli/command/system/completion_test.go
  cli/command/system/events.go
Labels: status/2-code-review, area/completion, process/cherry-pick/27.x

#5579 cli/command/container: parse: remove client-side warning
  cli/command/container/opts.go
Labels: status/2-code-review, kind/refactor

#5585 bump golangci-lint to v1.61.0 and cleanup config
  .golangci.yml
  cli-plugins/manager/candidate.go
  cli-plugins/manager/manager.go
  cli-plugins/manager/plugin.go
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, area/testing, process/cherry-pick/27.x

#5583 update to go1.23.2
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#5586 Buffer 'docker stats' text to avoid terminal flickering
  cli/command/container/stats.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/ux, process/cherry-pick/27.x

#5588 [27.x backport] Buffer 'docker stats' text to avoid terminal flickering
  cli/command/container/stats.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/ux
