Repository docker/cli, pull requests merged in 2024-07, with the labels that each got.

#5212 cli/command/stack: fix faulty sort for sorting stacks
  cli/command/stack/list.go
Labels: status/2-code-review, area/stack, kind/bugfix

#5213 vendor: github.com/fvbommel/sortorder v1.1.0
  vendor.mod
  vendor.sum
  vendor/github.com/fvbommel/sortorder/README.md
  vendor/github.com/fvbommel/sortorder/natsort.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5218 update to go1.21.12
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, process/cherry-pick, area/packaging, process/cherry-pick/25.0, process/cherry-pick/23.0, area/dependencies, process/cherry-pick/26.1, process/cherry-pick/27.0

#5208 [27.0 backport] vendor: github.com/docker/docker v27.0.3
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/docker/docker/pkg/archive/archive_other.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5219 [27.0 backport] update to go1.21.12
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, area/dependencies

#5220 [26.1 backport] update to go1.21.12
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, area/dependencies

#5168 fix: ctx cancellation on login prompt
  cli/command/registry.go
  cli/command/registry/login.go
  cli/command/registry/login_test.go
  cli/command/utils.go
  cli/command/utils_test.go
Labels: status/2-code-review, kind/bugfix

#5222 assorted minor changes in preparation of updating docker/docker dependency
  cli/command/container/attach_test.go
  cli/command/container/pause.go
  cli/command/container/start.go
  cli/command/container/unpause.go
  cli/command/container/update.go
  cli/command/container/wait.go
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
  cli/command/formatter/disk_usage.go
  cli/command/image/client_test.go
  cli/command/image/inspect_test.go
  cli/command/network/disconnect.go
  cli/command/trust/inspect_pretty_test.go
  internal/test/builders/container.go
Labels: status/2-code-review, kind/refactor

#5216 feat: force lf line endings by default
  .gitattributes
  .github/workflows/test.yml
Labels: kind/enhancement, status/2-code-review, area/testing

#5002 docs: make buildx build the canonical reference doc
  cli/command/image/build.go
  docs/reference/commandline/build.md
  docs/reference/commandline/builder_build.md
  docs/reference/commandline/image_build.md
  vendor.mod
  vendor.sum
  vendor/github.com/docker/cli-docs-tool/LICENSE
  vendor/github.com/docker/cli-docs-tool/annotation/annotation.go
  vendor/modules.txt
Labels: kind/docs, status/3-docs-review, process/cherry-pick

#5227 [27.0 backport] docs: make buildx build the canonical reference doc
  cli/command/image/build.go
  docs/reference/commandline/build.md
  docs/reference/commandline/builder_build.md
  docs/reference/commandline/image_build.md
  vendor.mod
  vendor.sum
  vendor/github.com/docker/cli-docs-tool/LICENSE
  vendor/github.com/docker/cli-docs-tool/annotation/annotation.go
  vendor/modules.txt
Labels: kind/docs, status/3-docs-review

#5225 cli/command/network: some cleanup and pass smaller interfaces
  cli/command/network/connect.go
  cli/command/network/create.go
  cli/command/network/disconnect.go
  cli/command/network/inspect.go
  cli/command/network/prune.go
  cli/command/network/remove.go
Labels: status/2-code-review, area/networking, kind/refactor

#5223 Enable completion for some 'image' sub commands
  cli/command/image/history.go
  cli/command/image/inspect.go
  cli/command/image/remove.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/completion

#5226 vendor: github.com/docker/docker 508cc7c61226 (master)
  cli/command/completion/functions.go
  cli/command/container/attach.go
  cli/command/container/attach_test.go
  cli/command/container/client_test.go
  cli/command/container/exec.go
  cli/command/container/exec_test.go
  cli/command/container/list_test.go
  cli/command/container/logs_test.go
  cli/command/container/pause.go
  cli/command/container/port_test.go
  cli/command/container/start.go
  cli/command/container/unpause.go
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
  cli/command/formatter/disk_usage.go
  cli/command/image/client_test.go
  cli/command/image/inspect_test.go
  cli/command/network/disconnect.go
  cli/command/trust/inspect_pretty_test.go
  internal/test/builders/container.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/container/container.go
  vendor/github.com/docker/docker/api/types/container/health.go
  vendor/github.com/docker/docker/api/types/container/network_settings.go
  vendor/github.com/docker/docker/api/types/container/port.go
  vendor/github.com/docker/docker/api/types/image/image_inspect.go
  vendor/github.com/docker/docker/api/types/storage/driver_data.go
  vendor/github.com/docker/docker/api/types/system/info.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/client/container_inspect.go
  vendor/github.com/docker/docker/client/container_list.go
  vendor/github.com/docker/docker/client/image_inspect.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/errdefs/http_helpers.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5230 cli/command/container: TestSplitCpArg: cleaner skip
  cli/command/container/cp_test.go
Labels: status/2-code-review, area/testing, kind/refactor

#5231 cli: make cli.StatusError slightly prettier
  cli/command/network/remove_test.go
  cli/command/system/info_test.go
  cli/error.go
Labels: kind/enhancement, status/2-code-review, area/ux

#5232 install bash-completion in dev container
  Makefile
  dockerfiles/Dockerfile.dev
Labels: kind/enhancement, status/2-code-review, area/testing, area/completion

#5246 push: Don't default to `DOCKER_DEFAULT_PLATFORM`, improve message
  cli/command/image/push.go
  docs/reference/commandline/image_push.md
  docs/reference/commandline/push.md
Labels: process/cherry-pick, kind/bugfix, area/ux, containerd-integration, process/cherry-pick/27.0

#5248 [27.0 backport] push: Don't default to `DOCKER_DEFAULT_PLATFORM`, improve message
  cli/command/image/push.go
  docs/reference/commandline/image_push.md
  docs/reference/commandline/push.md
Labels: status/2-code-review, kind/bugfix, area/ux, containerd-integration

#5247 fix: container stream should not be terminated by ctx
  cli/command/container/run.go
  e2e/container/run_test.go
Labels: status/2-code-review, process/cherry-pick, area/runtime, kind/bugfix, area/ux, process/cherry-pick/27.0

#5250 [27.0 backport] fix: container stream should not be terminated by ctx
  cli/command/container/run.go
  e2e/container/run_test.go
Labels: area/runtime, kind/bugfix, area/ux

#5251 vendor: github.com/docker/docker aae044039ca4 (master, v-next)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/prometheus/procfs/.golangci.yml
  vendor/github.com/prometheus/procfs/MAINTAINERS.md
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/arp.go
  vendor/github.com/prometheus/procfs/buddyinfo.go
  vendor/github.com/prometheus/procfs/cpuinfo.go
  vendor/github.com/prometheus/procfs/crypto.go
  vendor/github.com/prometheus/procfs/fscache.go
  vendor/github.com/prometheus/procfs/ipvs.go
  vendor/github.com/prometheus/procfs/loadavg.go
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/meminfo.go
  vendor/github.com/prometheus/procfs/mountinfo.go
  vendor/github.com/prometheus/procfs/mountstats.go
  vendor/github.com/prometheus/procfs/net_conntrackstat.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/net_sockstat.go
  vendor/github.com/prometheus/procfs/net_softnet.go
  vendor/github.com/prometheus/procfs/net_tls_stat.go
  vendor/github.com/prometheus/procfs/net_unix.go
  vendor/github.com/prometheus/procfs/net_wireless.go
  vendor/github.com/prometheus/procfs/proc.go
  vendor/github.com/prometheus/procfs/proc_limits.go
  vendor/github.com/prometheus/procfs/proc_ns.go
  vendor/github.com/prometheus/procfs/proc_psi.go
  vendor/github.com/prometheus/procfs/proc_smaps.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/github.com/prometheus/procfs/proc_sys.go
  vendor/github.com/prometheus/procfs/softirqs.go
  vendor/github.com/prometheus/procfs/stat.go
  vendor/github.com/prometheus/procfs/swaps.go
  vendor/github.com/prometheus/procfs/thread.go
  vendor/github.com/prometheus/procfs/zoneinfo.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5234 cli: improve output and consistency for unknown (sub)commands
  cli-plugins/manager/cobra.go
  cli/command/checkpoint/create_test.go
  cli/command/checkpoint/list_test.go
  cli/command/checkpoint/remove_test.go
  cli/command/config/create_test.go
  cli/command/config/remove_test.go
  cli/command/image/history_test.go
  cli/command/image/import_test.go
  cli/command/image/inspect_test.go
  cli/command/image/list_test.go
  cli/command/image/load_test.go
  cli/command/image/prune_test.go
  cli/command/image/pull_test.go
  cli/command/image/push_test.go
  cli/command/image/remove_test.go
  cli/command/image/save_test.go
  cli/command/image/tag_test.go
  cli/command/manifest/annotate_test.go
  cli/command/manifest/push_test.go
  cli/command/network/connect_test.go
  cli/command/network/create_test.go
  cli/command/network/disconnect_test.go
  cli/command/node/update_test.go
  cli/command/plugin/disable_test.go
  cli/command/plugin/enable_test.go
  cli/command/secret/remove_test.go
  cli/command/service/rollback_test.go
  cli/command/stack/ps_test.go
  cli/command/swarm/join_test.go
  cli/command/swarm/join_token_test.go
  cli/command/trust/key_generate_test.go
  cli/command/trust/key_load_test.go
  cli/command/trust/revoke_test.go
  cli/command/trust/sign_test.go
  cli/required.go
  cli/required_test.go
  cmd/docker/docker.go
  cmd/docker/docker_test.go
  e2e/cli-plugins/flags_test.go
  e2e/cli-plugins/testdata/docker-badmeta-err.golden
  e2e/cli-plugins/testdata/docker-nonexistent-err.golden
Labels: impact/changelog, kind/enhancement, area/ux

#5233 cli: FlagErrorFunc: don't print long usage output for invalid flags
  cli/cobra.go
  e2e/cli-plugins/help_test.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/ux

#5238 various improvements to shell completions
  cli/command/completion/functions.go
  cli/command/container/completion.go
  cli/command/container/create.go
  cli/command/container/exec.go
  cli/command/container/kill.go
  cli/command/container/restart.go
  cli/command/container/run.go
  cli/command/container/stop.go
  cli/command/container/update.go
  cli/context/store/store.go
  cli/context/store/store_test.go
  cmd/docker/completions.go
  cmd/docker/docker.go
Labels: kind/enhancement, status/2-code-review, area/completion

#5258 login: slightly cleanup warning about unencrypted store
  cli/command/registry/login.go
Labels: status/2-code-review, kind/refactor, area/authentication

#5264 Dockerfile: update buildx to v0.16.1, compose to v2.29.0
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#5260 [27.0 backport] fix: ctx cancellation on login prompt
  cli/command/registry.go
  cli/command/registry/login.go
  cli/command/registry/login_test.go
  cli/command/utils.go
  cli/command/utils_test.go
Labels: status/2-code-review, kind/bugfix, area/authentication

#5261 [27.0 backport] assorted fixes and enhancements for shell-completion
  Makefile
  cli/command/completion/functions.go
  cli/command/container/completion.go
  cli/command/container/create.go
  cli/command/container/exec.go
  cli/command/container/kill.go
  cli/command/container/restart.go
  cli/command/container/run.go
  cli/command/container/stop.go
  cli/command/container/update.go
  cli/command/image/history.go
  cli/command/image/inspect.go
  cli/command/image/remove.go
  cli/context/store/store.go
  cli/context/store/store_test.go
  cmd/docker/completions.go
  cmd/docker/docker.go
  dockerfiles/Dockerfile.dev
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/completion, kind/bugfix

#5262 gha: check-pr-branch: verify major version only
  .github/workflows/validate-pr.yml
Labels: status/2-code-review, area/testing

#5265 [27.0 backport] Dockerfile: update buildx to v0.16.1, compose to v2.29.0
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#5263 [27.1 backport] gha: check-pr-branch: verify major version only
  .github/workflows/validate-pr.yml
Labels: status/2-code-review, area/testing

#5268 gha: update to macOS 13, add macOS 14 arm64 (Apple Silicon M1)
  .github/workflows/test.yml
Labels: status/2-code-review, area/testing

#5269 [27.1 backport] gha: update to macOS 13, add macOS 14 arm64 (Apple Silicon M1)
  .github/workflows/test.yml
Labels: status/2-code-review, area/testing

#5098 add support for DOCKER_CUSTOM_HEADERS env-var (experimental)
  cli/command/cli.go
  cli/command/cli_options.go
  cli/command/cli_test.go
  docs/reference/commandline/docker.md
  docs/reference/dockerd.md
Labels: impact/changelog, kind/experimental, status/2-code-review, area/context, area/api, process/cherry-pick/27.0

#5271 [27.1 backport] add support for DOCKER_CUSTOM_HEADERS env-var (experimental)
  cli/command/cli.go
  cli/command/cli_options.go
  cli/command/cli_test.go
  docs/reference/commandline/docker.md
  docs/reference/dockerd.md
Labels: impact/changelog, kind/experimental, status/2-code-review, area/context, area/api

#5145 Add OomScoreAdj to "docker service create" and "docker compose"
  cli/command/service/create.go
  cli/command/service/opts.go
  cli/command/service/update.go
  cli/compose/convert/service.go
  cli/compose/loader/interpolate.go
  cli/compose/schema/data/config_schema_v3.13.json
  cli/compose/types/types.go
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_update.md
Labels: impact/changelog, status/2-code-review, area/swarm, area/stack

#5274 [27.1 backport] Add OomScoreAdj to "docker service create" and "docker stack"
  cli/command/service/create.go
  cli/command/service/opts.go
  cli/command/service/update.go
  cli/compose/convert/service.go
  cli/compose/loader/interpolate.go
  cli/compose/schema/data/config_schema_v3.13.json
  cli/compose/types/types.go
  docs/reference/commandline/service_create.md
  docs/reference/commandline/service_update.md
Labels: impact/changelog, status/2-code-review, area/swarm, area/stack

#5277 [25.0 backport] Fix codeql 2.16 in 25.0
  .github/workflows/codeql.yml
Labels: status/2-code-review, area/testing

#5236 cli/command/container: remove reportError, and put StatusError to use
  cli/command/container/create.go
  cli/command/container/create_test.go
  cli/command/container/run.go
  cli/command/container/run_test.go
Labels: kind/enhancement, status/2-code-review, kind/refactor, area/ux

#5278 [25.0 backport] Require changelog in 25.0
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/validate-pr.yml
Labels: status/2-code-review, area/testing

#5259 cli/config/credentials: move warning to fileStore
  cli/command/registry/login.go
  cli/config/credentials/file_store.go
Labels: status/2-code-review, kind/refactor, area/authentication

#5273 vendor: github.com/containerd/containerd v1.7.20
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5288 [23.0 backport] gha: update to use macos-12 runners
  .github/workflows/test.yml
Labels: status/2-code-review, area/testing

#5283 [23.0 backport] Fix codeql 2.16 in 23.0
  .github/workflows/codeql-analysis.yml
Labels: status/2-code-review, area/testing

#5267 [27.1] vendor: github.com/docker/docker v27.1.1
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/system/info.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5290 Fix flaky `TestCloseRunningCommand` test
  cli/connhelper/commandconn/commandconn_unix_test.go
Labels: area/testing

#5291 tests: fix other flaky `connhelper` tests
  cli/connhelper/commandconn/commandconn_unix_test.go
Labels: status/2-code-review, area/testing, process/cherry-pick/25.0, process/cherry-pick/27.0

#5289 docs: refresh image versions in examples
  docs/reference/commandline/container_attach.md
  docs/reference/commandline/container_commit.md
  docs/reference/commandline/container_ls.md
  docs/reference/commandline/image_pull.md
  docs/reference/commandline/service_create.md
  docs/reference/commandline/system_events.md
  docs/reference/run.md
  man/src/container/attach.md
  man/src/container/ls.md
  man/src/image/ls.md
  man/src/image/pull.md
  man/src/system/events.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/27.0

#5292 [25.0 backport] fix flaky `connhelper` tests
  cli/connhelper/commandconn/commandconn_unix_test.go
Labels: status/2-code-review, area/testing

#5293 [27.0 backport] tests: fix flaxy TestCloseRunningCommand test
  cli/connhelper/commandconn/commandconn_unix_test.go
Labels: status/2-code-review, area/testing

#5295 attach: don't return context cancelled error
  cli/command/container/attach.go
  cli/command/container/attach_test.go
  e2e/container/attach_test.go
Labels: status/2-code-review, kind/bugfix

#5296 [27.1 backport] attach: don't return context cancelled error
  cli/command/container/attach.go
  cli/command/container/attach_test.go
  e2e/container/attach_test.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/ux

#5297 attach: wait for exit code from `ContainerWait`
  cli/command/container/attach.go
  cli/command/container/attach_test.go
  e2e/container/attach_test.go
Labels: status/2-code-review, kind/bugfix, process/cherry-pick/27.0

#5252 vendor: docker/docker 2b1097f08088 (removes containerd dependency)
  vendor.mod
  vendor.sum
  vendor/github.com/containerd/containerd/LICENSE
  vendor/github.com/containerd/containerd/NOTICE
  vendor/github.com/containerd/containerd/pkg/userns/userns_linux.go
  vendor/github.com/containerd/containerd/pkg/userns/userns_unsupported.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/moby/sys/sequential/sequential_unix.go
  vendor/github.com/moby/sys/sequential/sequential_windows.go
  vendor/github.com/moby/sys/symlink/README.md
  vendor/github.com/moby/sys/symlink/doc.go
  vendor/github.com/moby/sys/symlink/fs.go
  vendor/github.com/moby/sys/symlink/fs_windows.go
  vendor/github.com/moby/sys/user/user.go
  vendor/github.com/moby/sys/user/userns/userns.go
  vendor/github.com/moby/sys/user/userns/userns_linux.go
  vendor/github.com/moby/sys/user/userns/userns_linux_fuzzer.go
  vendor/github.com/moby/sys/user/userns/userns_unsupported.go
  vendor/golang.org/x/sys/unix/mremap.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5303 tests/run: fix flaky `RunAttachTermination` test
  cli/command/container/run_test.go
Labels: status/2-code-review, area/testing, process/cherry-pick/27.1
