Repository docker/cli, pull requests merged in 2024-04, with the labels that each got.

#4939 feat: standardize error for prompt
  cli/command/builder/prune.go
  cli/command/builder/prune_test.go
  cli/command/container/prune.go
  cli/command/container/prune_test.go
  cli/command/image/prune.go
  cli/command/image/prune_test.go
  cli/command/network/prune.go
  cli/command/network/prune_test.go
  cli/command/network/remove_test.go
  cli/command/plugin/testdata/plugin-upgrade-terminate.golden
  cli/command/plugin/upgrade.go
  cli/command/plugin/upgrade_test.go
  cli/command/system/prune.go
  cli/command/system/prune_test.go
  cli/command/trust/revoke.go
  cli/command/trust/revoke_test.go
  cli/command/trust/signer_remove.go
  cli/command/trust/testdata/trust-revoke-prompt-termination.golden
  cli/command/utils.go
  cli/command/volume/prune.go
  cli/command/volume/prune_test.go
  cli/command/volume/testdata/volume-prune-no.golden
  cmd/docker/docker.go
  e2e/global/cli_test.go
  e2e/plugin/trust_test.go
  e2e/testutils/plugins.go
  e2e/testutils/plugins/basic.go
  internal/test/cmd.go
  internal/test/writer.go
Labels: kind/enhancement, area/testing, area/ux

#4985 otel: capture exit code as int64
  cli/command/telemetry_utils.go
  cli/command/telemetry_utils_test.go
Labels: area/metrics/otel

#4988 [25.0 backport] update to go1.21.9
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: status/2-code-review, area/packaging

#4987 [26.0 backport] update to go1.21.9
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: status/2-code-review, area/packaging

#4998 vendor: golang.org/x/sys v0.18.0, golang.org/x/term v0.18.0, golang.org/x/crypto v0.21.0, golang.org/x/net v0.23.0
  vendor.mod
  vendor.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-pick, process/cherry-pick/26.0

#4999 [26.0 backport] vendor: golang.org/x/sys v0.18.0, golang.org/x/term v0.18.0, golang.org/x/crypto v0.21.0, golang.org/x/net v0.23.0
  vendor.mod
  vendor.sum
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/env_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: status/2-code-review

#5005 cli-bin/windows: Add .exe extension
  Dockerfile
Labels: area/testing

#5006 [26.0 backport] cli-bin/windows: Add .exe extension
  Dockerfile
Labels: status/2-code-review, area/testing

#5007 [26.0] vendor: github.com/docker/docker v26.0.1-dev (60b9add796ae)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5025 Fix OTLP env var overriding
  cli/command/telemetry_docker.go
Labels: kind/bugfix, area/metrics/otel

#5024 plugins/hooks: run hooks when exit code != 0
  cmd/docker/docker.go
Labels: area/plugins

#5028 vendor: github.com/docker/docker v26.0.2-dev (7cef0d9c)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/dependencies

#4967 Feature option 'windows-dns-proxy'
  docs/reference/dockerd.md
Labels: kind/docs

#5031 vendor: github.com/docker/docker v26.1.0-dev (ee8b788538ea)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/runtime, area/dependencies

#4981 ci: Require changelog description
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/validate-pr.yml
Labels: process/cherry-pick, area/testing, process/cherry-pick/26.0, process/cherry-pick/25.0

#5030 hooks: include plugin name in hook data
  cli-plugins/manager/hooks.go
  cli-plugins/manager/hooks_test.go
  cmd/docker/docker.go
Labels: area/plugins

#5033 hooks: pass command execution error to plugins
  cli-plugins/manager/hooks.go
  cli-plugins/manager/plugin.go
  cmd/docker/docker.go
Labels: area/plugins

#5034 vendor: github.com/docker/docker v26.1.0-dev (c8af8ebe4a89)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime

#5035 vendor: update github.com/docker/docker to v26.1.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#4774 improve passing context
  cli-plugins/plugin/plugin.go
  cmd/docker/builder_test.go
  cmd/docker/docker.go
  cmd/docker/docker_test.go
  docs/generate/generate.go
  e2e/cli-plugins/plugins/nopersistentprerun/main.go
Labels: impact/changelog, status/2-code-review, area/plugins, area/api, kind/refactor

#5043 waitExitOrRemoved: Handle context cancellation
  cli/command/container/utils.go
Labels: process/cherry-picked, kind/bugfix

#5044 [26.1 backport] waitExitOrRemoved: Handle context cancellation
  cli/command/container/utils.go
Labels: kind/bugfix

#5045 [26.1] vendor: github.com/docker/docker ac2de55998d4 (v26.1.1)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/dependencies

#5047 [26.1 backport] cli-plugins: PluginRunCommand: use cmd.Environ instead of os.Environ
  cli-plugins/manager/manager.go
Labels: area/plugins
