Repository docker/cli, pull requests merged in 2024-09, with the labels that each got.

#5383 login: use normalized hostname when storing
  cli/command/registry/login.go
  cli/command/registry/login_test.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/authentication, process/cherry-pick/27.2

#5385 [27.x backport] login: use normalized hostname when storing
  cli/command/registry/login.go
  cli/command/registry/login_test.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/authentication

#5389 Dockerfile: update xx to v1.5.0
  Dockerfile
Labels: status/2-code-review, area/testing, area/packaging, process/cherry-pick/27.2

#5391 [27.x backport] Dockerfile: update xx to v1.5.0
  Dockerfile
Labels: status/2-code-review, area/testing, area/packaging

#5392 [27.x backport] cli/connhelper: getConnectionHelper: move ssh-option funcs out of closure
  cli/connhelper/connhelper.go
Labels: status/2-code-review, kind/refactor

#5386 docs: update docker login reference
  cli/command/registry/login.go
  cli/internal/oauth/manager/manager.go
  docs/reference/commandline/docker.md
  docs/reference/commandline/login.md
  e2e/registry/login_test.go
Labels: kind/docs, status/3-docs-review, area/authentication, process/cherry-pick/27.2

#5393 scripts/build/plugins: don't override CGO_ENABLED set by .variables
  scripts/build/plugins
Labels: status/2-code-review, area/testing, kind/bugfix, area/packaging, process/cherry-pick/25.0, process/cherry-pick/23.0, process/cherry-pick/26.1, process/cherry-pick/27.2

#5394 [27.x backport] docs: update docker login reference #5386
  cli/command/registry/login.go
  cli/internal/oauth/manager/manager.go
  docs/reference/commandline/docker.md
  docs/reference/commandline/login.md
  e2e/registry/login_test.go
Labels: kind/docs, status/3-docs-review, area/authentication

#5376 oauth/api: drain timer channel on each iteration
  cli/internal/oauth/api/api.go
  cli/internal/oauth/api/api_test.go
Labels: status/2-code-review, process/cherry-pick, kind/bugfix, area/authentication, process/cherry-pick/27.2

#5387 update to go1.22.6
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, process/cherry-pick/25.0, process/cherry-pick/23.0, process/cherry-pick/26.1, process/cherry-pick/27.2

#5395 [27.x backport] scripts/build/plugins: don't override CGO_ENABLED set by .variables
  scripts/build/plugins
Labels: status/2-code-review, area/testing, area/packaging

#5399 [27.x backport] oauth/api: drain timer channel on each iteration
  cli/internal/oauth/api/api.go
  cli/internal/oauth/api/api_test.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/authentication

#5400 [27.x backport] update to go1.22.6
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#5401 login: handle non-tty scenario consistently
  cli/command/registry.go
  cli/command/registry/login.go
  cli/command/registry/login_test.go
Labels: status/2-code-review, area/ux, area/authentication

#5402 [27.x backport] login: handle non-tty scenario consistently
  cli/command/registry.go
  cli/command/registry/login.go
  cli/command/registry/login_test.go
Labels: impact/changelog, status/2-code-review, area/ux, area/authentication

#5407 vendor.mod: put github.com/pkg/browser in the right group
  vendor.mod
Labels: status/2-code-review, process/cherry-picked, kind/refactor

#5408 [27.x backport] vendor.mod: put github.com/pkg/browser in the right group
  vendor.mod
Labels: status/2-code-review, kind/refactor

#5396 [26.1 backport[] scripts/build/plugins: don't override CGO_ENABLED set by .variables
  scripts/build/plugins
Labels: status/2-code-review, area/testing, area/packaging

#5410 update to go1.22.7
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/dependencies

#5411 [27.x backport] update to go1.22.7
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, area/dependencies

#5414 [27.x] vendor: github.com/docker/docker v27.2.1-dev (8b539b8df240)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/container/hostconfig.go
  vendor/modules.txt
Labels: area/dependencies

#5381 fix: gitattributes enforcing line endings
  .gitattributes
Labels: status/2-code-review, area/testing

#5403 docs: rename plugins index file and add linkTitle
  docs/deprecated.md
  docs/extend/_index.md
  docs/extend/legacy_plugins.md
  docs/extend/plugin_api.md
  docs/extend/plugins_authorization.md
  docs/extend/plugins_network.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked

#5420 volume/update: require 1 argument/fix panic
  cli/command/volume/update.go
  cli/command/volume/update_test.go
Labels: status/2-code-review, process/cherry-pick, area/volumes, kind/bugfix

#5397 [25.0 backport] scripts/build/plugins: don't override CGO_ENABLED set by .variables
  scripts/build/plugins
Labels: status/2-code-review, area/testing, area/packaging

#5406 [25.0 backport] update to go1.22.6
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: status/2-code-review, area/packaging

#5422 info: stop printing "Expected" commits
  cli/command/system/info.go
Labels: status/2-code-review, process/cherry-picked

#5423 [27.x backport] info: stop printing "Expected" commits
  cli/command/system/info.go
Labels: status/2-code-review

#5425 chore: remove duplicated `govet` linter config
  .golangci.yml
Labels: kind/enhancement

#5429 [27.x] vendor: github.com/docker/docker v27.2.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5424 command: check for wsl mount path on windows
  cli/command/telemetry_docker.go
  cli/command/telemetry_docker_test.go
Labels: kind/enhancement, status/2-code-review, area/metrics, area/metrics/otel, process/cherry-pick/27.x

#5431 [27.x] vendor: github.com/docker/docker bf60e5cced83 (v27.3.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/image/summary.go
  vendor/github.com/docker/docker/api/types/swarm/swarm.go
  vendor/github.com/docker/docker/api/types/volume/cluster_volume.go
  vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go
  vendor/github.com/docker/docker/pkg/pools/pools.go
  vendor/github.com/docker/docker/pkg/system/xattrs_linux.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5432 [27.x backport] command: check for wsl mount path on windows
  cli/command/telemetry_docker.go
  cli/command/telemetry_docker_test.go
Labels: kind/enhancement, status/2-code-review, area/metrics, area/metrics/otel

#5436 docs: add documentation for dockerd --feature flag
  docs/reference/dockerd.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/27.x

#5438 docs, man: dockerd: add documentation for "--log-format" option
  docs/reference/dockerd.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review, area/runtime, process/cherry-pick/25.0, process/cherry-pick/26.1, process/cherry-pick/27.x

#5439 [27.x backport] docs, man: dockerd: add documentation for "--log-format" and "--feature" options
  docs/reference/dockerd.md
  man/dockerd.8.md
Labels: kind/docs, status/3-docs-review, area/runtime

#5440 [27.x] vendor: github.com/docker/docker v27.3.0-rc.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5437 docs, man: dockerd: remove --api-cors-header (deprecated)
  docs/deprecated.md
  docs/reference/dockerd.md
  man/dockerd.8.md
Labels: impact/deprecation, kind/docs, status/3-docs-review, area/runtime

#5441 Dockerfile: update buildx to v0.17.1, compose to v2.29.4
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, process/cherry-picked, area/testing

#5435 Docs: Fix --rm=false flag in container_run.md
  docs/reference/commandline/container_run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/27.x

#5442 [27.x backport] Dockerfile: update buildx to v0.17.1, compose to v2.29.4
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#5443 [27.x backport] docs: Fix --rm=false flag in container_run.md
  docs/reference/commandline/container_run.md
Labels: kind/docs, status/3-docs-review

#5447 [27.x backport] gha: update codeql workflow to go1.22.7
  .github/workflows/codeql.yml
Labels: status/2-code-review, area/testing

#5446 gha: update codeql workflow to go1.22.7
  .github/workflows/codeql.yml
Labels: status/2-code-review, process/cherry-picked, area/testing, process/cherry-pick/25.0, process/cherry-pick/23.0, process/cherry-pick/26.1

#5445 command: change drive to lowercase for wsl path
  cli/command/telemetry_docker.go
  cli/command/telemetry_docker_test.go
Labels: status/2-code-review, process/cherry-picked, platform/windows, kind/bugfix, area/metrics/otel

#5449 [27.x backport] command: change drive to lowercase for wsl path
  cli/command/telemetry_docker.go
  cli/command/telemetry_docker_test.go
Labels: platform/windows, kind/bugfix, area/metrics/otel

#5448 [27.x backport] telemetry: handle otel errors on shutdown
  cli/command/telemetry_utils.go
  cmd/docker/docker.go
Labels: kind/enhancement, area/metrics/otel

#5452 [27.x] vendor: github.com/docker/docker v27.3.0-rc2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/dependencies

#5456 telemetry: fix early meterprovider shutdown
  cmd/docker/docker.go
Labels: status/2-code-review, process/cherry-picked, kind/bugfix, area/metrics

#5457 [27.x backport] telemetry: fix early meterprovider shutdown
  cmd/docker/docker.go
Labels: status/2-code-review, kind/bugfix, area/metrics, area/metrics/otel

#5458 [27.x] vendor: github.com/docker/docker v27.3.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5459 Dockerfile: update compose to v2.29.7
  Dockerfile
Labels: status/2-code-review, area/testing

#5460 Update `VERSION` file to `v27.3.1-dev`
  VERSION
Labels: process/cherry-picked, area/packaging

#5461 [27.x backport] Update `VERSION` file to `v27.3.1-dev`
  VERSION
Labels: status/2-code-review, area/packaging

#5462 [27.x] Dockerfile: update compose to v2.29.7
  Dockerfile
Labels: status/2-code-review, area/testing

#5471 docs: fix anchor link to web-based login section
  docs/reference/commandline/login.md
Labels: kind/docs

#5472 [27.x backport] fix anchor link to web-based login section
  docs/reference/commandline/login.md
Labels: kind/docs

#5468 cli/formatter: fix unbracketed IPv6 addrs
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
Labels: impact/changelog, kind/bugfix, area/ux

#5473 Do not underline image name
  cli/command/image/tree.go
Labels: kind/enhancement, area/ux

#5474 Images Tree: Change 'Used' to 'In Use'
  cli/command/image/tree.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/ux, containerd-integration

#5454 gha: codeql: minor touch-ups and fixes
  .github/workflows/codeql.yml
Labels: status/2-code-review, area/testing

#5428 vendor: github.com/docker/docker 164cae56ed95 (master, v-next)
  cli/command/image/client_test.go
  cli/command/image/history.go
  cli/command/image/history_test.go
  cli/command/image/load.go
  cli/command/image/load_test.go
  cli/command/image/save.go
  cli/command/image/save_test.go
  cli/command/registry.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/common.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/container/hostconfig.go
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/image/opts.go
  vendor/github.com/docker/docker/api/types/image/summary.go
  vendor/github.com/docker/docker/api/types/registry/authconfig.go
  vendor/github.com/docker/docker/api/types/registry/search.go
  vendor/github.com/docker/docker/api/types/swarm/swarm.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/api/types/volume/cluster_volume.go
  vendor/github.com/docker/docker/client/image_history.go
  vendor/github.com/docker/docker/client/image_load.go
  vendor/github.com/docker/docker/client/image_save.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go
  vendor/github.com/docker/docker/pkg/pools/pools.go
  vendor/github.com/docker/docker/pkg/system/xattrs_linux.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5481 docs: fix a typo in run.md
  docs/reference/run.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/27.x

#5482 cli/command/container: add unit tests for container restart and container stop
  cli/command/container/client_test.go
  cli/command/container/restart.go
  cli/command/container/restart_test.go
  cli/command/container/stop_test.go
Labels: status/2-code-review, area/testing

#5483 Check that --ip-range is a CIDR address
  cli/command/network/create.go
  cli/command/network/create_test.go
Labels: status/2-code-review, area/networking, kind/bugfix

#5484 docs/reference: stop, restart: add flag descriptions
  docs/reference/commandline/container_restart.md
  docs/reference/commandline/container_stop.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/27.x
