Repository docker/cli, pull requests merged in 2024-06, with the labels that each got.

#5096 gha: update to actions/upload-artifact@v4
  .github/workflows/build.yml
Labels: status/2-code-review, process/cherry-pick, area/testing, process/cherry-pick/25.0, process/cherry-pick/23.0, process/cherry-pick/26.1

#5105 [26.1 backport] gha: update to actions/upload-artifact@v4
  .github/workflows/build.yml
Labels: status/2-code-review, area/testing

#5106 [25.0 backport] gha: update to actions/upload-artifact@v4
  .github/workflows/build.yml
Labels: status/2-code-review, area/testing

#5107 [23.0 backport] gha: update to actions/upload-artifact@v4
  .github/workflows/build.yml
Labels: status/2-code-review, area/testing

#5108 [26.1 backport] migrate to new github.com/containerd/platforms package
  cli/command/container/create.go
  vendor.mod
  vendor.sum
  vendor/github.com/containerd/containerd/errdefs/errors.go
  vendor/github.com/containerd/containerd/errdefs/grpc.go
  vendor/github.com/containerd/containerd/log/context_deprecated.go
  vendor/github.com/containerd/platforms/.gitattributes
  vendor/github.com/containerd/platforms/.golangci.yml
  vendor/github.com/containerd/platforms/LICENSE
  vendor/github.com/containerd/platforms/README.md
  vendor/github.com/containerd/platforms/compare.go
  vendor/github.com/containerd/platforms/cpuinfo.go
  vendor/github.com/containerd/platforms/cpuinfo_linux.go
  vendor/github.com/containerd/platforms/cpuinfo_other.go
  vendor/github.com/containerd/platforms/database.go
  vendor/github.com/containerd/platforms/defaults.go
  vendor/github.com/containerd/platforms/defaults_darwin.go
  vendor/github.com/containerd/platforms/defaults_freebsd.go
  vendor/github.com/containerd/platforms/defaults_unix.go
  vendor/github.com/containerd/platforms/defaults_windows.go
  vendor/github.com/containerd/platforms/errors.go
  vendor/github.com/containerd/platforms/platforms.go
  vendor/github.com/containerd/platforms/platforms_other.go
  vendor/github.com/containerd/platforms/platforms_windows.go
  vendor/modules.txt
Labels: status/2-code-review, kind/refactor, area/dependencies

#5109 Correct typos in comments in the `cli/` folder
  cli/command/formatter/tabwriter/tabwriter.go
  cli/command/service/opts.go
  cli/command/service/progress/progress.go
  cli/compose/convert/service.go
  cli/compose/template/template.go
  cli/context/store/storeconfig.go
Labels: status/2-code-review

#5110 vendor: github.com/docker/docker cd3804655a25 (master / v27.0.0-dev)
  cli/command/completion/functions.go
  cli/command/network/client_test.go
  cli/command/network/list.go
  cli/command/network/list_test.go
  cli/command/stack/client_test.go
  cli/command/stack/swarm/client_test.go
  cli/command/stack/swarm/common.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/network/network.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/client/network_inspect.go
  vendor/github.com/docker/docker/client/network_list.go
  vendor/github.com/docker/docker/client/request.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5111 cli/command: use shallower interface for completions
  cli/command/completion/functions.go
  cli/command/config/cmd.go
  cli/command/secret/cmd.go
  cli/command/service/cmd.go
  cli/command/stack/cmd.go
  cli/command/stack/list.go
  cli/command/stack/swarm/list.go
Labels: status/2-code-review, area/completion, kind/refactor

#5115 vendor: github.com/containerd/containerd v1.7.17
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies, process/cherry-pick/26.1

#5117 update to go1.21.11
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, process/cherry-picked, area/packaging, process/cherry-pick/25.0, process/cherry-pick/23.0

#5118 [26.1 backport] update to go1.21.11, Alpine 3.20
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#5121 vendor: github.com/containerd/containerd v1.7.18
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5116 [26.1] vendor: github.com/docker/docker de5c9cf0b96e (v26.1.4-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5122 vendor: github.com/docker/docker c6aaabc9fc82 (master / v27.0.0-dev)
  cli/command/network/client_test.go
  cli/command/network/formatter.go
  cli/command/network/formatter_test.go
  cli/command/network/list_test.go
  cli/command/network/remove_test.go
  cli/command/service/client_test.go
  cli/command/service/formatter.go
  cli/command/service/inspect_test.go
  cli/command/service/opts_test.go
  cli/command/service/update_test.go
  cli/command/stack/client_test.go
  cli/command/stack/swarm/client_test.go
  cli/command/stack/swarm/common.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/stack/swarm/deploy_composefile_test.go
  cli/command/stack/swarm/remove.go
  internal/test/builders/network.go
  internal/test/network/client.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/network/network.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/client/network_inspect.go
  vendor/github.com/docker/docker/client/network_list.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/api

#4744 vendor: migrate to github.com/go-viper/mapstructure/v2 v2.0.0
  cli/compose/loader/loader.go
  vendor.mod
  vendor.sum
  vendor/github.com/go-viper/mapstructure/v2/.envrc
  vendor/github.com/go-viper/mapstructure/v2/.gitignore
  vendor/github.com/go-viper/mapstructure/v2/.golangci.yaml
  vendor/github.com/go-viper/mapstructure/v2/CHANGELOG.md
  vendor/github.com/go-viper/mapstructure/v2/LICENSE
  vendor/github.com/go-viper/mapstructure/v2/README.md
  vendor/github.com/go-viper/mapstructure/v2/decode_hooks.go
  vendor/github.com/go-viper/mapstructure/v2/flake.lock
  vendor/github.com/go-viper/mapstructure/v2/flake.nix
  vendor/github.com/go-viper/mapstructure/v2/internal/errors/errors.go
  vendor/github.com/go-viper/mapstructure/v2/internal/errors/join.go
  vendor/github.com/go-viper/mapstructure/v2/internal/errors/join_go1_19.go
  vendor/github.com/go-viper/mapstructure/v2/mapstructure.go
  vendor/github.com/go-viper/mapstructure/v2/reflect_go1_19.go
  vendor/github.com/go-viper/mapstructure/v2/reflect_go1_20.go
  vendor/github.com/mitchellh/mapstructure/README.md
  vendor/github.com/mitchellh/mapstructure/decode_hooks.go
  vendor/github.com/mitchellh/mapstructure/error.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5126 network create: make --ipv6 optional
  cli/command/network/create.go
  docs/reference/commandline/network_create.md
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/types.go
  vendor/modules.txt
Labels: kind/enhancement, status/2-code-review, impact/documentation, area/networking

#5128 cli/command/network: add minimal test for --ipv6 option
  cli/command/network/create_test.go
Labels: status/2-code-review, area/networking, area/testing

#5125 Handle networks.driver_opts for a service
  cli/compose/convert/service.go
  cli/compose/convert/service_test.go
  cli/compose/loader/full-example.yml
  cli/compose/loader/full-struct_test.go
  cli/compose/loader/loader_test.go
  cli/compose/loader/testdata/full-example.json.golden
  cli/compose/loader/testdata/full-example.yaml.golden
  cli/compose/schema/data/config_schema_v3.13.json
  cli/compose/schema/schema.go
  cli/compose/schema/schema_test.go
  cli/compose/types/types.go
Labels: impact/changelog, kind/feature, area/swarm, area/stack, area/networking

#5130 vendor: github.com/docker/docker 59996a493cfc (v27.0.0-dev)
  cli/command/network/client_test.go
  cli/command/network/create.go
  cli/command/network/create_test.go
  cli/command/network/prune_test.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/system/client_test.go
  cli/command/system/prune_test.go
  cli/compose/convert/compose.go
  cli/compose/convert/compose_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/network/network.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/client/network_create.go
  vendor/github.com/docker/docker/client/network_prune.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/api, area/dependencies

#5133 vendor: github.com/distribution/reference v0.6.0
  vendor.mod
  vendor.sum
  vendor/github.com/distribution/reference/README.md
  vendor/github.com/distribution/reference/normalize.go
  vendor/github.com/distribution/reference/reference.go
  vendor/modules.txt
Labels: status/2-code-review, area/distribution, area/dependencies

#5134 vendor: github.com/docker/docker a736d0701c41 (master, v27.0.0-dev)
  cli/command/container/client_test.go
  cli/command/container/cp.go
  cli/command/container/cp_test.go
  cli/command/container/exec.go
  cli/command/container/exec_test.go
  cli/command/container/prune_test.go
  cli/command/container/stats.go
  cli/command/container/utils.go
  cli/command/image/client_test.go
  cli/command/image/import.go
  cli/command/image/import_test.go
  cli/command/image/load_test.go
  cli/command/image/prune_test.go
  cli/command/node/cmd.go
  cli/command/registry/search.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/stack/swarm/remove.go
  cli/command/system/client_test.go
  cli/command/system/events.go
  cli/command/system/events_test.go
  cli/command/system/prune_test.go
  cli/command/trust/inspect_pretty_test.go
  cli/command/trust/sign.go
  cli/command/volume/client_test.go
  cli/command/volume/prune_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/configs.go
  vendor/github.com/docker/docker/api/types/container/config.go
  vendor/github.com/docker/docker/api/types/container/container.go
  vendor/github.com/docker/docker/api/types/container/exec.go
  vendor/github.com/docker/docker/api/types/events/events.go
  vendor/github.com/docker/docker/api/types/image/image.go
  vendor/github.com/docker/docker/api/types/image/opts.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/github.com/docker/docker/api/types/registry/search.go
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/api/types/volume/options.go
  vendor/github.com/docker/docker/client/container_copy.go
  vendor/github.com/docker/docker/client/container_exec.go
  vendor/github.com/docker/docker/client/container_prune.go
  vendor/github.com/docker/docker/client/container_stats.go
  vendor/github.com/docker/docker/client/events.go
  vendor/github.com/docker/docker/client/image_import.go
  vendor/github.com/docker/docker/client/image_load.go
  vendor/github.com/docker/docker/client/image_prune.go
  vendor/github.com/docker/docker/client/image_search.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/client/volume_prune.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5137 update golangci-lint to .v1.59.0 and fix linting issues
  .golangci.yml
  cli-plugins/manager/error_test.go
  cli/command/cli.go
  cli/command/cli_test.go
  cli/command/container/attach.go
  cli/command/container/attach_test.go
  cli/command/container/create_test.go
  cli/command/container/list_test.go
  cli/command/container/opts.go
  cli/command/container/opts_test.go
  cli/command/container/rm_test.go
  cli/command/container/run_test.go
  cli/command/container/stats.go
  cli/command/context/options.go
  cli/command/image/build.go
  cli/command/image/build/context.go
  cli/command/image/pull_test.go
  cli/command/image/remove_test.go
  cli/command/network/connect.go
  cli/command/plugin/create_test.go
  cli/command/plugin/disable_test.go
  cli/command/plugin/enable_test.go
  cli/command/plugin/inspect_test.go
  cli/command/plugin/install_test.go
  cli/command/plugin/list_test.go
  cli/command/plugin/remove_test.go
  cli/command/registry/login_test.go
  cli/command/registry_test.go
  cli/command/service/logs.go
  cli/command/service/progress/progress_test.go
  cli/command/stack/swarm/remove.go
  cli/command/swarm/ipnet_slice_test.go
  cli/command/system/info.go
  cli/command/system/prune.go
  cli/command/system/version_test.go
  cli/command/telemetry_docker.go
  cli/command/trust/key_load.go
  cli/command/trust/revoke.go
  cli/command/trust/signer_add.go
  cli/compose/schema/schema.go
  cli/manifest/store/store.go
  cli/registry/client/endpoint.go
  dockerfiles/Dockerfile.lint
  e2e/image/push_test.go
  e2e/plugin/trust_test.go
  e2e/trust/revoke_test.go
  e2e/trust/sign_test.go
  internal/test/cli.go
  opts/config.go
  opts/env_test.go
  opts/file.go
  opts/hosts_test.go
  opts/mount.go
  opts/network.go
  opts/opts.go
  opts/parse.go
  opts/port.go
  opts/secret.go
Labels: status/2-code-review, area/testing

#5139 gha: switch to Ubuntu 24.04
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing

#4984 cli/push: Add `platform` switch
  cli/command/image/push.go
  docs/reference/commandline/image_push.md
  docs/reference/commandline/push.md
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/auxprogress/push.go
  vendor/github.com/docker/docker/api/types/image/opts.go
  vendor/github.com/docker/docker/client/image_push.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/modules.txt
Labels: impact/changelog, area/api, area/ux

#5141 Removed all mentions of "please" from docs and messages
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/validate-pr.yml
  .gitignore
  CONTRIBUTING.md
  NOTICE
  README.md
  cli/cobra.go
  cli/command/cli.go
  cli/command/context/export.go
  cli/command/image/trust.go
  cli/command/registry.go
  cli/command/stack/config_test.go
  cli/command/stack/loader/loader.go
  cli/command/swarm/testdata/init-init-autolock.golden
  cli/command/swarm/testdata/unlockkeys-unlock-key-rotate.golden
  cli/command/swarm/testdata/unlockkeys-unlock-key.golden
  cli/command/swarm/testdata/update-autolock-unlock-key.golden
  cli/command/swarm/unlock.go
  cli/command/swarm/unlock_key.go
  cli/command/trust/revoke.go
  cli/command/trust/revoke_test.go
  cli/command/trust/signer_add.go
  cli/command/trust/signer_add_test.go
  cli/command/trust/testdata/trust-revoke-prompt-termination.golden
  cli/connhelper/commandconn/commandconn.go
  contrib/completion/bash/docker
  dockerfiles/Dockerfile.authors
  docs/deprecated.md
  docs/extend/EBS_volume.md
  docs/reference/commandline/container_cp.md
  docs/reference/commandline/swarm_unlock-key.md
  docs/reference/commandline/swarm_unlock.md
  docs/reference/commandline/trust_revoke.md
  e2e/cli-plugins/flags_test.go
  e2e/cli-plugins/run_test.go
  experimental/README.md
  man/docker.1.md
  man/dockerd.8.md
  man/src/system/events.md
  scripts/vendor
Labels: kind/enhancement, status/3-docs-review

#5144 cli/command/registry: fix link to credential stores
  cli/command/registry/login.go
Labels: kind/docs, status/3-docs-review, process/cherry-pick/26.1

#5143 cli: Wrap Err stream
  cli/command/cli.go
  cli/command/cli_options.go
  cli/command/cli_test.go
  cli/command/container/create.go
  cli/command/image/push.go
  cli/command/registry/login_test.go
  cli/command/telemetry_utils.go
  cli/command/telemetry_utils_test.go
  internal/test/cli.go
Labels: status/2-code-review, kind/refactor

#5148 cli/command: remove deprecated EventHandler, InitEventHandler
  cli/command/events_utils.go
Labels: status/2-code-review, kind/refactor

#5142 Deprecate non-standard (config) fields in image inspect output
  docs/deprecated.md
Labels: impact/changelog, impact/deprecation, status/3-docs-review, area/api

#5150 docs: extend deprecation target for non-TLS API
  docs/deprecated.md
Labels: kind/docs, status/3-docs-review, area/api

#5151 vendor: github.com/docker/docker v27.0.0-dev (bcd280a3ed2d)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/runtime, area/dependencies

#5146 plugins: cleanup sockets when done
  cli-plugins/socket/socket.go
  cmd/docker/docker.go
Labels: status/2-code-review, area/plugins, kind/bugfix, process/cherry-pick/26.1

#5153 vendor: golang.org/x/sys v0.19.0, golang.org/x/term v0.19.0, golang.org/x/crypto v0.22.0, golang.org/x/net v0.24.0
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5155 vendor: github.com/docker/docker ba69bd9c1e48 (v27.0.0-rc.2-dev)
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: area/runtime, area/dependencies

#5154 [26.1 backport] cli/command: more go1.19 ("predeclared any")
  cli/command/context/list.go
Labels: status/2-code-review, kind/bugfix

#5158 vendor: github.com/docker/docker ec4bac431c88 (v27.0.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/mount/mount.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/modules.txt
Labels: area/runtime, area/dependencies

#5162 cli/command/image: add go:build tag to prevent downgrading go version
  cli/command/image/push.go
Labels: status/2-code-review, kind/bugfix

#5164 bump version to v27.0.1-dev
  VERSION
Labels: status/2-code-review, area/packaging

#5167 vendor: github.com/docker/docker v27.0.0-rc.2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5165 gha: e2e: test against v27.0 release candidates
  .github/workflows/e2e.yml
Labels: status/2-code-review, area/testing

#5169 vendor: github.com/moby/swarmkit/v2 v2.0.0-20240611172349-ea1a7cec35cb
  vendor.mod
  vendor.sum
  vendor/github.com/moby/swarmkit/v2/api/api.pb.txt
  vendor/github.com/moby/swarmkit/v2/api/specs.pb.go
  vendor/github.com/moby/swarmkit/v2/api/specs.proto
  vendor/github.com/moby/swarmkit/v2/api/types.proto
  vendor/modules.txt
Labels: status/2-code-review, area/swarm, area/dependencies

#5172 Deprecate experimental graphdriver plugins
  docs/deprecated.md
  docs/extend/index.md
  docs/extend/plugins_graphdriver.md
  experimental/README.md
Labels: impact/changelog, impact/deprecation, kind/experimental, status/3-docs-review, area/runtime

#5173 Dockerfile: update buildx to v0.15.1
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#5174 update go-md2man to v2.0.4
  man/go.mod
  scripts/docs/generate-man.sh
Labels: status/2-code-review, area/packaging, area/dependencies

#5175 vendor: github.com/spf13/cobra v1.8.1
  vendor.mod
  vendor.sum
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/modules.txt
Labels: status/2-code-review, area/completion, area/dependencies

#5177 cli-plugins/manager: add GoDoc for getPluginDirs, defaultSystemPluginDirs
  cli-plugins/manager/manager.go
  cli-plugins/manager/manager_unix.go
  cli-plugins/manager/manager_windows.go
Labels: status/2-code-review, area/plugins, kind/refactor

#3975 Fix RFC3339 typo in docs
  docs/reference/commandline/container_logs.md
  docs/reference/commandline/container_prune.md
  docs/reference/commandline/image_prune.md
  docs/reference/commandline/network_prune.md
  docs/reference/commandline/service_logs.md
  docs/reference/commandline/system_events.md
  docs/reference/commandline/system_prune.md
  man/src/container/logs.md
  man/src/system/events.md
Labels: kind/docs, status/3-docs-review

#5170 vendor: github.com/docker/docker 1a1f3cff45ec (master, v27.0-dev)
  cli/command/container/stats_helpers.go
  cli/command/container/stats_helpers_test.go
  cli/command/container/stats_unit_test.go
  cli/command/image/build.go
  cli/command/service/update.go
  cli/command/service/update_test.go
  cli/compose/convert/service.go
  opts/ulimit.go
  opts/ulimit_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/client.go
  vendor/github.com/docker/docker/api/types/container/container.go
  vendor/github.com/docker/docker/api/types/container/hostconfig.go
  vendor/github.com/docker/docker/api/types/container/stats.go
  vendor/github.com/docker/docker/api/types/swarm/container.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/client/container_stats.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/registry/auth.go
  vendor/github.com/docker/docker/registry/search.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies, area/go-sdk

#5179 update mailmap and AUTHORS
  .mailmap
  AUTHORS
Labels: status/3-docs-review, area/packaging

#5180 vendor: github.com/docker/docker v27.0-dev (018d93decfb5)
  cli/command/container/exec_test.go
  cli/command/container/logs_test.go
  cli/command/registry/login_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/client/client.go
  vendor/modules.txt
Labels: area/runtime, area/dependencies

#3599 use local ConvertToHostname() implementation
  cli/command/registry.go
  cli/command/registry/logout.go
  cli/config/credentials/file_store.go
  cli/config/credentials/file_store_test.go
  cli/registry/client/client.go
  cli/registry/client/fetcher.go
Labels: status/2-code-review, kind/refactor

#5171 fix: force cli to exit after third sigint/sigterm
  cmd/docker/docker.go
Labels: status/2-code-review, kind/bugfix

#5178 build: allow BuildKit to be used on Windows daemons that advertise it
  cli/command/cli.go
  cmd/docker/builder.go
Labels: impact/changelog, kind/enhancement, kind/experimental, status/2-code-review, area/builder, area/builder/classic-builder, area/builder/buildkit

#5183 vendor: github.com/docker/docker v27.0.1-rc.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5185 docs/deprecated: update status for graphdriver-plugins
  docs/deprecated.md
Labels: impact/deprecation, status/3-docs-review, area/runtime

#5186 Dockerfile: update compose to v2.28.0
  Dockerfile
Labels: status/2-code-review, area/testing

#5187 cli/config: replace pkg/homedir dependency with local copy
  cli/config/config.go
Labels: status/2-code-review, kind/refactor

#5188 cli: make initializing the global meter- and tracing providers optional
  cli-plugins/plugin/plugin.go
  cli/command/cli.go
  cli/command/telemetry_options.go
  cmd/docker/docker.go
Labels: status/2-code-review, area/metrics, area/metrics/otel, process/cherry-pick/26.1, area/go-sdk, impact/go-sdk

#5189 update golangci-lint to v1.59.1
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, area/testing

#5190 [27.0] vendor: github.com/docker/docker v27.0.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5195 re-introduced support for port numbers in docker registry URL
  cli/config/credentials/file_store.go
  cli/config/credentials/file_store_test.go
Labels: kind/bugfix, area/authentication, process/cherry-pick/27.0

#5192 [27.0 backport] update golangci-lint to v1.59.1
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, area/testing

#5197 [27.0 backport] re-introduced support for port numbers in docker registry URL
  cli/config/credentials/file_store.go
  cli/config/credentials/file_store_test.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/authentication

#5196 cli/config/credentials: ConvertToHostname: handle IP-addresses
  cli/config/credentials/file_store.go
  cli/config/credentials/file_store_test.go
Labels: status/2-code-review, process/cherry-picked, kind/bugfix, area/authentication

#5191 gha/e2e: Update latest version to 27.0
  .github/workflows/e2e.yml
Labels: status/2-code-review, area/testing, process/cherry-pick/27.0

#5199 [27.0 backport] gha/e2e: Update latest version to 27.0
  .github/workflows/e2e.yml
Labels: status/2-code-review, area/testing

#5201 [27.0] vendor: github.com/docker/docker v27.0.2-dev (861fde8cc974)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/modules.txt
Labels: area/runtime, area/dependencies

#5202 [27.0] vendor: github.com/docker/docker v27.0.2-dev (e953d76450b6)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/modules.txt
Labels: area/runtime, area/dependencies

#5205 vendor: github.com/docker/docker v27.0.2
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/api/types/types_deprecated.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-picked, area/runtime, area/dependencies

#5206 [27.0 backport] vendor: github.com/docker/docker v27.0.2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies
