Repository docker/cli, pull requests merged in 2025-07, with the labels that each got.

#6160 cli/debug: fix OTELErrorHandler logging messages if there's no error
  cli/debug/debug.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/metrics/otel

#6154 vendor: github.com/docker/docker v28.3.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6158 cli/command/container: remove redundant uses of strslice.StrSlice
  cli/command/container/opts.go
Labels: status/2-code-review, kind/refactor

#6170 e2e/global: TestPromptExitCode: check for trailing newline
  e2e/global/cli_test.go
Labels: status/2-code-review, area/testing

#6173 docs: fix CDI device configuration anchor
  docs/reference/commandline/container_run.md
Labels: kind/docs

#6176 cli/command/container: don't set CopyToContainerOptions.AllowOverwriteDirWithFile
  cli/command/container/cp.go
Labels: status/2-code-review, kind/refactor, process/cherry-pick/25.0, process/cherry-pick/28.x

#6179 Dockerfile: bump gotest.tools/gotestsum v1.12.3 (for go1.25)
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#6177 cli/command: remove some redundant import-aliases
  cli/command/config/formatter.go
  cli/command/container/cp.go
  cli/command/container/formatter_stats.go
  cli/command/container/prune.go
  cli/command/formatter/disk_usage.go
  cli/command/formatter/image.go
  cli/command/formatter/volume.go
  cli/command/image/formatter_history.go
  cli/command/node/formatter.go
  cli/command/secret/formatter.go
  cli/command/service/formatter.go
  cli/compose/loader/loader.go
Labels: status/2-code-review, kind/refactor

#6182 remove use of github.com/docker/docker/pkg/longpath
  cli/command/image/build/context_windows.go
  cli/command/image/build/context_windows_test.go
  vendor/github.com/docker/docker/pkg/longpath/longpath.go
  vendor/modules.txt
Labels: status/2-code-review, area/builder, area/builder/classic-builder, kind/refactor

#6181 remove uses of github.com/docker/docker/pkg/ioutils ReadCloserWrapper
  cli/command/container/hijack.go
  cli/command/image/build/context.go
  vendor/github.com/docker/docker/pkg/ioutils/fswriters_deprecated.go
  vendor/github.com/docker/docker/pkg/ioutils/readers.go
  vendor/github.com/docker/docker/pkg/ioutils/writeflusher.go
  vendor/github.com/docker/docker/pkg/ioutils/writers.go
  vendor/modules.txt
Labels: status/2-code-review, kind/refactor

#6183 cli/command/container: diff: remove redundant validation and cleanup
  cli/command/container/diff.go
  cli/command/container/diff_test.go
Labels: status/2-code-review

#6155 Dockerfile: update to alpine 3.22
  Dockerfile
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, area/testing, area/packaging

#6184 cli/command: deprecate RegistryAuthenticationPrivilegedFunc
  cli/command/registry.go
Labels: impact/changelog, impact/deprecation, area/authentication, area/go-sdk, impact/go-sdk

#6189 cli/command/image: move build-context detection to build
  cli/command/image/build.go
  cli/command/image/build/context_detect.go
Labels: status/2-code-review, area/builder, area/builder/classic-builder, kind/refactor, area/go-sdk

#6190 add local fork of github.com/docker/docker/builder/remotecontext
  Dockerfile
  cli/command/image/build/context.go
  cli/command/image/build/context_detect.go
  cli/command/image/build/internal/git/gitutils.go
  cli/command/image/build/internal/git/gitutils_test.go
  cli/command/image/build/internal/urlutil/urlutil.go
  cli/command/image/build/internal/urlutil/urlutil_test.go
  dockerfiles/Dockerfile.dev
  vendor.mod
  vendor/modules.txt
Labels: status/2-code-review, area/builder, area/builder/classic-builder, kind/refactor

#6191 Include FirewallBackend in docker info output
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/command/system/testdata/docker-info-badsec.golden
  cli/command/system/testdata/docker-info-badsec.json.golden
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-no-swarm.golden
  cli/command/system/testdata/docker-info-no-swarm.json.golden
  cli/command/system/testdata/docker-info-plugins.golden
  cli/command/system/testdata/docker-info-plugins.json.golden
  cli/command/system/testdata/docker-info-with-devices.golden
  cli/command/system/testdata/docker-info-with-devices.json.golden
  cli/command/system/testdata/docker-info-with-labels-empty.golden
  cli/command/system/testdata/docker-info-with-labels-nil.golden
  cli/command/system/testdata/docker-info-with-swarm.golden
  cli/command/system/testdata/docker-info-with-swarm.json.golden
Labels: impact/changelog, kind/feature, area/networking

#6192 cli/command/image: remove use of api.NoBaseImageSpecifier
  cli/command/image/build.go
Labels: status/2-code-review, kind/refactor

#6186 opts: minor cleanup in tests, and remove some import aliases
  cli/command/container/opts.go
  cli/command/service/formatter.go
  cli/command/service/update.go
  cli/command/service/update_test.go
  opts/mount_test.go
Labels: status/2-code-review, kind/refactor

#6200 cli/command/registry: remove uses of registry.ParseSearchIndexInfo
  cli/command/registry/search.go
Labels: status/2-code-review, kind/refactor

#6201 vendor: docker/docker, moby/api, moby/client to latest
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/process/process.go
  vendor/github.com/docker/docker/pkg/process/process_linux.go
  vendor/github.com/docker/docker/pkg/process/process_nolinux.go
  vendor/github.com/docker/docker/pkg/process/process_unix.go
  vendor/github.com/docker/docker/pkg/process/process_windows.go
  vendor/github.com/moby/moby/api/stdcopy/stdcopy.go
  vendor/github.com/moby/moby/api/types/client.go
  vendor/github.com/moby/moby/api/types/container/container.go
  vendor/github.com/moby/moby/api/types/container/health.go
  vendor/github.com/moby/moby/api/types/image/opts.go
  vendor/github.com/moby/moby/api/types/registry/registry.go
  vendor/github.com/moby/moby/api/types/registry/search.go
  vendor/github.com/moby/moby/api/types/swarm/node.go
  vendor/github.com/moby/moby/api/types/swarm/runtime/gen.go
  vendor/github.com/moby/moby/client/container_exec.go
  vendor/github.com/moby/moby/client/container_list.go
  vendor/github.com/moby/moby/client/events.go
  vendor/github.com/moby/moby/client/hijack.go
  vendor/github.com/moby/moby/client/request.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6206 cli/registry/client: remove deprecated RepoNameForReference
  cli/registry/client/endpoint.go
Labels: impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#6209 image/tree: Unmark as experimental, warn when redirected
  cli/command/image/tree.go
Labels: status/2-code-review, area/ux, area/images

#6213 cli/command/plugin: fix linting issues, and assorted cleanups
  cli/command/plugin/create.go
  cli/command/plugin/disable.go
  cli/command/plugin/enable.go
  cli/command/plugin/enable_test.go
  cli/command/plugin/formatter.go
  cli/command/plugin/formatter_test.go
  cli/command/plugin/inspect.go
  cli/command/plugin/inspect_test.go
  cli/command/plugin/install.go
  cli/command/plugin/install_test.go
  cli/command/plugin/list_test.go
  cli/command/plugin/push.go
  cli/command/plugin/remove_test.go
  cli/command/plugin/set.go
  cli/command/plugin/testdata/plugin-inspect-single-without-format.golden
  cli/command/plugin/upgrade.go
Labels: status/2-code-review, kind/refactor

#6214 templates: deprecate NewParse()
  cli/command/container/list.go
  cli/command/system/info.go
  cli/command/system/version.go
  templates/templates.go
  templates/templates_test.go
Labels: impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#6211 vendor: update docker, api, client to master, consume client/pkg/stringid
  cli/command/container/client_test.go
  cli/command/container/hijack.go
  cli/command/container/run_test.go
  cli/command/formatter/displayutils.go
  cli/command/plugin/client_test.go
  cli/command/plugin/create.go
  cli/command/plugin/create_test.go
  cli/command/plugin/disable.go
  cli/command/plugin/disable_test.go
  cli/command/plugin/enable.go
  cli/command/plugin/enable_test.go
  cli/command/plugin/install.go
  cli/command/plugin/install_test.go
  cli/command/plugin/remove.go
  cli/command/plugin/remove_test.go
  cli/command/plugin/upgrade_test.go
  cli/command/system/df.go
  vendor.mod
  vendor.sum
  vendor/github.com/moby/moby/api/types/client.go
  vendor/github.com/moby/moby/api/types/system/disk_usage.go
  vendor/github.com/moby/moby/api/types/types.go
  vendor/github.com/moby/moby/client/client_interfaces.go
  vendor/github.com/moby/moby/client/container_attach.go
  vendor/github.com/moby/moby/client/container_exec.go
  vendor/github.com/moby/moby/client/hijack.go
  vendor/github.com/moby/moby/client/pkg/stringid/stringid.go
  vendor/github.com/moby/moby/client/plugin_create.go
  vendor/github.com/moby/moby/client/plugin_disable.go
  vendor/github.com/moby/moby/client/plugin_enable.go
  vendor/github.com/moby/moby/client/plugin_install.go
  vendor/github.com/moby/moby/client/plugin_remove.go
  vendor/github.com/moby/moby/client/plugin_upgrade.go
  vendor/github.com/moby/moby/client/system_disk_usage.go
  vendor/github.com/moby/moby/client/system_events.go
  vendor/github.com/moby/moby/client/system_info.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6218 [28.x] vendor: github.com/docker/docker v28.3.3, github.com/opencontainers/image-spec v1.1.1
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/registry/authconfig.go
  vendor/github.com/docker/docker/client/image_push.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6227 opts/swarmopts: minor cleanup and refactor
  opts/swarmopts/port.go
Labels: status/2-code-review, kind/refactor

#6228 bump version to v29.0.0-dev
  VERSION
Labels: status/2-code-review, area/packaging
