Repository docker/cli, pull requests merged in 2025-08, with the labels that each got.

#6234 internal/registry: remove RepositoryInfo, add NewIndexInfo
  cli/command/image/push.go
  cli/command/image/trust.go
  cli/command/plugin/install.go
  cli/command/plugin/push.go
  cli/command/service/trust.go
  cli/registry/client/endpoint.go
  cli/registry/client/fetcher.go
  cli/trust/trust.go
  cli/trust/trust_push.go
  internal/registry/config.go
  internal/registry/registry_test.go
  internal/registry/types.go
Labels: status/2-code-review, area/distribution, kind/refactor, area/authentication

#6239 cli/connhelper: remove dependency on pkg/process
  cli/connhelper/commandconn/commandconn_unix_test.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/LICENSE
  vendor/github.com/docker/docker/NOTICE
  vendor/github.com/docker/docker/pkg/process/doc.go
  vendor/github.com/docker/docker/pkg/process/process.go
  vendor/github.com/docker/docker/pkg/process/process_linux.go
  vendor/github.com/docker/docker/pkg/process/process_nolinux.go
  vendor/github.com/docker/docker/pkg/process/process_unix.go
  vendor/github.com/docker/docker/pkg/process/process_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6236 system prune: refactor to use "register" functions
  cli/command/builder/prune.go
  cli/command/container/prune.go
  cli/command/image/prune.go
  cli/command/network/prune.go
  cli/command/system/prune.go
  cli/command/system/prune_test.go
  cli/command/system/pruner/pruner.go
  cli/command/volume/prune.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6235 remove some remnants from CLI "experimental" config option
  cli-plugins/manager/candidate_test.go
  e2e/internal/fixtures/fixtures.go
Labels: status/2-code-review, area/testing

#6240 cli/command: remove deprecated CopyToFile, ConfigureAuth utilities
  cli/command/registry.go
  cli/command/utils.go
Labels: impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#6219 cli/command/service: credentialSpecOpt: use strings.Cut
  cli/command/service/opts.go
Labels: area/swarm, kind/refactor

#6241 remove deprecated `bind-nonrecursive` option for `--mount`
  docs/deprecated.md
  docs/reference/commandline/service_create.md
  man/docker-run.1.md
  opts/mount.go
  opts/mount_test.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, docs/revisit, area/volumes

#6243 cli/command: remove prompt utilities that were for internal use
  cli/command/utils.go
Labels: impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#6245 cli/command/completion: remove deprecated ValidArgsFn
  cli/command/completion/functions.go
Labels: impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#6247 update to go1.24.6
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  .golangci.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, process/cherry-pick/25.0, area/dependencies, process/cherry-pick/28.x

#6249 e2d skip flaky test: TestPromptExitCode/plugin_upgrade, plugin_install
  e2e/global/cli_test.go
Labels: status/2-code-review, area/testing

#6252 reduce uses of pkg/errors
  cli/cobra.go
  cli/command/cli.go
  cli/command/cli_options.go
  cli/command/config/create.go
  cli/command/container/attach.go
  cli/command/container/attach_test.go
  cli/command/container/cp.go
  cli/command/container/create.go
  cli/command/defaultcontextstore.go
  cli/command/formatter/formatter.go
  cli/command/formatter/reflect.go
  cli/command/idresolver/idresolver.go
  cli/command/image/build/internal/git/gitutils.go
  cli/command/manifest/annotate.go
  cli/command/manifest/create_list.go
  cli/command/manifest/inspect.go
  cli/command/manifest/push.go
  cli/command/registry.go
  cli/command/registry/login.go
  cli/command/registry/login_test.go
  cli/command/telemetry_docker.go
  cli/command/telemetry_utils.go
  cli/command/trust/key_generate.go
  cli/command/trust/key_load.go
  cli/command/trust/revoke.go
  cli/command/trust/sign.go
  cli/command/trust/signer_add.go
  cli/command/trust/signer_remove.go
  cli/command/utils.go
  cli/compose/convert/service.go
  cli/compose/convert/volume.go
  cli/compose/interpolation/interpolation.go
  cli/compose/loader/interpolate.go
  cli/compose/loader/loader.go
  cli/compose/loader/merge.go
  cli/compose/schema/schema.go
  cli/config/config.go
  cli/config/configfile/file.go
  cli/context/docker/load.go
  cli/context/tlsdata.go
  cli/manifest/store/store.go
  cli/manifest/types/types.go
  cli/registry/client/client.go
  cli/registry/client/endpoint.go
  cli/registry/client/fetcher.go
  cli/required.go
  cli/trust/trust.go
  cli/trust/trust_push.go
  e2e/cli-plugins/flags_test.go
  internal/volumespec/volumespec.go
Labels: status/2-code-review, kind/refactor

#6254 cli/command/container: copyToContainer: improve error-handling
  cli/command/container/cp.go
Labels: status/2-code-review

#6257 [28.x backport] cli/command: remove deprecated CopyToFile, ConfigureAuth utilities
  cli/command/registry.go
  cli/command/utils.go
Labels: impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#6259 [28.x backport] cli/command/completion: remove deprecated ValidArgsFn
  cli/command/completion/functions.go
Labels: impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#6260 .github/workflows: Add kind label validation to PR workflow
  .github/workflows/validate-pr.yml
Labels: kind/enhancement, area/ci

#6256 [28.x backport] cli/command: remove interactive login prompt from docker push/pull, deprecate RegistryAuthenticationPrivilegedFunc
  cli/command/image/push.go
  cli/command/image/trust.go
  cli/command/plugin/install.go
  cli/command/plugin/upgrade.go
  cli/command/registry.go
  cli/command/registry/search.go
  cli/command/trust/sign.go
Labels: impact/changelog, status/2-code-review, area/distribution, area/authentication, area/go-sdk, impact/go-sdk

#6264 [28.x] merge v28.3.3 tag into v28.x
  Dockerfile
  cli/command/config/formatter.go
  cli/command/container/cp.go
  cli/command/container/diff.go
  cli/command/container/diff_test.go
  cli/command/container/formatter_stats.go
  cli/command/container/formatter_stats_test.go
  cli/command/container/hijack.go
  cli/command/container/prune.go
  cli/command/formatter/buildcache.go
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
  cli/command/formatter/disk_usage.go
  cli/command/formatter/displayutils.go
  cli/command/formatter/displayutils_test.go
  cli/command/formatter/image.go
  cli/command/formatter/image_test.go
  cli/command/formatter/volume.go
  cli/command/formatter/volume_test.go
  cli/command/image/build/context.go
  cli/command/image/build/context_windows.go
  cli/command/image/build/context_windows_test.go
  cli/command/image/formatter_history.go
  cli/command/image/formatter_history_test.go
  cli/command/image/tree.go
  cli/command/network/formatter.go
  cli/command/network/formatter_test.go
  cli/command/node/formatter.go
  cli/command/node/formatter_test.go
  cli/command/plugin/formatter.go
  cli/command/plugin/formatter_test.go
  cli/command/secret/formatter.go
  cli/command/service/formatter.go
  cli/command/service/logs.go
  cli/command/service/progress/progress.go
  cli/command/task/formatter.go
  cli/command/trust/formatter.go
  cli/command/trust/formatter_test.go
  cli/compose/loader/loader.go
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  internal/test/randomid.go
  vendor/github.com/docker/docker/pkg/ioutils/fswriters_deprecated.go
  vendor/github.com/docker/docker/pkg/ioutils/readers.go
  vendor/github.com/docker/docker/pkg/ioutils/writeflusher.go
  vendor/github.com/docker/docker/pkg/ioutils/writers.go
  vendor/github.com/docker/docker/pkg/longpath/longpath.go
  vendor/github.com/docker/docker/pkg/stringid/stringid.go
  vendor/modules.txt
Labels: status/2-code-review

#6262 [28.x backport] cli/connhelper: remove dependency on pkg/process
  cli/connhelper/commandconn/commandconn_unix_test.go
  vendor/github.com/docker/docker/pkg/process/doc.go
  vendor/github.com/docker/docker/pkg/process/process_unix.go
  vendor/github.com/docker/docker/pkg/process/process_windows.go
  vendor/modules.txt
Labels: status/2-code-review, kind/refactor, area/dependencies

#6265 [28.x backport] add local fork of github.com/docker/docker/builder/remotecontext
  Dockerfile
  cli/command/image/build.go
  cli/command/image/build/context.go
  cli/command/image/build/context_detect.go
  cli/command/image/build/internal/git/gitutils.go
  cli/command/image/build/internal/git/gitutils_test.go
  cli/command/image/build/internal/urlutil/urlutil.go
  cli/command/image/build/internal/urlutil/urlutil_test.go
  dockerfiles/Dockerfile.dev
  vendor.mod
  vendor/modules.txt
Labels: status/2-code-review, area/builder/classic-builder, area/dependencies

#6274 opts: deprecate QuotedString
  cli/flags/options.go
  opts/quotedstring.go
Labels: impact/deprecation, status/2-code-review, process/cherry-picked, kind/refactor, area/go-sdk, impact/go-sdk

#6270 docs: fix output example for docker system prune
  docs/reference/commandline/system_prune.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked, kind/bugfix

#6277 [28.x backport] docs: fix output example for docker system prune
  docs/reference/commandline/system_prune.md
Labels: kind/docs, status/3-docs-review, kind/bugfix

#6279 opts: deprecate ValidateHost utility
  opts/hosts.go
Labels: impact/deprecation, status/2-code-review, process/cherry-picked, kind/refactor, area/go-sdk, impact/go-sdk

#6280 [28.x backport] opts: deprecate ValidateHost utility
  opts/hosts.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6221 [28.x] add internal fork of docker/docker/registry
  cli/command/image/push.go
  cli/command/image/trust.go
  cli/command/plugin/install.go
  cli/command/plugin/push.go
  cli/command/registry/login.go
  cli/command/registry/login_test.go
  cli/command/registry/logout.go
  cli/command/registry/search.go
  cli/command/service/trust.go
  cli/command/system/info.go
  cli/command/system/info_test.go
  cli/registry/client/endpoint.go
  cli/registry/client/fetcher.go
  cli/trust/trust.go
  cli/trust/trust_push.go
  internal/oauth/manager/manager.go
  internal/registry/auth.go
  internal/registry/config.go
  internal/registry/config_test.go
  internal/registry/doc.go
  internal/registry/errors.go
  internal/registry/registry.go
  internal/registry/registry_mock_test.go
  internal/registry/registry_test.go
  internal/registry/service.go
  internal/registry/service_v2.go
  vendor.mod
  vendor/github.com/docker/docker/pkg/homedir/homedir.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_linux.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_others.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/config_unix.go
  vendor/github.com/docker/docker/registry/config_windows.go
  vendor/github.com/docker/docker/registry/errors.go
  vendor/github.com/docker/docker/registry/search.go
  vendor/github.com/docker/docker/registry/search_endpoint_v1.go
  vendor/github.com/docker/docker/registry/search_session.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/service_v2.go
  vendor/github.com/docker/docker/registry/types.go
  vendor/modules.txt
Labels: status/2-code-review, area/distribution

#6272 [28.x backport] remove aliases for containerd/errdefs, disallow docker/errdefs
  .golangci.yml
  cli/command/container/create.go
  cli/command/container/errors.go
  cli/command/container/rm.go
  cli/command/context/create.go
  cli/command/context/remove_test.go
  cli/command/context/use_test.go
  cli/command/defaultcontextstore_test.go
  cli/command/image/remove.go
  cli/command/network/remove.go
  cli/command/registry/login.go
  cli/command/service/inspect.go
  cli/command/service/logs.go
  cli/command/stack/swarm/deploy_composefile.go
  cli/command/system/inspect.go
  cli/context/store/errors.go
  cli/context/store/metadata_test.go
  cli/context/store/store_test.go
  cli/context/store/tlsstore_test.go
  cmd/docker/docker.go
  internal/registry/config_test.go
  internal/registry/service.go
Labels: status/2-code-review

#6284 Unexport the builder and bake stub command
  cli/command/builder/cmd.go
  cli/command/commands/commands.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6285 Unexport checkpoint command
  cli/command/checkpoint/cmd.go
  cli/command/commands/commands.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6300 cli/command: TestRetrieveAuthTokenFromImage: don't decode authconfig
  cli/command/registry_test.go
Labels: area/testing, kind/refactor, process/cherry-pick/28.x

#6299 Unexport container commands
  cli/command/commands/commands.go
  cli/command/container/attach.go
  cli/command/container/attach_test.go
  cli/command/container/cmd.go
  cli/command/container/commit.go
  cli/command/container/commit_test.go
  cli/command/container/completion_test.go
  cli/command/container/cp.go
  cli/command/container/create.go
  cli/command/container/create_test.go
  cli/command/container/diff.go
  cli/command/container/diff_test.go
  cli/command/container/exec.go
  cli/command/container/exec_test.go
  cli/command/container/export.go
  cli/command/container/export_test.go
  cli/command/container/kill.go
  cli/command/container/kill_test.go
  cli/command/container/list.go
  cli/command/container/logs.go
  cli/command/container/pause.go
  cli/command/container/pause_test.go
  cli/command/container/port.go
  cli/command/container/port_test.go
  cli/command/container/prune.go
  cli/command/container/prune_test.go
  cli/command/container/rename.go
  cli/command/container/rename_test.go
  cli/command/container/restart.go
  cli/command/container/restart_test.go
  cli/command/container/rm.go
  cli/command/container/rm_test.go
  cli/command/container/run.go
  cli/command/container/run_test.go
  cli/command/container/start.go
  cli/command/container/stats.go
  cli/command/container/stop.go
  cli/command/container/stop_test.go
  cli/command/container/top.go
  cli/command/container/unpause.go
  cli/command/container/update.go
  cli/command/container/wait.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6263 docs/deprecated: legacy links env vars
  docs/deprecated.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/28.x

#6303 docs: deprecated: fix formatting of deprecated/removed in
  docs/deprecated.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/28.x

#6304 cli/registry/client: deprecate and move internal
  cli/command/manifest/annotate.go
  cli/command/manifest/client_test.go
  cli/command/manifest/push.go
  cli/registry/client/client_deprecated.go
  internal/registryclient/client.go
  internal/registryclient/endpoint.go
  internal/registryclient/fetcher.go
  internal/test/cli.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6307 [28.x backport] build(deps): bump actions/checkout from 4 to 5
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing

#6309 [28.x backport] docs/deprecated: legacy links env vars
  docs/deprecated.md
Labels: impact/deprecation, kind/docs, status/3-docs-review, area/networking

#6306 cli/flags: remove special quote handling for `--tlsXXX` flags
  cli/flags/options.go
  cli/flags/options_test.go
Labels: impact/changelog, status/2-code-review, kind/refactor, area/ux

#6296 cli: remove deprecated VisitAll, DisableFlagsInUseLine utilities
  cli/cobra.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6313 [28.x backport] cli/registry/client: deprecate and move internal
  cli/command/manifest/annotate.go
  cli/command/manifest/client_test.go
  cli/command/manifest/push.go
  cli/registry/client/client_deprecated.go
  internal/registryclient/client.go
  internal/registryclient/endpoint.go
  internal/registryclient/fetcher.go
  internal/test/cli.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6316 Unexport network commands
  cli/command/commands/commands.go
  cli/command/network/cmd.go
  cli/command/network/prune.go
  cli/command/network/prune_test.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk

#6317 Unexport node commands
  cli/command/commands/commands.go
  cli/command/node/cmd.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk

#6319 Unexport secret commands
  cli/command/commands/commands.go
  cli/command/secret/cmd.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6318 Unexport manifest command
  cli/command/commands/commands.go
  cli/command/manifest/cmd.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6320 Unexport service commands
  cli/command/commands/commands.go
  cli/command/service/cmd.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6321 Unexport volume commands
  cli/command/commands/commands.go
  cli/command/volume/cmd.go
  cli/command/volume/prune.go
  cli/command/volume/prune_test.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk

#6323 Unexport stack commands
  cli/command/commands/commands.go
  cli/command/stack/cmd.go
Labels: impact/changelog, impact/deprecation, kind/refactor, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6327 internal/registryclient: repositoryEndpoint: memoize repoName
  internal/registryclient/client.go
  internal/registryclient/endpoint.go
  internal/registryclient/fetcher.go
Labels: status/2-code-review, area/distribution, kind/refactor, area/manifest

#6332 [28.x] cli/command: deprecate prompt utilities that were for internal use
  cli/command/utils.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6329 Register CLI commands implicitly
  cli/command/builder/cmd.go
  cli/command/checkpoint/cmd.go
  cli/command/commands/commands.go
  cli/command/config/cmd.go
  cli/command/container/cmd.go
  cli/command/context/cmd.go
  cli/command/image/cmd.go
  cli/command/manifest/cmd.go
  cli/command/network/cmd.go
  cli/command/node/cmd.go
  cli/command/plugin/cmd.go
  cli/command/registry/login.go
  cli/command/registry/logout.go
  cli/command/registry/search.go
  cli/command/secret/cmd.go
  cli/command/service/cmd.go
  cli/command/stack/cmd.go
  cli/command/swarm/cmd.go
  cli/command/system/cmd.go
  cli/command/trust/cmd.go
  cli/command/volume/cmd.go
Labels: kind/refactor

#6334 internal/commands: remove mutexes / synchronisation and copy
  internal/commands/commands.go
Labels: status/2-code-review, kind/refactor

#6330 opts: deprecate ParseEnvFile
  cli/compose/loader/envfile.go
  cli/compose/loader/envfile_test.go
  cli/compose/loader/loader.go
  opts/env.go
  opts/envfile_deprecated.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6340 [28.x backport] cli/command/plugin: fix linting issues, and assorted cleanups
  cli/command/plugin/create.go
  cli/command/plugin/disable.go
  cli/command/plugin/enable.go
  cli/command/plugin/enable_test.go
  cli/command/plugin/formatter.go
  cli/command/plugin/formatter_test.go
  cli/command/plugin/inspect.go
  cli/command/plugin/inspect_test.go
  cli/command/plugin/install.go
  cli/command/plugin/install_test.go
  cli/command/plugin/list_test.go
  cli/command/plugin/push.go
  cli/command/plugin/remove_test.go
  cli/command/plugin/set.go
  cli/command/plugin/testdata/plugin-inspect-single-without-format.golden
  cli/command/plugin/upgrade.go
Labels: status/2-code-review, kind/refactor

#6341 [28.x backport] cli/command/*: deprecate formatting-related functions and types
  cli/command/checkpoint/formatter.go
  cli/command/checkpoint/formatter_test.go
  cli/command/checkpoint/list.go
  cli/command/config/formatter.go
  cli/command/config/formatter_test.go
  cli/command/config/inspect.go
  cli/command/config/ls.go
  cli/command/container/diff.go
  cli/command/container/formatter_diff.go
  cli/command/container/formatter_diff_test.go
  cli/command/image/formatter_history.go
  cli/command/image/formatter_history_test.go
  cli/command/image/history.go
  cli/command/network/formatter.go
  cli/command/network/formatter_test.go
  cli/command/network/list.go
  cli/command/node/formatter.go
  cli/command/node/formatter_test.go
  cli/command/node/inspect.go
  cli/command/node/list.go
  cli/command/plugin/formatter.go
  cli/command/plugin/formatter_test.go
  cli/command/plugin/list.go
  cli/command/registry/formatter_search.go
  cli/command/registry/formatter_search_test.go
  cli/command/registry/search.go
  cli/command/secret/formatter.go
  cli/command/secret/formatter_test.go
  cli/command/secret/inspect.go
  cli/command/secret/ls.go
  cli/command/service/formatter.go
  cli/command/service/inspect.go
  cli/command/service/inspect_test.go
  cli/command/task/formatter.go
  cli/command/task/formatter_test.go
  cli/command/task/print.go
  cli/command/trust/formatter.go
  cli/command/trust/formatter_test.go
  cli/command/trust/inspect_pretty.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6339 cli/command/*: remove deprecated formatting-related functions and types
  cli/command/checkpoint/formatter.go
  cli/command/config/formatter.go
  cli/command/container/formatter_diff.go
  cli/command/image/formatter_history.go
  cli/command/network/formatter.go
  cli/command/node/formatter.go
  cli/command/plugin/formatter.go
  cli/command/registry/formatter_search.go
  cli/command/secret/formatter.go
  cli/command/service/formatter.go
  cli/command/task/formatter.go
  cli/command/trust/formatter.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6343 [28.x backport] cli/command/builder: deprecate NewPruneCommand
  cli/command/builder/cmd.go
  cli/command/builder/prune.go
  cli/command/builder/prune_test.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6344 cli/command/trust: remove deprecated NewPruneCommand
  cli/command/builder/prune.go
Labels: impact/changelog, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6345 vendor: golang.org/x/sync v0.16.0
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies, process/cherry-pick/28.x

#6356 cli/command/image: deprecate AuthResolver and un-export
  cli/command/image/pull.go
  cli/command/image/trust.go
  cli/command/trust/common.go
  cli/command/trust/revoke.go
  cli/command/trust/sign.go
  cli/command/trust/signer_add.go
  cli/command/trust/signer_remove.go
Labels: impact/deprecation, status/2-code-review, process/cherry-picked, area/trust, kind/refactor, area/authentication, area/go-sdk, impact/go-sdk

#6362 cli/command/formatter: ContainerContext: assorted cleanups, fixes
  cli/command/formatter/container.go
  cli/command/formatter/container_test.go
Labels: status/2-code-review, kind/refactor

#6368 cli/command/config: deprecate exported types and functions
  cli/command/config/create.go
  cli/command/config/inspect.go
  cli/command/config/ls.go
  cli/command/config/remove.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/swarm, process/cherry-picked, kind/refactor, area/go-sdk, impact/go-sdk

#6369 [28.x backport] cli/command/config: deprecate exported types and functions
  cli/command/config/create.go
  cli/command/config/inspect.go
  cli/command/config/ls.go
  cli/command/config/remove.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/swarm, kind/refactor, area/go-sdk, impact/go-sdk

#6370 cli/command/config: remove deprecated types and functions
  cli/command/config/create.go
  cli/command/config/inspect.go
  cli/command/config/ls.go
  cli/command/config/remove.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/swarm, kind/refactor, impact/go-sdk

#6366 cli/config/types: update deprecation comment for AuthConfig.Email
  cli/config/credentials/file_store_test.go
  cli/config/credentials/native_store_test.go
  cli/config/types/authconfig.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, kind/refactor, area/authentication, area/go-sdk, impact/go-sdk, process/cherry-pick/28.x

#6348 [28.x backport] vendor: golang.org/x/sync v0.16.0
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6372 cli/command/plugin: simplify auth
  cli/command/plugin/install.go
  cli/command/plugin/push.go
Labels: status/2-code-review, kind/refactor, area/authentication

#6373 cli/command/image: remove deprecated AuthResolver utility
  cli/command/image/trust.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6374 cli/command/image: remove special handling for plugin errors on pull
  cli/command/image/pull.go
Labels: status/2-code-review, area/distribution, kind/refactor

#6376 cli/command/system: TestEventsFormat: remove use of deprecated fields
  cli/command/system/events_test.go
  cli/command/system/testdata/docker-events-json-template.golden
  cli/command/system/testdata/docker-events-json.golden
Labels: status/2-code-review, area/testing, process/cherry-pick/28.x

#6385 vendor: github.com/docker/go-events v0.0.0-20250114142523-c867878c5e32
  vendor.mod
  vendor.sum
  vendor/github.com/docker/go-events/README.md
  vendor/github.com/docker/go-events/SECURITY.md
  vendor/github.com/docker/go-events/vendor.mod
  vendor/github.com/docker/go-events/vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, process/cherry-picked, area/dependencies

#6386 [28.x backport] vendor: github.com/docker/go-events v0.0.0-20250114142523-c867878c5e32
  vendor.mod
  vendor.sum
  vendor/github.com/docker/go-events/README.md
  vendor/github.com/docker/go-events/SECURITY.md
  vendor/github.com/docker/go-events/vendor.mod
  vendor/github.com/docker/go-events/vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6382 opts: remove deprecated ParseEnvFile
  opts/envfile_deprecated.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6381 [28.x backport] opts: deprecate ParseEnvFile
  cli/compose/loader/envfile.go
  cli/compose/loader/envfile_test.go
  cli/compose/loader/loader.go
  opts/env.go
  opts/envfile_deprecated.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#6377 cli/command/trust: unconvert
  cli/command/trust/sign_test.go
Labels: status/2-code-review, area/testing, kind/refactor

#6390 [28.x backport] cli/command: rename vars for consistency and prevent shadowing
  cli/command/cli_test.go
  cli/command/container/create_test.go
  cli/command/container/exec_test.go
  cli/command/idresolver/idresolver_test.go
  cli/command/network/list.go
  cli/command/node/cmd.go
  cli/command/node/demote.go
  cli/command/node/inspect.go
  cli/command/node/list.go
  cli/command/node/promote.go
  cli/command/node/ps.go
  cli/command/node/update.go
  cli/command/secret/create.go
  cli/command/secret/inspect.go
  cli/command/secret/ls.go
  cli/command/service/inspect.go
  cli/command/service/opts_test.go
  cli/command/service/ps_test.go
  cli/command/service/update_test.go
  cli/command/stack/remove_test.go
  cli/command/stack/swarm/deploy_test.go
  cli/command/stack/swarm/ps.go
  cli/command/swarm/ca.go
  cli/command/swarm/join.go
  cli/command/swarm/leave.go
  cli/command/swarm/unlock.go
  cli/command/swarm/update.go
  cli/command/system/events.go
  cli/command/volume/inspect.go
  cli/command/volume/list.go
Labels: status/2-code-review, kind/refactor

#6389 cli/command/stack/*: deprecate exported functions and types
  .golangci.yml
  cli/command/stack/formatter/formatter.go
  cli/command/stack/list.go
  cli/command/stack/loader/loader.go
  cli/command/stack/options/opts.go
  cli/command/stack/services.go
  cli/command/stack/swarm/deploy.go
  cli/command/stack/swarm/list.go
  cli/command/stack/swarm/ps.go
  cli/command/stack/swarm/remove.go
  cli/command/stack/swarm/services.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, process/cherry-picked, kind/refactor, area/go-sdk, impact/go-sdk

#6266 [28.x] vendor: github.com/docker/docker 02b4a1a3decc (v28.4.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/build/disk_usage.go
  vendor/github.com/docker/docker/api/types/container/disk_usage.go
  vendor/github.com/docker/docker/api/types/filters/filters_deprecated.go
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/image/disk_usage.go
  vendor/github.com/docker/docker/api/types/network/endpoint.go
  vendor/github.com/docker/docker/api/types/network/ipam.go
  vendor/github.com/docker/docker/api/types/registry/authconfig.go
  vendor/github.com/docker/docker/api/types/swarm/runtime.go
  vendor/github.com/docker/docker/api/types/swarm/runtime/gen.go
  vendor/github.com/docker/docker/api/types/swarm/runtime/plugin.pb.go
  vendor/github.com/docker/docker/api/types/swarm/runtime/plugin.proto
  vendor/github.com/docker/docker/api/types/swarm/runtime/runtime.go
  vendor/github.com/docker/docker/api/types/swarm/task.go
  vendor/github.com/docker/docker/api/types/system/disk_usage.go
  vendor/github.com/docker/docker/api/types/volume/disk_usage.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/client_unix.go
  vendor/github.com/docker/docker/client/client_windows.go
  vendor/github.com/docker/docker/client/container_stats.go
  vendor/github.com/docker/docker/client/image_build.go
  vendor/github.com/docker/docker/client/utils.go
  vendor/github.com/docker/docker/internal/lazyregexp/lazyregexp.go
  vendor/github.com/docker/docker/internal/multierror/multierror.go
  vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6393 cli/command/stack: cleanups and optimizations
  cli/command/stack/formatter/formatter.go
  cli/command/stack/formatter/formatter_test.go
  cli/command/stack/list.go
  cli/command/stack/swarm/deploy.go
  cli/command/stack/swarm/list.go
Labels: status/2-code-review, area/stack, kind/refactor
