Repository docker/cli, pull requests merged in 2025-04, with the labels that each got.

#5975 cli/command/image: deprecate RunPull and make internal
  cli/command/image/pull.go
  cli/command/image/push.go
  cli/command/image/save.go
  cli/command/image/trust.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#5980 cli/command/container: TestNewCreateCommandWithContentTrustErrors use subtests
  cli/command/container/create_test.go
Labels: status/2-code-review, area/testing

#5976 cli/command: move TestExperimentalCLI to cli/config
  cli/command/cli_test.go
  cli/config/config_test.go
Labels: status/2-code-review, area/testing

#5986 update to go1.23.8 (fix CVE-2025-22871)
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  .golangci.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#5982 cli/context/store: un-export LimitedReader
  cli/context/store/io_utils.go
  cli/context/store/io_utils_test.go
  cli/context/store/store.go
Labels: status/2-code-review, area/context, kind/refactor

#5984 cli/command/network: fix error-message for cancelled prune
  cli/command/network/prune.go
Labels: status/2-code-review, kind/bugfix

#5985 cli/command: minor test-fixes and cleanups
  cli/command/cli_test.go
Labels: status/2-code-review, area/testing

#5989 vendor: github.com/google/go-cmp v0.7.0
  vendor.mod
  vendor.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/internal/function/func.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5988 vendor: github.com/moby/sys/user v0.4.0
  vendor.mod
  vendor.sum
  vendor/github.com/moby/sys/user/idtools.go
  vendor/github.com/moby/sys/user/idtools_unix.go
  vendor/github.com/moby/sys/user/idtools_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5991 vendor: golang.org/x/sys v0.31.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5921 vendor: github.com/docker/docker 185651d26bc6 (master, v28.0-dev)
  cli/context/store/metadatastore.go
  cli/context/store/tlsstore.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/common.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/image/image_inspect.go
  vendor/github.com/docker/docker/api/types/image/opts.go
  vendor/github.com/docker/docker/api/types/system/info.go
  vendor/github.com/docker/docker/client/container_commit.go
  vendor/github.com/docker/docker/client/image_create.go
  vendor/github.com/docker/docker/client/image_inspect.go
  vendor/github.com/docker/docker/client/image_inspect_opts.go
  vendor/github.com/docker/docker/client/image_pull.go
  vendor/github.com/docker/docker/client/image_push.go
  vendor/github.com/docker/docker/client/image_tag.go
  vendor/github.com/docker/docker/pkg/archive/changes.go
  vendor/github.com/docker/docker/pkg/idtools/idtools.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_windows.go
  vendor/github.com/docker/docker/pkg/ioutils/fswriters_deprecated.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/github.com/docker/docker/registry/search.go
  vendor/github.com/docker/docker/registry/search_endpoint_v1.go
  vendor/github.com/docker/docker/registry/search_session.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/service_v2.go
  vendor/github.com/moby/sys/atomicwriter/LICENSE
  vendor/github.com/moby/sys/atomicwriter/atomicwriter.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5992 migrate to use github.com/moby/go-archive
  cli/command/container/cp.go
  cli/command/container/cp_test.go
  cli/command/image/build.go
  cli/command/image/build/context.go
  cli/command/image/build/context_test.go
  cli/command/image/build_test.go
  cli/command/plugin/create.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/idtools/idtools.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_windows.go
  vendor/github.com/moby/go-archive/LICENSE
  vendor/github.com/moby/go-archive/archive.go
  vendor/github.com/moby/go-archive/archive_linux.go
  vendor/github.com/moby/go-archive/archive_other.go
  vendor/github.com/moby/go-archive/archive_unix.go
  vendor/github.com/moby/go-archive/archive_windows.go
  vendor/github.com/moby/go-archive/changes.go
  vendor/github.com/moby/go-archive/changes_linux.go
  vendor/github.com/moby/go-archive/changes_other.go
  vendor/github.com/moby/go-archive/changes_unix.go
  vendor/github.com/moby/go-archive/changes_windows.go
  vendor/github.com/moby/go-archive/copy.go
  vendor/github.com/moby/go-archive/copy_unix.go
  vendor/github.com/moby/go-archive/copy_windows.go
  vendor/github.com/moby/go-archive/dev_freebsd.go
  vendor/github.com/moby/go-archive/dev_unix.go
  vendor/github.com/moby/go-archive/diff.go
  vendor/github.com/moby/go-archive/diff_unix.go
  vendor/github.com/moby/go-archive/diff_windows.go
  vendor/github.com/moby/go-archive/path.go
  vendor/github.com/moby/go-archive/path_unix.go
  vendor/github.com/moby/go-archive/path_windows.go
  vendor/github.com/moby/go-archive/time.go
  vendor/github.com/moby/go-archive/time_nonwindows.go
  vendor/github.com/moby/go-archive/time_windows.go
  vendor/github.com/moby/go-archive/whiteouts.go
  vendor/github.com/moby/go-archive/wrap.go
  vendor/github.com/moby/go-archive/xattr_supported.go
  vendor/github.com/moby/go-archive/xattr_supported_linux.go
  vendor/github.com/moby/go-archive/xattr_supported_unix.go
  vendor/github.com/moby/go-archive/xattr_unsupported.go
  vendor/modules.txt
Labels: status/2-code-review, kind/refactor, area/dependencies

#5996 vendor: update golang.org/x/.. dependencies
  vendor.mod
  vendor.sum
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/internal/httpcommon/ascii.go
  vendor/golang.org/x/net/internal/httpcommon/headermap.go
  vendor/golang.org/x/net/internal/httpcommon/request.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5997 cli/command/system: needsServerInfo: add fast-paths
  cli/command/system/info.go
Labels: status/2-code-review, kind/refactor

#5977 cli/config/configfile: deprecate ConfigFile.Experimental field
  cli/config/configfile/file.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#5999 vendor: github.com/docker/docker 511cd1c0a736 (master, v28.x-dev)
  cli/command/system/testdata/docker-info-badsec.json.golden
  cli/command/system/testdata/docker-info-daemon-warnings.json.golden
  cli/command/system/testdata/docker-info-no-swarm.json.golden
  cli/command/system/testdata/docker-info-plugins.json.golden
  cli/command/system/testdata/docker-info-with-swarm.json.golden
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/github.com/docker/docker/api/types/system/info.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/registry/auth.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/github.com/docker/docker/registry/search.go
  vendor/github.com/docker/docker/registry/search_session.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/service_v2.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5914 cli/command: deprecate CopyToFile and reimplement with atomicwriter
  cli/command/container/export.go
  cli/command/container/export_test.go
  cli/command/image/save.go
  cli/command/image/save_test.go
  cli/command/utils.go
Labels: status/2-code-review, kind/refactor

#5998 use lazyregexp to compile regexes on first use
  .golangci.yml
  cli-plugins/manager/plugin.go
  cli/command/container/opts.go
  cli/command/image/build.go
  cli/command/system/info.go
  cli/command/trust/key_generate.go
  cli/command/trust/signer_add.go
  cli/compose/template/template.go
  cli/compose/template/template_test.go
  cli/context/store/store.go
  e2e/cli-plugins/help_test.go
  internal/lazyregexp/lazyregexp.go
  internal/lazyregexp/lazyregexp_test.go
  opts/opts.go
Labels: status/2-code-review, kind/refactor

#5983 cli/command: DockerCli.Initialize: make sure context-store config is set
  cli/command/cli.go
  cli/command/cli_options.go
Labels: status/2-code-review, kind/bugfix, kind/refactor

#6000 cli/command/image: Fix total content size calculation in image tree
  cli/command/image/tree.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/ux, area/images

#5924 docker images --tree: hide both untagged and dangling images by default
  cli/command/image/list.go
  cli/command/image/tree.go
Labels: impact/changelog, status/1-design-review, area/ux

#6002 vendor: github.com/docker/docker v28.1.0-dev (250792c1a540)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/AUTHORS
  vendor/modules.txt
Labels: area/dependencies

#5952 cli/command: move prompt utilities to separate package
  cli/command/builder/prune.go
  cli/command/container/prune.go
  cli/command/image/prune.go
  cli/command/network/prune.go
  cli/command/network/remove.go
  cli/command/plugin/install.go
  cli/command/plugin/upgrade.go
  cli/command/registry.go
  cli/command/registry/login_test.go
  cli/command/system/prune.go
  cli/command/trust/revoke.go
  cli/command/trust/signer_remove.go
  cli/command/utils.go
  cli/command/utils_test.go
  cli/command/volume/prune.go
  internal/prompt/prompt.go
  internal/prompt/prompt_test.go
  internal/test/cmd.go
Labels: status/2-code-review, kind/refactor

#5953 opts: remove deprecated PortOpt, ConfigOpt, SecretOpt aliases
  opts/opts_deprecated.go
Labels: impact/changelog, impact/deprecation, area/go-sdk, impact/go-sdk

#5981 context list: remove temporary ContextType from JSON output
  cli/command/context/list.go
  cli/command/context/testdata/list-json.golden
  cli/command/formatter/context.go
Labels: impact/changelog, status/2-code-review, area/context

#5947 add top-level "docker bake" command as alias for "docker buildx bake"
  cli/command/builder/cmd.go
  cli/command/commands/commands.go
  cmd/docker/builder.go
  cmd/docker/docker.go
  docs/reference/commandline/bake.md
  docs/reference/commandline/docker.md
Labels: impact/changelog, kind/enhancement, area/builder, area/builder/buildkit, area/ux

#6001 Dockerfile: fix and clean up shell prompt
  dockerfiles/Dockerfile.dev
Labels: kind/enhancement, status/2-code-review, area/testing

#5994 docs: replace sshfs with rclone
  docs/extend/_index.md
Labels: kind/docs, status/3-docs-review, area/plugins

#6006 vendor: github.com/docker/docker v28.1.0-rc.1
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5858 run: flag to include the docker socket
  cli/command/container/create.go
  cli/command/container/run.go
  docs/reference/commandline/container_create.md
  docs/reference/commandline/container_run.md
  docs/reference/commandline/create.md
  docs/reference/commandline/run.md
Labels: impact/changelog, kind/enhancement, kind/experimental, status/2-code-review, area/authentication

#6010 completion: remove generic "os-only" for platforms
  cli/command/completion/functions.go
Labels: kind/enhancement, status/2-code-review, area/completion

#6009 set CGO_ENABLED=1 on loong64
  scripts/build/.variables
Labels: status/2-code-review, area/packaging

#6012 Dockerfile: update buildx to v0.23.0, compose v2.33.1
  Dockerfile
  dockerfiles/Dockerfile.dev
Labels: status/2-code-review, area/testing

#6011 vendor: github.com/moby/go-archive v0.1.0
  cli/command/container/cp_test.go
  cli/command/image/build/context.go
  cli/command/image/build/context_test.go
  cli/command/image/build_test.go
  cli/command/plugin/create.go
  vendor.mod
  vendor.sum
  vendor/github.com/moby/go-archive/.gitattributes
  vendor/github.com/moby/go-archive/.gitignore
  vendor/github.com/moby/go-archive/.golangci.yml
  vendor/github.com/moby/go-archive/archive.go
  vendor/github.com/moby/go-archive/archive_unix.go
  vendor/github.com/moby/go-archive/archive_windows.go
  vendor/github.com/moby/go-archive/changes.go
  vendor/github.com/moby/go-archive/changes_linux.go
  vendor/github.com/moby/go-archive/compression/compression.go
  vendor/github.com/moby/go-archive/compression/compression_detect.go
  vendor/github.com/moby/go-archive/copy.go
  vendor/github.com/moby/go-archive/dev_freebsd.go
  vendor/github.com/moby/go-archive/diff.go
  vendor/github.com/moby/go-archive/tarheader/tarheader.go
  vendor/github.com/moby/go-archive/tarheader/tarheader_unix.go
  vendor/github.com/moby/go-archive/tarheader/tarheader_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6013 vendor: github.com/docker/docker 3f46cadf398a (master, v28.0.0-rc.2)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6015 Fix login hints should only show on hub registry
  cli/command/registry.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/authentication

#6016 context: add shell-completion for context-names
  cli/command/context/completion.go
  cli/command/context/completion_test.go
  cli/command/context/export.go
  cli/command/context/import.go
  cli/command/context/inspect.go
  cli/command/context/remove.go
  cli/command/context/update.go
  cli/command/context/use.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/completion, area/context

#6017 vendor: github.com/docker/docker v28.1.0-rc.2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6018 cli/command/container: --use-api-socket: don't write empty credentials
  cli/command/container/create.go
Labels: kind/enhancement, status/2-code-review

#6020 vendor: github.com/docker/docker v28.1.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6025 Dockerfile: update compose to v2.35.1
  Dockerfile
Labels: status/2-code-review, area/testing

#6026 vendor: github.com/docker/docker v28.1.1
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/modules.txt
Labels: area/dependencies

#6024 move hack/otel to contrib
  contrib/otel/README.md
  contrib/otel/compose.yaml
  contrib/otel/otelcol.yaml
  contrib/otel/prom.yaml
Labels: status/2-code-review, kind/refactor, area/metrics/otel

#6033 docs: image import: fix heading to be included in online docs
  docs/reference/commandline/image_import.md
Labels: kind/docs, status/3-docs-review

#6029 stack deploy: fail early on invalid image reference format
  cli/command/stack/loader/loader.go
Labels: kind/enhancement, status/2-code-review, area/stack

#6022 cli/connhelper: cleanups and test improvements
  cli/connhelper/commandconn/commandconn.go
  cli/connhelper/connhelper.go
  cli/connhelper/ssh/ssh.go
  cli/connhelper/ssh/ssh_test.go
Labels: status/2-code-review, kind/refactor

#6030 opts: ListOpts: implement cobra.SliceValue to fix shell completion
  opts/opts.go
  opts/opts_test.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/completion

#6031 cli/command: change uses of ListOpts.GetAll for GetSlice
  cli/command/config/create.go
  cli/command/container/commit.go
  cli/command/container/create.go
  cli/command/container/exec.go
  cli/command/container/opts.go
  cli/command/container/run.go
  cli/command/image/build.go
  cli/command/image/import.go
  cli/command/network/connect.go
  cli/command/network/create.go
  cli/command/node/update.go
  cli/command/secret/create.go
  cli/command/service/opts.go
  cli/command/service/update.go
  cli/command/trust/signer_add.go
  cli/command/volume/create.go
Labels: status/2-code-review, kind/refactor

#6032 opts: deprecate ListOpts.GetAll in favor of ListOpts.GetSlice
  opts/opts.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#6034 cli/connhelper/ssh: add NewSpec utility to prevent parsing URL twice
  cli/connhelper/connhelper.go
  cli/connhelper/ssh/ssh.go
  cli/connhelper/ssh/ssh_test.go
Labels: status/2-code-review, kind/refactor

#6028 chore: bump golangci-lint to v2
  .golangci.yml
  cli/command/formatter/tabwriter/tabwriter.go
  dockerfiles/Dockerfile.lint
Labels: status/2-code-review, area/testing, area/dependencies

#6037 fix(QF1003): Convert if/else-if chain to tagged switch
  .golangci.yml
  cli/command/volume/create.go
Labels: status/2-code-review, area/testing, kind/bugfix

#6041 vendor: github.com/docker/docker-credential-helpers v0.9.3
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/authentication, area/dependencies

#6036 cli/command/registry: login: improve flag validation
  cli/command/registry/login.go
  cli/command/registry/login_test.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/authentication
