Repository docker/cli, pull requests merged in 2025-01, with the labels that each got.

#5716 vendor: github.com/docker/docker 6f6c3b921180 (master, v28.0.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/changes.go
  vendor/github.com/docker/docker/pkg/archive/copy.go
  vendor/github.com/docker/docker/pkg/archive/diff.go
  vendor/github.com/docker/docker/pkg/ioutils/readers.go
  vendor/github.com/docker/docker/registry/search_session.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5719 Use io.copy for build context compression
  cli/command/image/build/context.go
  vendor/github.com/docker/docker/pkg/pools/pools.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5720 [27.x backport] test-fixes
  cli/command/container/cp_test.go
Labels: status/2-code-review, area/testing, kind/bugfix

#5718 docs, man: remove confusing example for "--isolation"
  docs/reference/commandline/image_build.md
  man/docker-build.1.md
  man/src/container/create-example.md
Labels: kind/docs, status/3-docs-review, process/cherry-pick/27.x

#5721 [27.x backport] docs, man: remove confusing example for "--isolation"
  docs/reference/commandline/image_build.md
  man/docker-build.1.md
  man/src/container/create-example.md
Labels: kind/docs, status/3-docs-review

#5722 remove remnants of --oom-score-adj daemon config (docs, completion)
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/reference/dockerd.md
Labels: kind/docs, status/3-docs-review, process/cherry-picked, area/completion

#5723 [27.x backport] remove remnants of --oom-score-adj daemon config (docs, completion)
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/reference/dockerd.md
Labels: kind/docs, status/3-docs-review, area/completion

#5727 vendor: github.com/moby/term v0.5.2
  vendor.mod
  vendor.sum
  vendor/github.com/Azure/go-ansiterm/osc_string_state.go
  vendor/github.com/moby/term/term_unix.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5725 contrib/completion: remove deprecated --api-cors-header
  contrib/completion/bash/docker
  contrib/completion/fish/docker.fish
  contrib/completion/zsh/_docker
Labels: status/2-code-review, area/completion

#5724 Deprecate configuration for pushing non-distributable artifacts
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/deprecated.md
  docs/reference/dockerd.md
  man/dockerd.8.md
Labels: impact/changelog, impact/deprecation, kind/docs, status/3-docs-review, area/completion

#5728 vendor: github.com/docker/docker 50212d215ba7 (master, v28.0-dev)
  cli/context/store/metadatastore.go
  cli/context/store/tlsstore.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/builder/remotecontext/urlutil/urlutil.go
  vendor/github.com/docker/docker/client/utils.go
  vendor/github.com/docker/docker/internal/lazyregexp/lazyregexp.go
  vendor/github.com/docker/docker/pkg/atomicwriter/atomicwriter.go
  vendor/github.com/docker/docker/pkg/idtools/idtools.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_unix.go
  vendor/github.com/docker/docker/pkg/idtools/idtools_windows.go
  vendor/github.com/docker/docker/pkg/idtools/usergroupadd_linux.go
  vendor/github.com/docker/docker/pkg/idtools/usergroupadd_unsupported.go
  vendor/github.com/docker/docker/pkg/idtools/utils_unix.go
  vendor/github.com/docker/docker/pkg/ioutils/fswriters_deprecated.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5729 cli/command/plugin: runCreate: minor cleanup
  cli/command/plugin/create.go
Labels: status/2-code-review, kind/refactor

#5734 gha/build: Publish bin image for release branches
  .github/workflows/build.yml
Labels: status/2-code-review, kind/bugfix, area/packaging, process/cherry-pick/27.x

#5735 [27.x backport] gha/build: Publish bin image for release branches
  .github/workflows/build.yml
Labels: status/2-code-review, kind/bugfix, area/packaging

#5732 [27.x] vendor: github.com/docker/docker v27.5.0-rc.2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5736 [27.x] vendor: github.com/docker/docker 38b84dce32c4 (v27.5.0)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/ioutils/bytespipe.go
  vendor/github.com/docker/docker/pkg/ioutils/writeflusher.go
  vendor/github.com/docker/docker/pkg/ioutils/writers.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#5737 ci: update bake-action to v6
  .github/workflows/build.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
  docker-bake.hcl
Labels: status/2-code-review, area/testing

#5708 vendor: github.com/docker/docker 69687190936d (master, v28.0-dev)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/ioutils/buffer.go
  vendor/github.com/docker/docker/pkg/ioutils/bytespipe.go
  vendor/github.com/docker/docker/pkg/ioutils/readers.go
  vendor/github.com/docker/docker/pkg/ioutils/writeflusher.go
  vendor/github.com/docker/docker/pkg/ioutils/writers.go
  vendor/modules.txt
Labels: status/2-code-review, kind/refactor, area/dependencies

#5740 Drop support for fluentd-async-connect
  contrib/completion/bash/docker
  contrib/completion/zsh/_docker
  docs/deprecated.md
Labels: kind/docs, status/3-docs-review

#5746 vendor: github.com/creack/pty v1.1.24
  vendor.mod
  vendor.sum
  vendor/github.com/creack/pty/README.md
  vendor/github.com/creack/pty/pty_unsupported.go
  vendor/github.com/creack/pty/pty_zos.go
  vendor/github.com/creack/pty/ztypes_openbsd_32bit_int.go
  vendor/modules.txt
Labels: status/2-code-review, area/testing, area/dependencies

#5747 vendor: github.com/containerd/platforms v1.0.0-rc.1
  vendor.mod
  vendor.sum
  vendor/github.com/containerd/platforms/.golangci.yml
  vendor/github.com/containerd/platforms/compare.go
  vendor/github.com/containerd/platforms/database.go
  vendor/github.com/containerd/platforms/defaults_windows.go
  vendor/github.com/containerd/platforms/platform_windows_compat.go
  vendor/github.com/containerd/platforms/platforms.go
  vendor/github.com/containerd/platforms/platforms_other.go
  vendor/github.com/containerd/platforms/platforms_windows.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5748 vendor: github.com/mattn/go-runewidth v0.0.16
  vendor.mod
  vendor.sum
  vendor/github.com/mattn/go-runewidth/runewidth_table.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5741 update cli-docs-tool to v0.9.0, go-md2man v2.0.6
  man/go.mod
  scripts/docs/generate-man.sh
  scripts/docs/generate-md.sh
  scripts/docs/generate-yaml.sh
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: kind/docs, status/2-code-review, area/packaging

#5751 cli/command: update semconv to 1.26.0
  cli/command/telemetry.go
  vendor/go.opentelemetry.io/otel/semconv/v1.21.0/README.md
  vendor/go.opentelemetry.io/otel/semconv/v1.21.0/attribute_group.go
  vendor/go.opentelemetry.io/otel/semconv/v1.21.0/doc.go
  vendor/go.opentelemetry.io/otel/semconv/v1.21.0/event.go
  vendor/go.opentelemetry.io/otel/semconv/v1.21.0/exception.go
  vendor/go.opentelemetry.io/otel/semconv/v1.21.0/resource.go
  vendor/go.opentelemetry.io/otel/semconv/v1.21.0/schema.go
  vendor/go.opentelemetry.io/otel/semconv/v1.21.0/trace.go
  vendor/modules.txt
Labels: status/2-code-review, area/metrics/otel

#5758 cli/tree: Use single character triple dot
  cli/command/image/tree.go
Labels: kind/enhancement, status/2-code-review, area/ux

#5756 cmd/docker: enable cobra completion descriptions
  cli-plugins/plugin/plugin.go
  cmd/docker/docker.go
Labels: kind/enhancement, status/2-code-review, area/ux

#5757 image/tree: Print longest names first and use full width
  cli/command/image/tree.go
Labels: impact/changelog, kind/enhancement, status/2-code-review, area/ux

#5763 gha: Adjust release branches
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: status/2-code-review, area/testing, kind/bugfix, process/cherry-pick/27.x

#5765 Dockerfile: dev-container: update buildx v0.20.0, compose v2.32.4
  Dockerfile
Labels: status/2-code-review, area/testing

#5663 pkg/command: wrap `jsonmessage.DisplayJSONMessagesStream` with go context
  cli/command/container/create.go
  cli/command/container/run_test.go
  cli/command/image/build.go
  cli/command/image/import.go
  cli/command/image/load.go
  cli/command/image/push.go
  cli/command/image/trust.go
  cli/command/plugin/install.go
  cli/command/plugin/push.go
  cli/command/plugin/upgrade.go
  cli/command/service/helpers.go
  cli/command/swarm/ca.go
  cli/internal/jsonstream/display.go
  cli/internal/jsonstream/display_test.go
Labels: status/2-code-review

#5766 [27.x backport] Dockerfile: dev-container: update buildx v0.20.0, compose v2.32.4
  Dockerfile
Labels: status/2-code-review, area/testing

#5762 [27.x] update to go1.22.11 (fix CVE-2024-45341, CVE-2024-45336)
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#5759 [27.x] vendor: github.com/docker/docker v27.5.0
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5767 Dockerfile: update to alpine 3.21
  Dockerfile
  dockerfiles/Dockerfile.authors
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
Labels: status/2-code-review, area/testing, area/packaging

#5770 Makefile: add "shell-completion" target
  Makefile
  scripts/build/shell-completion
Labels: status/2-code-review, area/completion, area/packaging

#5773 remove dockerd man-page (moved back to moby repository)
  man/dockerd.8.md
Labels: kind/docs, status/2-code-review, kind/refactor, area/packaging

#5739 Allow '--link' with '--network bridge'
  cli/command/container/opts.go
  cli/command/container/opts_test.go
Labels: impact/changelog, area/networking, kind/bugfix, version/25.0
