Repository docker/cli, pull requests merged in 2025-06, with the labels that each got.

#6124 update to go1.24.4
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  .golangci.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging, area/dependencies

#6130 bump version to v28.3.0-dev
  VERSION
Labels: status/2-code-review, area/packaging

#6135 cli/command: RegistryAuthenticationPrivilegedFunc: fix hints for login
  cli/command/registry.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/authentication

#6137 cli/command/container: remove use of ExecOptions.Detach as intermediate
  cli/command/container/exec.go
  cli/command/container/exec_test.go
Labels: status/2-code-review, kind/refactor

#6008 Use `DOCKER_AUTH_CONFIG` env as credential store
  cli/config/configfile/file.go
  cli/config/configfile/file_test.go
  cli/config/memorystore/store.go
  cli/config/memorystore/store_test.go
Labels: impact/changelog, area/authentication

#6144 remove undocumented top-level "docker remove" command
  cli/command/container/cmd.go
  cli/command/container/rm.go
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/ux

#6141 prevent login prompt on registry operations with no TTY attached
  cli/command/image/push.go
  cli/command/image/trust.go
  cli/command/plugin/install.go
  cli/command/registry.go
  cli/command/registry/search.go
  cli/command/trust/sign.go
Labels: impact/changelog, status/2-code-review, area/distribution, kind/bugfix, area/authentication

#6146 vendor: github.com/docker/docker 265f70964794 (v28.3.0-rc.2)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/types/container/exec.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/modules.txt
Labels: status/2-code-review, area/runtime, area/dependencies

#6148 vendor: github.com/docker/docker v28.3.0-rc.2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#6147 cli/connhelper: quote ssh arguments to prevent shell injection
  cli/connhelper/connhelper.go
  cli/connhelper/internal/syntax/LICENSE
  cli/connhelper/internal/syntax/doc.go
  cli/connhelper/internal/syntax/parser.go
  cli/connhelper/internal/syntax/quote.go
  cli/connhelper/ssh/ssh.go
  cli/connhelper/ssh/ssh_test.go
Labels: impact/changelog, status/2-code-review, area/api
