Repository docker/cli, pull requests merged in 2025-03, with the labels that each got.

#5877 cli/command/manifest: remove redundant uses of ParseRepositoryInfo
  cli/command/manifest/create_list.go
  cli/command/manifest/inspect.go
  cli/command/manifest/push.go
Labels: status/2-code-review, area/distribution, kind/refactor, area/manifest

#5879 cli/command: remove dependency on distribution/uuid
  .golangci.yml
  cli/command/telemetry.go
  vendor.mod
Labels: status/2-code-review, kind/refactor, area/dependencies

#5878 Assorted cleanups to reduce trust / notary imports
  cli/command/image/trust.go
  cli/command/image/trust_test.go
  cli/command/trust/helpers.go
  cli/command/trust/helpers_test.go
  cli/command/trust/key_generate_test.go
  cli/command/trust/key_load_test.go
  cli/command/trust/revoke_test.go
  cli/command/trust/sign.go
  cli/command/trust/sign_test.go
  cli/trust/trust.go
  cli/trust/trust_test.go
  internal/test/notary/client.go
Labels: status/2-code-review, area/trust, kind/refactor, area/dependencies

#5880 cli/registry/client: remove dependency on trust / notary
  cli/registry/client/client.go
  cli/registry/client/endpoint.go
Labels: status/2-code-review, area/distribution, kind/refactor

#5882 cli/registry/client: remove unused types, and deprecate RepoNameForReference
  cli/command/manifest/push.go
  cli/registry/client/client.go
  cli/registry/client/endpoint.go
  cli/registry/client/fetcher.go
Labels: status/2-code-review, kind/refactor, area/manifest

#5887 gha: validate-pr: update to ubuntu 24.04
  .github/workflows/validate-pr.yml
Labels: status/2-code-review, area/testing, process/cherry-pick/25.0, process/cherry-pick/23.0, process/cherry-pick/26.1, process/cherry-pick/27.x

#5885 cli/command: internalize and deprecate Cli.NotaryClient
  cli/command/cli.go
  cli/command/cli_deprecated.go
  cli/command/image/trust.go
  cli/command/trust/common.go
  cli/command/trust/revoke.go
  cli/command/trust/sign.go
  cli/command/trust/signer_add.go
  cli/command/trust/signer_remove.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, area/trust, kind/refactor, area/go-sdk, impact/go-sdk

#5881 cli/command: un-export ResourceAttributesEnvvar, DockerCliAttributePrefix
  cli-plugins/manager/cobra.go
  cli-plugins/manager/manager.go
  cli-plugins/manager/telemetry.go
  cli/command/cli.go
  cli/command/telemetry.go
Labels: status/2-code-review, kind/refactor, area/metrics, area/metrics/otel, impact/go-sdk

#5888 cli/command: remove direct import of docker/go-connections
  cli/command/cli.go
Labels: status/2-code-review, kind/refactor

#5889 cli/command: deprecate Cli.ManifestStore, Cli.RegistryClient
  cli/command/cli.go
  cli/command/cli_deprecated.go
  cli/command/manifest/annotate.go
  cli/command/manifest/create_list.go
  cli/command/manifest/inspect.go
  cli/command/manifest/push.go
  cli/command/manifest/rm.go
  cli/command/manifest/util.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#5890 update to go1.23.7
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  .golangci.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, area/packaging

#5893 small performance optimizations for running hooks
  cli/command/cli.go
  cmd/docker/docker.go
Labels: status/2-code-review, kind/refactor

#5875 vendor: github.com/docker/docker-credential-helpers v0.9.2
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker-credential-helpers/client/command.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5901 chore: make function comment match function name
  cli/command/trust/helpers.go
  cli/internal/oauth/api/api.go
Labels: status/2-code-review, kind/refactor

#5904 remove legacy build-tags
  cli/command/container/completion.go
  cmd/docker/internal/signals/signals_unix.go
  docs/generate/generate.go
  docs/generate/tools.go
Labels: status/2-code-review, kind/refactor

#5913 image load: combine checks to a single switch
  cli/command/image/load.go
Labels: status/2-code-review, kind/refactor

#5863 workflow/e2e: only run experimental daemon
  .github/workflows/e2e.yml
  docker.Makefile
  e2e/compose-env.experimental.yaml
  e2e/compose-env.yaml
  scripts/test/e2e/run
Labels: status/2-code-review, area/testing, kind/refactor

#5917 cli/command: PruneFilters: require smaller interface
  cli/command/utils.go
Labels: status/2-code-review, kind/refactor

#5916 cli/command: move PrettyPrint utility to cli/command/formatter
  cli/command/config/formatter.go
  cli/command/formatter/displayutils.go
  cli/command/node/formatter.go
  cli/command/secret/formatter.go
  cli/command/task/formatter.go
  cli/command/utils.go
Labels: status/2-code-review, kind/refactor, area/go-sdk, impact/go-sdk

#5915 cli/command: remove StringSliceReplaceAt utility
  cli/command/utils.go
  cli/command/utils_test.go
  cmd/docker/aliases.go
  cmd/docker/aliases_utils.go
  cmd/docker/aliases_utils_test.go
  cmd/docker/builder.go
Labels: status/2-code-review, kind/refactor

#5906 fix duplicate warnings on docker run / docker create, and slight refactor
  cli/command/container/create.go
  cli/command/container/create_test.go
  cli/command/container/testdata/container-create-daemon-multiple-warnings.golden
  cli/command/container/testdata/container-create-daemon-single-warning.golden
  cli/command/container/testdata/container-create-localhost-dns-ipv6.golden
  cli/command/container/testdata/container-create-localhost-dns.golden
  cli/command/container/testdata/container-create-oom-kill-true-without-memory-limit.golden
  cli/command/container/testdata/container-create-oom-kill-without-memory-limit.golden
Labels: status/2-code-review, kind/bugfix

#5911 cli/command/image: fix some minor linting issues
  cli/command/image/build.go
Labels: status/2-code-review, kind/refactor

#5910 service/logs: move to cli/internal/logdetails
  cli/command/service/logs.go
  cli/internal/logdetails/parse_logs.go
  cli/internal/logdetails/parse_logs_test.go
Labels: impact/deprecation, status/2-code-review, area/go-sdk, impact/go-sdk

#5909 move winresources into cmd/docker
  .dockerignore
  .gitignore
  Dockerfile
  cmd/docker/docker_windows_386.go
  cmd/docker/docker_windows_amd64.go
  cmd/docker/docker_windows_arm.go
  cmd/docker/docker_windows_arm64.go
  cmd/docker/internal/assets/docker.exe.manifest
  cmd/docker/internal/assets/docker.ico
  cmd/docker/winresources/winresources.go
  scripts/build/mkversioninfo
Labels: status/2-code-review, kind/refactor, area/packaging

#5903 cli-plugins/manager: use stdlib errors, and minor cleanup
  cli-plugins/manager/error.go
  cli-plugins/manager/plugin.go
  cli-plugins/manager/suffix_windows.go
Labels: status/2-code-review, area/plugins, kind/refactor

#5907 opts: remove uses pkg/errors, and move swarm-specific opts to a separate package
  cli/command/service/create_test.go
  cli/command/service/opts.go
  cli/command/service/update.go
  cli/compose/loader/loader.go
  opts/duration.go
  opts/env.go
  opts/gpus.go
  opts/gpus_test.go
  opts/mount.go
  opts/network.go
  opts/network_test.go
  opts/opts.go
  opts/opts_deprecated.go
  opts/opts_test.go
  opts/swarmopts/config.go
  opts/swarmopts/config_test.go
  opts/swarmopts/port.go
  opts/swarmopts/port_test.go
  opts/swarmopts/secret.go
  opts/swarmopts/secret_test.go
Labels: impact/deprecation, status/2-code-review, kind/refactor, area/go-sdk

#5919 cli/command/formatter: add missing go:build tag
  cli/command/formatter/displayutils.go
Labels: status/2-code-review, kind/bugfix

#5920 vendor.mod: update minimum go version to go1.23
  scripts/vendor
  vendor.mod
Labels: status/2-code-review

#5908 remove uses of cli.DefaultVersion()
  cli/command/cli.go
  cli/command/system/version.go
  internal/test/cli.go
Labels: status/2-code-review, kind/refactor

#5869 vendor: golang.org/x/crypto v0.35.0
  vendor.mod
  vendor.sum
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5912 secret create, config create: refactor, use limit reader, and touch up errors
  cli/command/config/create.go
  cli/command/config/create_test.go
  cli/command/secret/create.go
  cli/command/secret/create_test.go
Labels: status/2-code-review, area/swarm, kind/refactor

#5938 man: fix minor linting issues
  man/generate.go
  man/tools.go
Labels: status/2-code-review, kind/refactor

#5784 docs/generate: remove uses of pkg/errors
  docs/generate/generate.go
Labels: status/2-code-review, kind/refactor, area/packaging

#5932 test/cli-plugins: Attempt to make TestConnectAndWait less flaky
  cli-plugins/socket/socket_test.go
Labels: status/4-merge, area/testing, kind/bugfix

#5929 vendor: github.com/docker/docker v28.0.2-dev (bea4de25004d)
  cli/cobra.go
  cli/command/container/create.go
  cli/command/container/opts.go
  cli/command/container/run.go
  cli/command/image/push.go
  cli/command/plugin/install.go
  cli/command/plugin/push.go
  cli/command/service/create.go
  cli/command/service/opts.go
  cli/command/service/trust.go
  cli/command/utils.go
  cli/registry/client/endpoint.go
  cli/registry/client/fetcher.go
  cli/trust/trust.go
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/github.com/docker/docker/api/types/swarm/config.go
  vendor/github.com/docker/docker/api/types/swarm/secret.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/client/service_create.go
  vendor/github.com/docker/docker/pkg/archive/archive.go
  vendor/github.com/docker/docker/pkg/archive/archive_linux.go
  vendor/github.com/docker/docker/pkg/archive/archive_unix.go
  vendor/github.com/docker/docker/pkg/archive/archive_windows.go
  vendor/github.com/docker/docker/pkg/archive/changes.go
  vendor/github.com/docker/docker/pkg/archive/copy.go
  vendor/github.com/docker/docker/pkg/archive/time_nonwindows.go
  vendor/github.com/docker/docker/pkg/archive/wrap.go
  vendor/github.com/docker/docker/pkg/atomicwriter/atomicwriter.go
  vendor/github.com/docker/docker/pkg/stdcopy/stdcopy.go
  vendor/github.com/docker/docker/registry/auth.go
  vendor/github.com/docker/docker/registry/config.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/github.com/docker/docker/registry/search.go
  vendor/github.com/docker/docker/registry/search_session.go
  vendor/github.com/docker/docker/registry/service.go
  vendor/github.com/docker/docker/registry/types.go
  vendor/modules.txt
Labels: status/4-merge, area/dependencies

#5926 test: fix flaky TestRunAttachTermination
  cli/command/container/run_test.go
Labels: area/testing, kind/bugfix

#5942 cli/command: remove uses of GetAuthConfigKey, ParseRepositoryInfo
  cli/command/registry.go
Labels: status/2-code-review, kind/refactor, area/authentication

#5944 vendor: github.com/docker/docker v28.0.2
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5939 cmd/dockerd: use stdlib errors
  cmd/docker/aliases.go
  cmd/docker/builder.go
  cmd/docker/docker.go
  cmd/docker/docker_test.go
Labels: status/2-code-review, kind/refactor

#5876 cli/command, cil/command/image: remove deprecated methods and functions
  cli/command/cli.go
  cli/command/cli_deprecated.go
  cli/command/image/trust.go
Labels: impact/deprecation, status/2-code-review, area/trust, kind/refactor, impact/go-sdk

#5945 e2e: skip flaky test
  e2e/plugin/trust_test.go
Labels: status/2-code-review, area/trust, area/testing

#4903 docs: include required tools in source tree
  Makefile
  dockerfiles/Dockerfile.vendor
  docs/generate/go.mod
  docs/generate/tools.go
  man/go.mod
  man/tools.go
  scripts/docs/generate-man.sh
  scripts/docs/generate-md.sh
  scripts/docs/generate-yaml.sh
  scripts/vendor
  scripts/with-go-mod.sh
  vendor.mod
  vendor.sum
  vendor/github.com/cpuguy83/go-md2man/v2/.gitignore
  vendor/github.com/cpuguy83/go-md2man/v2/.golangci.yml
  vendor/github.com/cpuguy83/go-md2man/v2/Dockerfile
  vendor/github.com/cpuguy83/go-md2man/v2/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/v2/Makefile
  vendor/github.com/cpuguy83/go-md2man/v2/README.md
  vendor/github.com/cpuguy83/go-md2man/v2/go-md2man.1.md
  vendor/github.com/cpuguy83/go-md2man/v2/md2man.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/debug.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/docker/cli-docs-tool/.dockerignore
  vendor/github.com/docker/cli-docs-tool/.gitignore
  vendor/github.com/docker/cli-docs-tool/.golangci.yml
  vendor/github.com/docker/cli-docs-tool/Dockerfile
  vendor/github.com/docker/cli-docs-tool/README.md
  vendor/github.com/docker/cli-docs-tool/clidocstool.go
  vendor/github.com/docker/cli-docs-tool/clidocstool_man.go
  vendor/github.com/docker/cli-docs-tool/clidocstool_md.go
  vendor/github.com/docker/cli-docs-tool/clidocstool_yaml.go
  vendor/github.com/docker/cli-docs-tool/docker-bake.hcl
  vendor/github.com/docker/cli-docs-tool/markdown.go
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/entities.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/util.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
  vendor/modules.txt
Labels: kind/docs, status/2-code-review, kind/refactor, area/packaging

#5829 vendor: github.com/spf13/cobra v1.9.1
  cli/command/completion/functions.go
  cli/command/config/cmd.go
  cli/command/container/completion.go
  cli/command/node/completion.go
  cli/command/secret/cmd.go
  cli/command/service/cmd.go
  cli/command/stack/cmd.go
  cli/command/system/completion.go
  vendor.mod
  vendor.sum
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5960 vendor: github.com/docker/docker v28.0.3-dev (330857ad0ffb)
  vendor.mod
  vendor.sum
  vendor/github.com/docker/docker/pkg/atomicwriter/atomicwriter.go
  vendor/modules.txt
Labels: status/2-code-review

#5941 cmd/dockerd: TestUserTerminatedError: fix unhandled errors
  cmd/docker/docker_test.go
Labels: status/2-code-review, area/testing

#5964 Revert "cli/command: remove uses of GetAuthConfigKey, ParseRepositoryInfo"
  cli/command/registry.go
Labels: status/2-code-review, kind/bugfix, area/authentication

#5962 vendor: github.com/docker/docker v28.0.3
  cli/config/config.go
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies

#5968 Improve completion of `service scale` args
  cli/command/service/scale.go
Labels: kind/enhancement, status/2-code-review, area/completion

#5950 Dockerfile: fix JSONArgsRecommended warning
  Dockerfile
Labels: status/2-code-review, area/testing

#5969 cli/command: Reapply "remove uses of GetAuthConfigKey, ParseRepositoryInfo" and add test
  cli/command/registry.go
  cli/command/registry_test.go
Labels: status/2-code-review, kind/refactor, area/performance, area/authentication

#5959 cli/registry/client: skip RepositoryInfo as intermediate
  cli/registry/client/client.go
  cli/registry/client/endpoint.go
  cli/registry/client/fetcher.go
Labels: status/2-code-review, kind/refactor, area/authentication

#5966 man: rewrite to use cli-docs-tool manpage generator
  man/generate.go
  scripts/docs/generate-man.sh
Labels: kind/docs, status/2-code-review, area/packaging

#5970 cli/command/service: un-export CompletionFn
  cli/command/service/cmd.go
  cli/command/service/completion.go
  cli/command/service/inspect.go
  cli/command/service/logs.go
  cli/command/service/ps.go
  cli/command/service/remove.go
  cli/command/service/rollback.go
  cli/command/service/scale.go
  cli/command/service/update.go
Labels: status/2-code-review, area/swarm, area/completion, kind/refactor

#5961 cli/trust: GetNotaryRepository: remove intermediate var
  cli/trust/trust.go
Labels: status/2-code-review, kind/refactor

#5958 cli/command/registry: loginClientSide: use locally defined message
  cli/command/registry/login.go
Labels: status/2-code-review, kind/refactor, area/authentication

#5973 docs/reference: search: remove mention of deprecated "IsAutomated"
  docs/reference/commandline/search.md
Labels: kind/docs, status/3-docs-review

#5974 vendor: github.com/docker/docker v28.0.4
  vendor.mod
  vendor.sum
  vendor/modules.txt
Labels: status/2-code-review, area/dependencies
