Repository docker/cli, pull requests merged in 2025-10, with the labels that each got.

#6528 cli/command: deprecate ResolveDefaultContext
  cli/command/cli.go
  cli/command/defaultcontextstore.go
  cli/command/defaultcontextstore_test.go
Labels: impact/changelog, impact/deprecation, status/2-code-review, process/cherry-picked, area/context, kind/refactor, area/go-sdk, impact/go-sdk

#6531 [28.x backport] gha: add macOS 15, remove macOS 13 (deprecated)
  .github/workflows/test.yml
Labels: status/2-code-review, area/testing

#6525 remove support for AutoRemove (`--rm`) on API < 1.30
  cli/command/container/utils.go
Labels: impact/changelog, status/2-code-review, kind/refactor, area/ux

#6527 cli/command: don't use WithInitializeClient in test
  cli/command/cli_test.go
Labels: status/2-code-review, area/testing

#6530 gha: add macOS 15, remove macOS 13 (deprecated)
  .github/workflows/test.yml
Labels: status/2-code-review, process/cherry-picked, area/testing, process/cherry-pick/25.0

#6536 cli/command/container: inline some variables
  cli/command/container/opts.go
Labels: status/2-code-review, kind/refactor

#6540 update to go1.24.8
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  .golangci.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, process/cherry-picked, process/cherry-pick, kind/bugfix, process/cherry-pick/25.0, area/dependencies, impact/go-sdk

#6541 [28.x backport] update to go1.24.8
  .github/workflows/codeql.yml
  .github/workflows/test.yml
  .golangci.yml
  Dockerfile
  docker-bake.hcl
  dockerfiles/Dockerfile.dev
  dockerfiles/Dockerfile.lint
  dockerfiles/Dockerfile.vendor
  e2e/testdata/Dockerfile.gencerts
Labels: impact/changelog, status/2-code-review, kind/bugfix, area/dependencies, impact/go-sdk
